### ISSUE TITLE
Pyside autocomplete doesn't work

### ISSUE THREAD

**Issue by tamulionis** [DamnWidget/anaconda#165]
When I set my interpreter to python3.4, autocompletion for pyside doesn't work. Debug shows:
About push back to ST3: b'{"success": true, "completions": [["QtGui\timport", "QtGui"], ["quit\tstatement", "quit"]], "uid": "984bb5a9b3f94b7292784967e215846f"}\r\n'
About push back to ST3: b'{"error": "\'utf-8\' codec can\'t decode byte 0x80 in position 24: invalid start byte", "success": false, "uid": "dff792c09e3f4d2e878531bd6a5f3156"}\r\n'

**Comment by devhd** [comment]
I saw a similar problem in the ```tox``` environment:

```
ImportError: dlopen(....../.tox/docs/lib/python3.4/site-packages/PySide/QtGui.so,
2): Library not loaded: libpyside.cpython-34m.1.2.dylib
```

Maybe you also need to fix PySide library path pointers in your virtual environment:

```
python3.4 .virtualenvs/anaconda3k/bin/pyside_postinstall.py -install
```
