### ISSUE TITLE
Python 3 autocomplete does not suggest re.finditer

### ISSUE THREAD

**Issue by rahul-ramadas** [DamnWidget/anaconda#175]
This is probably an issue in the Jedi library, but when writing Python 3 code, Anaconda does not suggest `re.finditer`. The problem does not exist when writing Python 2 code.

**Comment by DamnWidget** [comment]
Hi @rahul-ramadas 

I was wondering if this has been fixed with the upgrade of the Jedi library in v1.3.6

**Comment by rahul-ramadas** [comment]
Yes, looks like it's fixed.
