### ISSUE TITLE
Anaconda + Autocompletion on dot [.] + SublimeREPL  = SublimeText crashes

### ISSUE THREAD

**Issue by white-hat** [DamnWidget/anaconda#229]
Having ST3 on macos 10.9 with Anaconda and SublimeREPL installed through package control.
I've got Autocompletion on dot [.]  enabled by this guide http://damnwidget.github.io/anaconda/IDE/#toc_3
when I start typing in any Repl python buffer - ST3 freezes forever.

**Comment by lopince** [comment]
i face the same problem now, help!

**Comment by DamnWidget** [comment]
Autocompletion is disabled for SublimeREPL (in fact it can not be enabled in any way). Being in your SublimeREPL buffer, open the ST3 console and write the following:
```python
print(view.settings().get('repl'))
```
What do you get?
