### ISSUE TITLE
[question] [enhancement] Add Preview Support on Usage

### ISSUE THREAD

**Issue by j5shi** [DamnWidget/anaconda#235]
Hi, when you use anaconda `anaconda_find_usages`, you get a dropdown list of reference where the symbol is referenced, and the problem is that from the list you can't know how the symbol is used, so is there any way to jump to the position where the symbol is used when you select the reference item in the dropdown list? just like the way you search symbol with `CTRL+R`, ST will jump to the position of the symbol you selected.

**Comment by DamnWidget** [comment]
This was already introduced with the new and improved ExplorerPanels
