### ISSUE TITLE
Error in console when Package Control upgrades a package

### ISSUE THREAD

**Issue by rahul-ramadas** [DamnWidget/anaconda#245]
Whenever Package Control upgrades any packages, I see the following error in the console:

```
error parsing lexer: Packages/Anaconda/PythonTest.tmLanguage: Bad XML
```

**Comment by DamnWidget** [comment]
@rahul-ramadas take a look at https://github.com/DamnWidget/anaconda/releases/tag/v1.3.6-1

This should be solved now

**Comment by rahul-ramadas** [comment]
Package Control does not seem to have picked this up. I'm unsure if it supports pre-release versioning...

**Comment by DamnWidget** [comment]
Yeah, I already noticed :/
