### ISSUE TITLE
Does not work with python 3.4

### ISSUE THREAD

**Issue by nikita-b** [DamnWidget/anaconda#251]
Anaconda does not work with Python3. I set the parameter of the interpreter:
`"python_interpreter": "python3",`
Or with the full path:
`"python_interpreter": "/ usr / bin / python3",`

But when you open any .py files in the logs an error:
````ERROR: root: [Errno 111] Connection refused
ERROR: root: Traceback (most recent call last):
   File "/home/nikita/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
     self.client = AsynClient (self.available_port)
   File "/home/nikita/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
     EventHandler .__ init __ (self, (host, port))
   File "/home/nikita/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 105, in __init__
     self.sock.connect (address)
ConnectionRefusedError: [Errno 111] Connection refused````

Python - Python 3.4.0
Anaconda - 1.3.4
OS - Xubuntu
What could be the cause of the problem? Thanks!

**Comment by kabamaru** [comment]
"/ usr / bin / python3" is not a valid path. Try removing the spaces. I also work with Python 3.4.2 and "/usr/local/bin/python3" works fine on my Mac (which has Python 2.7 as default).

**Comment by DamnWidget** [comment]
What you mean with "try removing the spaces"? I am a bit lost here right now...

**Comment by alsoicode** [comment]
I'm also having difficulty getting Anaconda to work with Python 3.4 on Ubuntu 14.04 LTS.

My project settings:

    {
        "build_systems":
        [
            {
                "name": "Anaconda Python Builder",
                "selector": "source.python",
                "shell_cmd": "/home/btaylor/python-virtualenvs/captialma/bin/python -u \"$file\""
            }
        ],
        "folders":
        [
            {
                "follow_symlinks": true,
                "path": "."
            }
        ],
        "settings":
        {
            "python_interpreter_path": "/home/btaylor/python-virtualenvs/captialma/bin/python3",
            "python_package_paths":
            [
                "/home/btaylor/python-virtualenvs/captialma/lib/python3.4/site-packages",
                "/home/btaylor/django-projects/captialma"
            ]
        }
    }

I'm getting zero code completion on imports, and go to definition won't work at all. Checking the jedi cache for the project doesn't reveal any errors, but it doesn't appear that anything is being indexed.
