### ISSUE TITLE
Import Validator picks up from and import in docstrings

### ISSUE THREAD

**Issue by jongiddy** [DamnWidget/anaconda#252]
Detection of import lines just looks for a leading `from` or `import`. One problem is that docstrings (or any multi-line string) can get detected as an import statement, and will usually be flagged as not importable.

e.g. the following file
```
"""This module retrieves
import records
   from the database.
"""
```

**Comment by DamnWidget** [comment]
Fixed in branch fix252, pending of release in version 1.3.6
