### ISSUE TITLE
anaconda can't do auto-formatting and keeps producing errors in console

### ISSUE THREAD

**Issue by shadowleaves** [DamnWidget/anaconda#253]
the same error seen in "Error on startup and linting in Windows XP #174".

ctrl+alt+R generates the following:
autoformatting failed; buffer not changed

opening any .py file and place cursor any where in the file will generate following error in the console:

ERROR:root:list index out of range
ERROR:root:Traceback (most recent call last):
  File "C:\Users\han.yan\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\worker.py", line 183, in start
    self.start_json_server()
  File "C:\Users\han.yan\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\worker.py", line 72, in start_json_server
    self.build_server()
  File "C:\Users\han.yan\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\worker.py", line 247, in build_server
    self.project_name = project_name()
  File "C:\Users\han.yan\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\helpers.py", line 223, in project_name
    project_name = window.folders()[0].rsplit(os.sep, 1)[1]
IndexError: list index out of range

**Comment by shadowleaves** [comment]
Reinstalled ST3 and didn't work. However, I'm able to fix the problem using the following code changes. basically I changed window.folders() to window.active_view().file_name().

all functions now works smoothly. I haven't tested this on Mac or Linux though. shall I create a pull request?

# --------------
# Please enter the commit message for your changes. Everything below
# this paragraph is ignored, and an empty message aborts the commit.
# Just close the window to accept your message.
diff --git a/anaconda_lib/helpers.py b/anaconda_lib/helpers.py
index 6741f78..c96c368 100644
--- a/anaconda_lib/helpers.py
+++ b/anaconda_lib/helpers.py
@@ -218,9 +218,9 @@ def project_name():
     window = sublime.active_window()
     project_name = window.project_file_name()
     if project_name is None:
-        folders = window.folders()
-        if len(folders) > 0:
-            project_name = window.folders()[0].rsplit(os.sep, 1)[1]
+        file_name = window.active_view().file_name()
+        if file_name is not None:
+            project_name = file_name.rsplit(os.sep, 1)[1]
         else:
             project_name = 'anaconda-{id}'.format(id=window.window_id)
     else:

**Comment by DamnWidget** [comment]
Hi.
This change will break anaconda in the case that there is no views/buffers opened
