### ISSUE TITLE
When offline, anaconda renders ST3 unusable

### ISSUE THREAD

**Issue by kabamaru** [DamnWidget/anaconda#255]
I'm running ST3 with the latest anaconda on OS X Lion, and whenever I disable wireless to preserve battery or simply an internet connection is not available, Sublime is sluggish to a degree that's it's unusable. I know that connecting to a JsonServer is a requirement for anaconda, but I think it shouldn't bog down the application. Even disabling the plugin (*) doesn't fix the issue, you have to completely remove it.

* Note that although I disabled it and got a confirmation on the status bar that it was successfully added to the list of disabled plugins, when I tried to re-enable it, the plugin wasn't in the list. So maybe there is a separate issue about disabling the plugin.

**Comment by DamnWidget** [comment]
Hi @kabamaru 

Anaconda doesn't use your internet connection at all, it connects to `localhost` so your OS should be using  the `loopback interface` to connect to the JsonServer (that runs locally in your computer).

Are you sure you don't have any other stuff going on?

**Comment by kabamaru** [comment]
Hello,

Well you can never be sure, but it's pretty much a vanilla setup, especially regarding my network settings. Here's the [error log] (http://pastebin.com/1t4SmBKU) if you can make something out of it, it would be of great help.

**Comment by DamnWidget** [comment]
Looks like your computer is unable to resolve `localhost`. Is the line `127.0.0.1	localhost` in your `/etc/hosts` file?

**Comment by kabamaru** [comment]
Thanks! The problem was a corrupted /etc/hosts file. I restored the file and now it works fine.

**Comment by DamnWidget** [comment]
You're welcome
