### ISSUE TITLE
Anaconda not showing on Package Settings menu

### ISSUE THREAD

**Issue by cachitas** [DamnWidget/anaconda#256]
I tried installing Anaconda and relaunching Sublime Text 3 but can't access any of Anaconda features.
It is listed as installed on Package Control but does not show up on Preferences -> Package Settings

Could this be a conflict with something I have installed?
```
"installed_packages":
[
	"AAAPackageDev",
	"All Autocomplete",
	"Anaconda",
	"Bash Build System",
	"Dark Neon Color Scheme",
	"Git",
	"GitGutter",
	"INI",
	"LaTeX-cwl",
	"LaTeXing",
	"LaTeXTools",
	"Markdown Preview",
	"Neon Color Scheme",
	"Package Control",
	"Predawn",
	"Python Improved",
	"SideBarEnhancements",
	"SublimeCodeIntel",
	"SublimeLinter",
	"SublimeLinter-annotations",
	"Tomorrow Color Schemes"
]
```

**Comment by DamnWidget** [comment]
Hard to say really. 

Make sure it is not in the disabled packages, I would try to disable SublimeCodeIntel and SublimeLinter just to test if they are interfering in any way with Anaconda (I don't think so but who knows).

Take a look at the Sublime Text 3 console to check if there are any errors related with that.

**Comment by cachitas** [comment]
Whoa!

After a little more digging I found out that it was listed as disabled.
Hard to guess because I had to go to `Package Control: Enable Package` to see it there. Even after several reinstall tries it remained disabled.

**Comment by cachitas** [comment]
Looks like I got it by the time of your answer but, anyway, let me thank you for your fast response!

**Comment by DamnWidget** [comment]
Glad to see that you solved the problem.
