### ISSUE TITLE
pep8_ignore ignored?

### ISSUE THREAD

**Issue by vindolin** [DamnWidget/anaconda#258]
After the last anaconda update my pep8_ignore settings doesn't seem to work anymore.

I tried setting pep8_ignore to:

    "pep8": true,
    "pep8_rcfile": false,
    "pep8_ignore":
    [
        402
    ],

But the lines are still marked as error.

    [W] PEP 8 (E402): module level import not at top of file...

Ubuntu 14.04 64
Sublime 3065

**Comment by DamnWidget** [comment]
Hi
The `pep8_ignore ` must be a list of strings with the full code of what you want to ignore, so in your case 
```python
"pep8_ignore":
[
    " E402"
]
```

**Comment by vindolin** [comment]
That's what I tried initially and it also does not work.

Here's my complete Anaconda.sublime-settings - User:

{
    "pyflakes_ignore":
    [
        "_"
    ],
    "pep8_ignore":
    [
        "E402"
    ],
}

**Comment by DamnWidget** [comment]
It's working for me.

Before the ignore:
![pep8_ignore1](https://cloud.githubusercontent.com/assets/329766/5817763/0275f8c0-a0a7-11e4-9a71-c5eaec9e0193.png)

After the ignore:
![pep8_ignore2](https://cloud.githubusercontent.com/assets/329766/5817773/1d4ca9e6-a0a7-11e4-841a-af2573a28be9.png)

Make sure that you are not hiding your configuration in another lower configuration level.

Btw, what is this "_" in the `pyflakes_ignore`?

**Comment by vindolin** [comment]
Strange, this how it looks on my system:

![pep8_ignore problem](https://i.imgur.com/tKQzM0q.png)

The thing in pyflakes_ignore is there because a gettext library here injects the function name "_" into the buildins.

**Comment by DamnWidget** [comment]
Hi
That's interesting, if you move it to your project configuration it will work, for some reason ST is not getting the `pep8_ignore` settings from the Anaconda.sublime-settings in the `User` directory but it takes whatever other option that you configure there.

I will take a look on this but I am not sure if this is a ST3 or an Anaconda problem.

**Comment by DamnWidget** [comment]
Hi again @vindolin 
I investigated a bit more about this and after delete all the anaconda related configuration (except the `python_interpreter`) in my `project.sublime-project` file, ST3 was using the configured `Anaconda.sublime-settings` `pep8_ignore` settings from the User package.

Make sure you don't have any empty `pep8_ignore` settings in your per project configuration.

**Comment by Dog** [comment]
I'm experiencing this issue with no per project configuration.

![capture](https://cloud.githubusercontent.com/assets/5172592/5909063/eb617622-a561-11e4-8fc2-812504ef170d.PNG)

**Comment by vindolin** [comment]
Sorry for the false alarm!
It turned out there was also a Python.sublime-settings that overrode the key in Anaconda.sublime-settings ಠ_ಠ

**Comment by DamnWidget** [comment]
I didn't knew that anaconda settings can be overridden by
Python.siblime-settings, I didn't expect it

**Comment by vindolin** [comment]
Me neither, I must have put it there by accident.
Is that "Settings - Syntax Specific - User" entry supposed to be in the Anaconda Package Settings menu?
![anaconda](https://cloud.githubusercontent.com/assets/834347/6025732/24d5468a-abd5-11e4-8254-79e30d0928ea.png)

**Comment by DamnWidget** [comment]
Hi.
I removed that entry from the options file template for the next release.

Thanks.
