### ISSUE TITLE
Bug in django tests in version 1.3.5 and later

### ISSUE THREAD

**Issue by p-p-m** [DamnWidget/anaconda#259]
My anaconda tests settings:
```
"test_command": "./manage.py test --settings=project.server.test_settings --noinput",
"test_delimeter": ".",
"test_virtualenv": "/path/to/my/project/venv"
```
In v1.3.4 Anaconda executes single test with args:
```
['./manage.py', 'test', '--settings=nodeconductor.server.test_settings', '--noinput', 'project.app.tests.test_file.TestClass.test_method']
```
and it works fine

But in v1.3.5 and later Anaconda executes test with such args:
```
['./manage.py', 'test', '--settings=nodeconductor.server.test_settings', '--noinput', .TestClass.test_method']
```
(no path from project to file)

Is this a bug? Or I have to change my settings?

**Comment by DamnWidget** [comment]
Looks like we introduced some bug in the path resolution

**Comment by DamnWidget** [comment]
Fix will be available in the next release, for now you can just use the fix259 branch if you want to have it right now.

**Comment by p-p-m** [comment]
Thanks
