### ISSUE TITLE
Allow overriding Test runner output window theme and syntax.

### ISSUE THREAD

**Issue by pradyun** [DamnWidget/anaconda#260]
It would be nice if Anaconda has a for the test-runner output window changing to a custom color theme and syntax. Should be as simple as changing the property lookups for the same in `commands/test_runner.py`.

**Comment by DamnWidget** [comment]
Implemented in branch enhancement#260, waiting for release

**Comment by pradyun** [comment]
Thanks for the fix.

Just one thing, wouldn't it be nicer if it allowed to specifying themes directly from Packages. It's trivial to allow from outside Anaconda, in fact you have extra-code to prevent that. So, it seems you have a reason to do so.

If you don't mind, could you please explain the current behaviour is like what it is?

Thanks again! :+1:
