### ISSUE TITLE
Anaconda pollutes console with unwanted info

### ISSUE THREAD

**Issue by bordaigorl** [DamnWidget/anaconda#261]
Even with debug set to false, I get every linter warning printed in JSON in the console, e.g.

    {'underline_range': True, 'offset': 0, 'lineno': 26, 'level': 'W', 'message': '[w] pep 8 (%s): %s', 'raw_error': '[W] PEP 8 (E402): module level import not at top of file'}

Can this be disabled?

**Comment by DamnWidget** [comment]
This is already fixed in one of the branches that are gonna be part of the
next release.

If you wanna get rid of it right now, open your
anaconda/anaconda_lib/linter/sublime.py file and in line 147 there is a
`print(error)` that shouldn't be there, just remove it and restart your
Sublime

**Comment by bordaigorl** [comment]
Thanks! (I am only complaining because it got really frustrating when trying to debug a plugin I'm writing!)
Great work by the way. :+1:
