### ISSUE TITLE
Error List display on save (enhancement?)

### ISSUE THREAD

**Issue by njamaleddine** [DamnWidget/anaconda#263]
My apologies if this is already a feature, but is there a setting that allows the error list to show after saving a file? http://damnwidget.github.io/anaconda/IDE/#toc_38

If not that would be a great feature. I'd like to say using anaconda as a lightweight python IDE in ST3 so far has been great.

**Comment by DamnWidget** [comment]
Hi.

Write `show error list` in the ST3 `Command Palette`

**Comment by njamaleddine** [comment]
If you add a `show_error_list_on_save` setting parameter in the future that allows for the `error list` to be shown automatically after saving the file that would be great. 

Another linter I've used in the past has the feature that causes the error list window to pop up automatically. 

You can close this case if you want and mention me in this case if you add the setting. 

Thanks

**Comment by DamnWidget** [comment]
Implemented in branch enhancement#263, waiting for release
