### ISSUE TITLE
conda environment loading

### ISSUE THREAD

**Issue by matzhaugen** [DamnWidget/anaconda#265]
I know that this package supports virtual environments but anaconda seems to already have a built in environment feature, "conda". Why not include this functionality. And if not how do I work with the existing functionality to include a conda environment?

**Comment by akabos** [comment]
I guess you are talking about conda package manager included in [Anaconda python distribution](http://docs.continuum.io/anaconda/index.html). This repo contains Anaconda IDE which is Sublime Text plugin and have nothing in common with former project except for name.

**Comment by DamnWidget** [comment]
Hi.

@matzhaugen if you mean to use Anaconda Distribution virtual environments with AnacondaST3 in Sublime Text 3 (this repo) I never tried to do it but it should be the same than use `virtualenv`.

If you know where your conda environment Python executable is, just add it as your `python_interpreter` in your AnacondaST3 plugin settings.
