### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by saulshanabrook** [DamnWidget/anaconda#268]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with anaconda. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable anaconda on @Sourcegraph by going to https://sourcegraph.com/github.com/DamnWidget/anaconda and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by DamnWidget** [comment]
Done
