### ISSUE TITLE
Autocomplete drop-down shows up incorrectly.

### ISSUE THREAD

**Issue by pradyun** [DamnWidget/anaconda#269]
In a Python view, with the contents:
```py
a = "Hello
```
if the user appends/types `"`, to end the string, and change the buffer to:
```py
a = "Hello"
```
The auto-complete box drops down, listing `str`'s methods.

This, IMO, is unexpected and unwanted behaviour. 
What would be expected behaviour is... Nothing. Unless the user type a `.` after the string, which is when this drop-down should show up.

-----
I took the time to make a nice gif showing the issue (Ignore the "_" at EOL):
![A nice GIF](https://cloud.githubusercontent.com/assets/3275593/6095100/9a548d4a-af71-11e4-8fff-79e889044174.gif)

**Comment by pradyun** [comment]
Offtopic suggestion....
How about you create an issue for tracking `v2.0.0` progress and linking to `v2.0.0` related issues? 

It could use [task lists][gfm-task-lists] and would serve as a nice way to track the current state of progress, because I think, a conversation is more informative than a milestone.

 [gfm-task-lists]: https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments

**Comment by DamnWidget** [comment]
Hi
I can't reproduce this behavior. Are you using autocompletion on dot? http://damnwidget.github.io/anaconda/IDE/#toc_2

**Comment by pradyun** [comment]
Here's my current `Python.sublime-settings` in "Packages/User":

```json
{
	"auto_complete_triggers": [
        {
            "selector": "source.python - string - comment - constant.numeric",
            "characters": "."
        }
    ]
}
```

**Comment by DamnWidget** [comment]
Weird... Can you give more details?:
Operating System
Sublime Text 3 Build
Anaconda Version

I wasn't able to reproduce it nor in Windows 7, Ubuntu 14.04 or OS X 10.10.2

**Comment by pradyun** [comment]
Sure.

Ubuntu 14.04
Build 3065
v1.3.7

**Comment by DamnWidget** [comment]
Still couldn't replicate this one.

Anyone with the same issue?

**Comment by martinhill** [comment]
Hi, I'm seeing the same problem. Similarly, I see auto-complete boxes every time I hit tab or space on the end of a complete statement, or on a blank line. This results in my adding "abs" almost everywhere as I type.

![anaconda_snap](https://cloud.githubusercontent.com/assets/1266945/6307766/a5d53fa8-b90c-11e4-9d2b-288a73a77ab2.png)

ST3 build 3065 on OSX Yosemite
Anaconda v1.3.7
Djaneiro v2014.11.26
SublimeCodeIntel v2.1.7+st3
Vintageous v3.8.7

I tried using these settings to minimize auto-complete
#### Preferences.sublime-settings
```json
{
	"auto_complete": false,
	"codeintel": false,
	"codeintel_live": false,
}
```

**Comment by DamnWidget** [comment]
As I said before, I can't replicate this behavior, when I press space ST3 just write an space, when I press tab ST3 just writes a tab (4 spaces in this case). Possible things that you can try out.

1) Enable [autocompletion on dot](http://damnwidget.github.io/anaconda/IDE/#toc_2)
2) Disable (or remove) SublimeCodeIntel (I don't know if Djaneiro triggers the completion popup in any way as I never used myself, if you are in doubt, disable/remove it as well).
3) Restart ST3 and try it again

Just for the record, anaconda hooks into normal ST3 auto completion, anaconda doesn't fire by himself the autocompletion if ST3 doesn't fired it first.

**Comment by martinhill** [comment]
Disabling SublimeCodeIntel was the answer. Thanks!

**Comment by DamnWidget** [comment]
You're welcome

**Comment by pradyun** [comment]
@DamnWidget SublimeCodeIntel is the culprit. You might want to document that it and Anaconda don't play along well...

Again thanks for this plugin! Wonderful job!
@martinhill Thanks!

**Comment by DamnWidget** [comment]
https://github.com/DamnWidget/anaconda#autocomplete-drop-down-shows-up-incorrectly

**Comment by pradyun** [comment]
:+1:
