### ISSUE TITLE
Disgusting typo in documentation

### ISSUE THREAD

**Issue by fm4d** [DamnWidget/anaconda#271]
Hello, documentation on http://damnwidget.github.io/anaconda/IDE/#toc_4 contains pretty disgusting typo in 
"hide_snippers_on_completion as true". It is supposed to be "snippets" instead of "snippers".

**Comment by DamnWidget** [comment]
I don't understand why it's `disgusting`, note that english is not my first (nor my second) language.

**Comment by fm4d** [comment]
Well, I am not sure "disgusting" is the proper word ( not my first language too ), but its not pretty when you copy some quite long string from documentation and there is typo in it. It is hard to "debug" and overall confusing. Thats why I wrote "disgusting".

**Comment by DamnWidget** [comment]
I think the word that you are looking for is "annoying"

**Comment by DamnWidget** [comment]
It's fixed by the way
