### ISSUE TITLE
Tab Key bug on code complete with keyword-like prefix

### ISSUE THREAD

**Issue by hu6360567** [DamnWidget/anaconda#272]
For example:
I'd like to code complete for "pass"
I've input "pa" and press tab key, the editor insert a tab and pop up the complete window.
This seems only happens to prefix matches keywords, other variable or function names don't have this problem.

Should I set something in user-setting file? or just a bug?

Setting-User:
```json
{
	"auto_complete": false,
	"caret_style": "solid",
	"color_scheme": "Packages/Theme - Nil/Big Duo.tmTheme",
	"default_line_ending": "unix",
	"draw_white_space": "all",
	"ensure_newline_at_eof_on_save": true,
	"file_exclude_patterns":
	[
		".DS_Store",
		"*.pid",
		"*.pyc"
	],
	"find_selected_text": true,
	"fold_buttons": false,
	"folder_exclude_patterns":
	[
		".git",
		"__pycache__",
		"env",
		"env3"
	],
	"font_face": "Monaco",
	"font_options":
	[
		"subpixel_antialias",
		"no_bold"
	],
	"font_size": 18,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage",
		"AlignTab"
	],
	"line_padding_bottom": 0,
	"line_padding_top": 0,
	"rulers":
	[
		72,
		79
	],
	"scroll_past_end": false,
	"show_minimap": false,
	"tab_size": 4,
	"theme": "Nil.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"wide_caret": true,
	"word_wrap": true,
	"wrap_width": 80
}
```

Anaconda-Setting-User:
```json
{
    "complete_parameters": true,
    "display_signatures": true,
    "anaconda_gutter_theme": "simple",
    "anaconda_linter_mark_style": "outline",
    "suppress_word_completions": false,
    "suppress_explicit_completions": false,
}
```

Mac OS X 10.10.2 & Windows 8.1
Sublime 3065
Anaconda 1.3.7

**Comment by DamnWidget** [comment]
Hi @hu6360567 
Anaconda hooks into the built-in ST3 autocompletion so I recommend you to enable the ST autocompletion (` "auto_complete": true`).

Anaconda works much better with automatic auto completion enabled and fire autocompletion on dot instead of tab, take a look [here](http://damnwidget.github.io/anaconda/IDE/#toc_2) to learn how to make ST3 fire autocompletions on dor for Python files

**Comment by hu6360567** [comment]
on dot autocompletion is working properly. I found this problem happens only when the symbol appears for the first time in current file. It bothers me when I first write "return" in the file.

**Comment by DamnWidget** [comment]
Make sure that you don't have SublimeCodeIntel enabled at the same time that you are using anaconda (at least for python code).

**Comment by DamnWidget** [comment]
Gonna close this one for now, feel free to open it if you get new information but for now I am just labeling it as "unconfirmed"
