### ISSUE TITLE
Integrate the new tooltip API

### ISSUE THREAD

**Issue by cryzed** [DamnWidget/anaconda#275]
Also see [this](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583&start=40) and possibly [this](https://github.com/jbrooksuk/Intellitip/pull/1). Sorry for being a bit short on words, but the links should speak for themselves. I think this would be way nicer than just being able to display a very limited amount of information in the statusbar and has potential to include more of Jedi's information.

**Comment by DamnWidget** [comment]
Hi
Tooltips are pretty cool but there are two problems with them right now

1. They are pretty bugged at the moment including non theme colors inheritance into de tooltip panel.
2. They are only available in the 3070 build that not everyone can access to

This feature is not gonna be part of anaconda until build 3070 (at least) is available to the general ST3 public.

Obviously we can start playing with it in some development branch, even use ST3 versioning check to make the feature available to anyone using the 3070 build branch or better, but that feel just wrong.

No one tell us that the 3070 branch is not gonna be unreleased for 12 months like already happened in the past.

But yeah definitely something to start playing with.

**Comment by cryzed** [comment]
> even use ST3 versioning check to make the feature available to anyone using the 3070 build branch or better, but that feels just wrong.

It might feel wrong, but the tooltips are gonna feel really good ;D

**Comment by DamnWidget** [comment]
https://github.com/DamnWidget/anaconda/releases/tag/v1.4.0

**Comment by cryzed** [comment]
Well that is really awesome, thank you so much for the quick feature addition!

**Comment by DamnWidget** [comment]
This is how it looks in darker themes:
![](http://damnwidget.github.io/anaconda/img/tooltips.png)

**Comment by cryzed** [comment]
![](http://i.imgur.com/pVKrWvE.png) This is what it looks like for me. My font of choice doesn't lend itself to being arbitrarily resized for the "title", but I could fiddle with the CSS I suppose. It's really neat, thank you!

**Comment by DamnWidget** [comment]
I told you, ST3 tooltips implementation is still bugged as hell :P 

Enjoy!

**Comment by cryzed** [comment]
And I still love it, thank you :)!

**Comment by DamnWidget** [comment]
Hey @cryzed 
I was wondering which platform do you work on because I was testing this thing in Linux today and I noticed that some of the docstrings were worng/weird.

Did you noticed something?

**Comment by cryzed** [comment]
I am using Windows 7 and haven't noticed anything of that sort, sorry that I can't be of more help. I'll let you know if I notice anything!
