### ISSUE TITLE
Disable completion on comma (,)

### ISSUE THREAD

**Issue by karolyi** [DamnWidget/anaconda#277]
Hey,

I'm trying to disable the completion popup when typing a comma (`,`) character, as I edit multi-line lists, and each line end after typing the comma, comes up with the autocompletion popup, where pressing enter adds the first element from the popup (usually `abs()`) instead of doing the newline. It's really annoying.

Is there any way to disable this behavior?

Cheers

**Comment by karolyi** [comment]
my non-default settings, if needed

```
{
    "anaconda_gutter_marks": true,
    "anaconda_gutter_theme": "hard",
    "anaconda_linter_mark_style": "none",
    "auto_formatting": true,
    "pep8_ignore": [
    "E501", // Is long lines
    ],
}
```

**Comment by karolyi** [comment]
Okay, it seems it was SublimeCodeIntel and Anaconda playing against each other. Removing the former and installing CodeComplice helped. I'll close this here.

**Comment by DamnWidget** [comment]
Anaconda doesn't trigger autocompletions @karolyi, it just hooks into default ST3 completions so yes, SublimeCodeIntel was getting in the way (as usual).
