### ISSUE TITLE
Test runner: syntax not applied to output panel (with fix)

### ISSUE THREAD

**Issue by rtxm** [DamnWidget/anaconda#278]
Tested versions of Sublime Text 3 : 3065 and 3071
OS: Linux (Arch, up-to-date)

When running tests with Anaconda, the output is not syntax highlighted. Text appears as plain.

My understanding is that `set_syntax_file` is called too early. An alternative that works (I have tested) is to pass the  `syntax` option to the `exec` command:
```
self.view.window().run_command(
            'exec', {
                'shell_cmd': command,
                'working_dir': self.test_root,
                'syntax': self.output_syntax,
            }
        )
```
I'm ready to send a pull request if you are OK.

**Comment by DamnWidget** [comment]
Send the PR please I will review it later today
