### ISSUE TITLE
Arcpy Autocomplete

### ISSUE THREAD

**Issue by gavreh** [DamnWidget/anaconda#284]
Hi,

Love the plugin. I'm having a problem - the autocomplete is working for normal python modules:
![datetime-autocomplete](https://cloud.githubusercontent.com/assets/209355/6394074/9f02045e-bd94-11e4-8f3d-703096734880.PNG)

... but I'm trying to use it with the [Arcpy module ](http://resources.arcgis.com/en/help/main/10.2/index.html#//002z00000008000000), it does not work:
![arcpy-autocomplete](https://cloud.githubusercontent.com/assets/209355/6394071/9ac70466-bd94-11e4-8695-f8560cda517b.PNG)

In PyScripter on the same machine it does have the autocompletes:
![pyscripter arcpy](https://cloud.githubusercontent.com/assets/209355/6394068/93886122-bd94-11e4-9eae-5cc5922c392c.PNG)

I don't know if this is an issue in Anaconda or just a configuration issue on my end ... any tips you can provide? Thanks!

**Comment by DamnWidget** [comment]
Open a PowerShell or CMD.exe and go to your anaconda installation under the `Packages` folder in your Sublime Text 3 `%APPDATA%`. CD into the `anaconda_lib` folder and start an interactive Python interpreter on that path.

Copy and paste the following:
```python
import jedi

print(jedi.Script('import arcpy; arcpy.').completions())
```

Paste it's results here

**Comment by gavreh** [comment]
Thanks for the response! I think I figured this out. I had to point my python_interpreter to the ArcGIS version of python:

`"python_interpreter": "C:\\Python27\\ArcGIS10.2\\python.exe"`

![anaconda-python-arcpy](https://cloud.githubusercontent.com/assets/209355/6394521/abe601cc-bd97-11e4-92e9-a417a6ac3b1f.PNG)

Hopefully this helps someone else out in the future!
- Gavin
