### ISSUE TITLE
when i exit the sublime,there are some python.exe stay in my os for ever

### ISSUE THREAD

**Issue by finalinches** [DamnWidget/anaconda#286]
my os is win 8.1, i user the sublime text 3(BUILD 3065)

when i exit the sublime,just close it

there are some python.exe still stay  in my os and listen some tcp port

**Comment by DamnWidget** [comment]
Hi @finalinches 
Don't worry about them, they wouldn't last long (of course they don't stay forever neither) and they are doing nothing (if ST3 is closed).

**Comment by finalinches** [comment]
e....... i have a test, when i close ST3, after 10 minutes, i find python.exe still exist.......

**Comment by finalinches** [comment]
my anaconda version is 1.4.3
