### ISSUE TITLE
import completions are not working

### ISSUE THREAD

**Issue by rahul-ramadas** [DamnWidget/anaconda#288]
Completions for module imports are not working. As soon as I type `import`, Anaconda shows me the list of modules I can import (I see that there is special handling for this in the code). However, as soon as I start to type the name of the module, the autocomplete list disappears.

I tried to dig into this but couldn't figure out what the issue was. It's certainly not Jedi, as the completions are coming back from the server correctly.

All I can see is that the autocomplete list closes, and on every character typed after that, Sublime queries for completions from Anaconda, and then promptly seems to ignore them. Even forcing autocomplete (`Ctrl + Space`) doesn't work; the status bar says `No available completion`.

I'm stumped :cry:

**Comment by DamnWidget** [comment]
Take a look at the README section 'Autocompletions for import behave badly' there is a workaround to fix that as its a ST3 problem

**Comment by rahul-ramadas** [comment]
Oh ok 😑
