### ISSUE TITLE
Jedi - autocompletion. 

### ISSUE THREAD

**Issue by jonathan-s** [DamnWidget/anaconda#290]
Hello, 

Regarding autocompletion there are some instructions on getting [autocompletion with dot](http://damnwidget.github.io/anaconda/IDE/#toc_3). That should be in the `Package settings > Anaconda > Settings - User` I presume. 

Then there is the issue of getting autocompletion when you have `,` and `:`. Is there any way of turning that off. Because it happens pretty often that I get unwanted completion when I write in commas and colons.

**Comment by DamnWidget** [comment]
Hi, you have to create a file called `Python.sublime-settings` in your `Packages/User` directory (use the Browse Packages option in the ST3 preferences menu to open it) with the following content:
```json
{
    "auto_complete_triggers": [{"selector": "source.python - string - comment
    - constant.numeric", "characters": "."}]
}
```

You shouldn't get any type of Anaconda autocompletion when you press colon or comma keys.

**Comment by jonathan-s** [comment]
This is what I get when I type in colon. When I remove the anaconda package from sublime this disappears so it seems like it comes from Anaconda and presumably Jedi. 

![image](https://cloud.githubusercontent.com/assets/2124818/6656250/46406d94-cb1b-11e4-919e-4c8bba9c213b.png)

**Comment by DamnWidget** [comment]
This is what I get when I type in colon.
![screen shot 2015-03-15 at 14 41 50](https://cloud.githubusercontent.com/assets/329766/6656397/91147aee-cb21-11e4-92da-71647aea72da.png)

Nothing. I said that before here and is in the documentation as well, anaconda doesn't implements any mechanism to fire the autocompletion event, instead, anaconda hook it himself into the regular ST3 autocompletion even that is why you have to configure the regular ST3 autocompletion trigger (you do that in `Python.sublime-settings` into your `Package/User` directory as anaconda doesn't trigger any action for autocomplete itself).

The plugin never fires any action for autocomplete that could interfere with any other ST3 packages that you can have installed.

As I already said, anaconda doesn't fire the autocomplete event at all so it's just not possible that anaconda fires the autocompletion event into ST3 when a colon or a comma or whatever other character is typed in the editor.

As the character that is firing this is just a colon, and as a guess, take a look at any package that completes PHP or C++, especially try to disable SublimeCodeIntel as they are not as considered with other packages that could be running in ST3 as anaconda is.

**Comment by jonathan-s** [comment]
Thanks for helping me debug that. When I removed SublimeCodeIntel the issue disappeared.

**Comment by DamnWidget** [comment]
You are welcome
