### ISSUE TITLE
auto show doc after upgrading to 3080

### ISSUE THREAD

**Issue by hu6360567** [DamnWidget/anaconda#292]
After Sublime Text upgrading to 3080,
everytime I typed a word, it shows the docstring in floating mode.

How can I turn it off?

I've tried
    "enable_signatures_tooltip":false,
    "display_signatures": true,

And this works

**Comment by DamnWidget** [comment]
Hi @hu6360567 

Just set `enable_signatures_tooltip` as `false`

**Comment by clawoflight** [comment]
Shouldn't this be closed?

@DamnWidget The issues seem to need some cleaning up either way.

**Comment by DamnWidget** [comment]
It's well documented in the package documentation
