### ISSUE TITLE
Ubuntu 14.04 Issue after closing sublime text

### ISSUE THREAD

**Issue by mohdmaqboolalam** [DamnWidget/anaconda#294]
when i close the sublimetext3 sometimes that little box  does not go then after 1 minutes it just gone maybe it's bug. 
![screenshot from 2015-04-02 19 35 07](https://cloud.githubusercontent.com/assets/7526000/6965516/bd21a6dc-d96f-11e4-8eeb-9fa95f1e2497.png)

**Comment by DamnWidget** [comment]
Sorry but you should be posting this issue in the Sublime Text 3 issues project itself, anaconda just uses the ST3 API to show those tooltips but it has nothing to do with how they are displayed or have any control on them beyond just use the ST3 API
