### ISSUE TITLE
"TypeError: 'NoneType' object is not callable" when use user settings for pep8

### ISSUE THREAD

**Issue by edgar-ch** [DamnWidget/anaconda#295]
I added this settings to the user configuration:
```
{
    "pep8_ignore": [
        "W191"
    ]
}
```
and now in console shows a lot of errors like this:
```
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "/home/edgar/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 94, in process_message
ERROR:root:    callback(data)
ERROR:root:  File "/home/edgar/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/callback.py", line 73, in __call__
ERROR:root:    return self._fire_callback(*args, **kwargs)
ERROR:root:  File "/home/edgar/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/callback.py", line 219, in _fire_callback
ERROR:root:    return callback(*args, **kwargs)
ERROR:root:TypeError: 'NoneType' object is not callable
```
but pep8 checking actually works.

How to get rid of these errors ?

**Comment by DamnWidget** [comment]
Hi @edgar-ch 

Is this error deterministic? Because I think is pure coincidence about the 'pep8_ignore'. Can you replicate it?

**Comment by edgar-ch** [comment]
Error not repeats with other files, only with one. Do you think that this is a problem with pep8 ?

**Comment by DamnWidget** [comment]
I don't know. Can I have access to that file contents?

**Comment by edgar-ch** [comment]
Yes, download it from here https://copy.com/ZwZ9GPpFK0BzTarX

**Comment by DamnWidget** [comment]
Hi @edgar-ch 

I did test that file and it works for me. Can you give me more details about your specific environment? OS, Python version, Virtualenv Version (if any), ST3 version, Anaconda version.

**Comment by edgar-ch** [comment]
System:
> Linux edgar-desktop 3.16.0-34-generic #45~14.04.1-Ubuntu SMP Tue Mar 24 11:14:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Python version:
> Python 2.7.6 (default, Mar 22 2014, 22:59:56)

Anaconda v1.4.7, Sublime 3 Build 3083

**Comment by DamnWidget** [comment]
I am gonna close this one, as I could not replicate it ever.
