### ISSUE TITLE
[Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by mobedigg** [DamnWidget/anaconda#296]
Anaconda made sublime work very slowly, I checked sublime console and found these error messages. A lot of them.

>ERROR:Anaconda.anaconda_lib.worker:Unexpected error in `server_is_active`: [Errno 8] nodename nor servname provided, or not known
ERROR:root:[Errno 8] nodename nor servname provided, or not known
ERROR:root:Traceback (most recent call last):
  File "/Users/knikolenko/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/knikolenko/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/knikolenko/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

Sublime Text 3, Build 3083. Anaconda 1.4.4 Internet is working fine. After I disabled Anaconda in package control sublime is working with normal speed.

**Comment by DamnWidget** [comment]
Which operating system are you working on?

**Comment by mobedigg** [comment]
OS X Yosemite 10.10.2 (14C1514)

**Comment by mobedigg** [comment]
It worked fine last week, this problem started on Monday evening.

**Comment by mobedigg** [comment]
I figured out source of error. I commented out string in /etc/hosts 127.0.0.1 localhost and it caused this. Not sure why it's slowed down sublime so much. Anyway if you think it's not important now you can close the issue.

**Comment by DamnWidget** [comment]
Anaconda tries to resolve "localhost". Closing this now. Thanks.
