### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by alimony** [DamnWidget/anaconda#297]
I've started getting this from Anaconda:

```
ERROR:root:[Errno 61] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/Users/markus/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/markus/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/markus/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```

Either from updating my system to OS X 10.10.3, or updating Anaconda to 1.4.5.

I've seen a number of very similar cases in the past but none of their solutions works for me. Running the JSON server in debug mode works fine, the server responds and Anaconda is working properly. But running everything normally gives the above error every time.

**Comment by colorfulfool** [comment]
I have OSX 10.9.5. Today Anaconda updated itself to 1.4.5 and immediately stopped working.

Whenever I type something, Sublime lags pretty bad and autocomplete popup has no options from Anaconda (only default Sublime ones). "Go to definition", "Show documentation", etc. also don't work. The console is empty.

**Comment by mattayes** [comment]
Same problem as @colorfulfool. OSX 10.10.2, ST3 Build 3083, and Anaconda 1.4.5.

Once I disable Anaconda the typing lag goes away.

**Comment by DamnWidget** [comment]
Every time that I've seen those kind of error reports from users it's
because some misconfiguration of the /etc/hosts in OS X that makes anaconda
not able to connect/resolve to localhost.

Make sure that your /etc/hosts is not corrupted or missconfigured.

**Comment by DamnWidget** [comment]
Fixed in the last version

**Comment by colorfulfool** [comment]
That was quick. Thank you.

**Comment by alimony** [comment]
Yes, super fast response and fix, thanks a lot!

**Comment by DamnWidget** [comment]
No problem
