### ISSUE TITLE
Gutter hover error msg

### ISSUE THREAD

**Issue by harwoodspike** [DamnWidget/anaconda#301]
Is it possible to get the current lines error to pop up if you hover on the gutter icon? If this isn't currently a feature, can it be added?

**Comment by DamnWidget** [comment]
I don't think we can capture the hover event for the gutter icons section of the interface

**Comment by harwoodspike** [comment]
Is there a hover event for the highlight line?
Also is there a way to sort the error list by line numbers?

I just don't like having to open the the show error list (which is in some random order on my computer) so that I can see what is wrong.

**Comment by DamnWidget** [comment]
The order is for severity as far as I can remember now. When you put the cursor over a linted line, you get a message about the error in the Sublime Text 3 status bar.
