### ISSUE TITLE
Annoying "abs"

### ISSUE THREAD

**Issue by ryanaleksander** [DamnWidget/anaconda#305]
After the latest update, whenever I close a parenthesis in a python file, anaconda will suggest adding "abs" to the end of the line. If I press enter to create a new line, it will just add "abs" instead.

This problem is very irritating, hope you will fix it soon. Thank you!

**Comment by DamnWidget** [comment]
Hi.
I can't replicate the described behavior neither on Linux or OS X, make sure is not other plugin (like SublimeCode Intel) the one that is causing that problem.

**Comment by ryanaleksander** [comment]
Oh thanks, you're right.

**Comment by DamnWidget** [comment]
Sublime CodeIntel is always the culprit :)
