### ISSUE TITLE
Autoformatting suddenly not working anymore.

### ISSUE THREAD

**Issue by jaggerwang** [DamnWidget/anaconda#309]
I'm using the newest Sublime Text 3 and Anaconda, and my project is using virtual env with Python 3.4. The autoformatting works great before, but suddenly it stopped working. I've tried restart Sublime Text. I'm using Mac OS X 10.10.3.

When I type ^+`+R, the bottom line shows "Autoformatting failed, buffer unchanged". The output in console as following.

Calback ea176483741b40e3873c62c8feb9c7e6 came back with data but it's status was `timed_out` already
INFO:Anaconda.anaconda_lib.callback:Calback ea176483741b40e3873c62c8feb9c7e6 came back with data but it's status was `timed_out` already

**Comment by DamnWidget** [comment]
Hi @jaggerwang 
This is probably because the size of the file that you are working on is big enough to take more than one second in get formatted.

Try raising the value of `auto_formatting_timeout` from 1 second to whatever works and is acceptable for you.
