### ISSUE TITLE
Has never worked for me, is there a log file to look at

### ISSUE THREAD

**Issue by osiloke** [DamnWidget/anaconda#310]
Hi, I have occasionally tried to get this plugin to work with sublime text 3 but its always failed. 
I am using python3 as my interpreter but autocompletions don't work most of the time, it can't find the time package (No pun intended)
I would like to know if there is a log file i could take a look at while testing because it does not show any errors in the sublime console.

**Comment by DamnWidget** [comment]
Hi.
Depending on your Operating System you can find log files in different places

*  Linux: $HOME/.cache/jedi/<your_project_name>/anaconda_jsonserver.log
* OS X: $HOME/Library/Caches/Jedi/<your_project_name>/anaconda_jsonserver.log
* Windows: %APPDATA%\Jedi\Jedi\<your_project_name>/aanconda_jsonserver.log
