### ISSUE TITLE
Python has gone rogue just having sublime open

### ISSUE THREAD

**Issue by DanielPaikoffVSolvit** [DamnWidget/anaconda#313]
If I leave my sublime open I will get high memory usage warnings from my os. If I check task manager it is a python process that I did not kick off. When I kill the process the sublime text error message points to the anaconda package as the culprit.

**Comment by DamnWidget** [comment]
Can you provide more information? Logs, operating system and versions of ST
and Anaconda?

**Comment by DanielPaikoffVSolvit** [comment]
OS = Windows 7 pro
ST = Build 3083
Where do I check the version of Anaconda? I am looking in *AppData\Roaming\Sublime Text 3\Packages\Anaconda

I installed Anaconda on 4/29 using package control and re installed it on 4/29 the issue persisted.

Where does sublime keep logs?

**Comment by DamnWidget** [comment]
Continue this issue in #318, closing this one (even if it was first)
