### ISSUE TITLE
"Undefined name PermissionError" even though the code works.

### ISSUE THREAD

**Issue by Graypup** [DamnWidget/anaconda#316]
This (python 3) code creates the error message "Undefined name PermissionError" but works when run. Is there some special setting that I'm missing to enable python 3 compatibility?

    if os.geteuid() != 0:
        raise PermissionError("You forgot a sudo. If you didn't, this is a bug.")

**Comment by DamnWidget** [comment]
Make sure that your configured Python interpreter is a Python 3 interpreter, take a look to the [documentation](http://damnwidget.github.io/anaconda/anaconda_settings/) for more information.

**Comment by Graypup** [comment]
That would be why.
