### ISSUE TITLE
Sublime Text 3 closes unexpectedly when "cls" gets written and Anaconda plugin is enabled

### ISSUE THREAD

**Issue by gukoff** [DamnWidget/anaconda#317]
It appears to happen in many cases. For exmaple, this string:
assert all(isinstance(cls, item) for item in items)
When I try to add a bracket after cls in this line - ...cls(... - ST3 crashes and instantly closes.
When I delete the word "cls" in this line and write it again, the same happens as soon as I type the 's' letter.
If the Anaconda plugin is disabled, everything is all right.

**Comment by gukoff** [comment]
Here is the code example. Every line is important, every import exists. (ST3 doesn't crash otherways)
The names of modules are changed.

from folder.someclass.m1 import C1
from folder.someclass.m2 import C2

def check(items, cls):
    assert all(isinstance(cls, item) for item in items)

check([], C1)
check([], C2)

**Comment by DamnWidget** [comment]
Hi. I can't reproduce the described behaviour neither in Linux or OS X.

Can you provide more information?, ST3 version, Anaconda version, Operating System, other installed plugins.

Thank you.

**Comment by gukoff** [comment]
As I understood from jedi's bugtracker, it's jedi's error indeed.

I'm getting now a new error btw. Can't even enable anaconda.

Anaconda can not spawn a new process with your current configured python interpreter (python), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: /usr/bin/python

**Comment by DamnWidget** [comment]
About the Spawn problem, take a look at #314, seems like ST3 added some kind of bug in their last releases that maintain rubbish/garbage configuration and this is affecting how anaconda decides from which directories append your project code.
