### ISSUE TITLE
Feature request: add icon on tab if PEP warning/violation/error is present in file

### ISSUE THREAD

**Issue by Gabriel-p** [DamnWidget/anaconda#319]
The [NINJA IDE](http://ninja-ide.org/) has a quite useful feature where an icon will appear in a file's tab if an error or PEP violation/warning is found somewhere in the article.

See image for example:

![captura de pantalla de 2015-05-08 17 41 27](https://cloud.githubusercontent.com/assets/6054951/7547589/dcb46048-f5c6-11e4-87d5-db6538a5dff7.png)

where different icons are associated with PEP violations/warning/errors/etc.

This is particularly useful when you have a large file so you can quickly check if there are any issues in it without having to scroll through the whole thing.

**Comment by DamnWidget** [comment]
I don't think we can add icons to the tabs in Sublime Text
