### ISSUE TITLE
Keyword-only arguments syntax shows up as invalid.

### ISSUE THREAD

**Issue by DiegoPomares** [DamnWidget/anaconda#323]
Anaconda fails to recognize the following syntax:
    def func(arg1, arg2, *, kwarg1, kwarg2):

Which is a perfectly fine syntax that forces all the arguments after the *, to be keyword only.

Source: https://www.python.org/dev/peps/pep-3102/

**Comment by DamnWidget** [comment]
Can you explain what you mean?

**Comment by DiegoPomares** [comment]
I'm sorry, i just edited the original post

**Comment by DamnWidget** [comment]
Working perfectly fine for me, are you sure that you have configured a Python3 interpreter to be used by anaconda?

P.S: Maybe your definition of "recognize" and mine is just different, for me means that it's parsed with no lint errors.

**Comment by DiegoPomares** [comment]
Ahhh forgive my stupidity, I wasn't aware of this:

"python_interpreter": "python3"

Thank you!

**Comment by DamnWidget** [comment]
Don't worry, we are all humans after all.

Regards.
