### ISSUE TITLE
How do I use autocomplete?

### ISSUE THREAD

**Issue by rvong** [DamnWidget/anaconda#324]
Installed Anaconda, autocomplete does not seem to work the way it does it any sane or useful way.

type import then space, then after space, the list of suggestions show up, then press anything and the box disappears, then only pressing tab will make it show again, but pressing take also inserts a tab character after "import " then pressing letters will then properly filter items from within the suggestion box, whereas right after pressing the space and before pressing tab, pressing anything will close the suggestions box.

The Python.sublime-settings thing suggested for getting dots to activate autocomplete does nothing at all.

**Comment by DamnWidget** [comment]
Hi. There is a bug in ST3 itself that makes anaconda behave weird with the `import`. Take a look at ethe project README https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly

**Comment by rvong** [comment]
How do I get CTRL+space to activate the suggestion box?

**Comment by DamnWidget** [comment]
I think is much better if you activate the [autocompletion in dot](http://damnwidget.github.io/anaconda/IDE/#toc_3) support.

**Comment by rvong** [comment]
How do I activate dot completion?
I create the Python.sublime-settings file with the text:
{
    "auto_complete_triggers": [{"selector": "source.python - string - comment - constant.numeric", "characters": "."}]
}

Reloaded sublime and dot does nothing

**Comment by LucianKaltz** [comment]
It seems dot completion stop working in a large python file.

**Comment by DamnWidget** [comment]
@rvong that is a Sublime Text 3 feature, it has to work if you created the file in the right directory and you don't have any other plugin overriding that configuration (remember that SublimeCode Intel totally interfere with Anaconda and other plugins as well so if you have installed it, disable it and test it again).

@LucianKaltz that's not true, anaconda doesn't parse the whole file to autocomplete so it doesn't matters if the file has a few lines or thousands. The autocompletion is limited by what Jedi can eat and I think it can eat a lot.

**Comment by LucianKaltz** [comment]
@DamnWidget It's interesting that if I copy the whole Python file into a new file and set the syntax to Python, the dot completion works, but after I save the file and then try again, the dot completion stops working immediately. 

I thought it was sublimecodeintel behind all these but uninstalling codeintel didn't change a thing. So I guess it might be some kind of bug?

**Comment by DamnWidget** [comment]
Every single time that anyone had those kind of problems was Sublime Code Intel, maybe there are other plugins that I don't know about that also interferes with anaconda. Take into account that anaconda doesn't fire it's own auto-completion mechanism but hooks into the regular Sublime Text 3 auto-completion mechanism itself so anything that interfere into the Sublime Text default auto-completion will interfere into anaconda as well.

**Comment by gatspy** [comment]
try add file extension as shown below in Python.sublime-settings.
```
"extensions":
	[
		"py"
	]
```
