### ISSUE TITLE
No completion for sublime module?

### ISSUE THREAD

**Issue by Zhro** [DamnWidget/anaconda#325]
Maybe I've configured something incorrectly but I'm unable to get autocompletion for the "sublime" module:

```
import sublime
import sublime_plugin

def test():
    sublime.
```

There is an autocompletion list but not the list I would expect. For example, there is no result for "message_dialog".

If I copy/paste sublime.py into my package directory then the list completes as expected.

**Comment by DamnWidget** [comment]
You need to add the "sublime.py" and "sublime_plugin.py" locations as an extra path in your project configuration. Take a look into the [configuration](http://damnwidget.github.io/anaconda/anaconda_settings/#toc_5) for more information.
