### ISSUE TITLE
Anaconda always complain about exist interpreter

### ISSUE THREAD

**Issue by ronin1184** [DamnWidget/anaconda#326]
When modify anything in my python code, I always got message:

Anaconda can not spawn a new process with your current configured python interpreter (/usr/bin/python3.4), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: /usr/bin/python

I've checked /usr/bin/python3.4 and it is a valid python interpreter and put it in Anaconda.sublime-setting -- User.

"python_interpreter": "/usr/bin/python3.4"

I'm using Sublime Text 3 Build 3083 and latest Anaconda plugin.

**Comment by DamnWidget** [comment]
Probably same issue than #314, take a look on that issue as there is some workarounds.

**Comment by ProProgrammer** [comment]
I just faced similar issue however in my case `"python_interpreter"` was set to just `"python"`. After I changed it to `"/usr/bin/python"` It worked well for me.

Note: I do not have Python 3 installed on my system. I am only using Python 2.7.
Environment: Ubuntu 14.04.2 LTS, Sublime Text 3 Build 3083, Anaconda latest plugin (just fresh installed today)
