### ISSUE TITLE
Instance of jsonserver goes into 100% cpu and increase ram usage.

### ISSUE THREAD

**Issue by Grokzen** [DamnWidget/anaconda#327]
![anacondabug](https://cloud.githubusercontent.com/assets/892309/7672423/a50bd1fc-fcf2-11e4-997b-bdfeaf145be1.png)

Randomly the jsonserver goes into some buged mode where it just sits at 100% cpu and gains ~5mb ram per second. It happens at random times and i can't figure out what the trigger for this issue is.

**Comment by DamnWidget** [comment]
Let me guess, big project with lot of files and big libraries?

**Comment by Grokzen** [comment]
Well this depends on what you mean by a big project. ~20 source code files and 3 installed dependencies in the venv is not that big i would say :]

**Comment by DamnWidget** [comment]
Which ones are those dependencies?

**Comment by Grokzen** [comment]
Hmm, there was more dependencies then 3 installed in the dev environment :p 

```
Jinja2==2.7.3
MarkupSafe==0.23
PyYAML==3.11
Pygments==2.0.2
coverage==3.7.1
coveralls==0.5
docopt==0.6.2
flake8==2.3.0
jedi==0.8.1-final0
mccabe==0.3
pep8==1.6.2
prompt-toolkit==0.32
ptpdb==0.3
ptpython==0.6
py==1.4.26
pyflakes==0.8.1
pytest==2.6.4
python-dateutil==2.4.2
requests==2.5.0
six==1.9.0
testfixtures==4.1.1
tox==1.8.1
virtualenv==1.11.6
wcwidth==0.1.4
```

**Comment by DamnWidget** [comment]
Do you have mccabe, jedi, pep8 and pyflakes installed in your environment for some special reason?

**Comment by Grokzen** [comment]
pep8 is part of flake8 that i use to check my code.

Jedi and mccabe is part of ptpdb och ptpython that i use to debug and REPL my code.

**Comment by DamnWidget** [comment]
Anaconda includes it's own versions of all those libraries (except for flake8), have locally installed versions of those libraries doesn't necessarily have to break it but we saw in the past that have a local version of Jedi interfered with how anaconda works.

Anaconda uses specific versions of all those libraries, I repeat, it shouldn't affect but in general is not a good idea to bypass the versions contained into `anaconda_lib` directory as anaconda expects specific features and/or versions of the libraries that empowers it.

**Comment by Grokzen** [comment]
If there is a problem and possibility for collision with existing libraries, would it not make more sense to use the "vendor" pattern instead of path magic? For example pip uses this pattern https://github.com/pypa/pip/tree/develop/pip where they put all their dependencies inside the _vendor package and they do `from pip._vendor.requests import whatever` to avoid that kind of dependency conflicts. I think it should be rather easy to implement it here because you already have the packages inside the repo and then it would be a question of removing the path magic addition and replace the `import jedi` with something like `from anaconda._vendor import jedi` or wherever the jedi lib will be?

**Comment by DamnWidget** [comment]
That is something to review, for now, just take a look at the log file that I commented about in the previous answer, maybe the problem is totally unrelated :)

**Comment by Grokzen** [comment]
This is the log around the time i posted the original image https://gist.github.com/Grokzen/c60118d2af5efd0283b3

The 00:19:xx time stamps is just after the post and where i restarted ST3. I am not sture what happened at 00:14:xx where it looks like it restarted? O.o

**Comment by DamnWidget** [comment]
This looks like there is some library probably crashing the Python interpreter, I am afraid that you will have to start the server in debug mode to can figure out where the problem is.

Take a look to [this section](https://github.com/DamnWidget/anaconda/blob/master/Anaconda.sublime-settings#L62-L83) of the configuration file where it is explained how to make it work (remember to restart sublime text 3 before and after the debug test).

**Comment by glenfant** [comment]
Same thing for me. Opening with ST3 + latest Anaconda a small Python file of a small project (les than 600 lines) in a virtualenv that has only the "requests" 3rd party package.

A Python process devours about 90% to 98% of CPU and 1.1 RAM Gb (!!). And this process is still alive after quitting ST3 !

The project's `anaconda_jsonserver.log` does not show anything valuable to this issue.

My `anaconda.sublime-settings` file :

```json
{
    "pep8_max_line_length": 120,
    "anaconda_linting_behaviour": "load-save",
    "anaconda_linter_mark_style": "none"
}
```

**Comment by DamnWidget** [comment]
I am afraid that you need to start the JsonServer in debug mode in order to get all the information that we need to can follow the problem to it's root, take a look on my previous answer on this issue discussion.

**Comment by DamnWidget** [comment]
Any updates here @Grokzen and @glenfant ?

**Comment by Grokzen** [comment]
@DamnWidget I have not seen any problems for maybe the last 6 months or so. I would consider this not valid any longer and close it?

**Comment by DamnWidget** [comment]
I am glad that you didn't had any more problems, let's wait to see what @glenfant feedback is

**Comment by glenfant** [comment]
Hi, consider this issue as closed (for me) since I didn't notice this with the latest anaconda as of today. Thank you for your support and for Anaconda.

**Comment by DamnWidget** [comment]
OK, feel free to open it if you experience more issues
