### ISSUE TITLE
AutoComplete for basic python libraries not working? (os & os.path)

### ISSUE THREAD

**Issue by annblackz** [DamnWidget/anaconda#331]
Hello :) I was trying to use anaconda & I can't seem to get it to do auto completion for the std python libraries such as os & os.path.  I am running on Mac OSX  I have tried to follow some of the basic suggestions in other posts.  When I use jedi directly, I get the following:

Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
>>> from jedi import Script
>>> print (Script('import os.').completions())
[<Completion: path>]
>>> print (Script('import os.path.').completions())
[]

I was hoping it would provide completions for functions and data items available in each of the modules. 

Any advice would be appreciated. I re-installed jedi to the latest release with pip.

**Comment by DamnWidget** [comment]
Hi. Try uninstalling any version of Jedi that you have installed yourself and make sure that your configured Python interpreter path is right.

**Comment by annblackz** [comment]
Awesome - those tips fixed it up for me. THANKS!
