### ISSUE TITLE
import *, autocomplete/docs not working

### ISSUE THREAD

**Issue by ocean1** [DamnWidget/anaconda#333]
Don't know if it's an intended behaviour but i notice that when importing specific submodules anaconda works as expected, but if i just ```import *``` autocomplete and docs tooltips won't be available as I would expect.

**Comment by DamnWidget** [comment]
And how Jedi or PyFlakes would know what is in your scope after you poluted it with everything that si defined in the modules that you import all from them?

**Comment by ocean1** [comment]
There are some packages ( https://github.com/Gallopsled/pwntools ) which "require" this kind of behaviour and include in __all__ everything is needed to use the package.
It somehow worked on an old sublime project i used (or an old version of anaconda i don't know) that's why I filled this bug report.

**Comment by DamnWidget** [comment]
Well, anaconda bases it's autocompletion/docs in Jedi, Jedi will be able to analyze whatever is visible by the Python interpreter that is running the JsonServer but the linting is not gonna work to identify undefined elements in your code.

Make sure the python interpreter that you defined in your configuration is able to see whatever library that you are trying to auto-complete.

**Comment by ocean1** [comment]
It should be visible I did set correctly the virtualenv in the project config, in fact importing a single class/function/whatever shows correctly autocompletion, instead importing * the docs/autocompletion won't work correctly.
Using this:
```
from pwn import *
context(arch='i386', os='linux', log_level="info")
```
the anaconda documentation/go to definition won't work.

If instead I do this:
![schermata del 2015-05-27 18 26 07](https://cloud.githubusercontent.com/assets/745932/7841605/fee34c0c-049d-11e5-96aa-5e4e7e6310d8.png)
as you can see it works correctly (maybe it's a bug with jedi and not anaconda? sorry but didn't knew about jedi)

Linting is not a problem as it doens't show any error/warning if there's an ```import *```.

**Comment by DamnWidget** [comment]
Well, seems like is just happening what I already told you in my first answer, Jedi has no way to know that the `context` object is part of the `pwn` module when you use `*` import as Jedi does a lexical analysis of the python code without executing it (that means that it doesn't import it neither) so specific names should be in your file text for Jedi can process them.

```python
import jedi
jedi.Script('''from pwn import *
context(''').completions()
[]
```

**Comment by ocean1** [comment]
got it thank you! :bow:
