### ISSUE TITLE
Import validator not working

### ISSUE THREAD

**Issue by keathmilligan** [DamnWidget/anaconda#337]
Import validator does not appear to be working using the current code from git.

 "validate_imports": true is set in User/Anaconda.sublime-settings, but entering an obviously bogus import statement shows no error or other indication. Other Anaconda functions (linting, go to definition, etc.) all seem to be working fine.

**Comment by DamnWidget** [comment]
Working pretty fine for me.

![import_check](https://cloud.githubusercontent.com/assets/329766/8009862/813b5238-0ba3-11e5-9d88-93e71bbb642c.png)
![import_check1](https://cloud.githubusercontent.com/assets/329766/8009861/813ac8b8-0ba3-11e5-9773-9893befe92b6.png)

**Comment by keathmilligan** [comment]
All I get is a linter warning about the import not being used, no error. Seeing this on both Windows and Mac.

**Comment by DamnWidget** [comment]
Make sure that you don't override the setting in a more specific
configuration level

On 5 June 2015 at 18:14, keathmilligan <notifications@github.com> wrote:

> All I get is a linter warning about the import not being used, no error.
> Seeing this on both Windows and Mac.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/337#issuecomment-109367435>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by keathmilligan** [comment]
I don't. I've tried adding the setting to my user settings and to the project settings. I added a debug statement to sublime.py and it looks like "validate_imports": true is getting passed to the worker. Any other advice on debugging this?

**Comment by DamnWidget** [comment]
You can take a look at the JsonServer logs, you will get a line saying something about the import validator located at:

* Windows: %APPDATA%\Jedi\Jedi\<YourProjectName>\anaconda_jsonserver.log
* OS X: ~/Library/Cache/Jedi/<YourProjectName>/anaconda_jsonserver.log

**Comment by keathmilligan** [comment]
I see the following message at the beginning of each lint operation:

2015-06-09 08:39:50,186: INFO    : client requests: lint
2015-06-09 08:39:50,200: ERROR   : 'Script' object has no attribute 'goto'
2015-06-09 08:39:50,200: DEBUG   : ['Traceback (most recent call last):', '  File "C:\\Users\\kmilligan\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_server\\commands\\import_validator.py", line 31, in run', "    'errors': [] if v.is_valid() else self._convert(v),", '  File "C:\\Users\\kmilligan\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_server\\handlers\\../../anaconda_lib\\import_validator.py", line 30, in is_valid', '    error, valid = self._validate_import(line)', '  File "C:\\Users\\kmilligan\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_server\\handlers\\../../anaconda_lib\\import_validator.py", line 51, in _validate_import', '    if not Script(module_line, 1, offset, self.filename).goto():', "AttributeError: 'Script' object has no attribute 'goto'"]

**Comment by DamnWidget** [comment]
Ok, seems like you have Jedi installed at your own and your configured Python interpreter is using it instead of the one that comes with Anaconda, try to uninstall Jedi and try again.

This conflict problem is an issue that should be addressed sometime in the future anyway.

**Comment by keathmilligan** [comment]
I have no jedi in site-packages or anywhere else on my system except in anaconda_lib.

**Comment by DamnWidget** [comment]
If is not very painful, completely remove Anaconda from your Sublime Text 3, then remove Sublime Text 3 itself including any configuration or user data, install Sublime Text 3 again and then install anaconda in a fresh ST3 installation.

There is something very wrong in your installation.

**Comment by keathmilligan** [comment]
Same results:

Uninstalled ST3, verified no residual data left in Program Files
Deleted AppData\Local\Sublime Text 3
Deleted AppData\Roaming\Sublime Text 3
Deleted AppData\Roaming\Jedi
Installed ST3
Installed PackageControl
Installed Anaconda via PackageControl
Enabled "validate_imports": true in Anaconda user settings and in project settings section.

I see the same error in the Jedi log.

**Comment by DamnWidget** [comment]
Open file `anaconda_lib/import_validator.py` and change line 5 to:
```python
 if not Script(module_line, 1, offset, self.filename)._goto():
```

Let me know if it worked for you

**Comment by keathmilligan** [comment]
Closer. It now appears to be running the check and finding the invalid import, but highlights the wrong line:

![capture](https://cloud.githubusercontent.com/assets/2936304/8064460/78dae5f4-0ea0-11e5-9f87-aaff24e832bf.PNG)

**Comment by keathmilligan** [comment]
It looks this issue is related to docstrings. If I remove the docstring or change it to a # comment, it highlights the correct line.

**Comment by DamnWidget** [comment]
The funny part is that this feature perfectly work for me using the last anaconda version. I don't have too much time lately but I will try to give this a look on weekend.

**Comment by DamnWidget** [comment]
I fixed the wrong call to the deprecated `goto` method, need to investigate the wrong line linting still, hopefully I will have a bit more of time to look after the plugin next week.

**Comment by Effenberg0x0** [comment]
Hi DamnWidget. Thank you so much for Anaconda. [My pull request](https://github.com/DamnWidget/anaconda/pull/510) seems to fix the problem with the wrong line being highlighted when validating imports. Regards.
