### ISSUE TITLE
Small Inconsistency in the documentation

### ISSUE THREAD

**Issue by NotTheEconomist** [DamnWidget/anaconda#338]
Hi there,

Not sure where else to put this, but in the documentation on advanced configuration http://damnwidget.github.io/anaconda/anaconda_settings/ the section "Overriding details per project" explicitly tells you to put settings such as `"python_interpreter"` in a `"settings"` dictionary and gives you an example thereof.

>To edit your project configuration file just go to Project > Edit Project. The options must be placed inside the settings dictionary

>```
{
    "build_systems":
    [
        {
            "name": "Anaconda Python Builder",
            "selector": "source.python",
            "shell_cmd": "/home/damnwidget/.virtualenvs/anaconda/bin/python -u \"$file\""
        }
    ],
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ],
    "settings":
    {
        "python_interpreter": "/home/damnwidget/.virtualenvs/anaconda/bin/python"
        ...
    }
}
```

Immediately afterwards, in the "Configuring the Python Interpreter" section, the example shows

>Exaple of project configuration (~/projects/my_project/MyProject.sublime-project):
(*note the typo above, but unrelated to issue below*)
>```
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ]
    "python_interpreter": "~/virtualenvs/my_project/bin/python"  # in global dict??
}
```

Do I just not understand, or is the second example incorrect?

**Comment by DamnWidget** [comment]
The second example is incorrect. You can amend it yourself and make a pull request (if you want of course) into the documentation project in https://github.com/DamnWidget/anaconda.github.io

Thank you, good catch.

**Comment by NotTheEconomist** [comment]
@DamnWidget Thanks for pointing me at the right repo. I've submitted a PR there.

**Comment by DamnWidget** [comment]
Merged in the other repo
