### ISSUE TITLE
anaconda_linter_show_errors_on_save is using old buffer

### ISSUE THREAD

**Issue by hyperknot** [DamnWidget/anaconda#339]
I am trying to have the same behaviour from Anaconda lint as from Flake8Lint.

I set the following settings:

```
"anaconda_linting_behaviour": "save-only",
"anaconda_linter_show_errors_on_save": true
```

With these settings, Anacoda does indeed show the errors on save, but it shows the errors from the **previously saved** buffer. Thus the errors don't make any sense, unless you save the file **twice**.

**Comment by DamnWidget** [comment]
Are you sure of that?
As you can see in [the related code](https://github.com/DamnWidget/anaconda/blob/master/listeners/linting.py#L88-L100) this feature is called **after** the buffer has been saved.

**Comment by hyperknot** [comment]
Yes, I've even made a video about it:
https://youtu.be/MdLU51O0c9U

I did a bit of debugging, and what I found out is that `run_linter(view)` doesn't update the ANACONDA object.

Try this code:
```
def on_post_save(self, view):
        """Called post file save event
        """

        print(ANACONDA['WARNINGS'])
        if check_linting(
                view, NOT_SCRATCH | LINTING_ENABLED, code=self.lang.lower()):
            if self.lang in view.settings().get('syntax'):
                self.run_linter(view)
                print(ANACONDA['WARNINGS'])
                if get_settings(
                        view, "anaconda_linter_show_errors_on_save", False):
                    sublime.active_window().run_command('anaconda_get_lines')
        else:
            self._erase_marks_if_no_linting(view)
```
You'll see that the lines are the same, before and after `run_linter(view)`.

It seems that ANACONDA dict is being cached somehow in Python.

**Comment by DamnWidget** [comment]
The video wasn't necessary but thank you for take your time to make it :). I will take a look on that as soon as I can, there are lot of features in anaconda that I don't even use, this is one of them so I never noticed that problem, thank you for the report.

**Comment by mdalpi** [comment]
I can confirm this issue as well :+1:

**Comment by DamnWidget** [comment]
This issue has been fixed, it was related to the asynchronous nature of Anaconda. It will be available in the next release, probably tomorrow or next Saturday
