### ISSUE TITLE
Anaconda cannot spawn a new process error.

### ISSUE THREAD

**Issue by Sudeepto** [DamnWidget/anaconda#346]
I have Sublime Text 3 build 3086 installed on my *Windows 8.1 x64* .  Recently when I started Sublime Text, a pop up window appeared saying ""Anaconda can not spawn a new process with your current configured python interpreter (C:\Python27\python.exe), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: C:\Python27\python.exe" 

I have Python 3.4.3 installed on **D:\Python34** folder. I have also set the environment variable to point to that folder. So I have no problem in running python from the command prompt. I have also installed python 2.7.6 on **D:\Python27** folder and set the environment variable to point to that folder. 

I apologize because I know some has already informed about this issue at #314  
But I was not able to understand how to solve the issue.

Please tell me how to solve this problem . I don't get this issue on my LInux Mint 17.1 x64 bit OS. 

I am attaching the images of the error window, as well as the output of the sublime text console. 

![anaconda_error](https://cloud.githubusercontent.com/assets/3418193/8271593/6cba53e4-183d-11e5-81b1-c723f9a4b4f0.JPG)

![sublime_command_prompt](https://cloud.githubusercontent.com/assets/3418193/8271594/73e6e862-183d-11e5-880b-ad30676972a3.JPG)

**Comment by DamnWidget** [comment]
Try to use "D:\\Python34\\python.exe" as absolute route as your python
interpreter (or whatever route that interpreter is on)

**Comment by Sudeepto** [comment]
@DamnWidget 
You mean I should set the system **path** variable from **D:\Python34** to     **D:\Python34\python3.exe** ?? I have the python3.exe executable inside the Python34 directory.

**Comment by DamnWidget** [comment]
No, I mean you set the absolute route to your Python interpreter in the
Anacoda.Sublime-settings file or in your project configuration to make sure
that context and environment is not messing around.

On 22 June 2015 at 13:28, Sudeepto <notifications@github.com> wrote:

> @DamnWidget <https://github.com/DamnWidget>
> You mean I should set the system *path* variable from *D:\Python34* to
> *D:\Python34\python3.exe* ?? I have the python3.exe executable inside the
> Python34 directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/346#issuecomment-114084656>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom
