### ISSUE TITLE
Tooltips on User Defined Functions

### ISSUE THREAD

**Issue by 4StarGeneral** [DamnWidget/anaconda#348]
Hi, I'm a newbie so maybe my question is a little bit silly... anyway, is there a way to edit tooltip options in order to display hits on a user defined functions?

**Comment by DamnWidget** [comment]
Not sure to understand what you mean here

**Comment by 4StarGeneral** [comment]
Sorry, my fault, as you might understand, english isn't my first language...

Anyway, let's say I've create a new function called  func(a,b)

I'd like to know whether I can create a custom tooltip for it
like the one below

https://camo.githubusercontent.com/5c81c99de6ba44b2de6327aeaff7fcb91a9a3f57/687474703a2f2f64616d6e7769646765742e6769746875622e696f2f616e61636f6e64612f696d672f746f6f6c746970732e706e67

Ah ty for reply :)

**Comment by DamnWidget** [comment]
What the tooltip is doing is just taking a function/class docstring and signature and formatting it. It will already display any docstring/signature for any function that you defined in your project.

**Comment by 4StarGeneral** [comment]
ty
