### ISSUE TITLE
Support for extra package path?

### ISSUE THREAD

**Issue by Cissoid** [DamnWidget/anaconda#350]
I store my code in HOME directory, so that the ImportValidator always reports "can't import module", even if I created a .pth file into site-packages folder.

The *Jedi Autocompletion* sublime plugin has a configure option named "python_package_paths", it allow to add additional package path.

I saw *Anaconda* also use Jedi for auto completion support, why not add this option too?

**Comment by DamnWidget** [comment]
The described feature has been always supported by the plugin since the first release, take a look in the dcoumentation: http://damnwidget.github.io/anaconda/anaconda_settings/#toc_5
