### ISSUE TITLE
some problems with class __init__ ?

### ISSUE THREAD

**Issue by okuteur** [DamnWidget/anaconda#351]
Hi,

i'm a bit new with anaconda but i fail to initialize a class

sublime text 3 build 3083
anaconda 1.4.11
python 3.4

example:

class Connexion:
    def __init__(self):
        print("created object !")

print("toto1")

test_object = Connexion()

print("toto2")

the result is only:
>>toto1

if i use the command line (manually)
>>toto1
>> created object !
>>toto2

My setup is bad ?

**Comment by DamnWidget** [comment]
I am afraid that I don't understand the question, what are you trying to do?

**Comment by okuteur** [comment]
hi 

sorry the question is missing ...

The __init__ of the class didn't return anything, when i run with SublimText + anaconda unlike when i run the same class with command promp.

Do I need configure something more ?

**Comment by DamnWidget** [comment]
A part from the fact that the `init` method must be `__init__` everything else looks fine, in fact, it do the expected thing when you fix the `__init__` method.

```
created object !
toto1
toto2
[Finished in 0.3s]
```

**Comment by okuteur** [comment]
the underscore is missing cause i dont find the code tag (sorry)

**Comment by okuteur** [comment]
I just re-installed Anaconda and now all is fine ...

**Comment by DamnWidget** [comment]
I am happy to know that your "toto" printing is now working :)
