### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by bensheff** [DamnWidget/anaconda#354]
I'm running sublime text 3 on windows 7 with anaconda, and usually within an hour of starting up the program, task manager will list a python process eating up to three GB of RAM. When I force quit it, sublime throws an error, saying the windows socket is unstable

**Comment by DamnWidget** [comment]
Hi, Ok but we need more information.

ST3 Version 
Anaconda Version
Console Logs
Anaconda JsonServer Logs (localted in %APPDATA%\Jedi\Jedi\<your_project_name>\anaconda_jsonserver.log

Your anaconda's configuration
Since when this happens?
Can you replicate the problem always that you want?

**Comment by bensheff** [comment]
Sublime Text 3, build 3083
Anaconda 3
Assuming you're talking about the console where error information and code output is placed, the jump in used RAM happens while coding, not in any correlation I can find with compiling. The error appears in a separate window, with the following text:
"Unfortunately, the Windows socket is in inconsistent state, restart your sublime text 3. If the problem persist, fill an issue report on: https://github.com/DamnWidget/anaconda/issues"

The jsonserver log is rather large. I haven't used Git very much, how should I upload the file?

I don't think I've changed anything from the default configuration, but it was a while ago, and I'm not sure how to check. The user specific settings for anaconda file is empty.
It's been happening for a while, order of magnitude a couple weeks maybe.

I cannot replicate the problem at will, just after working for a while, my computer will slow down dramatically as some process labelled python.exe suddenly eats all my RAM.

**Comment by DamnWidget** [comment]
You can create a gist to paste the contents of the log file.

On 17 July 2015 at 17:41, bensheff <notifications@github.com> wrote:

> Sublime Text 3, build 3083
> Anaconda 3
> Assuming you're talking about the console where error information and code
> output is placed, the jump in used RAM happens while coding, not in any
> correlation I can find with compiling. The error appears in a separate
> window, with the following text:
> "Unfortunately, the Windows socket is in inconsistent state, restart your
> sublime text 3. If the problem persist, fill an issue report on:
> https://github.com/DamnWidget/anaconda/issues"
>
> The jsonserver log is rather large. I haven't used Git very much, how
> should I upload the file?
>
> I don't think I've changed anything from the default configuration, but it
> was a while ago, and I'm not sure how to check. The user specific settings
> for anaconda file is empty.
> It's been happening for a while, order of magnitude a couple weeks maybe.
>
> I cannot replicate the problem at will, just after working for a while, my
> computer will slow down dramatically as some process labelled python.exe
> suddenly eats all my RAM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/354#issuecomment-122336236>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by bensheff** [comment]
All right, here:
https://gist.github.com/98fe8b8edf3abcf9491e.git

**Comment by DamnWidget** [comment]
I get a 404 error when I use that link

**Comment by bensheff** [comment]
weird, maybe without the .git?: https://gist.github.com/98fe8b8edf3abcf9491e

**Comment by DamnWidget** [comment]
Right, the log seems quite normal to me. Is gonna be hard to know what the problem can be. I know sometimes jedi can allocate lot of memory to parse big modules like PyQt or NumPy but I can't tell you more as I can't replicate the problem even using those big modules (I mean, the allocation is done but the memory usage is consistent).

That's probably some kind of obscure bug related with Windows platform inside Jedi or inside the Anaconda async loop, hard to debug I am afraid.

**Comment by bensheff** [comment]
I am using pyqtgraph and pyqt4, if that could be a cause. Otherwise, it seems manageable as long as I keep task manager open to watch for the leak to spring.

**Comment by DamnWidget** [comment]
Take a look on sys manager and let me know if you spot when exactly the problem appears

**Comment by bensheff** [comment]
what is sys manager?

**Comment by DamnWidget** [comment]
I meant "task manager"

On 21 July 2015 at 20:59, bensheff <notifications@github.com> wrote:

> what is sys manager?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/354#issuecomment-123461624>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom
