### ISSUE TITLE
autocomplete fails when importing some moudules

### ISSUE THREAD

**Issue by Cescfangs** [DamnWidget/anaconda#355]
>With OS X 10.10.4, sublime text3 and anaconda, python3 and PyQt5 installed by Homebrew, other packages installed by pip3.

After searching and reading several pages,  understood that there's nothing special about installed by brew or pip, all packages are in the same path `/usr/local/lib/python3.4/site-packages`, and `PyQt5` is not the only package can't be autocompleted, other packages installed by pip such as `envelopes` fails either. 
However, with IPython, autocomplete works for all moudules, maybe there's something to do with python interpreter path, so i tried ` "path": "$PATH:/usr/local/Cellar"`,  `"path": "$PATH:/usr/local/Cellar/"`,`"path": "$PATH:/usr/local/Cellar/python3/3.4.3_2/bin"` ,`"path:""/usr/local/bin/python3"`( the path got from `which python3` in terminal), but none of them worked.

**Comment by DamnWidget** [comment]
Take a look at the README.md in the landing page -> https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly

**Comment by Cescfangs** [comment]
Thanks for the quick reply!
the autocomplete for `import` trouble solved after reading #89 ;
how about the autocomplete for the package installed by brew?

**Comment by DamnWidget** [comment]
Anaconda should be able to "see" whatever your configured python interpreter can "see", if your interpreter can see and use those modules, anaconda should too.

**Comment by Cescfangs** [comment]
Yeah，the configured python interpreter can "see"(PyQt5 autocompleted in IPython and Python shell ), and the script `import PyQt5` run successfully using sublime text and terminal, but still no autocomplete in sublime text with anaconda.

**Comment by Cescfangs** [comment]
Edited this issue, any updates?

**Comment by DamnWidget** [comment]
Hi
I just tested this in my Linux box and it just works as expected. Are you sure that your configured python interpreter is right?

![pyqt4](https://cloud.githubusercontent.com/assets/329766/8827934/78166194-3087-11e5-9053-91ac1471e585.png)

**Comment by Cescfangs** [comment]
I am not sure about that, tried several path, all successfully ran, but no autocomplete,  how did you configured the python interpreter? Is there anything to do with sublime python path?

**Comment by DamnWidget** [comment]
Nope, this is my configuration:

```json
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "python -u \"$file\""
		}
	],
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "."
		}
	],
	"settings":
	{
		"python_interpreter": "python"	
	}
}
```
PyQt was installed using `apt-get install python-pyqt`

**Comment by Cescfangs** [comment]
I was so stupid!!! sorry, that's all my fault.
After reading your configuration, I found that I made a really stupid mistake, somehow edited the` "python_interpreter":` to `"path":`, I confused it with sublime python path. 
Anaconda works perfect now, best plugin of sublime!!!

**Comment by DamnWidget** [comment]
Closing that then :)

**Comment by aleksbykov** [comment]
@DamnWidget Hi Guys.
Got this error again and explicitly for PyQt5 package
I use ubuntu 19.10, install pipenv --python 3.8, install with pipenv PyQt5.
change in project settings python_interpreter: to valid interpreter in pipenv.
And autocomplete doestn't work only for PyQt5. It even doesn't appear in moduls in Sublime.
Installed in same virtual_env with pipenv any other package (paramiko) works fine.

**Comment by aleksbykov** [comment]
The issue looks, like json server is not started with python interpreter from project settings. It started with global python interpreter. Once i switch the in anaconda default settings to pipenv python interpreter, the json server started with it and autocomplete works perferct
