### ISSUE TITLE
"from import" autocomplete

### ISSUE THREAD

**Issue by mdalpi** [DamnWidget/anaconda#359]
Hi, it's actually a question: when I type "from" + space, the suggestions doesn't appears. Is this the correct behavior? It's weird because if I press Ctrl + Space, the suggestions do appears.

Also, using "import" + space the suggestions appears right after the space. I'm using autocomplete on dot (http://damnwidget.github.io/anaconda/IDE/#toc_2) and the workaround for the imports (https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly).

Thanks

OS X 10.10.4
Sublime 3 Build 3083
Latest Anaconda via Package Manager

**Comment by DamnWidget** [comment]
That's not WAI, the auto completion box should appear by himself. Said
that, take into account that anaconda does not fire the auto completion box
but hooks into regular ST3 one.
