### ISSUE TITLE
How to force Anaconda Autoformat pep8 to not put new line before docstring in class?

### ISSUE THREAD

**Issue by utek** [DamnWidget/anaconda#361]
I've tried:
```
	"autoformat_ignore":
	[
		"D203",
	]
```

and 

```
	"autoformat_ignore":
	[
		"E301",
		"E26"
	]
```

**Comment by DamnWidget** [comment]
All of the autoformat_ignore fields are passed to the autopep8 as the
command line option `--ignore=E301,E26` in your case, try to run autopep8
from the command line passing those arguments to see if the behaviour is
different.

On 12 August 2015 at 15:50, Łukasz Bołdys <notifications@github.com> wrote:

> I've tried:
>
>     "autoformat_ignore":
>     [
>         "D203",
>     ]
>
> and
>
>     "autoformat_ignore":
>     [
>         "E301",
>         "E26"
>     ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/361>.
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by utek** [comment]
It looks like it's "E309". Sorry fot that. Thanks for great plugin.
