### ISSUE TITLE
python-3.4 99,5% cpu usage on osx

### ISSUE THREAD

**Issue by eduedix** [DamnWidget/anaconda#362]
High CPU usage when Anaconda is enabled in Sublime. I think it is running something in the background but I do not know how to figure out what the real problem can be.

I do not have anything special setting for Anaconda in Sublime. Sublime Build: 3083, anaconda is the latest version from Package Control.

In OSX Activity Monitor, python-3.4 seems to have a very high CPU time and errors just keep increasing. Please direct me on how to help you further on this issue.

**Comment by DamnWidget** [comment]
Do you have the autoformating enabled?

**Comment by eduedix** [comment]
No, I do not think so, though could you tell me how I could check it up?

**Comment by eduedix** [comment]
Sorry for late response, but did you mean PEP8 Autoformatting? I have it enabled on save.

**Comment by DamnWidget** [comment]
Try to deactivate it, probably is that

**Comment by yanenok** [comment]
running into the same issue, pep8 autoformatting disabled
