### ISSUE TITLE
Highlight ALL decorators AND function declaration on decorated duplicate declaration.

### ISSUE THREAD

**Issue by pradyunsg** [DamnWidget/anaconda#363]
Currently, when a function/method has decorated duplicated declaration, only the first decorator is highlighted.

Currently, here's what happens:
![anaconda-decorated-duplicated-function](https://cloud.githubusercontent.com/assets/3275593/9292262/ca3f8986-440b-11e5-85d6-b12182176851.png)

The desired behaviour in my opinion should be to highlight all decorators and the duplicate function declaration which means line 10 should **also** be included in the outline.

**Comment by DamnWidget** [comment]
I understand that the function definition starts in the decorator and not
in the "def" and that is why the decorator get highlighted.

Anyway this is how PyFlakes works, that behaviour is not defined into
anaconda but PyFlakes. If you want to see that behaviour changed, you
should put yourself in contact with PyFlakes maintainers.

**Comment by pradyunsg** [comment]
I understand what you are saying. And I agree with this behaviour on PyFlake's side.

In fact, I'm saying that this should be special-cased in Anaconda. It should show the outline till the line containing the `def`.

**Comment by Stibbons** [comment]
I don't think this is legal, you should not have 2 members of your module with the same name, one will overwrite the other, from the point of view of outside modules (it should work thou).

Pylint does the same error.

**Comment by pradyunsg** [comment]
That's the point. Any error regarding a decorated function should highlight both the decorators as the function definition line.

**Comment by Stibbons** [comment]
Indeed, but I think this is more a pyflex (or pylint) error :)

**Comment by pradyunsg** [comment]
Just in case, I have used the word "also".

**Comment by pradyunsg** [comment]
Bump.

@Stibbons 
> I don't think this is legal
It's perfectly legal Python code. Check out https://pypi.python.org/pypi/multipledispatch . This is how it works. But that's beside the point... The point is 

@DamnWidget 
PyFlakes' behavior is correct as it stands. What I am suggesting is that Anaconda should make an outline/highlight the decorators as well as the entire function name and parameters (from `def` to `:`). Some extra handling by Anaconda, for it's special use case.

Now that I am revisiting it, I'm not really feeling strongly about this but you're up to decide what to do.

**Comment by DamnWidget** [comment]
Honestly, I barely have time to maintain anaconda, I can't expend the amount of time that such feature will cost but as always I am open to PR's and contributions.

**Comment by pradyunsg** [comment]
Sure. No issues. I guess I'll just close this issue now.
