### ISSUE TITLE
How to disable comment linting?

### ISSUE THREAD

**Issue by octohedron** [DamnWidget/anaconda#364]
Anaconda keeps telling me there are errors in my comments, i don't want to lint my comments, only the code that is not a comment. How can i do this? 

Thanks

**Comment by DamnWidget** [comment]
Can you provide an screenshot please?

On 20 August 2015 at 17:11, octohedron <notifications@github.com> wrote:

> Anaconda keeps telling me there are errors in my comments, i don't want to
> lint my comments, only the code that is not a comment. How can i do this?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/364>.
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by octohedron** [comment]
Hello, there is no need for a screenshot, i just want to disable all linting for comments, i don't want comments to be linted at all, my program runs smooth i just don't want to have anaconda linting my comments.

**Comment by DamnWidget** [comment]
Thank you for your clarification about you don't wanting anaconda to lint
your comments, that's great, I already understood that reading the first
post.

Now, said that, anaconda *does not* lint your comments or docstrings unless
you configure it to do it, this is why I am asking about a screenshot as I
am guessing that if you don't want it to lint your comments, you didn't
enable the comments/docstrings linting so I need to see what that "linting"
that you are referring to looks like to know if you just enable any option
by mistake or there is another problem in there.

Now, can you please provide an screenshot?

Thanks.

On 20 August 2015 at 17:21, octohedron <notifications@github.com> wrote:

> Hello, there is no need for a screenshot, i just want to disable all
> linting for comments, i don't want comments to be linted at all, my program
> runs smooth i just don't want to have anaconda linting my comments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/364#issuecomment-133065214>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by DamnWidget** [comment]
Bad indentation is PEP8 violation E114, you shouldn't get any complaint from anaconda about that if you configure your sublime text to use 4 spaces as tabs, you can also disable E114 from the pep8 errors but I wouldn't do that.

What are the "other errors" that you spoke about in your previous comment? Anaconda doesn't parse comments contents.

**Comment by octohedron** [comment]
No i dont meant the content of the comments, i want the comments to be left alone 100%

**Comment by DamnWidget** [comment]
The comment is part of the document structure, if your document structure has a violation, it's gonna be linted, as I said, if you don't want to get a lint about a document structure violation just add the violation code to the `pep8_ignore` list.

**Comment by octohedron** [comment]
no, i just want to ignore the errors for comments, could you add this feature in the future? because i want my comments in different ways so it would be nice to simply be able to disable linting for comments completely
![example](http://i.imgur.com/lnS3dqF.png)

**Comment by DamnWidget** [comment]
The E303 has nothing to do with the comment but with too many blank lines in the document.

You can add E266 and E265 to the pep8_ignore list in the settings and anaconda will ignore them.

**Comment by octohedron** [comment]
Okay, that will do :) ty.

**Comment by soulslicer** [comment]
I tried doing this and it does not work

>     "pep8_ignore":
>     [
>         "E309",
>         "E501",
>         "E266",
>         "E265"
>     ]

This gives me those unrequired errors
