### ISSUE TITLE
Mac OS X Show tooltip with docstring with cyrillic text issue

### ISSUE THREAD

**Issue by ikwado** [DamnWidget/anaconda#366]
1. From file with class definition works fine
   <img width="811" alt="screenshot 2015-08-22 11 26 12" src="https://cloud.githubusercontent.com/assets/3368268/9423192/9f38c160-48c2-11e5-8007-84b7535f2a30.png">
2. From other files there is encoding issue with docstring in tooltip
   <img width="899" alt="screenshot 2015-08-22 11 26 32" src="https://cloud.githubusercontent.com/assets/3368268/9423194/ab468c26-48c2-11e5-90bd-aa48bd659c1e.png">

**Comment by ikwado** [comment]
Same problem on linux too

**Comment by DamnWidget** [comment]
I think this was fix in #481 

Feel free to open if the problem persist
