### ISSUE TITLE
Autocompletion for NumPy and PyQt4 works only in debug mode

### ISSUE THREAD

**Issue by membranepotential** [DamnWidget/anaconda#368]
I'm on Anaconda 1.4.12, Sublime Build 3083, the Anaconda Python distribution on Mac OSX.
The Autocompletion/Documentation features do not work for NumPy and PyQt4, but for other (smaller) packages they work.
I tried to check the server's debug mode to see what's going on, this resolved the issue. However, after going back to normal, it stopped working.
Would be cool to get it to work =)

**Comment by DamnWidget** [comment]
Probably a miss configured python path when you are not using the debug mode, we've seen this problem before and thee culprit was always that.

Make sure that you have a valid python interpreter configured as your `python_interpreter` in all your configuration levels.

**Comment by membranepotential** [comment]
I set the python_interpreter to the "/anaconda/bin/python3.4". This solved the issue. Thank you!
