### ISSUE TITLE
docstring support chinese

### ISSUE THREAD

**Issue by tongguang** [DamnWidget/anaconda#369]
hello
       I encountered a problem, that is when I described in the document which contains the Chinese, the document cannot be effective. So I try to solve it.  I found the documentation string generation place. After the query data, may be the encoding problem. So I add
import sys
reload(sys)
sys.setdefaultencoding('utf-8')  
 in C:\Users\tongguang\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\commands\doc.py
![image](https://cloud.githubusercontent.com/assets/9032204/9705498/fb6b12e8-54f8-11e5-90ed-302344977b21.png)

Set encoding.
So the docstring can show Chinese. Like this
![image](https://cloud.githubusercontent.com/assets/9032204/9705495/ebca2022-54f8-11e5-9ab2-4504c0506533.png)

So I suggest that you add this encoding support.
Thank you

**Comment by tongguang** [comment]
Please forgive my poor English。。。。

**Comment by DamnWidget** [comment]
Sorry guys, I've been really busy lately, I will make a fast release with these changes as soon as possible

**Comment by DamnWidget** [comment]
Looking at the suggested solution, I am not sure if I want to reload the whole sys module, it scares me a bit

**Comment by tongguang** [comment]
I have found some information, many people use this method, or ,can you have other ways to ensure that encoding is UTF-8 ?utf-8 is very good for like chinese.

**Comment by DamnWidget** [comment]
This should not be a problem anymore

**Comment by tongguang** [comment]
thanks
