### ISSUE TITLE
Mac OS X 10.11 Beta 6: Cannot connect to jsonserver.py

### ISSUE THREAD

**Issue by ColtonProvias** [DamnWidget/anaconda#370]
Returned error is:

```
ERROR:root:[Errno 61] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/Users/coltonprovias/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/Users/coltonprovias/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/Users/coltonprovias/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```

The error is still returned even when running the server in debug mode.  Just using urllib from the console shows that I can connect with the server running in debug mode.

**Comment by DamnWidget** [comment]
Hi. Are you 100% sure that you can connect to localhost from the Sublime Text 3 python embedded interpreter?

**Comment by ColtonProvias** [comment]
Yes, I am 100% certain.

**Comment by DamnWidget** [comment]
If you can connect from the embedded Sublime Text 3 interpreter (using the ST3 console) to the JsonServer there is nothing that could prevent anaconda to do the same, in fact, if that is happening to you, there is really nothing that I can do about, the package just start the JsonServer process in your machine in the port N and then connect's to it, that simple.

If that is really your problem, my only suggestion is to deinstall your ST3 completely removing anything in `/Users/coltonprovias/Library/Application Support/Sublime Text 3`

**Comment by ColtonProvias** [comment]
Reinstalling ST3 did not fix the issue.  What ended up fixing it was building Python via homebrew instead of using the system-installed Python.
