### ISSUE TITLE
Anaconda messes with vintage keybindings

### ISSUE THREAD

**Issue by dvcrn** [DamnWidget/anaconda#373]
Hi, I found this snippet here inside the Default keymap

```
    {"command": "anaconda_goto", "keys": ["g", "d"],
        "context":
        [
            { "key": "selector", "operator": "equal", "operand": "source.python" },
            { "key": "setting.command_mode", "operand": true },
            { "key": "setting.is_widget", "operand": false }
        ]
    },
```

This effectively messes with the vim keybindings due tue SublimeTexts way of handling keybindings. 

`g g` in vintage will jump to the top of the file, but since this is bound as a vintage command and not as a sublimetext command, it does not use the keymap system. Defining `g d` as a anaconda shortcut inside SublimeTexts key binding system will jam the `g` key until it is either resolved by a timeout or a second key has been pressed. So now for all `g`-related commands inside VIM, you have to press `g g`

`g g` for normal `jump to top of the file` suddenly becomes `g g g` for `jump to top of the file` inside python files.

**Comment by dvcrn** [comment]
Ref - https://github.com/DamnWidget/anaconda/issues/124 and https://github.com/DamnWidget/anaconda/pull/126

**Comment by yichuan1118** [comment]
For me, on OSX 10.11, adding back this keymap is not messing with default vim key binding. 'g g' still works as expected.
