### ISSUE TITLE
Tooltips Stuck on Top

### ISSUE THREAD

**Issue by dabeastro** [DamnWidget/anaconda#377]
Linux using multiple workspaces. When moving from sublime to another applications, the tooltip appears overtop the applications. 

![selection_001](https://cloud.githubusercontent.com/assets/4381132/10322108/7a46b91c-6c39-11e5-9778-ab0f99b0e18e.png)

**Comment by DamnWidget** [comment]
That is a bug in Sublime Text itself and as far as I know, it was reported some few months ago
