### ISSUE TITLE
Ubuntu Unity keybinding collision

### ISSUE THREAD

**Issue by Railslide** [DamnWidget/anaconda#378]
On Ubuntu - with Unity as a desktop environment - the keybindings 
```{"command": "anaconda_goto", "keys": ["super+g"]},
    {"command": "anaconda_find_usages", "keys": ["super+f"]} ```

collide with Unity lenses keybindings (social and file lens).
The problem can of course be avoided by overriding those keys with custom ones.

For the record, I've changed Anaconda keybindings to:
```
{"command": "anaconda_goto", "keys": ["ctrl+alt+g"]},
{"command": "anaconda_find_usages", "keys": ["ctrl+alt+f"]},
{"command": "anaconda_doc", "keys": ["ctrl+alt+d"]},
{"command": "anaconda_auto_format", "keys": ["ctrl+alt+r"]}
```
(I've changed them all for a matter of consistency)

**Comment by DamnWidget** [comment]
Hi @Railslide 

Can you please make a PR with your proposal?

**Comment by Railslide** [comment]
Just opened a PR. Is the documentation automatically generated from somewhere? Or can I just edit the markdown file in the doc repo?
