### ISSUE TITLE
how to set max-line-length?

### ISSUE THREAD

**Issue by s-trooper** [DamnWidget/anaconda#38]
how to set max-line-length for pep8?

**Comment by atc-** [comment]
If you ended up here through Google like I did; in Sublime Text 3 you can set the following through "Preferences -> Package Settings -> Anaconda -> Settings - User":

`{ "pep8_max_line_length": 120 }`

**Comment by thefourtheye** [comment]
@atc- Thanks :) It works. :+1:

**Comment by srugano** [comment]
It doesn't work for me.

**Comment by DamnWidget** [comment]
It has to work @srugano 
how and where are you configuring `pep8_max_line_length`?

**Comment by kaijan** [comment]
for those who google to here.

If the "pep8_max_line_length" doesn't work, try to remove the Python Pep​8 Lint plugin, and use "anaconda" for lint check.

It works for me.

**Comment by JayRizzo** [comment]
@DamnWidget

I know this is an old post but found myself here, 
and wanted to share that  I was able to find this differently then @atcol,

I found it in Sublime Text 3 under:
"Preferences" > "Package Settings" > "SublimePythonIDE" > "Settings - Default"
Make your defaults here or set them in "Settings - User" as per usual.

**Comment by DamnWidget** [comment]
@JayRizzo SublimePythonIDE is another plugin

**Comment by mangatinanda** [comment]
For VSCode, add this in your User Settings file
```json
"python.linting.pep8Enabled": true,
"python.linting.pep8Args": ["--max-line-length=120" ]
```

**Comment by sheecegardezi** [comment]
For Pycharm, 
click on the long line
press ALT+Enter
select ignore errors like this.

**Comment by shravantal** [comment]
This is way set to `max-line-length`
`pycodestyle --max-line-length=120 test_pep8_tc.py`

**Comment by finalcreator** [comment]
> If you ended up here through Google like I did; in Sublime Text 3 you can set the following through "Preferences -> Package Settings -> Anaconda -> Settings - User":
> 
> `{ "pep8_max_line_length": 120 }`

yyds
