### ISSUE TITLE
goto definition in vintage mode ('gd') is not working after Anaconda update

### ISSUE THREAD

**Issue by yichuan1118** [DamnWidget/anaconda#380]
Hi Author of Anaconda,

Thanks for this awesome tool!

It was working great, after upgrade v1.4.13, goto definition in vintage mode ('gd') is not working.
Using the Anaconda -> goto definition in the context menu still works.

Sublime Text 3 Build 3083, Mac OSX 10.11

**Comment by DamnWidget** [comment]
Take a look here https://github.com/DamnWidget/anaconda/issues/373

**Comment by yichuan1118** [comment]
Got it, thanks!
