### ISSUE TITLE
i hav a problem of running anaconda on sublime text 3

### ISSUE THREAD

**Issue by gucharles** [DamnWidget/anaconda#386]
my st3 version : 3083
my anaconda version : latest one
window 7
python : 2.7.1

Hi there, thanks for the patience. Actually i am new to this world and i really want to use sublime text collaborated with anaconda.

And my problem is i cannot run tests, if i run it, it returns the message like this:

 [Finished in 0.0s with exit code 1]
[shell_cmd: nosetests 1]
[dir: C:\Users\Administrator\Desktop\new folder]
[path: C:\\Python27\\python.exe;C:\\Python27\\python.exe]

While if i use the normal method which is ctrl+B, everything is good.

And i read your discussion on 
"Anaconda can not spawn a new process with your current configured python interpreter #314"

so i tried to fix the problem myself, i tried to edit the helpers.py
And here is the log file
http://pastebin.com/z87SMD9x

sorry, really hav no idea what's going on there, hope you can help me out of it.

**Comment by DamnWidget** [comment]
Looks like your ST3 python embedded interpreter is a mess, it is missing
the subprocess module try to completely remove ST3 from your system
(including plugins, options and cache) and reinstall it from scratch.

**Comment by gucharles** [comment]
haha,all right, thanks a lot for your quick response.
i will try it know and keep you informed.

**Comment by gucharles** [comment]
ok, I reinstall the ST3 and download a new portable version which i think is cleaner, i hope
and now the problem is like this

http://pastebin.com/uDYUygMk

which seems index out of range is a problem right?
I saw the code you put on the website to edit helper.py
https://github.com/DamnWidget/anaconda/commit/24fe240a3912219fe684102f6dea442feb0640c2
But unfortunately i can not follow it maybe lots of changes have been made during the two years right.

So what s next step to fix the problem?

Thanks  ^^

**Comment by DamnWidget** [comment]
Hi
I've seen this problem happen to other users and was related with the way that ST3 handles the it's cache, for some reason your ST3 thinks you don't have any open directory in your interpreter. You have to delete all the ST3 cache files (probably in %APPDATA%) after uninstall it, I can't find the specific issue were that problem was exposed in the past but is here in the issues (maybe a closed one)

P.S: you can see your cache path using this in the ST3 console `sublime.cache_path()`

**Comment by gucharles** [comment]
Ok, i really delete all the cache after i uninstall ST3

And the problem still exists - -

Anything else i can do to give a try? it s really strange...

**Comment by DamnWidget** [comment]
I never had the problem myself and the only information that I have in hand is that the users updated in that issue, it just got fixed for them after delete any cache from ST3. I am afraid that I can't offer you any more help as it's really a problem out of our control. 

You can try to create a project and use that project configuration to set your python interpreter and bypass the auto folder detection (not sure if is gonna work but you lose nothing for try).

**Comment by gucharles** [comment]
OK, while still no good.
Fine , anyway thanks for your help !!!

**Comment by DamnWidget** [comment]
I just noticed that you are using SublimeCodeIntel along with anaconda, SublimeCodeIntel is known to interfere with other packages, including anaconda and make them to don't work, there are lots of examples of issues related with CodeIntel in this very issues tracker (just search for it). 

I suggest you to disable SublimeCodeIntel while you are using anaconda.
