### ISSUE TITLE
PEP8: E501; Won't ignore, and pep8_max_line_length not honored

### ISSUE THREAD

**Issue by tomthorogood** [DamnWidget/anaconda#391]
My Anaconda user-settings are:

```json
{
    "pep8_max_line_length" : 120,
    "pep8_ignore" : ["E501"]
}
```
Yet lines greater than 79 characters trigger the E501 warning and I get the pop-up when I save. Interestingly, if I have a line that goes beyond 120, I get the pop-up about that as well. So, it's recognizing the 120 limit somewhere, but still giving me the error on 79.

(Unfortunately, I wasn't able to attach a screenshot to the issue, as I don't have write permission to the repo, which is fine, but I'd be happy to provide one)

**Comment by DamnWidget** [comment]
Both options working perfectly fine for me, can't replicate any of this behavior. Are you sure that you didn't set anything different than `false` to the `pep8_rcfile` option?
