### ISSUE TITLE
Autocomplete Popup disappears quickly

### ISSUE THREAD

**Issue by hhk1989** [DamnWidget/anaconda#392]
Sometimes the popup disappears before I make the right selection - is there anyway to configure the popup to not disappear and make it go away (say) only on pressing escape ?

**Comment by DamnWidget** [comment]
There is nothing in anaconda that makes the auto-completion pop-up to disappear earlier, anaconda just inject data into the regular ST3 popup. 

Are you sure there is no other package causing that behavior?

**Comment by DamnWidget** [comment]
I am pretty sure that you have SublimeJedi installed along with anaconda, SublimeJedi and anaconda uses the same approach to inject their completions into ST3 so they can not work together, one or the other must be disables/deinstalled..

Closing this and I did not get any feedback.
