### ISSUE TITLE
Python 3.5 compatable

### ISSUE THREAD

**Issue by ivlevdenis** [DamnWidget/anaconda#393]
Should we expect support for python 3.5?

**Comment by DamnWidget** [comment]
I don't see why not

**Comment by ivlevdenis** [comment]
I'm about await, async, lang constructions.

**Comment by DamnWidget** [comment]
Still doesn't see any problem, let's be positive :)

On 2 November 2015 at 16:57, Ivlev Denis <notifications@github.com> wrote:

> I'm about await, async, lang constructions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/393#issuecomment-153082290>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by Smirl** [comment]
This is because the version of pyflakes installed with Anaconda is out of date. If you use `async def` the linter will fail. This is a known and fixed issue in flake8. https://gitlab.com/pycqa/flake8/issues/94

From the anaconda server you see this error message, which matches what is in the flake8 issue link above:
```
About push back to ST3: b'{"success": false, "uid": "0998f15d71f843109dc95013cb162edf", "errors": "\'Checker\' object has no attribute \'ASYNCFUNCTIONDEF\'", "vid": 18}\r\n'
```

**Comment by Smirl** [comment]
Hi Thanks for the quick turnaround. However I think you have broken pyflakes linting (at least for me I am having issues). Pyflakes 1.0.0 wasn't just a drop in thing I think.

They changed some of the errors which you look for in https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/linting/anaconda_pyflakes.py#L102.

Here is the error I see now:
```
About push back to ST3: b'{"errors": "\'module\' object has no attribute \'Redefined\'", "vid": 16, "uid": "b33bb381d5bb48abb9b6e8d8201e29e9", "success": false}\r\n'
```

I should mention that I tested 2.7.9, 3.4.2, 3.5.0 and most linting is ok until it has to look for `pyflakes.messages.Redefined`.

**Comment by DamnWidget** [comment]
I missed that one, thank you for the warning

**Comment by ariscn** [comment]
`async def` is linting as a syntax error. ST3, latest version of Anaconda. Do I need to take any extra steps to enable Python 3.5 support?
