### ISSUE TITLE
Project-Settings Don't Work

### ISSUE THREAD

**Issue by tommyc38** [DamnWidget/anaconda#395]
Computer: Macbook Pro Retina 2014
OS:  El Capitan
Sublime Version:  Sublime Text 3 (3083)

My <project>.sublime-project configuration doesn't work.  I haven't changed any of my Anaconda default settings, other than to try and trouble shoot the problem.

Below is a copy of my project settings:

{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "python -u \"$file\""
		}
	],
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	[
		{
			"anaconda_gutter_theme": "alpha",
			"anaconda_linting": true,
			"pep8_ignore":
			[
				"E501",
				"E303"
			],
			"python_interpreter": "~/.virtualenvs/py3/bin/python3.5"
		}
	]
}

Here is the Problem:

"shell_cmd": "python -u \"$file\"" - the only way I can get this to work is if I do something like:
 
"shell_cmd": "~/.virtualenvs/py3/bin/python3.5 -u \"$file\"" 

However, when I reopen ST3 and run by build it reverts back to:

 "shell_cmd": "python -u \"$file\""

I don't understand why this happens.  I have tried adding a build "path": variable, using different venvs, python versions, and with "python" at the end (vs. my example above with "python3.5") to "shell_cmd": yet the problem persists.  I don't even understand what the setting "python_interpreter": "xxxx" is doing if it's not giving the path for my venv executable.  
I am at a loss because I have read your documentation extensively and can't find anything I am doing wrong.  This seems like it should work out of the box and is one of the major benefits to using Anaconda.  I shouldn't have to update my "shell_cmd" or "cmd" (yeah, I tried that too) once I set it in my project-settings file.  
Lastly, I thought one of the benefits to using Anacoda's sublime-project builds was that I wouldn't have to update my python $PATH via my .bash_profile or something like that in order to get it to work.  Please tell me what I am missing.

Also, I can't get either:

"anaconda_gutter_theme": "alpha",
OR
"pep8_ignore":
			[
				"E501",
				"E303"
			],

to work at the project scope but could at both the User and Default scope.  Your help would be greatly appreciated!!!!!!!!!!!!!!!!

**Comment by DamnWidget** [comment]
Hi. In your config, the settings is a list and it should be a dictionary

"settings":
{
    "anaconda_gutter_theme": "alpha",
    "anaconda_linting": true,
    "pep8_ignore": [
        "E501",
        "E303"
    ],
    "python_interpreter": "~/.virtualenvs/py3/bin/python3.5"
}

I am not sure about the `shell_cmd` fix first the other stuff and let's see

**Comment by tommyc38** [comment]
That fixed my issues.  I will reopen the issue if it overwrites my "shell_cmd" again.  Thank you!

**Comment by DaZzz** [comment]
I have the same problem with this file project settings:
```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "$project_path/bin/python -u $file"
		}
	],
	"folders":
	[
		{
			"file_exclude_patterns":
			[
				"pip-selfcheck.json",
				"pyvenv.cfg"
			],
			"folder_exclude_patterns":
			[
				"lib",
				"include",
				"bin"
			],
			"follow_symlinks": true,
			"path": "."
		}
	],
	"settings":
	{
		"binary_file_patterns":
		[
			"*.jpg",
			"*.jpeg",
			"*.png",
			"*.gif",
			"*.ttf",
			"*.tga",
			"*.dds",
			"*.ico",
			"*.eot",
			"*.pdf",
			"*.swf",
			"*.jar",
			"*.zip",
			"client/node_modules/**",
			"data/**"
		]
	}
}
```

**Comment by DamnWidget** [comment]
I am not sure to understand what your problem is @DaZzz I see  no anaconda options at all in your configuration...

**Comment by DaZzz** [comment]
@DamnWidget Well, I know, but I just lost a hope. Every time I restart sublime it changes my settings from this
```
"shell_cmd": "$project_path/bin/python -u $file"
```
to 
```
"shell_cmd": "\"python\" -u \"$file\""
```
So I came here seeing that people already had this issue. I thought maybe Anaconda is trying to fix something, which is actually not broken. Did anyone have this problem before? I just need a hint....

**Comment by nicebug** [comment]
@DaZzz i have same issue with u

**Comment by DamnWidget** [comment]
@nicebug  take a look at [this answer in StackOverflow](http://stackoverflow.com/questions/36127925/fix-substitution-of-shell-cmd-on-mac-osx-in-sublime-text-3/36730844#36730844)

**Comment by nicebug** [comment]
@DamnWidget  fixed  thks
