### ISSUE TITLE
Autodetect python2 and python3?

### ISSUE THREAD

**Issue by txtsd** [DamnWidget/anaconda#396]
Is it possible to get Anaconda to autodetect if the file is using python2 or python3 by parsing the shebang, and then setting `python_interpreter` to the appropriate python?
Or do I *have* to create a project and use per project settings?

**Comment by DamnWidget** [comment]
I guess that should be something possible to implement but I don't think that is a good idea as we can end up with multiple JsonServer copies using multiple interpreters for the same ST3 window and that is against the current package architecture so a full redesign of the package should be accomplish and the waste of resources could be huge.

**Comment by txtsd** [comment]
Ah. In that case, I'll just set it on a per-project basis. Thank you for the explanation!
