### ISSUE TITLE
"Undefined name <variable name>" validation fails in version > 1.4.3 

### ISSUE THREAD

**Issue by p-p-m** [DamnWidget/anaconda#398]
`"Undefined name <variable name>"` error does not appear in anaconda with version > 1.4.3 

Steps to reproduce:
1. Create new python file.
2. Add undefined variable.

Logs are fine. In anaconda v1.4.3 error appears.

**Comment by DamnWidget** [comment]
As you can see in the attached screenshot, is working perfectly fine with last version v1.4.15

![undefined_name](https://cloud.githubusercontent.com/assets/329766/11089247/493c97fe-8860-11e5-9a5a-7c0ba6b8317f.png)

**Comment by p-p-m** [comment]
Looks like it was only in v1.4.14, works in v1.4.15 for me too. Thanks.
