### ISSUE TITLE
Getting ride of it

### ISSUE THREAD

**Issue by matthieudelaro** [DamnWidget/anaconda#400]
Hi,

I'm using ST3 on Mac OSX Yosemite.
I installed Anaconda with the Package Installer today.

Since then:
- ST crashed twice
- shortcut super+shift+t doesn't open recently closed tab anymore, but instead opens the command line
- the menu opened by super+p doesn't react as usual anymore

So I wanted to remove it : 
- Package installer : remove package.
- Restarted ST
=> it seems to be uninstalled, but:
- shortcut super+shift+t still doesn't open recently closed tab, and open the command line instead. 
- the menu opened by super+p is still not as usual

How do I get rid of it for good and get my original settings back please ?

**Comment by DamnWidget** [comment]
Are you are able to find any Super+Shift+T shortcut in anaconda for Mac OS X? That is amazing as there is no such shortcut for Mac OS X into anaconda.

https://raw.githubusercontent.com/DamnWidget/anaconda/master/Default%20(OSX).sublime-keymap

Probably is another package the one that is causing you those problems.
