### ISSUE TITLE
Why does function/method autocomplete doesn't insert parenthesis 

### ISSUE THREAD

**Issue by Mikaz-fr** [DamnWidget/anaconda#403]
Hi,

I'm setting up Anaconda for my python development and it looks great so far, good job.

Although there is a behavior which I don't understand: when I select an autocompletion function it will fill the function name only, not the parenthesis with it (nor the parameters if the option is enabled).
Is there a reason for that ? I have seen that it's reference in the documentation (http://damnwidget.github.io/anaconda/IDE/#toc_5) so I believe it's a feature and not a bug.

I would really like to have the whole function name + parenthesis + parameters filled when I select an autocompletion. Do you think such an option could be made available ?

Best
Michael

**Comment by DamnWidget** [comment]
The use of "(" has special meanings into anaconda depending of the user settings, is needed for the plugin in order to trigger some events, if the plugin places these by himself it can lead to missconfigured installations with bizarre behavior

**Comment by Mikaz-fr** [comment]
Ok, thanks for the quick response.

If I understand correctly, auto-filling the parenthesis can lead to bizarre behavior in some cases. If you think this is fixable maybe we can have this as a future feature.
If you think it is not possible to achieve then we can just close this question.
