### ISSUE TITLE
Goto Definition does not work if import like " from some import * "

### ISSUE THREAD

**Issue by divanovGH** [DamnWidget/anaconda#405]

**Comment by DamnWidget** [comment]
Goto Definition is working fine for me even using star imports, by the way.

If you pollute the global scope with an star import how do you want the lexical analyzer to know what exists in the scope and what doesn't? The linter is gonna be unable to properly detect undefined variables in your scripts.

PEP8 already forbid from use `from x import *` and is documented as a bad practice. That is supposed to be used when it gives you real benefits.
