### ISSUE TITLE
Functions decorated with @asyncio.coroutine do not have proper tooltips

### ISSUE THREAD

**Issue by Rapptz** [DamnWidget/anaconda#410]
Example:

![](http://i.imgur.com/GUOUvH8.png)

I don't really know where jedi gets the tooltip from -- I had assumed it was from `__doc__`. In which case the decorator does handle properly:

```py
>>> import asyncio
>>> @asyncio.coroutine
... def test():
...     """Does something"""
...     return 10
...
>>> test.__doc__
'Does something'
```

**Comment by DamnWidget** [comment]
Can't replicate

![snapshot1](https://cloud.githubusercontent.com/assets/329766/11930239/9a565fa6-a7d9-11e5-9a41-31a3d8462fc1.png)

**Comment by vanadium23** [comment]
Have same behavior for contract decorator from [contracts](https://pypi.python.org/pypi/PyContracts).
Basically, I think it is because contract parse docstring. can we fix this?

![screenshot](https://cloud.githubusercontent.com/assets/2872741/13234016/9e2efcda-d9c7-11e5-8921-4ca8c4dd8ab1.jpg)

**Comment by baliame** [comment]
I am also having this issue with a large number of decorators in general.

**Comment by vanadium23** [comment]
With contracts all is normal know. Don't know what happened, but thanks.

**Comment by DamnWidget** [comment]
Mysteries of the life, it always worked for me. Closing this :)
