### ISSUE TITLE
Tooltip does not show more than one line of signature.

### ISSUE THREAD

**Issue by devavret** [DamnWidget/anaconda#412]
Tooltip shows only the first line of signature. The docstring has the third line onward of the signature prefixed to it.

<img width="636" alt="screen shot 2015-12-27 at 12 26 06 am" src="https://cloud.githubusercontent.com/assets/3027195/12008952/8ce7ae5a-ac30-11e5-8804-38af0dec3324.png">

**Comment by DamnWidget** [comment]
This was fixed, no one closed it.
