### ISSUE TITLE
int signature displaying when typing numbers

### ISSUE THREAD

**Issue by danmoser** [DamnWidget/anaconda#416]
The boring `int` function signature is displayed when typing numbers... 
I believe the condition below is not enough to get rid of "int()" function (listeners/signatures.py): 
    
    if ('(' in self.signature and self.signature.split('(')[0].strip() not in self.exclude):

The modification below worked for me:

    if ('(' in self.signature and self.signature.find('int') != 0 and 
       self.signature.split('(')[0].strip() not in self.exclude):

**Comment by DamnWidget** [comment]
Hi, I will try to take a look as soon as I can
