### ISSUE TITLE
tooltips does not show complete

### ISSUE THREAD

**Issue by nicebug** [DamnWidget/anaconda#417]
unittest.assertLessEqual doc does not complete, as follows
![image](https://cloud.githubusercontent.com/assets/1947907/12166080/1f3a902a-b55e-11e5-870d-dfe3a28ed8f2.png)

unittest.assertLessEqual doc is:
![image](https://cloud.githubusercontent.com/assets/1947907/12166104/6378bc26-b55e-11e5-9759-f3049c729dcc.png)

**Comment by DamnWidget** [comment]
Can you check if this issue has been fixed with yesterday release?

**Comment by nicebug** [comment]
not yet. still not work, console show some Parser error:

![image](https://cloud.githubusercontent.com/assets/1947907/12226514/25cfac52-b858-11e5-9b92-7bc2f072180a.png)

**Comment by pradyunsg** [comment]
@nicebug (The pun in the name :)

Could you post the contents of your console on a fresh Sublime Text window?

Fresh: A new window opened after closing all others that were open (if they were).

**Comment by nicebug** [comment]
@pradyunsg  closed all files and then open st3. this is the log file:
https://gist.github.com/nicebug/4e39b70095942bf50ef2

**Comment by mrvkino** [comment]
I have the same issue when the tooltip tries to show the doc from 're'.
![sublime_anaconda_re](https://cloud.githubusercontent.com/assets/279511/14328329/34056d80-fc04-11e5-8499-c6cc3e28aa17.png)

**Comment by pradyunsg** [comment]
Guess: Do the html entities need escaping?
