### ISSUE TITLE
auto_formatting formats after save instead of before

### ISSUE THREAD

**Issue by txtsd** [DamnWidget/anaconda#420]
When I `Ctrl+S`, I expect my file to be formatted and saved, but my file is saved first, and then formatted, requiring me to save again.

**Comment by DamnWidget** [comment]
Anaconda uses AutoPEP8 (that is a 3rd party dependency) to implement the auto formatting feature, unfortunately autopep8 doesn't accept a string as input but a file in the filesystem, this is why anaconda saves your buffer after format your file.

I understand that you have enabled the autoformat on save option and that is why you are expecting that behavior. I would like to do some modifications to the overall autoformatting behavior, I will take a look into this issue that you just did rise as well.

**Comment by txtsd** [comment]
You could save the buffer as a temp file, use AutoPEP8 on that file, replace the buffer with the contents of autoformatted temp file, then let ST3 save.

**Comment by DamnWidget** [comment]
resolved, will be live in next release

**Comment by txtsd** [comment]
Thank you!

**Comment by DamnWidget** [comment]
You are welcome
