### ISSUE TITLE
Support for spaces in the Python Interpreter filepath

### ISSUE THREAD

**Issue by glm-nchaverou** [DamnWidget/anaconda#421]
When setting my python_interpreter settings to the Windows maya default dir, I get an error.
here's my setting:

{
    "python_interpreter": "C:/Program Files/Autodesk/Maya2014/bin/mayapy.exe",
   [...]
}

And the error:
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.

I tried using a %20, replace C:/Program Files with %ProgramFiles% but was not successful
Or maybe I missed something ?

**Comment by DamnWidget** [comment]
Try

```json
{
    "python_interpreter": "C:\\Program Files\\Autodesk\\Maya2014\\bin\\mayapy.exe",
[...]
}
```

**Comment by glm-nchaverou** [comment]
Not better:
Instead I get : 'C:\Program' is not recognized as an internal or external command :D

**Comment by DamnWidget** [comment]
Well, I don't know what to tell you, there are loads of people using spaces in their paths with no issue. Can you paste your ST3 console log at least?

**Comment by glm-nchaverou** [comment]
Yes that's what I thought, I can't be the first one :)

Here's the content of my Anaconda user settings file:

{
    "python_interpreter": "C:\\Program Files\\Autodesk\\Maya2014\\bin\\mayapy.exe",
    "pep8_max_line_length": 120,
    "pep8_ignore" : ["E501", "E302"]
}

And the complete build console result
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.0s with exit code 1]
[shell_cmd: C:\Program Files\Autodesk\Maya2014\bin\mayapy.exe -u "C:\Users\chaverou\Desktop\print.py"]
[dir: C:\Users\chaverou\Desktop]
[path: ...]

And ST3 console log:

Running C:\Program Files\Autodesk\Maya2014\bin\mayapy.exe -u "C:\Users\chaverou\Desktop\print.py"

If I move the python exe and the relative dll to a non space dir, that works properly

**Comment by DamnWidget** [comment]
Ok, so I am understanding that this issue is only when you use the Ctrl+B to build the file?

**Comment by glm-nchaverou** [comment]
Yep indeed. Sorry should have specified that before

**Comment by DamnWidget** [comment]
Can you paste the content of your "build_systems" configuration?

**Comment by glm-nchaverou** [comment]
Sure. It's actually the default one:

`{
    "name": "Anaconda Python Builder",
    "shell_cmd": "${python_interpreter} -u \"$file\"",
    "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
    "selector": "source.python"
}
`

**Comment by pradyunsg** [comment]
@glm-nchaverou Try putting single quotes around ${python_interpreter}

**Comment by glm-nchaverou** [comment]
Haaaaa good suggestion! single quotes did not worked but \" around solved the issue!
Thanks

**Comment by glm-nchaverou** [comment]
Maybe that would be worth setting this by default ?

**Comment by pradyunsg** [comment]
It would. @DamnWidget the solution to this issue seems to be escape quoting the `${python_interpreter}` variable in the `shell_cmd`...

```json
{
    "name": "Anaconda Python Builder", 
    "shell_cmd": "\"${python_interpreter}\" -u \"$file\"", 
    "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)", 
    "selector": "source.python" 
}
```
