### ISSUE TITLE
sublime3 become extremely slow when I edit python file

### ISSUE THREAD

**Issue by RushPu** [DamnWidget/anaconda#423]
I've tested a lot of times on my mac, reinstalled sublime3 and just add anaconda package on it, still the same problem.I try to configure like [this page](http://stackoverflow.com/questions/32773522/autocompletion-for-sublime-text-3-package-anaconda-is-slow),still not work.

**Comment by DamnWidget** [comment]
Do you see any logs in the sublime text console?

**Comment by RushPu** [comment]
No logs in console,just slow

**Comment by DamnWidget** [comment]
Anything in `~Library/Cache/Jedi/`?

**Comment by RushPu** [comment]
3 anaconda dir in jedi, some error logs，I‘ve solved that，thanks！

**Comment by ludbek** [comment]
@RushPu  how did you solve it?
