### ISSUE TITLE
Show a nicer error messages

### ISSUE THREAD

**Issue by pradyunsg** [DamnWidget/anaconda#425]
There are multiple issues (#3, #370, #353, #347, #297, #23), where the user has seen a ConnectionRefusedError traceback and requested assistance.

I think it might be a good idea to cover the erroring line in a try-except and raise a custom exception with a nicer message. Along with that, maybe a pointer to someplace listing why such an error is raised and possible fixes... I'm thinking that the "someplace" should be an FAQ in the wiki...

```python
try:
    self.sock.connect(address)
# You could use ConnectionRefusedError here; this is more generic
except IOError:
    # Maybe a subclass of Exception, like AnacondaError?
    raise Exception(
        "Anaconda could not connect to it's linting Python process. "
        "Please see <someplace> for more information on this."
    )
```

In fact, there are multiple edge-cases when the plugin reaches an invalid state and raises an error. It would be nice if the Anaconda checked it's actions and reported errors nicely instead of erroring out. (as pointed out in #347)

**Comment by dufferzafar** [comment]
This would be neat. :+1:

**Comment by DamnWidget** [comment]
I am doing a release today with more verbose and useful information, I also added [this wiki page](https://github.com/DamnWidget/anaconda/wiki/Connection-Refused-Information) that after the release anaconda will point to when these kind of errors get raised.

**Comment by dufferzafar** [comment]
@DamnWidget I was having those Connection Refused errors (no 111) and all I did to "solve" them was re-install Anaconda :/

**Comment by DamnWidget** [comment]
There is some cache bug going on since ST3 3087 that get fixed reinstalling the plugin or ST3 but that's totally out of our control unfortunately

**Comment by pradyunsg** [comment]
I just went about editting the wiki directly. I hope you don't mind. :smiley:

Since there's not much space there to write about the changes... I'm listing them here.

The import block should also import subprocess.  
```python
from Anaconda.anaconda_lib import helpers; import subprocess
```

> To check that your configured...

`s/that/if/`

> If your python_interpreter is not set or set wrong, anaconda will fail to... 

`s/anaconda/Anaconda/`

The numbered list in Check Connectivity section is coming up inline. You probably forgot to put an empty before the list.
The paths have been formed like a table.

**Comment by DamnWidget** [comment]
Thank you @pradyunsg
