### ISSUE TITLE
Anaconda Python Builder can't print Chinese characters in Sublime Text 3 Terminal

### ISSUE THREAD

**Issue by pingshunhuangalex** [DamnWidget/anaconda#431]
Hi

I'm really new to everything here.

ST3 version : 3103
Anaconda version : latest
Window 10 (64-bit)
Python version: 3.5.1

I tried to run Anaconda build to print some Chinese characters, like print('xxx'), but there is nothing shown in the ST3 terminal. After some research, it seems to be an encoding issue. It can be easily solved by creating a new build in ST3, but to stick to Anaconda build, I just wonder is there a way to add the below line

"env": {"PYTHONIOENCODING": "UTF-8"}

to Anaconda Python Builder, so it can print Chinese in ST3 terminal, and still allows me to stick to Anaconda builder instead of creating my own python sublime builder. Thanks.

**Comment by DamnWidget** [comment]
You can add it with no problems but it will probably get overwritten if you change your `python_interpreter`. My suggestion is to probably copy the structure of the `Anaconda Python Builder` and create your own modifying the name so Anaconda will not overwrite it ever.

**Comment by saraphineshps** [comment]
Sorry, I'm really new on this. Where to find the structure of the Anaconda Python Builder? I spent a good couple of hours but no luck...

**Comment by DamnWidget** [comment]
In your project file (if you have one)

**Comment by saraphineshps** [comment]
No I don't, I'm just getting started on my Python journey. Right now I don't save things as project, I just run a simple python script. That's the reason I want to find an elegant solution to add the line of code in the default anaconda builder. I guess if I follow your method, I'll need to add it to a builder file every time I start a new project right?

**Comment by DamnWidget** [comment]
If you don't use a project, you don't run anaconda's builder but Sublime Text 3 one. 

I recommend that you take a look at ST3 documentation (unofficial but really good) here:
http://docs.sublimetext.info/en/latest/reference/build_systems.html

Then read anaconda's own doc here:
http://damnwidget.github.io/anaconda

**Comment by saraphineshps** [comment]
Thanks mate. One last question, so even I select anaconda builder in the builder list (or ctrl + shift + B), if I'm not using a project, it still uses ST3 python builder?

**Comment by DamnWidget** [comment]
If you don't have a project, Anaconda's Python builder shouldn't even appear in the list of builders.

**Comment by saraphineshps** [comment]
Mmm interesting, I did have it in the list, and I can select it just fine. Anyway, once I create a project and add that line to the project builder, everything works perfectly. Thanks you for your help and patience. Have a nice day:)
