### ISSUE TITLE
Gutter icons not displayed properly on light themes

### ISSUE THREAD

**Issue by eugenesvk** [DamnWidget/anaconda#436]
In light themes (e.g. Material Theme Light) the gutter icons lose their colors (e.g. Retina icons are all black, other icons are poorly visible).
This is a ST3 issue, but it has a fix that is addon-specific. 
For example, for the [GutterColor](https://github.com/ggordan/GutterColor) addon the issue is similar (see https://github.com/ggordan/GutterColor#icon-tinting-and-light-color-schemes) and the fix would be to add to user's color scheme the following code that would change the color for gutter icon output, allowing icons to be properly formatted.
```xml
		<dict>
			<key>name</key>
			<string>GutterColor</string>
			<key>scope</key>
			<string>gutter_color</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#ffffff</string>
			</dict>
		</dict>
```

However, I don't understand how to apply the same fix to your addon. Is it possible (maybe the way you put icons in the gutter is very different and this wouldn't work)? If so, which `scope` should I use?
If not, how else can I fix the issue of icons not displaying properly?

**Comment by DamnWidget** [comment]
This is how GutterColor is doing it https://github.com/ggordan/GutterColor/blob/997786d07b4725c09c16a4250ff12af6b463edaf/gutter_color.py#L79-L122

Anaconda doesn't set the theme for the gutter marks, just the icon type so I am not sure how you can apply that fix to any theme as I think that GutterColor is a key thay is set for regions directly by GutterColor plugin itself in here https://github.com/ggordan/GutterColor/blob/a40e4b444a631ef744d9d78e54ea0dff0ea7cfa0/line.py#L276.

**Comment by eugenesvk** [comment]
Yep, and that fix add a simple [XML paragraph](https://github.com/ggordan/GutterColor/blob/997786d07b4725c09c16a4250ff12af6b463edaf/background_fix.xml) via the code you linked to and this [line](https://github.com/ggordan/GutterColor/blob/997786d07b4725c09c16a4250ff12af6b463edaf/gutter_color.py#L147) to an existing color scheme.
And definition of the `gutter_color` region is exactly what allows that paragraph have any effect.

Is there any chance you can add something like `anaconda_gutter` region so that color scheme can include a fix similar to that of GutterColor (by adding just one additional key)?

**Comment by DamnWidget** [comment]
Anaconda creates regions for any every kind of severity, you can see the related code here https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/linting/sublime.py#L227-L237

You can find the regions that anaconda creates in the wiki https://github.com/DamnWidget/anaconda/wiki/Linting-theme-customization

**Comment by eugenesvk** [comment]
Thanks! That's exactly what I was looking for!
Would you kindly add in the readme (and maybe in default settings) that setting **Outline** **foreground** colors is required for gutter icons to be displayed properly in light themes?
Adding _gutter_ word to wiki could also help (though wikis don't seem to be searchable by default when you type something in the `search` box).
Otherwise I couldn't find anything with `gutter` search words.

**Comment by DamnWidget** [comment]
I am a bit busy since a couple of years ago xDD, can you do a pull request?
