### ISSUE TITLE
SublimeText 3 + LESS file = plugin_host exit

### ISSUE THREAD

**Issue by HayesData** [DamnWidget/anaconda#438]
I have found an issue where if a Less file is being edited with Anaconda installed it will crash the plugin_host 100% of the time on the second save of the file. In addition this usually causes lots of instability in the rest of SublimeText.

I have uninstalled all of my packages except for Anaconda and the crash only occurs when Anaconda is installed.

ST3 Build 3103 installed on OS X 10.11.3 with the newest release of Anaconda in the package management channel.

Additionally nothing of note is written to the console, it just crashes the plugin_host without warning.

**Comment by DamnWidget** [comment]
Unless Sublime Text reports .less files as Python code, anaconda is not even active during its edition. All the functions return without executing their body as the file being edited is not Python.

Did you try to remove anaconda as well and try?

**Comment by HayesData** [comment]
I did in fact remove Anaconda and it immediately fixed the issue.

It's admittedly a strange problem and I'm thinking it may have more to do with SublimeText than Anaconda specifically.

That said I can reproduce the issue 100% of the time.

**Comment by DamnWidget** [comment]
Make sure that you don't have some kind of LESS highlight messing around I can't reproduce this myself (because it has no sense at all).

![anaconda_less](https://cloud.githubusercontent.com/assets/329766/13248263/44f13306-da15-11e5-9e6e-a24de93acf98.png)
