### ISSUE TITLE
[feature request] mypy support

### ISSUE THREAD

**Issue by ipfans** [DamnWidget/anaconda#439]
mypy is am optional static typing for Python.
The project is locate at https://github.com/python/mypy

**Comment by fredcallaway** [comment]
You can highlight mypy errors using sublime linter and this package

https://github.com/fredcallaway/SublimeLinter-contrib-mypy

**Comment by DamnWidget** [comment]
Mypy support will be added as optional (disabled by default) in v2.0.0

**Comment by DamnWidget** [comment]
Feature implemented, waiting for v2.0.0 release
