### ISSUE TITLE
[BUG] json only imported if sublime import fails

### ISSUE THREAD

**Issue by danfrankj** [DamnWidget/anaconda#442]
the json module  is needed here: 
https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/jsonclient.py#L84

but json is only imported if the sublime import fails :  
https://github.com/DamnWidget/anaconda/blob/master/anaconda_lib/jsonclient.py#L16

Seems like we should fail if  
import sublime  fails?

**Comment by DamnWidget** [comment]
No, the `NameError` exception is raised if the `sublime` module is not imported, what I can't remember now is why I added the `ValueError` exception in there
