### ISSUE TITLE
gitgutter compatibility 

### ISSUE THREAD

**Issue by yaroslavyaroslav** [DamnWidget/anaconda#445]
I'm using this [plugin](https://github.com/jisaacks/GitGutter) for showing what lines were modified against last commit. And it conflicts with Anaconda marks when drawing it's marks near the line numbers.

So to prevent all that conflicts it have it's [own](https://github.com/jisaacks/GitGutter/issues/113#issuecomment-148744744) [mechanism](https://github.com/jisaacks/GitGutter/blob/master/GitGutter.sublime-settings#L58) which is set protected regions that are needed to see more that gitgutter marks. So to set it you must know it. And here's the problem. I don't know anaconda regions names. Only mentioned about regions i've find in anacondas sources is in anaconda-master/anaconda_lib/jediusages.py:
105: region_name = 'anaconda.indicator.{}.{}'.format(self.text.view.id(), lineno)

But still i don't know what should i set in [here](https://github.com/jisaacks/GitGutter/blob/master/GitGutter.sublime-settings#L58) to prevent rewrite anacondas mark with gitgutter marks.

**Comment by DamnWidget** [comment]
Here you have all the regions that anconda creates: https://github.com/DamnWidget/anaconda/wiki/Linting-theme-customization

**Comment by jmrd98** [comment]
For future google searchers/viewers searching for this topic, I found the pertinent lines in anaconda: They are found at [~line 228 in sublime.py](https://github.com/DamnWidget/anaconda/blob/2a4a3e67a6870346e855c916a380dfa7aa71f498/anaconda_lib/linting/sublime.py#L228).

Long story short, the region names of interest (as of the time of writing) are "anaconda-lint-outlines-illegal, anaconda-lint-outlines-warning, anaconda-lint-outlines-violation".

**Comment by DamnWidget** [comment]
All the section names where already in the first link that I did post, but thanks.
