### ISSUE TITLE
[Question] re: completing Pyside

### ISSUE THREAD

**Issue by mbo42** [DamnWidget/anaconda#447]
Hi and thanks for all the work.
Is it possible to get completions of PySide ui elements when referenced via self.ui ?

![anaconda_completions](https://cloud.githubusercontent.com/assets/2717656/13413657/4fdacfbc-dfa0-11e5-9ebd-482f0b4a3b2b.png)

I'm suspicious that it could work if I had the correct install of Pyside in the virtualenv.?
I see this all the time in the log.

    ERROR   : The underlying Jedi library as raised an exception
    ERROR   : No module named Shiboken
I've tried compiling PySide a couple of different ways (wheel and egg) but no luck.
Completions are good in the `QtGui.lineEdit.` form, but don't work in any other situation.

**Comment by DamnWidget** [comment]
Did you tried to install Shiboken?

**Comment by mbo42** [comment]
Thank you ! It works beautifully now.
Including the screen cap for other PySide users to see.
![anaconda_completions_great](https://cloud.githubusercontent.com/assets/2717656/13445396/f39eccd8-e05f-11e5-892d-ceb5c81946f3.png)

This has 'weaponized' sublime :-)
