### ISSUE TITLE
Assigning to 'self' in a for cycle breaks completion for it afterwards

### ISSUE THREAD

**Issue by karolyi** [DamnWidget/anaconda#449]
Hey,

great plugin! I donated you recently.

I found an issue: if you use a for cycle, in where you assign variables to the class instance reference `self`, it breaks the completion on it afterwards in the function.

an example:

before the for cycle, it works:
![image](https://cloud.githubusercontent.com/assets/987055/13457675/a0261750-e069-11e5-8db6-5b6e7a70ae47.png)

after the for cycle, it doesn't:
![image](https://cloud.githubusercontent.com/assets/987055/13457697/c7442548-e069-11e5-8359-0ec88306b46b.png)

the line which breaks the completion (probably) is the one with the for cycle, where I assign a variable directly into self.

Cheers!

**Comment by DamnWidget** [comment]
I can't replicate this issue as it is described in the issue report, this is a completion before a for the set a value using the `self` pointer:

![issue_449-1](https://cloud.githubusercontent.com/assets/329766/13491260/504178cc-e129-11e5-8163-e111826dc1dc.png)

And this is after assigning a value:

![issue_449-2](https://cloud.githubusercontent.com/assets/329766/13491263/5c6b3872-e129-11e5-9621-ea588caba703.png)

As you can see there is no problem. Can I have a copy of that file?

**Comment by karolyi** [comment]
It's easy to reproduce but probably I did a poor job to define it.

here's a test code, copy it to a file, and test it for yourself:

```python
class TestClass(object):
    def __init__(self):
        self.list_test_variable = [1,2,3]

    def test_func(self):
        # autocompleting self works here BEFORE the for cycle
        for self._iter_variable in [6,7,8]:
            pass
        # autocompleting self fails here AFTER the for cycle
```

Autocompleting self will show up `list_test_variable` before the `for` cycle, but not after the `for` cycle. The problem lies probably in the `for` cycle, where assign values directly to `self`.

Can you work with this?

**Comment by DamnWidget** [comment]
That is because for some reason the jedi library thinks that `self` after that operation is a boolean (don't ask me why) you should take a look at the Jedi project issues tracker and report it there if is not reported already.

As you know Python is a dynamic language, in order to offer auto completion, some heavy lexical parsing and operations are performed by Jedi (that doesn't executes the code in the buffer and that is an awesome achievement from them) as some type need to be infered in order to determine which methods and properties could be defined on the word under the cursor.

**Comment by karolyi** [comment]
Did a bug report over there, thanks for your cooperation.

**Comment by DamnWidget** [comment]
No problem, I will maintain this open until they fix it and we update the library in anaconda (probably months).

**Comment by karolyi** [comment]
Well, it's not such a huge breaker, just something I stumbled upon. Cheers :)

**Comment by karolyi** [comment]
@DamnWidget ?

**Comment by karolyi** [comment]
@DamnWidget ?

**Comment by DamnWidget** [comment]
I will update Jedi as soon as that commit gets merged into the Jedi's master branch

**Comment by DamnWidget** [comment]
I think I can close this as the change has been long included into anaconda, feel free to reopen if there is any problem
