### ISSUE TITLE
Autocomplete does not infer from Type Hint (PEP 0484) when interpreter is python3

### ISSUE THREAD

**Issue by surajx** [DamnWidget/anaconda#451]
When using python3 as interpreter autocomplete fails to infer the type of function params whose type is explicitely specified using PEP 0484 - Type Hinting. (pressing TAB on `dot` just complete with `self.`)

![screenshot - saturday 05 march 2016 - 04 50 00 aedt](https://cloud.githubusercontent.com/assets/925885/13535348/c174f4aa-e28d-11e5-824c-6a63fd4e920c.png)

Somehow the issue is not there when the interpreter is python2. Although there is a linter error for the type hinting format in the function signature, the autocomplete on the param is resolved successfully.

![screenshot - saturday 05 march 2016 - 04 51 12 aedt](https://cloud.githubusercontent.com/assets/925885/13535374/e94c9c3a-e28d-11e5-97e8-cccc032e081e.png)

**Comment by fredcallaway** [comment]
I could not replicate this issue. Type hinting informs autocomplete for me using a python3 interpreter.

**Comment by DamnWidget** [comment]
Jedi (the library that anaconda uses internally to suggest completions) doesn't seems to give any completion for that code. 

Take look in [jedi's project page](https://github.com/davidhalter/jedi) to see if there is already an issue addressing this problem, if not, you can just open a new one.
