### ISSUE TITLE
Underlining errors.

### ISSUE THREAD

**Issue by ciechowoj** [DamnWidget/anaconda#452]
It would be nice to have a possibility to enable "underlining" of errors (the fill and outline looks ugly for me). Actually I implemented some prototype and it seems to work. Here is a diff:

    index 462b5b6..899abd1 100644
    --- a/anaconda_lib/linting/sublime.py
    +++ b/anaconda_lib/linting/sublime.py
    @@ -203,6 +203,9 @@ def add_lint_marks(view, lines, **errors):
         if len(lines) > 0:
             outline_style = {
                 'outline': sublime.DRAW_OUTLINED,
    +            'underline': sublime.DRAW_SQUIGGLY_UNDERLINE 
    +                | sublime.DRAW_NO_FILL 
    +                | sublime.DRAW_NO_OUTLINE,
                 'none': sublime.HIDDEN,
                 'fill': None
             }

**Comment by neuroticnerd** [comment]
Unless I am mistaken, I believe you can use the following settings (menu -> preferences -> package settings -> anaconda -> settings -- user) to have it underline errors:
```
{
    /*
        If 'outline' (default) anaconda will outline error lines
        If 'fill' anaconda will fill the lines
        If 'none' anaconda will not draw anything on error lines
    */
    "anaconda_linter_mark_style": "none",

    /*
        If anaconda_linter_mark_style is set to none and this is set to false,
        anaconda will not underline errors

        If anaconda_linter_mark_style is set to anything else, this option is
        ignored
    */
    "anaconda_linter_underlines": true,
}
```

Although admittedly, I'm a little confused as to why those are separate settings values to begin with, I would think that having those behaviors as part of one settings value would make more sense:
```
    /*
        If 'outline' (default) anaconda will outline error lines
        If 'fill' anaconda will fill the lines
        If 'underline' anaconda will underline errors
        If 'none' anaconda will not draw anything on error lines
    */
    "anaconda_linter_mark_style": "underline",
```

**Comment by ciechowoj** [comment]
I see, I had to miss that one, it works. However now I prefer those sublime text 'squiggly' underlines : ). I'll close the PR, as it isn't very useful at least for now (both anaconda and sublime underlines appear for some reason).

**Comment by DamnWidget** [comment]
Hi, I completely missed this issue.

The settings are separate because some people like Anaconda to draw boxes surrounding the affected lines code and underline under the specific parts of the line that are affected.

Mark styles and underlines are two separate ST3 regions as well.
