### ISSUE TITLE
Fix substitution of “shell_cmd” on Mac OSX in Sublime Text 3

### ISSUE THREAD

**Issue by DaZzz** [DamnWidget/anaconda#456]
I have a problem with my build system specified in project settings. Currently my project settings look like this
```
{
    "build_systems":
    [
        {
            "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
            "name": "Anaconda Python Builder",
            "selector": "source.python",
            "shell_cmd": "$project_path/bin/python -u $file"
        }
    ],
    "folders":
    [
        {
            "file_exclude_patterns":
            [
                "pip-selfcheck.json",
                "pyvenv.cfg"
            ],
            "folder_exclude_patterns":
            [
                "lib",
                "include",
                "bin"
            ],
            "follow_symlinks": true,
            "path": "."
        }
    ],
    "settings":
    {
        "binary_file_patterns":
        [
            "*.jpg",
            "*.jpeg",
            "*.png",
            "*.gif",
            "*.ttf",
            "*.tga",
            "*.dds",
            "*.ico",
            "*.eot",
            "*.pdf",
            "*.swf",
            "*.jar",
            "*.zip",
            "client/node_modules/**",
            "data/**"
        ]
    }
}
```

The actual problem problem is in the line:

```
"shell_cmd": "$project_path/bin/python -u $file"
```

Every time I close sublime and reopen it my shell_cmd gets substituted with this

```
"shell_cmd": "\"python\" -u \"$file\""
```

Actually, sometimes it happens without particular reason when I run build command. When I disable Anaconda this substitution never happens.

Is there a way to fix this problem? What do I do to disable this automatic substitution?

- Mac OS X 10.11.3
- Sublime Text 3103

**Comment by DamnWidget** [comment]
That is because that is not "your build system" is anaconda's one, if you want to add your own, add a new entry as anaconda is always gonna overwrite it's own build system using whatever python interpreter that is set as value for the `python_interpreter` option var.
