### ISSUE TITLE
Calling Cython functions does not support auto-completion, go to definition

### ISSUE THREAD

**Issue by samson333** [DamnWidget/anaconda#458]
I am writing some Cython functions to call my C++ code from Python. Is there a way to have these powerful facilities (auto-completion, go to definition, show documentation and so on) when call the Cython functions? Thanks.

**Comment by DamnWidget** [comment]
Hi @samson333 
You should be able to use whatever anaconda feature just in Python code, you won't be able to use it in any C code.

**Comment by samson333** [comment]
Hi @DamnWidget 
Thank you for your reply. Apparently I didn't clarify my question. Here is my situation: 
I had some c++ code. I wrapped them with Cython and build a module_name.pyd file, a Windows dll file accroding to http://docs.python.org/faq/windows.html#is-a-pyd-file-the-same-as-a-dll. 

In Python, I can "import module_name" and use all the functions and classes I defined in Cython. While writing Python, I would like to see the docstring and have auto completion when I use this package. 

When I use IPython Notebook or console, after importing the module, the docstring will pop up and auto completion works. But not in sublime. So I wonder if it is the setting problem or anaconda does not support this. 
Thank.

**Comment by DamnWidget** [comment]
Anaconda uses the Jedi library to provide auto-completion and docstrings, as far as I know if your library can be imported as a Python library, you anaconda should be able to complete and offer docstrings if your configured python interpreter is able to see/import that libraries.

**Comment by samson333** [comment]
Thanks. Adding the path solves the problem.
