### ISSUE TITLE
return vs print

### ISSUE THREAD

**Issue by junyiri** [DamnWidget/anaconda#459]
Hi could you please make 'return' in a function also print the output like in IDLE? Thanks.

**Comment by DamnWidget** [comment]
I don't understand what u mean, sorry. You mean in the editor buffer?

**Comment by junyiri** [comment]
Sorry it wasn't clear. In IDLE a function call also prints what it returns without having to explicitly command it to 'print'. I was hoping you could add this feature to Anaconda so that it would be more convenient. Thanks!

**Comment by RobinStephenson** [comment]
I think you're mistaking the IDE for a REPL. IDLE when running a script does not print data which is returned. However if you are using IDLE as a read evaluate print loop, it will print the result of the previous line.

**Comment by RobinStephenson** [comment]
Maybe label as wontfix / invalid
