### ISSUE TITLE
Setting python interpreter states virtual environment is not there OSX 

### ISSUE THREAD

**Issue by excetara2** [DamnWidget/anaconda#462]
I can't seem to figure out how to get anaconda to build my python files.

I have set the interpereter variable `python_interpreter` and added `extra_paths` but I get the error below when running. I use the other Anaconda environment for managing my virtual environments. It states no such file or directory but it definitely exists and if I navigate there in terminal I have no problems running the python executable.

Also if I run `open -a Sublime\ Text` with `source activate py2k` already run then I can compile and run with no problems. Anything I am doing wrong?

```
bin/bash: ~/anaconda/envs/py2k/bin/python: No such file or directory
[Finished in 0.0s with exit code 127]
[shell_cmd: "~/anaconda/envs/py2k/bin/python" -u "/Users/Spen/Dropbox/Research/Code/Model/Scripts/muschords_figure_220ActSteps.py"]
[dir: /Users/bigtyme/Dropbox/Research/Code/Model/Scripts]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

**Comment by DamnWidget** [comment]
Try to add the Python interpreter as absolute path `/Users/bigtyme/anaconda/envs/py2k/bin/python`, OS X is known to do weird things when the parent process of ST3 doesn't include BASH variables (like for example run it from spotlight).

**Comment by excetara2** [comment]
Yes I have tried both ways actually becaused originally I used the full path thinking that would be better. I couldn't get it to work either way but maybe just anytime I want to use Sublime for python editing I should open it via the terminal with the environment activated and not spotlight.

**Comment by DamnWidget** [comment]
Sorry to don't be more helpful here

**Comment by excetara2** [comment]
Yeah because loading from Spotlight it only loads the basic path `[path: /usr/bin:/bin:/usr/sbin:/sbin]`. I guess there is no way to force it to load a different path when starting.
