### ISSUE TITLE
PEP8 errors ignored even when not present in 'pep8_ignore'

### ISSUE THREAD

**Issue by p5gbryce** [DamnWidget/anaconda#464]
Hello, I love this plugin, however I am experiencing an issue. I'm using the following plugin settings:
```
    "use_pylint": false,
    "pep8": true,
    "pep8_rcfile": false,
    "pep8_ignore": ["E309"],
    "pep8_max_line_length": 79,
```
When it lints files, there are certain pep8 errors that it does not seem to catch, usually related to indentation like `E123`. My understanding is that with the above settings, *only* `E309` should be ignored but that is not what is happening. Running `flake8 --ignore E309` directly in a terminal on the same file(s), after making sure it was up to date, shows the missing errors.

I'm not sure if this is a bug somewhere, or if I have missed/botched some part of the configuration, any help would be appreciated!

**Comment by DamnWidget** [comment]
I never had any problem with E123, can you provide more information but your environment? A snippet of code where that problem happens could be helpful as well.

**Comment by p5gbryce** [comment]
Wow, thank you for such a quick reply!

OS X El Capitan - 10.11.3
SublimeText3 - build 3103 (installed via homebrew)
Python 2.7.11
Anaconda 1.4.18

Example snippet that should trigger E123 but does not:
```
    @staticmethod
    def model_method_name(date_filter=None, **kwargs):
        # ...

        filter_kwargs = dict(
            date_completion__isnull=True,
            date_due__lte=cutoff_date,
            persona_owner__isnull=False,
            )

        # ...
```

Let me know if there is other information you need!

**Comment by DamnWidget** [comment]
I can replicate it so I confirm this is a bug (a weird one btw).

**Comment by p5gbryce** [comment]
Thank you for the timely responses, if I have some time after work tonight I'll try to help diagnose the problem. I haven't done any testing yet to find which other errors might be getting silenced, I just happen to notice E123 since its one of my pet peeves anyway :P Sorry for finding such an odd one!

**Comment by DamnWidget** [comment]
Hi @p5gbryce 
Seems like that error is ignored by default by pep8 (https://pep8.readthedocs.org/en/1.4.6/intro.html look at the very bottom in the notes section). The thing is, if you add a `--ignore=E#NUM` when you use `pep8` directly from the command line you get reports for those errors that are ignored by default.

Anaconda was adding it's ignores to the default ignores from pep8 (anaconda uses pep8 as a library and doesn't call it from the command line). I made some modifications to replicate the pep8 behaviour.

**Comment by p5gbryce** [comment]
@DamnWidget awesome, thank you so much for fixing this! all the work you've put into making and maintaining Anaconda is greatly appreciated!

**Comment by DamnWidget** [comment]
Thank you :)
