### ISSUE TITLE
ERROR:Anaconda.anaconda_lib.worker:Something is using the port 43349 in your system

### ISSUE THREAD

**Issue by Gabriel-p** [DamnWidget/anaconda#465]
Today I tried to launch my default difftool (Meld) via `Git: Diff Tool All` and `Git: Diff Tool Current File`. After Meld did not open I checked the console, which said:

````
Something is using the port 43349 in your system
ERROR:Anaconda.anaconda_lib.worker:Something is using the port 43349 in your system
````

How can I fix this?

**Comment by Gabriel-p** [comment]
Apparently this message is displayed when there are no changes to show?

**Comment by DamnWidget** [comment]
What you mean with "there are no changes to show?". That is one of those error messages that you should never get, and I am seriously here, never.

Is there any more logs in the console?

Which operating system and versions of everythign are you using?

**Comment by Gabriel-p** [comment]
I'm running [elementary OS](https://elementary.io) 0.3.2 64 bit.

What I mean is that apparently the `difftool` was not popping up (Meld) because there were no diffs to show.

I can not reproduce this message now, sorry.

**Comment by DamnWidget** [comment]
Closing it then
