### ISSUE TITLE
star unpacking(*) kills anaconda

### ISSUE THREAD

**Issue by Cescfangs** [DamnWidget/anaconda#466]
I found a really interesting bug when star unpacking is used, for example:

```python
a = [(1, 2, 3, 4)]
b = [x for x, *_ in a]
```
<img width="319" alt="screen shot 2016-04-17 at 11 23 52" src="https://cloud.githubusercontent.com/assets/11382612/14584950/25108afc-0493-11e6-8a47-13e888084e6d.png">

<img width="230" alt="screen shot 2016-04-17 at 11 55 14" src="https://cloud.githubusercontent.com/assets/11382612/14584953/63c14f34-0493-11e6-8157-fe5b9cdf51a9.png">

the second line could kill anaconda to dead,  all support  provided by anaconda then not available anymore, deleting `*` could bring anaconda to life:

```python
a = [(1, 2, 3, 4)]
b = [x for x in a]
```
<img width="352" alt="screen shot 2016-04-17 at 11 25 48" src="https://cloud.githubusercontent.com/assets/11382612/14584952/2d85a8ca-0493-11e6-939b-86eb92a39be5.png">

<img width="337" alt="screen shot 2016-04-17 at 11 55 29" src="https://cloud.githubusercontent.com/assets/11382612/14584957/68f7d84c-0493-11e6-9fc1-9dade197bd4d.png">

> under OS X 10.11.3, sublime build 3103

**Comment by DamnWidget** [comment]
If you check in your `~/Library/Cache/Jedi/` directory logs you will find something like `The underlying Jedi library as raised an exception`, seems to be a bug in Jedi (the library that anaconda uses to get documentation, signatures and autocompletion), at least in the version that we are currently using.

Obviously it only affects Python3 as that syntax is incorrect in Python2. I will take a look in deeper detail as soon as I can.

**Comment by DamnWidget** [comment]
Seems like is an already known bug in Jedi -> https://github.com/davidhalter/jedi/issues/707

**Comment by Cescfangs** [comment]
Yes, there're a lot `The underlying Jedi library as raised an exception` error in log file, hope this bug would be fixed soon and THX for the quick reply!

**Comment by DamnWidget** [comment]
@Cescfangs this was fixed by Jedi and is not affecting anaconda anymore can anyway, can you confirm and close the issue?

Thanks.

**Comment by Cescfangs** [comment]
Problem solved @DamnWidget
