### ISSUE TITLE
PEP 8 (E226) started showing now?

### ISSUE THREAD

**Issue by Gabriel-p** [DamnWidget/anaconda#471]
A line like the following:

    [0.]*len(all)

started, I believe two days ago, to be highlighted as a a violation of PEP8 E226 (no space around operator). I'm 100% sure this wasn't the case before.

Did something change in Anaconda or did I inadvertently change something either in this or some other package?

To be clear, I never added E226 to Anaconda's `pep8_ignore"` setting.

**Comment by DamnWidget** [comment]
Hi @Gabriel-p yeah we changed some specific pep8 behavior in the last update.

Just to put you in context, the `pep8` tool defines some errors as *ignored by default*, if you pass something in the `--ignore` flag, it then overrides the default ignored list in `pep8` and it gives you messages about those errors (as you are not ignoring them).

That is a weird behavior if you ask me, but if you have been using `pep8` you expect that behavior to be part of anaconda (in fact you didn't had any way before to make `pep8` to inform you about some ignored by default errors in anaconda, no way at all).

You can follow the discussion about that change [here](https://github.com/DamnWidget/anaconda/issues/464)
You can read a bit more about which errors are ignored by default in `pep8` [here](http://pep8.readthedocs.org/en/latest/intro.html)

The solution is easy, just add those errors to your ignore list.

**Comment by Gabriel-p** [comment]
Thanks for the explanation @DamnWidget.

One thing bothers me though. For example this line:

    hypot2 = x*x + y*y

will be highlighted  as a E226 violation, but in Guido's [style guide](https://www.python.org/dev/peps/pep-0008/#other-recommendations) that's actually the recommended use.

Who decides that this should be marked as a E226 violation? Can I change it? I definitely like Guido's style guide better.

**Comment by DamnWidget** [comment]
The last word to accept a Python Enhancement Proposals is as far as I know, Guido  Van Rossum but if E226 is accepted part of PEP8 and that syntax is detected as a violation, I guess it's a violation doesn't matter if is suggested by Guido or not.

Is up to you to ignore that PEP8 violation or not I guess :)

**Comment by Gabriel-p** [comment]
I'd like to avoid having to ignore E226, but I also don't like the current interpretation.

Where does Anaconda get its PEP8 guidelines from? I'd like to go over there and propose Guido's interpretation of E226 which I prefer. Would you be so kind to point me to the right repo?

**Comment by DamnWidget** [comment]
Anaconda uses the [pep8](https://github.com/PyCQA/pycodestyle) package from the Python Code Quality Authority but the pep8 tool itself is made following the [PEP8](https://www.python.org/dev/peps/pep-0008/) itself

**Comment by Gabriel-p** [comment]
Thank you! Will got to complain over there :)

**Comment by David-OConnor** [comment]
I submitted this on pep8 years go and it's till there!

**Comment by Gabriel-p** [comment]
@David-OConnor I'll wait a day or two to see if there's an answer, if not I'll open a new one.

**Comment by dev169** [comment]
I had to do a double take reading this issue, so to restate the problem:

If you decide to manually ignore checks by adding them to `pep8_ignore` in Anaconda user settings, these and only these settings will be ignored by `pycodestyle`. 

Everything that used to be ignored by the default `pycodestyle` configuration will be un-ignored, since we are passing a custom configuration now, and you'll have to manually add them to your `pep8_ignore` list if you want the default `pycodestyle` behaviour.

These checks are E121, E123, E126, E133, E226, E241, E242, E704 and W503 (can be found [here](https://github.com/PyCQA/pycodestyle/blob/master/docs/intro.rst)).

Therefore your `/User/Anaconda.sublime-settings` should look like this:

```json
{ 
    "pep8_ignore": [
        <YOUR_STUFF_HERE>,

        "E121",
        "E123",
        "E126",
        "E133",
        "E226",
        "E241",
        "E242",
        "E704",
        "W503",
    ] 
}
```

Phew!

**Comment by DamnWidget** [comment]
That sounds about right yeah
