### ISSUE TITLE
1.4.21 and test runner issue?

### ISSUE THREAD

**Issue by montegoode** [DamnWidget/anaconda#475]
I've been using this configuration (example from the official docs) to run the tests for one of my projects with everything in a virtualenv:

```
        "test_before_command": "source $HOME/.virtualenvs/myproject/bin/python",
        "test_after_command": "deactivate"
```

After the update this morning, this doesn't seem to be working anymore. Initially I'll get an error about `/bin/bash: nosetests: command not found`. Normally I just launch sublime from Alfred. If I kill sublime, and restart it from a terminal shell that has that virtualenv already activated, then `nosetests` will run. However not I get an error trace `/bin/bash: deactivate: command not found`.

Has there been a change in how the test runner needs to be configured, etc?

Cheers!

**Comment by DamnWidget** [comment]
There was this [pull request](https://github.com/DamnWidget/anaconda/pull/441) related with tests.

Can you paste any error in your ST3 console? The `deactivate` command is environmental dependent as far as I understand.

**Comment by montegoode** [comment]
Sure thing. I wonder if that PR is somehow interfering with running tests with virtualenv.

Here is my original configuration that I've been using for a couple of months:

```
		"pylint_rcfile": "~/Dropbox/Work/pypond/pypond/pylint.rc",
		"python_interpreter": "~/Dropbox/Work/pypond/venv/bin/python",
		"test_before_command": "source ~/Dropbox/Work/pypond/venv/bin/activate",
		"test_after_command": "deactivate",
```

After the update this morning when I start sublime with my launcher (Alfred) and try to invoke the tests (using the anaconda default of nose):

```
/bin/bash: nosetests: command not found
/bin/bash: deactivate: command not found
[Finished in 0.0s with exit code 127]
[shell_cmd: source ~/Dropbox/Work/pypond/venv/bin/activate & nosetests  & deactivate]
[dir: /Users/monte/Dropbox/Work/pypond/pypond]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

Even though the virtualenv is being activated, it now can not find `nosetests`. I've verified that these shell commands work from the command line and `nosetests` are installed just like they always were. Somehow the path from the activated `virtualenv` is not getting set or inherited from.

So if I kill sublime, start the terminal, activate the virtualenv for my project, and then start sublime with `subl` and try to run the tests, I get a little farther but still have errors:

```
/bin/bash: deactivate: command not found
create a regular Event from datetime, dict. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
[Finished in 0.2s with exit code 127]
[shell_cmd: source ~/Dropbox/Work/pypond/venv/bin/activate & nosetests tests.event_test:TestRegularEventCreation.test_regular_with_dt_data_key & deactivate]
[dir: /Users/monte/Dropbox/Work/pypond/pypond]
[path: /Users/monte/Dropbox/Work/pypond/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]
```
It is now finding `nosetests` because it is inheriting the environment from my shell now, but it should be getting it from the activated `virutalenv`. And now it can't execute `deactivate` for some reason as well.

It looks like the recent change impacted how the test runner is dealing with the environment under the hood so if you're trying to run your tests from a `virutualenv` instead of a global python installation, it's messed up.

Does this help?

**Comment by DamnWidget** [comment]
Can you rollback your anaconda to v1.4.18 and try that again?

To rollback anaconda just follow the steps below:

1. Remove Anaconda package from your Sublime Text 3 using the `Command Palette`
2. Open a terminal ans go to: `cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/`
3. Clone anaconda repo: `git clone https://github.com/DamnWidget/anaconda
3. Checkout v1.4.18: `git checkout v1.4.18`

**Comment by montegoode** [comment]
That worked fine with my pre-existing configuration. Didn't need to launch from the shell with the virtualenv activated, deactivate worked, etc etc. Something in the test runner definitely changed with this release.

I also tried using the `test_virtualenv` directive rather than the before and after ones. It works fine in 1.4.18 but not in the 1.4.21 - same environment problem.

**Comment by DamnWidget** [comment]
Ok, I am gonna rollback that PR today

**Comment by DamnWidget** [comment]
@montegoode version 1.4.22 rollback PR #441, can you test it and close this ticket accordingly please?

**Comment by montegoode** [comment]
@DamnWidget I pulled down 1.4.22 with sublime package control and I'm seeing the same behavior as in 1.4.21:

```
/bin/bash: nosetests: command not found
/bin/bash: deactivate: command not found
[Finished in 0.0s with exit code 127]
[shell_cmd: source ~/Dropbox/Work/pypond/venv/bin/activate & nosetests tests.event_test & deactivate]
[dir: /Users/monte/Dropbox/Work/pypond/pypond]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

I'm not sure what is different between .18 and .21. I can't tell if either 1) the virtualenv is not being activated (it looks like it is from the `shell_cmd` traceback however) or 2) if the virtualenv is being activated and the new environment is somehow not being inherited? The traceback is showing that the virtualenv is not being added to the `path`.

I know that interacting with the virtualenv still works - I set the `python_interpreter` directive to point at a virtualenv to among other things run pylint which works fine. This behavior is impacting the test runner only.

**Comment by DamnWidget** [comment]
I think I found the problem but I can't test it myself, I need you to edit a file in your anaconda installation and tell me if it solved your problem.

Open `~/Library/Aplication\ Support/Sublime\ Text\ 3/Packages/Anaconda/commands/test_runner.py` and change line 16 from:
```python
COMMAND_SEPARATOR = "&" if os.name == "nt" else "&"
```
to:
```python
COMMAND_SEPARATOR = "&" if os.name == "nt" else ";"
```
Thanks

**Comment by montegoode** [comment]
@DamnWidget That did the trick!
