### ISSUE TITLE
Too many jsonservers are being spawned

### ISSUE THREAD

**Issue by logileifs** [DamnWidget/anaconda#476]
![anaconda_jsonserver2](https://cloud.githubusercontent.com/assets/2317815/14848027/396c8a58-0c5b-11e6-913d-7ec8e711acd6.png)

Somehow I have 29 instances of jsonserver running but only two sublime windows. I tried closing some files but that had no effect on the number of instances. This sometimes reaches a point where sublime text becomes unresponsive. If there is something I can do to avoid this happening I would appreciate some advice.

**Comment by DamnWidget** [comment]
Hi, definitely that is a non expected behavior, I would need more information about your environment. I see that you are using Linux but I need as well:

* Sublime Text 3 Version
* Anaconda Version
* Sublime Text 3 console logs
* Anaconda JsonServer logs (you can find them in `~/.cache/jedi/anconda-3/anaconda_jsonserver.log`

**Comment by logileifs** [comment]
OS: Linux 4.4.0-21-generic #37-Ubuntu SMP x86_64 GNU/Linux

- OS: Linux 4.4.0-21-generic #37-Ubuntu SMP x86_64 GNU/Linux
- Anaconda version '1.4.22'

**Comment by DamnWidget** [comment]
I am afraid that you need to start your JsonServer in debug mode to see what is happening as there is some exception but is not logged into the log file.

To do so you need to do a couple of things, follow the steps below 

1. Close Sublime Text 3 completely
2. Run: `python -B ~/.config/sublime-text-3/Packages/anaconda/anaconda_server/jsonserver.py -p test 9999 DEBUG`
3. Set `jsonserver_debug` as `true` and `jsonserver_debug_port` as `9999` in your Anaconda settings
4. Start Sublime Text 3 and open any Python file

You will get whatever exception is occurring in the terminal that you did run the JsonServer manually, copy and paste it in pastebin or similar and come back.

Thanks

**Comment by logileifs** [comment]
I'm not sure why but when running in debug mode it never spawned more than one process but [here](http://pastebin.com/ibf8Q2Ca) is the log anyway, hope there is something useful there.

**Comment by logileifs** [comment]
As soon as I started Sublime Text again without jsonserver_debug set as True I'm seeing [this](http://pastebin.com/f9fQgjpJ)

**Comment by DamnWidget** [comment]
That is weird, seems like you have a `html` package in your Python2 path that is messing with the logic in the doc command.

Can you start a python interpreter and give me the output of the following code?
```python
import html
print(html.__file__)
print(html.__doc__)
```

**Comment by logileifs** [comment]
>>> import html
>>> print(html.__file__)
/home/logi/.local/lib/python2.7/site-packages/html/__init__.py
>>> print(html.__doc__)
None

**Comment by DamnWidget** [comment]
I have no idea what is that html package in your Python installation, can you do a `pip freeze --all` to see from where that package comes from? Also a `python -c "import html; print(html);"` would be nice.

**Comment by logileifs** [comment]
logi@UX305CA:~/tmp$ python -c "import html; print(html);"
    <module 'html' from '/home/logi/.local/lib/python2.7/site-packages/html/__init__.py'>

**Comment by logileifs** [comment]
output of `pip freeze --all`: http://pastebin.com/4Sg4sAqr

**Comment by DamnWidget** [comment]
That package doesn't appears in your pip freeze and is installed in your
user directory, can you check with IPython or opening the module directly
in your ST3 which methods does it have? Doing a print(dir(html)) after
import it would be interesting too.

On 27 April 2016 at 21:20, Logi <notifications@github.com> wrote:

> output of pip freeze --all: http://pastebin.com/4Sg4sAqr
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/476#issuecomment-215215823>
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by apapanico** [comment]
Hey, I am having this exact same issue.  

That html package is supposed to raise an ImportError if called from python3.

```
$ cat /usr/local/lib/python2.7/dist-packages/html/__init__.py
from __future__ import absolute_import
import sys

if sys.version_info[0] < 3:
    from future.moves.html import *
else:
    raise ImportError('This package should not be accessible on Python 3. '
                      'Either you are trying to run from the python-future src folder '
                      'or your installation of python-future is corrupted.')

```

Python3 imports a different html package:
```
>>> import html
>>> html.__path__
['/usr/lib/python3.4/html']
```

Wouldn't a potential solution be to change the try/except on `import html` to a conditional on the Python version just like in the `_html` method?

**Comment by DamnWidget** [comment]
Seems like that `html` module comes from `python2-future` provided by `http://python-future.org` that distributes an incomplete version of the Python3 `html` module as the `unescape` method is missing on it. I still don't understand why people continue creating these kind of packages that doesn't really solve the compatibility problems and break stuff.

Continue this discussion in #477

**Comment by DamnWidget** [comment]
@logileifs can you confirm that this issue is fixed for you and close it please?

**Comment by logileifs** [comment]
@DamnWidget looks like it is fixed now, still not 100% sure but I will report back if I experience anything similar again. By the way, thanks for an awesome sublime plugin :)

**Comment by DamnWidget** [comment]
No, thank you, I just created this plugin for personal use and you all made it great with your suggestions, ideas and contributions.

I am closing this one, feel free to open it again if you need.
