### ISSUE TITLE
Autocomplete does not conform to PEP8 style

### ISSUE THREAD

**Issue by baubaid** [DamnWidget/anaconda#483]
I don't know if this is considered an issue per se, but whenever I use autocomplete to get the body of a 'for' loop or the body of a 'def' block, the indentation does not conform to PEP8 style (i.e. the body of the block is only indented with 2 spaces rather than 4). This would mean that every time I use autocomplete I get a linting error that I have to fix or auto-fix.

Is it possible to fix this somehow to make this conformance automatic?

P.S. I'm new hear and a novice at this stuff so I apologize if this is simple enough to be fixed easily.

But thanks!

Edit: Spelling, punctuation, and clarification.

**Comment by DamnWidget** [comment]
Try to set the tab options as is shown in the screenshot below

![screenshot_20160521_182653](https://cloud.githubusercontent.com/assets/329766/15449862/a14dea70-1f81-11e6-89a7-56cbd2ce4d28.png)

**Comment by baubaid** [comment]
Simple enough, indeed. Thanks!

Follow-up question: Is there a way to fix other non-conformances? For instance:
Using autocomplete for a for loop gives:
`for x in xrange(1,10):`
whereas we would need:
`for x in xrange(1, 10):`
with a space after the comma.

Can this be fixed as well?

**Comment by DamnWidget** [comment]
The `for` completion is what in Sublime Text is known as a `snippet` those snippets comes with your Sublime Text 3 installation they are not part of anaconda themselves, said that, you could be able to fix any PEP8 violation using the anaconda's auto formatting capabilities.

To do so, just open your Command Palette and write `autoformat` and then press enter, anaconda will autoformat your whole file, you can also use a keyboard shortcut (Ctrl+Alt+R on Linux and Windows for example) . You can also configure anaconda to run the autoformat every time that you save your file.

I don't recommend run the autoformat with very long files as the ST3 performance can be compromised.

For more information take a look to the [official documentation for autoformat](http://damnwidget.github.io/anaconda/IDE/#toc_42), that is an extensive anaconda documentation where you can learn how to configure multitude of options and discover what the plugin can offer you.

**Comment by baubaid** [comment]
Thanks for clearing that up! I did not realize that the `for` completion was not part of anaconda as I installed anaconda immediately after I installed ST3 and did not realize that.

Thanks again for your help and for the awesome package!

**Comment by DamnWidget** [comment]
No problem, there is a chat room in gitter where you can also ask for any help that you need, me or other people that are available could help you with your doubts.

You can join the chat room cliking on [this link](https://gitter.im/DamnWidget/anaconda?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
