### ISSUE TITLE
How to disable annoying selection for each line ?

### ISSUE THREAD

**Issue by xtipacko** [DamnWidget/anaconda#484]
How to disable annoying selection for each line ? and why does it appear?
![image](https://cloud.githubusercontent.com/assets/18727066/15452922/0ff3fb8c-2008-11e6-8580-bf955dfc22a9.png)

**Comment by xtipacko** [comment]
When i set "anaconda_linter_mark_style": "none", selection is gone, but now there are dashes at the begining of each line, what is that? how to disable it? 
![image](https://cloud.githubusercontent.com/assets/18727066/15452936/a84e9414-2008-11e6-808c-7fcbc1c95271.png)

**Comment by DamnWidget** [comment]
That is what in computer science is known as code linting, you can check the [wikipedia article](https://en.wikipedia.org/wiki/Lint_(software)) for more information.

They are annoying for a reason, in that way you are "forced" to fix your code, anaconda is telling you that your code "smells" for whatever reason, the package support code analysis and style analysis. If you move your cursor to one of the lines, you will get a complete description of what the problem in that line is in the Sublime Text 3 status bar, I guess you are mixing spaces with tabs and this is why you have all of your lines marked.

I recommend you to take a look to the plugin documentation [about linting](http://damnwidget.github.io/anaconda/IDE/#toc_28)  and that you read the documentation in general.

Even if anaconda allows you to completely disable code linting, I recommend you that don't do it and get used to fix your code to don't get marks, in no time you will be writing fully compliant code.

Btw, in your `generate_url` function, you use string concatenation using the + symbol, that is considered a bad practice in Python as strings are non mutable data structures and every time that you concatenate them (like it was PHP) python is allocating new memory and creating a new string to append the right side of the expression, that is slow. You will probably want to take a look at the Wikipedia article about [string interpolation](https://en.wikipedia.org/wiki/String_interpolation) where you can find examples for python and the official Python documentation about [common string operations](https://docs.python.org/2/library/string.html).

Regards

**Comment by xtipacko** [comment]
Thanks this is very usefull. If only i have more time...
