### ISSUE TITLE
Address already in use issue 

### ISSUE THREAD

**Issue by prakashversion1** [DamnWidget/anaconda#486]
When I start sublime text for the first time I am receiving the following error : 
[http://pastebin.com/iU2EMGX1]
Also, this is freezing my sublime text menu bar from time to time.

**Comment by DamnWidget** [comment]
Hi, the [docker branch](https://github.com/DamnWidget/anaconda/tree/docker) refactors how the workers spawns and connects to the JsonServer there is no much point in look at this now as all its current subsystem form is gonna be replaced soon.

If the problem grows and makes impossible to you to use ST3 re-open this issue so I Could give you further assistance.
