### ISSUE TITLE
raise from is recognised as invalid syntax

### ISSUE THREAD

**Issue by bofm** [DamnWidget/anaconda#487]
Example:
```python
try:
    1 / 0
except ZeroDivisionError as e:
    raise RuntimeError('x') from e
```
<img width="400" alt="screen shot 2016-05-29 at 17 25 16" src="https://cloud.githubusercontent.com/assets/3646419/15633997/c30981e8-25ca-11e6-8b42-15c38eba4ec9.png">

ST3 build 3113 on OS X.

**Comment by DamnWidget** [comment]
Probably you are not using a python3 interpreter for your `python_interpreter` settings.
