### ISSUE TITLE
[meta] Moving non python-support specific code into a Package Control Dependency

### ISSUE THREAD

**Issue by pradyunsg** [DamnWidget/anaconda#489]
Some off-topic:
- Many thanks for such a wonderful package!
- I would like to help you with this package. Do you have any suggestions ("easy" issues) for me to start with?

This issue is really somewhere between a question and a feature request.

Would it be possible to move code that would be shared by Anaconda and Anaconda Rust into a Package Control dependency that can be reused by the two of them? If so, would it be advantageous in any manner whatsoever?

I think if it would be done right, all the language-specific and tool-specific code would live in this package and the Package Control dependency would have all the non-language-specific infrastructure. That way, someone else may also be able to utilize the infrastructure to provide first-class support for other languages, to the extent possible.

What are your thoughts on this?

PS: Also, Anaconda Rust doesn't sound right...

**Comment by DamnWidget** [comment]
Answering your first question, you can take a quick look at the open issues and pick one to start working on, if you do, diverge your code from `v2.0.0-rc1` branch please.

About the non python-support, well, anaconda offers a plugable architecture ready to use with any ST3 package, you can find more information in the [plugable architecture](https://damnwidget.gitbooks.io/anacondast3-developers-documentation/content/anaconda_plugable_architecture/index.html) section of the [anaconda's developer documentation](https://damnwidget.gitbooks.io/anacondast3-developers-documentation)

I am not native English speaker but I can't see why anaconda rust doesn't sound right ;)

**Comment by pradyunsg** [comment]
> you can take a quick look at the open issues and pick one to start working on

On it. :wink: 

I meant moving the "plugable architecture" portion into a Package-Control Dependency. And adding it as a dependency for all `anaconda*` projects.

> I am not native English speaker but I can't see why anaconda rust doesn't sound right ;)

I am (kinda) but I don't really mind if it doesn't change.

**Comment by DamnWidget** [comment]
I already have a plans to decouple even more the anaconda JsonServer from ST3 itself, and make it a standalone service that could be then used with other editors like atom, brackets, vim or emacs what I don't have is time.

The only downside to move the anaconda asynchronous infrastructure (workers, jsonclient, ioloop) into a separate package is the added complexity, is something that I am open to study and review but right now I am focusing my limited time into release version 2.

Btw, if you choose an issue to work on, let me know cos probably I am working on it as well or I can guide you a bit about it.

**Comment by pradyunsg** [comment]
Great to know! I guess this issue could become a tracking issue for that.

Note: I ended up taking up an issue with pip. I will come back to this project, as soon as I'm done with that.

I like #414 and #235. They are both feature-requests. I don't think you're not going to get the time to work on these with 2.0.0 coming up. Any tips for these or other issues?

**Comment by DamnWidget** [comment]
Sorry for the delay, I have been really busy lately. 

I think #414 is gonna be a bit tricky as the support for HTML in the ST3 tooltip thing is not too complete.
About #235, I think ST3 already implements something like that in the vanilla packages in the Goto everywhere.

**Comment by DamnWidget** [comment]
Hey @pradyunsg, any progress about the issues that you did choose?

**Comment by pradyunsg** [comment]
Nope. No progress. The pip issue took waaay too long and still isn't over. :disappointed: And I then got low on time. Anyway, I'll to tackle them today or in the weekend.

**Comment by DamnWidget** [comment]
No worries, there is no rush I was just checking old issues so I had to ask

**Comment by pradyunsg** [comment]
Thanks for the reminder.

**Comment by DamnWidget** [comment]
@pradyunsg https://github.com/DamnWidget/anaconda/projects

**Comment by pradyunsg** [comment]
Count me in a contributor for this.

Just a few doubts:

- Why Go?
- I don't think you know about this: https://en.wikipedia.org/wiki/Golconda - Maybe we need a new name?
- So... Golconda would be a central server that would provide the functionality provided by JSONServer (makes sense). So, we would end up having language-specific components and editor-specific components, talking through Golconda. Right?

   ```
   Python-Support  ─┐                ┌─ Atom
   Rust-Support    ─┼─── Golconda ───┴─ Sublime Text
   Go-Support      ─┘
   ```

**Comment by DamnWidget** [comment]
I will try to answer your doubts:
* It is easy to distribute (just a binary) and it's seriously fast as an HTTP router plus it's easy to make concurrent/asynchronous work with it  and support contextual operations out of the box since Go 1.7. I am open to other languages with similar capabilities like Rust, the reason that I did not choose Rust is that I am not that proficient with is as with Go. I also like Twisted and PyPy but the redistribution of the server if it is written into Python depends too much in the end user environment something that we don't really want.
* I don't really see any problem for some cities called the same than the application, at least there is no other software called the same (like the situation that we have now)
* That's right

**Comment by DamnWidget** [comment]
@pradyunsg can you send me an email? My email address is in my Github information.

Regards.

**Comment by pradyunsg** [comment]
I'm on to move right now... I'll do that when I get to my destination.

**Comment by pradyunsg** [comment]
@DamnWidget Did you receive the email?   My email address is Github username at Gmail.com.

**Comment by DamnWidget** [comment]
nope, I did not get anything

**Comment by pradyunsg** [comment]
I sent it to the fsf mail id. Whoops!

**Comment by pradyunsg** [comment]
I got the mail!
