### ISSUE TITLE
Pep 484

### ISSUE THREAD

**Issue by qmmp123** [DamnWidget/anaconda#491]
Will you add support for pep 484?
for example:

```
def some() -> str:
    # some actions
    return str_var

some(). # and after dot i want to get list methods of returned object 
```

**Comment by DamnWidget** [comment]
That is more a question for Jedi, our auto-completion underlying library and seems like it's already answered https://github.com/davidhalter/jedi/issues/729

I will update to the latest stable Jedi version for v2.0.0 that is on the way now but Jedi will move that feature to the stable branch in the future I am afraid.

**Comment by qmmp123** [comment]
Thank for your answer. I will wait
