### ISSUE TITLE
Garbage in the footer

### ISSUE THREAD

**Issue by kkurian** [DamnWidget/anaconda#493]
While working on a file, the ST3 footer will as expected contain something like this:

![screen shot 2016-06-25 at 11 46 49 pm](https://cloud.githubusercontent.com/assets/70291/16360404/24335f2e-3b2f-11e6-9e6e-3d54c3f1ff3b.png)

or like this:

![screen shot 2016-06-25 at 11 47 00 pm 1](https://cloud.githubusercontent.com/assets/70291/16360406/263c1f36-3b2f-11e6-943f-258107f39802.png)

Frequently and for no apparent reason, however, anaconda starts displaying garbage in the footer like this:

![screen shot 2016-06-25 at 11 39 18 pm](https://cloud.githubusercontent.com/assets/70291/16360399/e7be6ee4-3b2e-11e6-8a2e-829f76c5f8ee.png)

or garbage trailing an expected lint error like this:

![screen shot 2016-06-26 at 12 10 57 am](https://cloud.githubusercontent.com/assets/70291/16360453/8488e24c-3b32-11e6-9df4-19c6617bc4d0.png)

The garbage sticks around for awhile until, again for no apparent reason, the footer goes back to normal.

Other things to note:

Closing and reopening the file being edited temporarily resolves the issue.

The issue does not immediately affect other panes: If the footer for one pane starts behaving badly then switching focus to another pane may reveal the expected footer (i.e., no garbage in the footer) for the other pane.

ST3 Build 3114
Anaconda 1.4.26

**Comment by AndreasBackx** [comment]
The `show_signatures` does not seem to show the signatures for me anymore, but instead the docstring every single time and makes it quite a pain to use.

**Comment by DamnWidget** [comment]
From the config file:

**Comment by kkurian** [comment]
@DamnWidget According to the config files, the tooltip settings relate to floating popups not the footer.

```json
    /*
        If you set the following option as true, anaconda will display the
        signatures of the methods in a floating popup

        *note*: this action takes effect if "display_signatures" is true
    */
    "enable_signatures_tooltip": true,

    /*
        If you set the following option as true, anaconda will display the
        documentation of modules, classes or methods in a floating popup
    */
    "enable_docstrings_tooltip": true,
```

That said I'll give your suggestion a try. If it works then, at least, comments in the default config file ought to be updated.

**Comment by AndreasBackx** [comment]
@DamnWidget I thought the same thing. But it only seems to work for the tooltips and I have all of the tooltip settings set to false.

**Comment by DamnWidget** [comment]
I will take a look

**Comment by DamnWidget** [comment]
I already fixed this bug but I am not sure when I am gonna release it, I don't know if wait for v2.0.0 or push a small one. I will decide it later.

**Comment by AndreasBackx** [comment]
I would really love a small one, most people use the signatures shown in the footer. Thanks for the fix.

**Comment by DamnWidget** [comment]
I made my mind, I will release this fix later today
