### ISSUE TITLE
Support to run scripts using arguments

### ISSUE THREAD

**Issue by Jorg3Moreno** [DamnWidget/anaconda#494]
Hi everyone.

Currently is posible run scripts using arguments with `shell_cmd`, for example:
`"shell_cmd": "python -u \"$file\" arg1 arg2"`
But, when i use `"Anaconda Python Builder",` `"shell_cmd"` is override and is not possible use arguments.

I think it's a good idea to include a setting (like `"python_interpreter")` that allows pass arguments to run the scripts.

Thank you for your attention.

**Comment by DamnWidget** [comment]
Hi Jorge

You really shouldn't be using the Anaconda Python Builder, create one for your own and attach to it, anyway, I will think about add something like what you requested but the Anaconda Python Builder is not designed to be flexible but easy to use.
