### ISSUE TITLE
[v2.0.0] We need brave man and women

### ISSUE THREAD

**Issue by DamnWidget** [DamnWidget/anaconda#498]
Hi everyone,

Release of v2.0.0 is now very close, there is only one more issue to be addressed in the milestone and then we are ready to rock. As some of you already know, I program now much more in Go and Rust than in Python, I find myself using vim a lot now and when I have a GUI and I am able to use ST3 I use `anaconda_rust` for rust or `GoSublime` for Go (I am thinking in take `anaconda_go` back to live as I am missing some features related with linting more than anything in `GoSublime` but that is a topic for other story).

What I am trying to say is that I don't use any of the new v2.0.0 features (except MyPy) so I need you to test it for a while before go live and break thousand of user development environments.

Can those of you that are brave enough to checkout branch `v2.0.0-rc1` and use it for your day to day work? Version 2.0.0 comes with lot of improvements in the network field, I completely rewrote how the workers are implemented and now we support some sweet features like remote workers, and native docker and vagrant support (no more vagrant branch).

There is some information about that topic in the [wiki](https://github.com/DamnWidget/anaconda/wiki) left side in the v2.0.0 documentation. I will really appreciate if some brave men and women step forward and help to test this new release.

Regards.

**Comment by sametmax** [comment]
Ok, will give it a try.

**Comment by sametmax** [comment]
2 stuff I tried to do but couldn't find how:

- Activate mypy linting;
- test the docker integration.

The rest seems to work fine for now, but I'll need a week of fiddling to confirm it's solid.

**Comment by DamnWidget** [comment]
Hi, thank you for test anaconda v2.0.0 as being the next major release I
am beinng very cautious about it.

You can check the options for MyPy in here:
https://github.com/DamnWidget/anaconda/blob/v2.0.0-rc1/Anaconda.sublime-settings#L451-L495

For docker you can follow the wiki:
https://github.com/DamnWidget/anaconda/wiki/Anaconda-v2:-Using-a-remote-python-interpreter-through-Docker

Regards

**Comment by DamnWidget** [comment]
Anaconda v2.0.0 has been already released

**Comment by sametmax** [comment]
I've been using it for days now. No problem so far. Great job !
