### ISSUE TITLE
Anaconda cuases plugin_host exited unexpectedly error- sublime build 3114 Windows 10

### ISSUE THREAD

**Issue by cameronnn** [DamnWidget/anaconda#504]
Hi, Whenever I install Anaconda package I got this error frequently during work and I have to restart sublime text because package control and snippets seems to be out of reach.
Also Anaconda causes a slightly performance issue during writing the code.
I removed all my plugins each by each and tested which cause this problem and it is Anaconda

What can I do ? I appreciate your help

**Comment by DamnWidget** [comment]
Hi, there are several things that you can do yo help us to help you.

- Give us a detailed list of plugins that you use in your ST3
- Capture any output log from the ST3 console
- Create a gist with the contents of the file in `%APPDATA%\\Jedi\\Jedi\\<your_project_name>\\anaconda_jsonserver.log

**Comment by DamnWidget** [comment]
Any update here?

**Comment by cameronnn** [comment]
List of my plugins right now: 

-Anaconda
-Autoprefixer
-Babel
-BracketHighlighter
-Can I use
-Color Highlighter
-Color picker
-CSS Extended completions
-CSS Media query snippets
-CSS snippets
-DocBlocker
-Emmet
-Flask Completions
-Flask Starter
-HTML Snippets
-HTML5
-HTML5 Doctor CSS Rest Snippet
-Javascript Completions
-JavascriptNext
-JQuery
-JSFormat
-JSHint
-LiveReload
-LiveStyle
-Package Control
-PyV8
-Requirnmentstxt
-SidebarEnhhancements
-SublimeCodeIntel

**Comment by DamnWidget** [comment]
Those are quite a few plugins that you are using.

First thing, don't use SublimeCodeIntel and anaconda together, if you are gonna edit python code, consider to disable SublimeCodeIntel, this is a plugin well known for interfere with other autocompletion plugins, anaconda being one of them.

I still need the logs that I asked for. Can you provide them please?

**Comment by xuyuheng** [comment]
The macOS has same problems!

**Comment by DamnWidget** [comment]
I am gonna close this as right now is just noise, feel free to re-open if you find a reliable way to reproduce the problem
