### ISSUE TITLE
Feature request: Suppress output pr. line using a comment

### ISSUE THREAD

**Issue by AllanLRH** [DamnWidget/anaconda#505]
Would be nice to be able to suppress output pr. line using a comment like `# ignore: E127, W311`.

**Comment by DamnWidget** [comment]
What you mean with "output pr"? You can use `# noqa` to suppress some of the linting errors

**Comment by AllanLRH** [comment]
Meant exactly like the `# noqa` comment, but for all linting errors – maybe it could be suppressed at the plugin level of the code?

**Comment by DamnWidget** [comment]
Is not that simple to suppress them at the plugin level, the data that comes from the linters have no information about the comments in the line that has being linted. I would need to think about this deeper to know if it would be viable.

In the meanwhile you have several options

* Add the errors/warnings that annoys you to the ignore list (but it would be disable in the whole project ;___;)
* Disable linting in that file :|

**Comment by DamnWidget** [comment]
I think I can implement this but it has to wait till v2.0.0

**Comment by AllanLRH** [comment]
That would make linting through anaconda immensely more useful and unobtrusive for me 👍

**Comment by DamnWidget** [comment]
This was release a while ago, can you @AllanLRH  confirm that is working as expected and close the ticket please?

**Comment by AllanLRH** [comment]
Yes, it works as requested/expected. Thanks for putting in the work! 👍
