### ISSUE TITLE
"E125" and "E129" means the same??

### ISSUE THREAD

**Issue by redstoneleo** [DamnWidget/anaconda#506]
The doc here syas
http://damnwidget.github.io/anaconda/IDE/#toc_46
"E125" and "E129" means the same : Indent to distinguish line from next logical line

**Comment by DamnWidget** [comment]
Seems like they modified the error codes descriptions since that page that you referenced was written, they have a much more accurate descriptions now, I should update ours.

More info: http://pep8.readthedocs.io/en/latest/intro.html#error-codes

**Comment by DamnWidget** [comment]
I updated the documentation to reflect a more accurate description of what each error means instead of what the autoformat tool do
