### ISSUE TITLE
Sublime is barely responsive while editing python file.

### ISSUE THREAD

**Issue by ludbek** [DamnWidget/anaconda#507]
Sublime is barely responsive while editing python file.

**Comment by DamnWidget** [comment]
There is nothing that we can do with the information that you provided that is none. You should tell us which versions are you using in which operating system and which other packages are you using along side with anaconda.

The first thing that you should do is disable all plugins but anaconda and check if your ST3 is unresponsive, if it is, you probably configured a non valid `python_interpreter` or you didn't configured a `python_interpreter` and there is no `python` command in your PATH.

Please, refer to the documentation: http://damnwidget.github.io/anaconda/

**Comment by commutecat** [comment]
My current work around : DISABLE Package control  and re-enable it. 

At first , I suspect something with sublime when I notice text entry turn sluggish.  

OS : ubuntu 14.04.1  , kernel version  3.16.0-77 x86_64
```
# removal of sublime-text
sudo apt-get purge sublime-text 

# remove ALL sublime config
rm -fr ~/.config/sublime-text*

# install sublime build 3114 
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt-get install sublime-text-installer

# check the package install
dpkg -l | grep sublime 
ii  sublime-text-installer   3114-2~webupd8~0 all  Sublime Text 3 installer - beta build

# check python availability 
which python 
> /usr/bin/python
```

Then follow typical sublime Package Control installation. Then install anaconda using package controller.  As soon as Anaconda install into Sublime, all my text editing will slow to snail. 

After another retry, I decide to use Package Control to disable Package Control.   And it is strange that Anaconda now works without a hitch. 
Then I open "Preferences - Settings - User", look for the ignored_packages :  
```
"ignored_packages":
	[
		"Vintage",
                "Package Control",
	]
```
Delete the entry "Package Control". Restart Sublime.  By "miracle", everything works.

**Comment by commutecat** [comment]
The proper diagnosis found, a required log file used by anaconda json server permission overwrite by root.  
https://github.com/DamnWidget/anaconda/issues/511

Because purging of sublime and re-installation will clean up the log folder used by Anaconda, that temporary "fix"(in exact, delete) the log file .
