### ISSUE TITLE
vagrant_server cannot start

### ISSUE THREAD

**Issue by divinites** [DamnWidget/anaconda#508]
I tried to configure vagrant + anaconda following your instruction here:
[http://damnwidget.github.io/anaconda/vagrant/](http://damnwidget.github.io/anaconda/vagrant/)

But I encountered an error when starting the vagrant server on the guest machine:
`python server.py`

the error message is:

> Traceback (most recent call last):
  File "/vagrant/anaconda/anaconda_lib/enum.py", line 367, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "../anaconda_server/jsonserver.py", line 9, in <module>
    import socket
  File "/usr/local/lib/python3.5/socket.py", line 73, in <module>
    IntEnum._convert(
  File "/vagrant/anaconda/anaconda_lib/enum.py", line 369, in __getattr__
    raise AttributeError(name)
AttributeError: _convert
Starting the server...                                                   [Fail]
(None, None)

**Comment by DamnWidget** [comment]
Can't reproduce it using Python 3.5.2, what is that vagrant machine running?

**Comment by divinites** [comment]
Vagrant is running ubuntu 14.04 x64. This problem only happens when I
change the entry in config.py from python to python3. The server runs okay
when using python 2.7.



On 2016年8月15日 at 上午8:26:25, Campos Oscar (notifications@github.com) wrote:

Can't reproduce it using Python 3.5.2, what is that vagrant machine running?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DamnWidget/anaconda/issues/508#issuecomment-239743817>,
or mute the thread

**Comment by divinites** [comment]
This is my config file:

> """
Anaconda standalone server configuration
"""

> python_interpreter = "python3"       # the interpreter to use
project = "github_crawler"                # the name of the project
extra_paths = None                  # a list of extra paths
port = '19360'                      # the port to listen on (as string)

**Comment by DamnWidget** [comment]
In the traceback looks like your Python 3 interpreter is using the Enum backport for Python 2 instead of it's own native Enum class.

I don't think this is related with anaconda itself but environmental to your vagrant.

By the way, if you are using anaconda with vagrant, you would probably give a try to the v2.0.0-rc1 branch using this configuration: https://github.com/DamnWidget/anaconda/wiki/Anaconda-v2:-Using-a-remote-python-interpreter-through-Vagrant

**Comment by divinites** [comment]
Good, I will try anaconda 2.0 then.

**Comment by divinites** [comment]
My situation is that I have a headless server runing osx + vagrant linux, I would like to use anaconda in my laptop to connect to this server and write code. 

In this situation, vagrant and sublime text is not in the same computer, so I suppose what I should do is to git clone the anaconda 2.0rc in the server and set it as a synced folder, that's fine.

But how can I set the python interpreter? should I bypass vagrant:// and use tcp:// instead?

**Comment by DamnWidget** [comment]
I see that we have a nice use case in here, try this:

- Clone anaconda v2.0.0-rc1 in the vagrant guest (linux)
- Remove your current anaconda version from ST3 (1.4.28)
- Clone anaconda v2.0.0-rc1 in your ST3 Packages directory
- Configure your vagrant to expose the port that you are gonna run anaconda to the internet (you can check how to do that in [this link](https://github.com/DamnWidget/anaconda/wiki/Anaconda-v2:-Using-a-remote-python-interpreter-through-Vagrant#public-network-using-defaults)
- Start the anaconda's `minserver.py` in the Linux guest using: `python minserver.py -p <your_project_name> -e <any_extra_path_that_you_need> <port>`
- Set this as your `python_interpreter` in your ST3: `"python_interpreter": "tcp://OS_X_HEADLESS_IP:ANACONDA_MINSERVER_PORT"`

It will work.

P.D: You can also use a regular guest:host port forwarding and connect trough an SSH tunnel from your laptop to the OS X server

**Comment by divinites** [comment]
problems in running minserver.py of anaconda 2.0.0-rc1:

> python minserver.py -p github_crawler 19360
Traceback (most recent call last):
  File "minserver.py", line 28, in <module>
    from lib.log import log_directory
ImportError: No module named log

if run with python3:
> Traceback (most recent call last):
  File "minserver.py", line 28, in <module>
    from lib.log import log_directory
ImportError: No module named 'lib.log'

There is no log.py in anaconda/anaconda_server/lib.

**Comment by DamnWidget** [comment]
@divinites I am wondering if you tried with the last v2.0.4, let me know if it's finally working for you

**Comment by divinites** [comment]
The same error:

```
python ./minserver.py -p github_crawler 19360

Traceback (most recent call last):

  File "./minserver.py", line 28, in <module>

    from lib.log import log_directory

ImportError: No module named log
```

**Comment by DamnWidget** [comment]
For some reason the minserver.py version that got into the release is old...
Please, change the line 28 to of anaconda_server/minserver.py to
```python
from lib.path import log_directory
```

I will fix it in next release

**Comment by divinites** [comment]
Bingo! It works, thanks a lot for your help!

**Comment by DamnWidget** [comment]
This issue has been fixed already in last version
