### ISSUE TITLE
Anaconda runs very slow, jsonserver.py crash because anaconda_jsonserver.log user change to root

### ISSUE THREAD

**Issue by commutecat** [DamnWidget/anaconda#511]
Ubuntu 14.04.5 LTS, 
kernel Linux ubuntu 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Sublime : 3.6.2

Anaconda slow the editing and navigation to snails.  Using ps to check anaconda process, I found this 

`xyz  16051 16041  9 14:51 ?        00:00:00 [python] <defunct>
`

After enough search , I found someone in sublimetext forum encounter the same issue. 
https://forum.sublimetext.com/t/ubuntu-16-sublime-text-3-slow/20170

It sound crazy, so I  try to open sublime using sudo, then do a ps -ef | grep python again. And this is what I found. 

`root     16088 16081  5 14:54 ?        00:00:00 python -B /home/myxyzpc/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py -p anaconda-2 55874 16081
`
The editing works seems smooth now.   

Then I taking the command and try to run using normal user, and this is the error I get. 

`python -B /home/myxyzpc/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py -p anaconda-2 55874 16081
Traceback (most recent call last):
  File "/home/myxyzpc/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py", line 311, in <module>
    logger = get_logger(jedi_settings.cache_directory)
  File "/home/myxyzpc/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py", line 253, in get_logger
    encoding='utf-8'
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 930, in _open
    stream = codecs.open(self.baseFilename, self.mode, self.encoding)
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: '/home/myxyzpc/.cache/jedi/anaconda-2/anaconda_jsonserver.log'`

I check folder, and quite surprise that the anaconda_jsonserver.log ownership change to root:root.  
After changing log file ownership to my user name, everything works fine, I can start sublime not in sudo mode and anaconda  jsonserver.py run without a hitch. 

I don't know what cause the anaconda_jsonserver.log ownership change.

**Comment by DamnWidget** [comment]
No idea, probably you ran ST3 as root in some moment and the file was written by root? In any case the `jsonserver` runs as the user that runs the ST3's `plugin_host` that runs as the user that runs `sublime_text` binary, so in some moment that user was root.

**Comment by commutecat** [comment]
Is it possible for anaconda to warn user of anaconda_jsonserver.log  permission?  Or update the FAQ to warn user when using sudo sublime to edit file?

**Comment by DamnWidget** [comment]
I will probably add something regarding that to the README.md after release v2.0.0 later this afternoon

**Comment by alexfradiani** [comment]
After the update installed today the editor has become extremely slow. Not sure if this is the same issue, I didn't find anything for anaconda in ~/Library/Logs. Running os x 10.11.6 / ST3 build 3114.

What should I be looking for?, I had to remove anaconda in the meantime because editor was unusable like that.

**Comment by DamnWidget** [comment]
What you mean about not finding anything for anaconda in `~/Library/Logs`? That directory doesn't exists?

**Comment by alexfradiani** [comment]
I mean this from the README:

> Anaconda behaves slowly and jsonserver crashes
> 
> If you are in POSIX systems (Linux or OS X) take a look at the owner of the anaconda's jsonserver log files, they must be owned by your user or the jsonserver would be unable to start up. Log files can be found in:
> OS X: ~/Library/Logs/anaconda

**Comment by DamnWidget** [comment]
@alexfradiani consider to install version 1.4.28 while I investigate about this. You can do it uninstalling anaconda (if you didn't uninstalled it yet) and then running the following in your terminal (after close your ST3 running instance if any):
* `cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages`
* `git clone https://github.com/DamnWidget/anaconda.git`
* `git checkout v1.4.28`

That will install anaconda v1.4.28 for you. I have no access to my OS X box right now and that is why I am suggesting you to do a downgrade, you should have a `~/Library/Logs/anaconda` directory in your user home, the fact that you don't have it could mean that there is a serious major bug in OS X that I could not be able to check in a while :|

**Comment by alexfradiani** [comment]
Ok. I installed v1.4.28 and is working normally, thanks. I'll wait until new info before updating.

**Comment by kichooo** [comment]
My anaconda plugin also got superslow after update. I'm on ubuntu 16.04

**Comment by DamnWidget** [comment]
@kichooo can you provide us with logs?

**Comment by DamnWidget** [comment]
@alexfradiani I am able to run anaconda in OS X I need you to start the anaconda's JsonServer manually in debug mode ans try again. To do so:

* Stop ST3
* Just checkout the master branch in the anaconda git repo
* execute: `<your_python_interpreter> -B ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/anaconda/anaconda_server/jsonsever.py -p anaconda DEBUG`
* Start ST3

If you don't get any exception after run that command you will have a log file in `~/Library/Logs/anaconda/anaconda/anaconda_jsonserver.log` you can get debug output from both the log file and the standard output.

**Comment by kichooo** [comment]
Quite a few errors in the console, if this is what you mean:

http://paste.ubuntu.com/23119851/

**Comment by DamnWidget** [comment]
@kichooo create a pastebin (or a gist) with the contents of:
`~/.local/share/anaconda/logs/<your_project_name>/anaconda_jsonserver.log`

**Comment by kichooo** [comment]
Hello, thank you for your reply.

anaconda catalog doesn't exist in my ~/.local/share

**Comment by DamnWidget** [comment]
@kichooo try this:

* close ST3
* In a terminal write: `python -B ~/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p anaconda DEBUG`
* open ST3 and edit a Python file
* take a look at the directory that I told you before, you will have some output as well in the standard output of the terminal that you ran the command 

If anaconda works in that scenario, your `python_interpreter` is probably wrong or is not in your `PATH`

**Comment by kichooo** [comment]
However funny it sounds it fixed itself with restart. Logs are now properly created and anaconda is super fast again. 

It is strange because I think that I restarted before, but maybe one more update sneaked in between?

Anyway, from my side it looks good now, thanks for help!

**Comment by DamnWidget** [comment]
No problem, glad to hear that is solved.

**Comment by DamnWidget** [comment]
Can we close this?
