### ISSUE TITLE
unexpected function of autocomplete on import

### ISSUE THREAD

**Issue by gbritton1** [DamnWidget/anaconda#515]
If I start to enter:

import

a list pops of possible modules.  Suppose I want to import the math module.  I hit "m" and the list disappears!  I think it should rather automatically filter itself to modules beginning with"m" (math, mailbox, etc.) and not disappear.   Then I should be able to hit "a" for more filtering, etc.

If, OTOH, I enter "m" and hit tab, the editor shows:

import m

then tabs and displays a sublist of modules beginning with "m" (at least that's a step in the right direction!)  If I scroll down to math and hit enter, I now have:

import m    math

which is not what I want and is also invalid syntax.

Is this desired behavior?  Am I using it wrong?  Really I just expect it to work like autocomplete in other IDEs

**Comment by DamnWidget** [comment]
That is a well known issue with ST3 import mechanism, use [this workaround](https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly) to solve it (is in the README.md)

**Comment by DamnWidget** [comment]
Any update here @gbritton1 ?

**Comment by gbritton1** [comment]
The workaround didn't work.  The behavior is the same as before

**Comment by Effenberg0x0** [comment]
I agree with the original reporting, but the workaround fixed it for me. Here's  a small screencast showing how completion works for me after applying the workaround. Sorry for the low quality: github does not accept video files, had to convert from mkv to gif...

![anaconda_screencast](https://cloud.githubusercontent.com/assets/4016782/18101217/373304ee-6ec4-11e6-8b87-f1e595abf51a.gif)

**Comment by gbritton1** [comment]
OK -- did that.  Stopped and restarted Sublime.  But the issue persists.  No discernible change in behavior.  I believe I followed the instructions to the letter

**Comment by gbritton1** [comment]
@Effenberg0x0 What directory did you put the file CompletionRules.tmPreferences.xml in?  I put it in:

"C:\Users\xxxxx\AppData\Roaming\Sublime Text 3\Packages\Python\Completion Rules.tmPreferences.xml"

At least, that's what I understood from the link to the workaround.

Also, did you have to restart sublime for that to take effect?

**Comment by Effenberg0x0** [comment]
I don't have a computer with windows, but it's the Linux equivalent:
~/.config/sublime-text-3/Packages/Python/Completion\ Rules.tmPreferences

Yes, I restarted sublime after applying the workaround.

Maybe there's a conflicting package? Which packages do you have (ctrl+shift+p and list packages).
I have  Anaconda, BracketHighlighter, Color Highlighter, GitGutter, Package Control, Python Improved, requirementstxt, rsub, Seti_UI, SideBarEnhancements, SublimeLinter and Theme - Monokai.

**Comment by Effenberg0x0** [comment]
Oops, just noticed your file has a xml extension (Completion Rules.tmPreferences.xml), mine has no xml extension (Completion Rules.tmPreferences).

**Comment by gbritton1** [comment]
That was it!  Thanks for the help

**Comment by Effenberg0x0** [comment]
Glad it worked :)
