### ISSUE TITLE
How to run current python file

### ISSUE THREAD

**Issue by gbritton1** [DamnWidget/anaconda#516]
While in the ide editing some python file, I want to execute that file from within the IDE.  How do I do that?

**Comment by avamsi** [comment]
Use [SublimeREPL](https://github.com/wuub/SublimeREPL)

**Comment by DamnWidget** [comment]
Use `Ctrl+B`?

**Comment by arita37** [comment]
How to change sublime REPL interpreter to another one ?

**Comment by avamsi** [comment]
@arita37 I use custom key-bindings. For example, here's a snippet from my key-bindings file:

``` json
{
    "keys": ["ctrl+b"],
    "command": "repl_open",
    "args": {
        "type": "subprocess",
        "encoding": "utf8",
        "cmd": ["python", "-u", "$file_basename"],
        "cwd": "$file_path",
        "syntax": "Packages/Python/Python.tmLanguage",
        "external_id": "python3"
    }
},
{
    "keys": ["ctrl+shift+b"],
    "command": "repl_open",
    "args": {
        "type": "subprocess",
        "encoding": "utf8",
        "cmd": ["python2", "-u", "$file_basename"],
        "cwd": "$file_path",
        "syntax": "Packages/Python/Python.tmLanguage",
        "external_id": "python"
    }
},
{
    "keys": ["ctrl+b"],
    "command": "repl_open",
    "args": {
        "type": "subprocess",
        "encoding": "utf8",
        "cmd": ["go", "run", "$file_basename"],
        "cwd": "$file_path",
        "syntax": "Packages/Go/Go.tmLanguage",
        "external_id": "go"
    },
    "context": [
        {"key": "selector", "operand": "source.go"}
    ]
}

```

**Comment by gbritton1** [comment]
So Ctrl-B does nothing out of the box.  With @avamsi's keybindings I got further, though there's an error (attached)
![2016-08-29_18-43-40](https://cloud.githubusercontent.com/assets/12263288/18069988/cb4ac998-6e18-11e6-9e1f-a85bf4eca780.png)

SublimeRepl looks interesting, How do I install it into Sublime?

**Comment by avamsi** [comment]
@gbritton1 Just to be clear, that error has nothing to do with my key-bindings. Those key-bindings execute commands added by SublimeREPL -- which you can install by following [these instructions](https://github.com/wuub/SublimeREPL#installation).

**Comment by avamsi** [comment]
@DamnWidget, as this issue is not related to Anaconda, I guess you can close it.

**Comment by DamnWidget** [comment]
Well, we don't really know as the provided information is not enough to know if anaconda is working for the user but I guess that I would let you guys talk on this issue.
