### ISSUE TITLE
Python interpreter no longer uses $VIRTUAL_ENV

### ISSUE THREAD

**Issue by jslang** [DamnWidget/anaconda#517]
I configured anaconda to use existing $VIRTUAL_ENV variable, which previously worked. However after latest update, I am no longer able to do this.

Anaconda user settings:

```json
{
    "python_interpreter": "$VIRTUAL_ENV/bin/python"
}
```

For error output in console:

> ERROR:root:Your operating system denied the spawn of /bin/python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
> The OS did return [Errno 2] No such file or directory: '/bin/python'
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_process.LocalProcess object at 0x104a80150> process can not start a new anaconda JsonServer in the operating system because:

> Anaconda can not spawn a new process with your current configured python interpreter (/bin/python)

> Make sure your interpreter is a valid binary and is in your PATH or use an absolute path to it, for example: /usr/bin/python

Shell:

```sh
jared@lagom: echo $VIRTUAL_ENV
/Users/jared/Yola/yousers/virtualenv
```

Sublime console:

```python
>>> os.environ.get('VIRTUAL_ENV')
'/Users/jared/Yola/yousers/virtualenv'
```

**Comment by jslang** [comment]
I'm closing this as I just realized this is not necessarily an Anaconda problem, but rather could be Sublime screwing up instead. Will investigate further.

**Comment by DamnWidget** [comment]
It maybe is an issue with anaconda, I just redesigned how the `python_interpreter` option is handled, let me take a look, I will re-open it again is a problem with anaconda.

**Comment by irfus** [comment]
Seeing the same issue here. Works with the absolute path to the virtualenv python binary, but not with "$VIRTUAL_ENV/bin/python". I'm using ST3 Build 3114 and the latest Anaconda release from Package Control.

**Comment by YusufGandhi** [comment]
I got the same problem too. In the end, I needed to reinstall the anaconda package for it to work normally. I'm using ST3 Build 3126 and the latest Anaconda from Package Control

**Comment by jgirardet** [comment]
hello,
same thing with subl 3126, anaconda installed via package control today
Using the Hook file project.anaconda solve the problem. but putting again "$VIRTUAL_ENV/bin/python
in project setting or user settings reproduce the bug.

**Comment by DamnWidget** [comment]
Guys, `$VIRTUAL_ENV` is an environment variable, if you are using ST3 from POSIX operating systems (Linux or macOS) you have to start ST3 from the command like to import those variables from your SHELL

**Comment by jgirardet** [comment]
The probleme is  it. Lauched from command line $VIRTUAL_ENV is not well converted


28. Aoû 2017 09:21 de notifications@github.com:

**Comment by mhubig** [comment]
Same problem here. Im using [pipenv](https://github.com/kennethreitz/pipenv) to manage the virualenvs for all of my projects now.

```shell
$ cd project
$ pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
$ echo $VIRTUAL_ENV
/Users/mh/.local/share/virtualenvs/project-mDBmXP8E
$ grep python_interpreter project.sublime-project
"python_interpreter": "$VIRTUAL_ENV/bin/python3"
$ supl project.sublime-project
```

<img width="456" alt="screenshot 2017-09-18 15 35 14" src="https://user-images.githubusercontent.com/219704/30544507-003e0e56-9c87-11e7-85f6-b61bce6dc8ae.png">

If I set `python_interpreter` to `/Users/mh/.local/share/virtualenvs/project-mDBmXP8E/bin/python3` anaconda works like a charm.

**Comment by flablog** [comment]
Hi !
I'm using Anaconda 2.1.25 (with pipenv)
and still having the same issue. $VIRTUAL_ENV is not used (or any other environement variable that I've exported previously)

anyone has found a solution ?

**Comment by mzpqnxow** [comment]
Still an issue, very annoying..

```
$ subl --version
Sublime Text Build 3143
```

**Comment by rco-ableton** [comment]
@DamnWidget any update on this? I've just been bitten by the same issue (ST v3.1.1, build 3176).

**Comment by agronskiy** [comment]
Same here, Anaconda installed today (4.06.18)

`subl --version 
Sublime Text Build 3176`

**Comment by snitramodranoel** [comment]
Same problem here as of today:

* Anaconda 2.1.29
* ST3 Build 3173

**Comment by rev3ks** [comment]
I was having this issue, and believe I figured out what I was doing incorrect. When using the project settings to configure Anaconda, I had settings outside of the "settings" key like so 
```
{...
...
"pep257": false,
"settings":
	{
		"python_interpreter": "$VIRTUAL_ENV/bin/python3"
        }
}
```
once I moved "pep257 inside of the "settings" I stopped having this issue.
