### ISSUE TITLE
Crash upon startup: AF_UNIX path too long

### ISSUE THREAD

**Issue by fredcallaway** [DamnWidget/anaconda#519]
```
<Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x110cca710> initial check failed because:

unexpected exception: AF_UNIX path too long
```

There is a python 3.5 process associated with Anaconda, but I can't see what file is being executed using `top ps aux | grep`. I know it's associated with Anaconda because it only shows up when I un-disable the package.

This was caused by a recent update (probably 2.0 as I haven't used the package in a while). Any advice would be much appreciated!

**Comment by DamnWidget** [comment]
Can I know the following?
* Your Operating System
* Your $HOME path
* Your ST3 project name (or directory that contains the code you are editing name)

**Comment by DamnWidget** [comment]
It doesn't matters, version v2.0.4 has a fix for this, I will release later today
