### ISSUE TITLE
DamnWidget vs ContinuumIO

### ISSUE THREAD

**Issue by gbritton1** [DamnWidget/anaconda#520]
What's the diff between the DamnWidget anaconda forum and the one at ContinuumIO?

**Comment by DamnWidget** [comment]
Forum, huh?

Anaconda from Continuum is a Python distribution including a Python Interpreter and lot of ready to use Python packages for scientific usage mainly.

Our Anaconda is a package that converts Sublime Text 3 into a full featured Python IDE

**Comment by gbritton1** [comment]
OK --thanks
