### ISSUE TITLE
Silence "no library stub" warnings for mypy

### ISSUE THREAD

**Issue by sametmax** [DamnWidget/anaconda#522]
Right now you can either ask to no follow imports, or follow imports and get the whole file filled with gutters about "no library stub".

Following imports is useful to get informations about external lib that do provide stubs, but I don't need all the warnings about ones not providing them.

**Comment by DamnWidget** [comment]
Can you paste an example of the linting and the messages in the status bar?

**Comment by sametmax** [comment]
Here is what I get:

![capture du 2016-08-31 12-01-19](https://cloud.githubusercontent.com/assets/1673950/18124484/c0c1db3c-6f72-11e6-8900-5d9510064e9c.png)

```
MyPy error: No library stub file for module 'django.http'
MyPy note: (Stub files are from https://github.com/python/typeshed)
MyPy error: No library stub file for module 'django.db'
MyPy error: No library stub file for module 'django.contrib.auth.models'
MyPy error: No library stub file for module 'django.conf'
MyPy error: No library stub file for module 'django.db.models.signals'
MyPy error: No library stub file for module 'django.dispatch'
MyPy error: No library stub file for module 'django.db.models'
MyPy error: No library stub file for module 'django_extensions.db.models'
MyPy error: Need type annotation for variable

```

**Comment by DamnWidget** [comment]
I added a new configurable option (enabled by default) `mypy_suppress_stub_warnings` that do what it's name suggest.

Waiting for release

**Comment by sametmax** [comment]
Just tried it. It works, but seems to shift the position of the next visible warning gutters.

**Comment by DamnWidget** [comment]
The only thing that the option is doing is ignore lines that contains the
stub word it doesn't mess with that it just call continue in a for loop
