### ISSUE TITLE
Anaconda treats PEP448 (new unpacking) in py3.5 as syntax error

### ISSUE THREAD

**Issue by gitfred** [DamnWidget/anaconda#534]
![screen shot 2016-09-09 at 10 39 43](https://cloud.githubusercontent.com/assets/2721405/18380937/0252db74-767a-11e6-9b61-2945c347e981.png)

**Comment by DamnWidget** [comment]
Did you configured a Python >= 3.5 interpreter to work with?

![pep448](https://cloud.githubusercontent.com/assets/329766/18381679/52efda14-7675-11e6-8522-f058b771f030.png)

**Comment by gitfred** [comment]
it's configured properly. But you know, I realized that use it in multiple places and only this one shows syntax error. Wierd... I will close the issue and try to figure it out and then possibly reopen the issue

**Comment by DamnWidget** [comment]
I see, don't hesitate to open it again if you find what could be causing the anomaly.
