### ISSUE TITLE
Autocomplete Fails if whitespace before module docstring.

### ISSUE THREAD

**Issue by MatthewGieger** [DamnWidget/anaconda#535]
It took me hours to realize this, but if i have a space before my module doctoring, the autocomplete features of Anaconda don't work in the rest of the file.  It's definitely something i can work around, but i thought i'd report it anyway. Autocomplete works flawlessly otherwise. See images below (notice the whitespace before the module doctoring in the first image).
<img width="145" alt="whitespace" src="https://cloud.githubusercontent.com/assets/10717998/18407859/1840c0ce-76eb-11e6-8529-c8632a3e945e.png">
<img width="349" alt="no whitespace" src="https://cloud.githubusercontent.com/assets/10717998/18407860/184eefaa-76eb-11e6-9995-0aee3fbae727.png">

Great work on Anaconda!

**Comment by DamnWidget** [comment]
I did look really fast at this issue and could replicate it, so weird. I will look into it in deeper detail as soon as I have some free time.

**Comment by DamnWidget** [comment]
Well, I already resolved it, It will be inlcuded in v2.0.9

**Comment by MatthewGieger** [comment]
Wow! That was fast! Thanks!

If you don't mind me asking, what was causing that weird behavior?

**Comment by DamnWidget** [comment]
Jedi (the underlying completion library) is not able to parse the source if there is one or more leading whitespaces at the beginning of the file and the first node in the AST is a comment.
