### ISSUE TITLE
"Your operating system denied the spawn of vagrant process" error

### ISSUE THREAD

**Issue by tamakisquare** [DamnWidget/anaconda#537]
Prior to v2.0, I had been a happy camper with Anaconda's support for Vagrant with the setup of jsonserver in the vagrant guest machine. 

Yesterday, I replaced all that with the new setup for v2.0+. Unfortunately, I haven't been able to get it working. 

My project setting:
```
	"settings":
	{
		...
        "python_interpreter": "vagrant://rose:19360?network=private&address=192.168.5.10&shared=/home/vagrant/.anaconda",
	}
```

My Vagrantfile:
```
...
config.vm.network "private_network", ip: "192.168.5.10"
config.vm.define "rose" do |devbox|
    devbox.vm.hostname = "rose"
    devbox.vm.synced_folder "my_project", "/var/my_project", type: "nfs"
    devbox.vm.synced_folder "~/Library/Application Support/Sublime Text 3/Packages/Anaconda", "/home/vagrant/.anaconda", type: "nfs"
...
```

Below is what I see in the Sublime Text 3 console after opening up my project, while the Vagrant machine is already up and running. Not sure what's going on here. It would be great If someone can give me pointers on how to troubleshoot this issue. Thanks.

> ERROR:root:Your operating system denied the spawn of vagrant process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
> The OS did return [Errno 2] No such file or directory: 'vagrant'
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
>     expr()
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 252, in <lambda>
>     run_callback('on_load', callback, lambda: callback.on_load(v))
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/listeners/linting.py", line 80, in on_load
>     self.run_linter(view)
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 347, in run_linter
>     Worker().execute(Callback(on_success=parse_results), **data)
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 86, in execute
>     worker = cls.hire(cls)
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/market.py", line 32, in hire
>     itprt = Interpreter(raw_interpreter)
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/interpreter.py", line 26, in __init__
>     self.__parse_raw_interpreter()
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/workers/interpreter.py", line 224, in __parse_raw_interpreter
>     VagrantMachineGlobalInfo(self.machine).machine_id, self.dev
>   File "/Users/windbottle/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/vagrant.py", line 190, in __init__
>     raise RuntimeError('vagrant command not found')
> RuntimeError: vagrant command not found

**Comment by DamnWidget** [comment]
Looks like the `vagrant` app is not in your PATH, try to start ST3 from the command line using `subl` command.

**Comment by tamakisquare** [comment]
@DamnWidget - I think this is it. `vagrant` is now recognized by Sublime Text. Thanks.

But now I have another issue after passing this point. #539
