### ISSUE TITLE
Autocompletion breaks Sublime Text 3 build 3121

### ISSUE THREAD

**Issue by plamen-nikolov** [DamnWidget/anaconda#538]
I just updated Sublime Text 3 to build 3121 and it's started crashing when I type **self.** (Python). I tried to reproduce the error many times and also to disable all packages one by one and it turned out the issue is with Anacoda.

**Comment by DamnWidget** [comment]
I don't exactly know how did you got to that conclusion but you are wrong.

![st3121](https://cloud.githubusercontent.com/assets/329766/18517809/7fcdbb04-7a95-11e6-857d-aba43f5086cc.png)

As you can see in that screenshot (the code is being linted by anaconda 2.0.8) I am using the last ST3 nightly build without any kind of problem.

Disable all packages but anaconda and try again, if you still have any problem, please, gist the contents of the anaconda's JsonServer logs (you can follow [this](https://github.com/DamnWidget/anaconda#anaconda-behaves-slowly-and-jsonserver-crashes) to find them) and provide useful information like your operating system, anaconda version and configuration.

**Comment by plamen-nikolov** [comment]
That's what I did. I disabled ALL other packages and then tried to enable/disable Anaconda it always happens the same way. Anyways, Sublime Text 3 build 3122 fixes the issue and still have no idea how Anaconda triggers that crash. Thanks

**Comment by DamnWidget** [comment]
probably the problem was in ST3 and not in anaconda :)
