### ISSUE TITLE
Replace non-breaking spaces in Autoformat PEP8 errors

### ISSUE THREAD

**Issue by AndreasBackx** [DamnWidget/anaconda#540]
I often accidentally type a non-breaking space on my machine with alt+space which I don't see (because it of course looks exactly like a space character) and it causes some problems and frustration to find and usually end up rewriting the line on which I see the error (often `[E] Invalid character in identifier,`). It would be awesome if Anaconda would be able replace these with normal spaces as they have no use in Python afaik. It happens multiple times a day and I have yet to see any IDE really solve the problem. It's encoded as `U+00A0` in Unicode.

Below is a keymap for Sublime Text that is a temporary solution for the problem.
```javascript
{
    "keys": [
        "alt+space"
    ],
    "command": "insert_snippet",
    "args": {
        "contents": " "
    }
}
```
The problem is that this doesn't solve the problem where you really need to have non-breaking spaces in strings or other files when using Sublime Text.

**Comment by DamnWidget** [comment]
Well, that is not a PEP8 error so I don't see how the auto pep8 formatter would be responsible of fix such thing, anyway you can make a small pulg-in in your own to solve that problem, follow this steps (I didn't test it myself but it will work just fine)

# Create Small Python File
In `~/Library/Application\ Support/Sublime \Text\ 3/Packages/User` create a file called `nbsp.py` with the following contents
```python
import sublime_plugin


class ReplaceNbsp(sublime_plugin.TextCommand):
    def run(self, edit):
        for nbsp in self.view.find_all('\u00A0'):
            self.view.replace(edit, nbsp, ' ')


class ReplaceNbspOnSave(sublime_plugin.EventListener):
    def on_pre_save(self, view):
        view.run_command('replace_nbsp')
```

Restart your ST3.

That will hook a new save event that will find and replace any `0xa0` unicode character into a regular ascii blank space.

If it doesn't work just create a new directory in your `Packages` diurectory with whatever name that you want and move the `nbsp.py` file into it.

**Comment by AndreasBackx** [comment]
Cool, thank you. I assumed that it wasn't really be a PEP8 error, I just thought it would be handy but totally understand because I'm probably one of the only ones with this problem because of my keyboard layout. Thank you for taking the time to reply, this can be closed.

**Comment by DamnWidget** [comment]
Did it work @AndreasBackx ?

**Comment by AndreasBackx** [comment]
@DamnWidget I did not use your code example. I have simply replaced all non-breaking spaces and am using the keymap I posted from now on. Thank you again though.
