### ISSUE TITLE
Integrating prospector

### ISSUE THREAD

**Issue by nMustaki** [DamnWidget/anaconda#541]
Hello,

first thanks for Anaconda, it saves my life daily :-)
I would like to integrate [Prospector](http://prospector.landscape.io/en/master/index.html) into Anaconda, would be interested ? If so I'll open a pull request.

Thanks,
Nathan

**Comment by DamnWidget** [comment]
Hi
It looks that prospector is doing pretty much the same that anaconda already do trough it common linters, said that, I have no problems in add this as alternative linter as far as you continue supporting it and taking care of it, that means, integrate new versions, fix any issue, solve problems and give support here in the issues to users that could use it.

Apart from that any new tool needs unit tests and probably we will need to discuss about it in the mailing list or/and in gitter as there are some integrations that should be done to introduce this tool (for example, currently, Pylint is an alternative linter in anaconda as we use PyFlakes by default, so if the user configures anaconda to use Pylint, PyFlakes gets automatically deactivated no matter other configurations and PEP8 gets merged into Pylint results, something like that but more complex should be done in this case.

**Comment by nMustaki** [comment]
​
Hi,

your comments got me thinking that I should try to modify my pylintrc before adding complexity to Anaconda; I'll go this route and if that's not enough I'll come back.

Thanks again !
