### ISSUE TITLE
Linter fails when it sees a possible keyword

### ISSUE THREAD

**Issue by ParthKolekar** [DamnWidget/anaconda#542]
# initial classification
    classified_correctly = map(lambda x: False, dataset)

Anaconda thinks that the above is a class declaration and tells me to put a space before and after the declaration.

**Comment by DamnWidget** [comment]
As I already explained in the PR, that is an external library so this should be addresses [https://github.com/PyCQA/pycodestyle/issues](there)

**Comment by ParthKolekar** [comment]
The PR was brought into the master of pycodestyle.

**Comment by DamnWidget** [comment]
Nice, I will update it as soon as possible.

**Comment by DamnWidget** [comment]
PyCodetyle was updated in v2.1.8 btw
