### ISSUE TITLE
linter fails when use "global"

### ISSUE THREAD

**Issue by h-li** [DamnWidget/anaconda#544]
```python
class A(object):
    def f(self):
        self.a = b  # "Undefined name, it's ok"
```

```python
class A(object):
    def f(self):
        self.a = b  # "failed when use 'global'"

def g():
    global x
```

**Comment by DamnWidget** [comment]
Seems to be a problem in PyCodeStyle itself, I just ran it manually in a file with that contents and it didn't returned any error back, flake8 do it.

Do you think you can send a report for this in the [PyCodeStyle project](https://github.com/PyCQA/pycodestyle/issues) itself?
