### ISSUE TITLE
Anaconda stops working

### ISSUE THREAD

**Issue by sergei-maertens** [DamnWidget/anaconda#546]
* ST 3123
* Project configured with `python_interpreter` set to virtualenv python (3.5)
* Initially autocomplete, docstrings etc. work, clicking through to object definitions is fine
* After a while Anaconda seems to freeze, logs don't give any useful information - except that new connections seem to be incoming (see attached [anaconda.txt](https://github.com/DamnWidget/anaconda/files/491740/anaconda.txt))

Closing ST3 does not immediately kill the `jsonserver.py` process, sometimes it hangs and I have to kill it via PID manually.

This is on Arch Linux, x86_64, latest version.

If you miss any information, I'll be happy to provide it.

**Comment by DamnWidget** [comment]
Stop ST3, open a terminal and start anaconda server in DEBUG mode with:
```
/home/bbt/.virtualenvs/<your_virtual_env>/bin/python -B /home/bbt/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p got-djent -e /home/bbt/coding/got-djent-v3,/home/bbt DEBUG```
Then start your ST3 open your `got-djent` project if is not still open and work normally, if it happens again, you will have a lot of debugging logs in the terminal, create a gist with them and paste it here.

It would be also useful if you paste the output of the command `ps aux | grep jsonserver` next time.

**Comment by sergei-maertens** [comment]
Will do, thanks!

**Comment by DamnWidget** [comment]
Any update here?

**Comment by sergei-maertens** [comment]
Not yet, I haven't been working much yet, was only just back from vacation.

**Comment by sergei-maertens** [comment]
I probably had missed some message or my settings were incorrect from the beginning. My `python_interpreter` was not scoped in `settings` (in the project settings). Since I've fixed that, I haven't run into the issues anymore.

In the global settings I had `python_interpreter: $VIRTUAL_ENV/bin/python`, maybe it's related to the jsonserver dying and then not receiving the envvars anymore?

Can be closed for me, I don't know if you want to investigate further or not @DamnWidget

**Comment by DamnWidget** [comment]
Let's close it for now I have more than enough work to do already ;)
