### ISSUE TITLE
Bad UX with reading violations

### ISSUE THREAD

**Issue by flux627** [DamnWidget/anaconda#548]
Right now (unless I am mistaken), then only why to find out what the exact linting error is is to use the "Show Error List" command, which gives you line numbers that you need to then manually correlate back to each gutter mark. Wouldn't it be a much better experience to be able to see what the gutter mark is there for without having to pull up the errors list?

If gutter marks are turned off, then maybe hovering over the violation itself could give some kind of indicator?

**Comment by DamnWidget** [comment]
If you move the cursor to the offending line you get a full description about the problem in the status bar
