### ISSUE TITLE
ipython support 

### ISSUE THREAD

**Issue by MordechaiMaman** [DamnWidget/anaconda#549]
I failed to use anaconda in the first place so I debugged it and I noticed that when anaconda does not have the property 'python_interpreter' it find it out automatically.
So far so good, but when it decide that my 'python_interpreter' is ipython the troubles begin...
The 'jsonserver.py' can't start due to wrong parameters to ipython such as -B and -p.
 
My solution of course was to change the 'python_interpreter' to python, but I think it would be nice to support ipython or at least add a validation to the set_python_interpreter function that the interpreter is not ipython or any unsupported interpreter.

Awesome plugin BTW :) :+1:

**Comment by DamnWidget** [comment]
Well, ipython is not a Python interpreter but an Interactive Python Shell or a REPL so is not possible at all to support it as a python interpreter

**Comment by DamnWidget** [comment]
There is no such function, the `python_interpreter` is just a configuration field, anything can be written off in there, by default it is `python` if it is not set and supposing that the user have a `python` binary her `$PATH` it will provide always a valid python interpreter.

The idea behind the `python_interpreter` to be configurable is to be able to set other interpreters different than the system one, so for example anyone can use Jython or IronPython, or PyPy but it's main usage is to set interpreters of virtual environments to use the packages installed on those virtual environments.

A part from that, the `python_interpreter` can be set to whatever [implements Python](https://wiki.python.org/moin/PythonImplementations) or any kind of wrappers that wraps or hide the Python interpreter in any way.

That means that any user could be using whatever obscure wrapper written in let's say BASH or whatever with whatever kind of arbitrary name that could be a perfectly valid Python interpreter so there is no way that anaconda could be able to check if an arbitrary value written in there "looks like a valid Python interpreter or not". We just try to start the `jsonserver` script and if it fails for any reason we report it back I think that is just enough in any case.

**Comment by DamnWidget** [comment]
I am closing this, feel free to open it again in the future if you have new doubts/comments/ideas
