### ISSUE TITLE
Anaconda autocompletion flickers the screen.

### ISSUE THREAD

**Issue by kindlychung** [DamnWidget/anaconda#550]
Here is a [video](https://www.youtube.com/watch?v=EXOvtVvqI-Q&feature=youtu.be).

**Comment by DamnWidget** [comment]
Disable/Uninstall SublimeJedi and/or Disable SublimeCodeIntel for Python while using anaconda

**Comment by DamnWidget** [comment]
Solved your problem @kindlychung?

**Comment by kindlychung** [comment]
Yes, removing jedi solved my problem. Thanks!
