### ISSUE TITLE
Python3.5: async def in module scope is linted as error

### ISSUE THREAD

**Issue by rawler** [DamnWidget/anaconda#551]
Minimal code to reproduce:
```python
async def foo():
    pass
```

**Comment by DamnWidget** [comment]
Are you using a Python3.5 interpreter in your 'python_interpreter'
configuration settings?

**Comment by rawler** [comment]
Haha. Nope!

**Comment by DamnWidget** [comment]
[![Nod of approval](http://4.bp.blogspot.com/-9QjARWd5a84/T3OXHJJbe1I/AAAAAAAAA34/OVtLNvwpMvI/s190/nod-of-approval.gif)](http://4.bp.blogspot.com/-9QjARWd5a84/T3OXHJJbe1I/AAAAAAAAA34/OVtLNvwpMvI/s190/nod-of-approval.gif)

Glad to know
