### ISSUE TITLE
mypy on Windows

### ISSUE THREAD

**Issue by Solanar** [DamnWidget/anaconda#559]
I was trying to get mypy to work on Windows and ran into some issues. I'm using a virtualenv with mypy==0.4.4 (latest version does not work with anaconda) installed as well. Looking through the anaconda_jsonserver.log and the source code I've found some issues:

In [anaconda_mypy.py 63-67](https://github.com/DamnWidget/anaconda/blob/928d8ceca121aa98b25f0e67fdbcc16d5f125bd5/anaconda_lib/linting/anaconda_mypy.py#L63-L67), The executable and the filename tokens should be surrounded by quotes in case of spaces in the filepaths. Ex. `C:/space dir/file.ext`

    args = shlex.split('"{0}" -O -m mypy {1} {2} "{3}"'.format(
        sys.executable, '--suppress-error-context',
        ' '.join(self.settings[:-1]), self.filename),
        posix=os.name != 'nt'
    )

This lead to another issue where shlex would output the new quotes and cause the Popen call (line 78) to fail. I had to comment out line 66 `posix=os.name != 'nt'` to get it to not put the quotes in and continue working. I am unsure of this change as it seems wrong but I couldn't figure out the proper combination.

    args = shlex.split('"{0}" -O -m mypy {1} {2} "{3}"'.format(
        sys.executable, '--suppress-error-context',
        ' '.join(self.settings[:-1]), self.filename),
        # posix=os.name != 'nt'
    )

The other issue happened during parsing of the mypy errors in [anaconda_mypy.py 94-105](https://github.com/DamnWidget/anaconda/blob/928d8ceca121aa98b25f0e67fdbcc16d5f125bd5/anaconda_lib/linting/anaconda_mypy.py#L94-L105). Window filepaths have `:`'s in them, which throws off splitting by them. If we ignore the filename (which is unused at this time) by removing it before we split, it works.

    line = line.replace(self.filename, '')
    error_data = line.split(':')
    errors.append({
        'level': 'W',
        'lineno': int(error_data[1]),
        'offset': 0,
        'code': ' ',
        'raw_error': '[W] MyPy {0}: {1}'.format(
            error_data[2], error_data[3]
        ),
        'message': '[W] MyPy%s: %s',
        'underline_range': True
    })

These two changes made mypy via anaconda on Windows work for me. Thoughts?

I also get `[W] MyPy  error: Cannot find module named 'mypy'; [W] MyPy  note:  (Perhaps setting MYPYPATH or using the "--silent-imports" flag would help)` in anaconda_mypy.py but it's still working.

One more thing, it's only running mypy lint on save, is there a way to get it to lint as I type?

**Comment by DamnWidget** [comment]
Hi, thank you for take your time in look into this problem that you had with mypy on Windows. Is very strange that you have any problem with how the command is passed to Popen as shlex takes care of format the arguments right for every platform, I will take a look into it as I think your changes will break POSIX.

I didn't test the mypy feature on Windows I will take a look as soon as I have some time to do it so I can parse the results for windows and it doesn't fails.

The warning that you get can be ignored, just set `mypy_silent_imports` to `true` in your configuration.
Mypy does not works in buffers, just in files that is why it only lints on file saving, to make it work as you type we should need to save the buffer to a temporary location every time that 0.5s passed since your last key stroke and that will be very very IO intrusive, we don't like that.

**Comment by DamnWidget** [comment]
About the 0.4.5 support, yep, looks like they broke anaconda with this merge https://github.com/python/mypy/pull/2192 as one of the parameters that we pass to mypy was renamed

**Comment by Solanar** [comment]
Thanks for looking into this so promptly!

I checked out the fix and it's working but as I mentioned above it still does not handle spaces in the path of `sys.executable` nor `self.filename`. `shlex` splits on spaces and requires quotes or something to delimit tokens.

**Comment by DamnWidget** [comment]
Working fine for me, shlex was designed just to handle that, I am not sure how is possible that is not working for you, I have no problems really.

**Comment by Solanar** [comment]
I hope it's not too much to ask, but can I ask for your parameters to the shlex call? I'd like to use it to diagnose what's happening on my end. 

- sys.executable
- self.filename
- args (what shlex.split returns)
- os.name != 'nt'

When I run shlex.split in my terminal it spits out:

    [
        'E:\\venv\\Scripts\\python.exe', 
        '-O', 
        '-m', 
        'mypy', 
        '--hide-error-context', 
        'C:\\Users\\Name', 
        'Here\\AppData\\Roaming\\Sublime', 
        'Text', 
        '3\\Packages\\Anaconda\\anaconda_lib\\linting\\anaconda_mypy.py'
    ]

**Comment by DamnWidget** [comment]
Yeah you are right, I made a commit to solve it, if Package Control does not automatically updates your installation do a git pull in the anaconda directory.

**Comment by Solanar** [comment]
Thanks for looking into this again, but I'm still running into an issue.
    
    import sys, shlex
    from subprocess import Popen, PIPE
    Popen(["'{}'".format(sys.executable)], stderr=PIPE, stdout=PIPE)
    Popen(shlex.split("'{}'".format(sys.executable), posix=False), stderr=PIPE, stdout=PIPE)
    Popen("'{}'".format(sys.executable), stderr=PIPE, stdout=PIPE)
->

    FileNotFoundError: [WinError 2] The system cannot find the file specified
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    FileNotFoundError: [WinError 2] The system cannot find the file specified

You can't have quotes when passing a sequence or a string to Popen, which `shlex` with `posix=False` outputs.

I've tested this on four different machines (both python 2 and 3), one with Windows Vista, one with Windows 7 and two with Windows 10. `shlex` outputs the quotes when using `posix=False`, which is causing `Popen` to fail.

If you do not set `posix`, it works:

    Popen(shlex.split("'{}'".format(sys.executable)), stderr=PIPE, stdout=PIPE)

->

    <subprocess.Popen object at 0x032BF6F0>

If you are getting different results, what version of Windows/Python are you testing this on?

**Comment by DamnWidget** [comment]
The problem of removing the posix=False is that Windows paths are not gonna be corrected in case that they need and the backslashes are gonna get removed, anyway, I will make the change.

**Comment by DamnWidget** [comment]
It is pushed on master, I will make a release when I have more fixes/changes to make a release

**Comment by Solanar** [comment]
Sorry to be a bother on this issue. Thanks for believing me. 

Could you provide an example of what you mean?

Here's my testing:

    a=shlex.split("'C:\\Users\\First Last\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe' -m mypy 'E:\\antyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py'")
    b=shlex.split("'C:\\Users\\First Last\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe' -m mypy 'E:\\antyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py'", posix=False)
    c=shlex.split("'C:/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe' -m mypy 'E:/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py'")
    d=shlex.split("'C:/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe' -m mypy 'E:/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py'", posix=False)
    e=shlex.split("'C:\Users\First Last\AppData\Local\Programs\Python\Python35-32\python.exe' -m mypy 'E:\antyc_solutions\projects\django-knockout-dev\django-knockout\setup.py'")
    f=shlex.split("'C:\Users\First Last\AppData\Local\Programs\Python\Python35-32\python.exe' -m mypy 'E:\antyc_solutions\projects\django-knockout-dev\django-knockout\setup.py'", posix=False)
    g=shlex.split("'/c/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe' -m mypy '/e/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py'")
    h=shlex.split("'/c/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe' -m mypy '/e/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py'", posix=False)

    # ['C:\\Users\\First Last\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe', '-m', 'mypy', 'E:\\antyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py']
    # ["'C:\\Users\\First Last\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe'", '-m', 'mypy', "'E:\\antyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py'"]
    # ['C:/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe', '-m', 'mypy', 'E:/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py']
    # ["'C:/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe'", '-m', 'mypy', "'E:/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py'"]
    # ['C:\\Users\\Andrew Charles\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe', '-m', 'mypy', 'E:\x07ntyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py']
    # ["'C:\\Users\\Andrew Charles\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe'", '-m', 'mypy', "'E:\x07ntyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py'"]
    # ['/c/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe', '-m', 'mypy', '/e/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py']
    # ["'/c/Users/First Last/AppData/Local/Programs/Python/Python35-32/python.exe'", '-m', 'mypy', "'/e/antyc_solutions/projects/django-knockout-dev/django-knockout/setup.py'"]

    aa=Popen(a, stderr=PIPE, stdout=PIPE)
    bb=Popen(b, stderr=PIPE, stdout=PIPE)
    cc=Popen(c, stderr=PIPE, stdout=PIPE)
    dd=Popen(d, stderr=PIPE, stdout=PIPE)
    ee=Popen(e, stderr=PIPE, stdout=PIPE)
    ff=Popen(f, stderr=PIPE, stdout=PIPE)
    gg=Popen(g, stderr=PIPE, stdout=PIPE)
    hh=Popen(h, stderr=PIPE, stdout=PIPE)

    # <subprocess.Popen object at 0x012B26D0>
    # FileNotFoundError: [WinError 2] The system cannot find the file specified
    # <subprocess.Popen object at 0x01A366F0>
    # FileNotFoundError: [WinError 2] The system cannot find the file specified
    # <<subprocess.Popen object at 0x012C69F0>
    # FileNotFoundError: [WinError 2] The system cannot find the file specified
    # FileNotFoundError: [WinError 2] The system cannot find the file specified
    # FileNotFoundError: [WinError 2] The system cannot find the file specified

    # >>> aa
    # setup.py:2: error: No library stub file for module 'setuptools'\r\nsetup.py:2: note: (Stub files are from https://github.com/python/typeshed)
    # >>> cc
    # setup.py:2: error: No library stub file for module 'setuptools'\r\nsetup.py:2: note: (Stub files are from https://github.com/python/typeshed)
    # >>> ee
    # mypy: can't read file 'E:\x07ntyc_solutions\\projects\\django-knockout-dev\\django-knockout\\setup.py': Invalid argument

Only a and c worked.

**Comment by DamnWidget** [comment]
What I mean is that with `posix=False` any path with regular slashes will be converted to backslashes, anyway that would not apply as shlex will take the path as a literal and will not try to convert it so it does not really matters.

**Comment by Solanar** [comment]
Ah, I see. Thanks again! This is an amazing project and I couldn't do Python dev without it :)

**Comment by DamnWidget** [comment]
Thank you for your kind words, I really appreciate it.
