### ISSUE TITLE
GoTo Definition tracebacks on Windows

### ISSUE THREAD

**Issue by dpiche174** [DamnWidget/anaconda#564]
## Expected Behaviour

Using "GoTo Definition" on Windows should work without errors.

## Actual Behaviour

Using "GoTo Definition" on Windows results in a traceback (see section "ST3 Console Logs"). The cursor is actually moved to the definition but the traceback in the log is unexpected. I think it is only the focusing of the cursor that is not working.

The error seems to be cause by the string split() at `anaconda_lib/explore_panel.py:137`.
I think `path, line, column = self.position.split(':')` should be replaced with `path, line, column = self.position.rsplit(':', 2)` because on Windows a path can contain the character ':' (the drive separator, `C:` for example).

## ST3, Anaconda and OS versions

Anaconda 2.1.3
Windows 7 64-bit

## ST3 Console Logs

```python
ERROR:root:too many values to unpack (expected 3)
ERROR:root:Traceback (most recent call last):
ERROR:root:  File "C:\Users\dpiche\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\jsonclient.py", line 104, in process_message
ERROR:root:    callback(data)
ERROR:root:  File "C:\Users\dpiche\AppData\Roaming\Sublime Text 3\Packages\Anaconda\commands\goto.py", line 49, in on_success
ERROR:root:    ExplorerPanel(self.view, symbols).show([])
ERROR:root:  File "C:\Users\dpiche\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\explore_panel.py", line 53, in show
ERROR:root:    Jumper(self.view, cluster[0]['position']).jump()
ERROR:root:  File "C:\Users\dpiche\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\explore_panel.py", line 130, in jump
ERROR:root:    self._toggle_indicator()
ERROR:root:  File "C:\Users\dpiche\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib\explore_panel.py", line 137, in _toggle_indicator
ERROR:root:    path, line, column = self.position.split(':')
ERROR:root:ValueError: too many values to unpack (expected 3)```

**Comment by DamnWidget** [comment]
Please, feel free to open if you find the problem persists.

**Comment by dpiche174** [comment]
I tried the fix and it works. Thanks!

**Comment by DamnWidget** [comment]
No, tank you, the fix is yours :)
