### ISSUE TITLE
Go to assignment

### ISSUE THREAD

**Issue by muffinmad** [DamnWidget/anaconda#569]
Sometimes I need to find out how an instance was created rather than jump to class definition.
Would it be acceptable to implement new command like `anaconda_goto_assignment`?

**Comment by DamnWidget** [comment]
Are you asking if would be acceptable that you implement the command yourself? If that is the case, PRs are more than welcome but remember to follow the [developers guidelines](https://damnwidget.gitbooks.io/anacondast3-developers-documentation/) and add a test case for the new feature.

**Comment by muffinmad** [comment]
Some links in Anaconda Developers Documentation is broken.
[This](https://damnwidget.gitbooks.io/anacondast3-developers-documentation/content/getting_involved/getting_involved/anaconda_coding_style_guide/README.html) and [this](https://github.com/DamnWidget/anaconda/blob/master/templates/relnotes.tpl) gives me 404.
