### ISSUE TITLE
Stop autocomplete on typing "print("

### ISSUE THREAD

**Issue by jbruck** [DamnWidget/anaconda#573]
## Expected Behaviour

No autoformat on typing "print" or simply a close paren
## Actual Behaviour

"print(value, ...)"
## Steps to Reproduce

type "print(" 
## ST3, Anaconda and OS versions

Recent. Ubuntu 16.10 

I find having to delete the comma and the ellipsis annoying. Can it be turned off?

**Comment by DamnWidget** [comment]
The autocompletion gives you what you tell him to give you. This is from the anaconda configuration file
```javascript
/*
        If complete_parameters is true, anaconda will add function and class
        parameters to its completions.

        If complete_all_parameters is true, it will add all the possible
        parameters, if it's false, it will add only required parameters
    */
    "complete_parameters": false,
    "complete_all_parameters": false,
```
The `print` function gets completed as any other function as there is nothing special about it, the behaviour that you get is expected behaviour taking into account your configuration.
