### ISSUE TITLE
Connection to localhost:35615 timed out after 0.2s. tried to connect 7 times during 2 seconds

### ISSUE THREAD

**Issue by evandrocoan** [DamnWidget/anaconda#575]
## Expected Behaviour

Is expected to this window do not pop up when I open Sublime Text:

![image](https://cloud.githubusercontent.com/assets/5332158/19839809/eba57d04-9ecf-11e6-94c3-cf6a4f28415d.png)

```
<Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x04391470> initial check failed because:
connection to localhost:35615 timed out after 0.2s. tried to connect 7 times during 2 seconds
check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:
import socket; socket.socket(socket.AF_INET, socket.SOCK.STREAMj.connecttC'localhost", 35615))
If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow.startup.errors' to 'true' in your configuration file.
```

Neither is expected to this strange and undoable/permanent selections marks on my python file:

![image](https://cloud.githubusercontent.com/assets/5332158/19839821/20891440-9ed0-11e6-8702-7bc0d52f9631.png)
## Steps to Reproduce

Install the package and open a python file.
## ST3, Anaconda and OS versions
1. ST3 3126,
2. Anaconda v2.1.5,
3. Windows 10 with Python 2.7.12 on the system path.
4. Sublime built-in Python version 3.3.6 (default, Sep 22 2016, 23:27:53) [MSC v.1600 32 bit (Intel)]
## ST3 Console Logs

```
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x04391470> initial check failed because:

connection to localhost:35615 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 35615))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
error: <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x04391470> initial check failed because:

connection to localhost:35615 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 35615))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
Package Control: Skipping automatic upgrade, last run at 2016-10-30 17:59:56, next run at 2016-10-30 18:59:56 or after
```
## Anaconda's JsonServer Logs

**Note**: Anaconda's JsonServer logs can be found in:
- Linux: ~/.local/share/anaconda/logs
- OS X: ~/Library/Logs/anaconda
- Windows: %APPDATA\Anaconda\Logs

[anaconda_jsonserver.txt](https://github.com/DamnWidget/anaconda/files/560724/anaconda_jsonserver.txt)

Related threads:
1. https://github.com/DamnWidget/anaconda/issues/514 _ warning popup after start of ST3
2. https://github.com/DamnWidget/anaconda/issues/526 _ exception constantly happening after upgrade: initial check failed
3. https://github.com/DamnWidget/anaconda/issues/527 _ <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object > initial check failed

**Comment by DamnWidget** [comment]
As I can see in the logs, your client works fine so you can just ignore the errors setting the `swallow_startup_errors` to `true`.

Closing and as it is duplicated of the already open #527

**Comment by DamnWidget** [comment]
The marks is just the plugin linter telling you that there are violations of the Python Code Style Guide (PEP8)

**Comment by gabriellima** [comment]
In mine, there's an ERROR being logged (although Anaconda autocomplete is "working").

[WinError 10048] Only one usage of each socket address (protocol/networ
k address/port) is normally permitted


I mean "working" because somehow my ST3 is using its "auto completion" by default, so first I see the default auto completion, than after some seconds, I see the result of anaconda auto completion refreshing the list of options in the autocompletion mini-window.
