### ISSUE TITLE
Disable linting on this file doesn't work on an usaved buffer

### ISSUE THREAD

**Issue by AllanLRH** [DamnWidget/anaconda#579]
When editing in an unsaved buffer (not just a edited file, but a "file" which was never saved to the disk), selecting _Anaconda: Disable linting on this file_ from the Command Palette won't disable the linting.

I'm using build 3125 and the MagicPython syntax definition.

**Comment by DamnWidget** [comment]
Why you want to disable the linting in an unsaved buffer? If you are creating the file, just follow PEP8, if you don't want to follow PEP8 just disable the linter completely or just disable PEP8 linter.

`Disable linter on this file` do what it indicates, disable the linter "on files", a ST3 buffer is not a file.

**Comment by AllanLRH** [comment]
When working in a Jupyter notebook, it's sometimes convenient to copy-paste code between ST and the notebook, when it's in need of heavy editing, but the massive amount of warnings (missing imports and such), makes the code difficult to read.
Since the code is linted, I suspect at Anaconda / Jedi is able to treat the unsaved buffer as a file, so consider this a feature request to add support for disabling linting on an unsaved buffer :)

**Comment by DamnWidget** [comment]
Being honest, I have no time to implement new features because of https://github.com/DamnWidget/anaconda/projects but I can guide you into how this specific feature works right now so you can implement it yourself if you wish (and make a PR).

**Comment by AllanLRH** [comment]
I'd probably like to look into this after my upcoming exams, provided that the codebase isn't too complex, as to allow me to do this in a reasonable amount of time – will write here after my exams :)

**Comment by DamnWidget** [comment]
This feature will be present in v2.1.10
