### ISSUE TITLE
Provide a setting hook to setup MYPYPATH

### ISSUE THREAD

**Issue by sametmax** [DamnWidget/anaconda#581]
Currently the only way to set MYPYPATH is to use an environment variable. Without MYPYPATH, you can't use mypy in any file doing an import outside of your current directory, because mypy won't be able to follow that import. Indeed, mypy does not follow the PYTHONPATH and requires that you set MYPYPATH manually.

**Comment by DamnWidget** [comment]
I will take a look into it as soon as I have some free time, time that currently I don't have so for now I suggest you to add it to your environment.

**Comment by DamnWidget** [comment]
This has been solved, pending for release

**Comment by codergator** [comment]
Would you happen to have a link to docs?
