### ISSUE TITLE
Import undefined name does not work

### ISSUE THREAD

**Issue by asfaltboy** [DamnWidget/anaconda#582]
## Expected Behaviour

Import of the object is added at top of file

## Actual Behaviour

A sublime error alert dialog is displayed with:
> The word under the cursor is not an undefined name.

<img width="885" alt="screen shot 2016-11-09 at 11 35 47" src="https://cloud.githubusercontent.com/assets/321520/20135590/bc73cbf0-a670-11e6-85fd-99f1a94ed719.png">

## Steps to Reproduce

1. Type new unimported name, e.g "print(sys.path)";
2. select/place-cursor-at typed word.
3. Attempt "Auto import" command from right-click context menu > anaconda section.

## ST3, Anaconda and OS versions

ST3 Build 3126, Anaconda version 2.1.5 checked out from github master branch, OS X El Capitan 10.11.4.

## ST3 Console Logs

[ST3-console.log.zip](https://github.com/DamnWidget/anaconda/files/580532/ST3-console.log.zip)

## Anaconda's JsonServer Logs

[anaconda_jsonserver.log.zip](https://github.com/DamnWidget/anaconda/files/580526/anaconda_jsonserver.log.zip)

**Comment by DamnWidget** [comment]
Are you sure that your cursor was over the word `sys`?. I am not able to reproduce this.

**Comment by asfaltboy** [comment]
I'm certain, any verbose debug I can enable?

**Comment by DamnWidget** [comment]
The autoimport command is a very simple an naive implementation that just get whatever word is under the cursor and check if it is in the linted errors list and it's description contains the word `Undefined`, there is not much else in there, you can take a look at the code at  https://github.com/DamnWidget/anaconda/blob/master/commands/autoimport.py

**Comment by asfaltboy** [comment]
I see, so it requires linting to be enabled? I have `"anaconda_linting": false` in my settings, this may be why? This should probably be added to both [the documentation][1] and as a test in [the command][2]

[1]: https://github.com/DamnWidget/anaconda.github.io/blob/6b419b2e46d88f4c36d13b7c0ba0c5ec395a2df7/content/IDE.md#autoimport-undefined-names
[2]: https://github.com/DamnWidget/anaconda/blob/07d1772a4d09198741ac231386e3578692a4a8c4/commands/autoimport.py#L23

**Comment by DamnWidget** [comment]
If linting is disabled, anaconda can not possible know if a symbol is not defined so yes, that is why is failing. About SublimeLinter, nope, the new SublimeLinter is still slower than anaconda as it is still using a thread based Queue that locks the ST3 python interpreter GIL while anaconda uses an asynchronous client-server approach that does not lock the GIL or the GUI.

Said that, I have plans to improve all the linting related code and modernize it to make it comparable to the current SublimeLinter linting style.

**Comment by asfaltboy** [comment]
Sounds great! If you add support for a pluggable linters then I'm sold 👍  !

**Comment by schumannd** [comment]
is there support for external linters with this feature?
