### ISSUE TITLE
Autocomplete triggers after typing "def doit:"

### ISSUE THREAD

**Issue by mkroiss** [DamnWidget/anaconda#583]
## Expected Behaviour
No autocompletion here, but newline (and indent cursor)

## Actual Behaviour
Autocomplete window opens after :
Pressing enter for newline commits then instead of a newline

If using "auto_complete_commit_on_tab" alternatively, a newline is created,
but the autocomplete list shows again immediately in the new line.
Hitting TAB to indent the cursor then commits again instead of indenting.

## Steps to Reproduce
type in editor:
def doit:

## ST3, Anaconda and OS versions
3126, current, Windows

**Comment by DamnWidget** [comment]
Can not replicate, make sure you don't have any configuration triggering your auto completion when you type the `:` (that probably is your problem actually).

**Comment by mkroiss** [comment]
Thanks @DamnWidget  for the hint. I searched for settings before but all were standard ... but after disabling all other packages i found out that SublimeCodeIntel triggered the autocompletion.

I also found that it is working much faster and really smooth now. :+1:
