### ISSUE TITLE
Autocomplete hijacks the return key

### ISSUE THREAD

**Issue by 13am** [DamnWidget/anaconda#587]
## Expected Behaviour

When I am typing, I expect the return key to move the cursor to a new line.

## Actual Behaviour

Let's say I have finished typing a line and whatever letter I typed last has automatically triggered the autocomplete dialog to be shown. In the picture below, I have just typed ':' and now intend to press the return key to start typing on a new line:

![ana_1](https://cloud.githubusercontent.com/assets/11457975/20393211/ab5d349a-ace3-11e6-9855-cd3e5def8558.png)

But the autocomplete dialog has now automatically hijacked the function of the return key so that when I now press return, it triggers the first autocomplete option in the dialog instead of my expected behavior of starting a new line:

![ana_2](https://cloud.githubusercontent.com/assets/11457975/20393277/ef41d71a-ace3-11e6-9cb3-2443b77f0dee.png)

## Steps to Reproduce

See above.

## Suggestion

I'd like to be able to change the autocomplete dialog to function so that I'd have to press a key when I want to move the focus of the return key to the autocomplete dialog and thus change its normal behavior. So that the return key would never automatically to be focused on the autocomplete dialog. And I'd also prefer this to be the default behavior, but maybe that's just me. :)

**Comment by DamnWidget** [comment]
Or better, just disable SublimeCodeIntel that is making your Sublime Text 3 to fire the autocompletion dialog when you type `:`
