### ISSUE TITLE
Use current color scheme for help popup (tooltip)

### ISSUE THREAD

**Issue by nanoant** [DamnWidget/anaconda#595]
## Expected Behaviour
Currently Anaconda ships with two help popup (`anaconda_tooltip_theme`) themes - `dark` (default) and `light`. It would be much better (and reasonable) to use current color scheme colors instead than somehow hard-coded colors.

Also hardcoded themes for some reason use bold fonts everywhere which is pretty annoying. It would be much better if bolds were used only for headers, see attached sshot for kind of expected L&F.

![anacondalighttooltip](https://cloud.githubusercontent.com/assets/103067/20668445/3db58c6e-b56f-11e6-8162-2d211869a0fc.png)

## Actual Behaviour
Anaconda use hard coded themes, that somehow are not reflecting current color scheme.

**Comment by DamnWidget** [comment]
Totally agreed, take into account that anaconda tooltips where introduced as soon as ST3 API supported the first ever version of minihtml, in was pretty bad at the moment and the hardcoded CSS and theme was needed. 

Now things have improved in the ST3 API and there is no need anymore for the hardcoded templates, that is something that I will change in some moment and I am totally aware of.

**Comment by nanoant** [comment]
@DamnWidget that's great. thanks!

**Comment by DamnWidget** [comment]
By the way, you can override the default anaconda CSS styles creating a directory called `Anaconda.themes` in your `Packages/User` and saving there your own CSS files
