### ISSUE TITLE
support for cython .pxi and .pxd files

### ISSUE THREAD

**Issue by pjc42** [DamnWidget/anaconda#603]
## Expected Behaviour

There are three file types in Cython:

* Implementation files carry a .pyx suffix
* Definition files carry a .pxd suffix
* Include files which carry a .pxi suffix

AnacondaST3 currently supports cython implementation files .pyx. Cython has two other source/header file types *.pxi and *.pxd. Would be ideal if AnacondaST3 also recognized these file types as cython source files and apply syntax highlighting and so on.

## Actual Behaviour

Does not recognize file types .pxi and .pxd as cython source files.

## Steps to Reproduce

open any .pxi or .pxd file

## ST3, Anaconda and OS versions
ST3: Build 3126
AnacondaST3: 2.1.11
Windows 10, x64

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Hi, currently anaconda does not apply any kind of syntax highlight to Python files but relies in syntax highlighters (from third parties) to know when a Python source file is being edited. 

Is not in our aim to implement any kind of syntax highlighter into anaconda and continue relying in the different highlighters for Python available for Sublime Text 3.

There are actually three packages implementing Cython support in Package Control: https://packagecontrol.io/search/cython

Just install any of them, if the files are highlighted as Python code, anaconda will recognize them as Python code as anaconda uses ST3 builting source recognition capabilities that are tied to syntax highlight.

**Comment by pjc42** [comment]
Got it; was confused about what package was doing what. Perfect answer, thanks.

**Comment by DamnWidget** [comment]
No problem
