### ISSUE TITLE
Please update jedi for python3.6 support

### ISSUE THREAD

**Issue by shiman** [DamnWidget/anaconda#604]
I am using sublime text 3 under Arch Linux. One day, after upgrading the system, I found the auto completion not working. After checking the log at `anaconda_jsonserver.log`, I located this error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/shim/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jedi/parser/grammar3.6.txt'
```

The latest `grammar3.6.txt` has already been updated from the jedi upstream: https://github.com/davidhalter/jedi/pull/823

Please update at your convenience. Thanks!

**Comment by DamnWidget** [comment]
I see that Arch updated it's Python version to Python 3.6 already, awesome. I will update it as soon as I test that the plugin works with latest Jedi master version (that is not always true). In the meanwhile, you could probably add the `parser/grammar3.6.txt to `~/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jedi/parser/` it will probably work.

**Comment by DamnWidget** [comment]
I will release a new version with the last master Jedi later today

**Comment by shiman** [comment]
Awesome! Thanks for your fast response!
