### ISSUE TITLE
Sublime text 3 - Anaconda plugin. Not working '(' symbol?

### ISSUE THREAD

**Issue by haikuoyao** [DamnWidget/anaconda#612]
I don't get it why, but if I install Anaconda plugin (for Python development), then I can't use '(' symbol. I mean, when I try to shift + 9, to write (, nothing happens. Its like such keyboard combination is disabled (or should do something else maybe?). And of course I mean when writing it in sublime text editor.

**Comment by haikuoyao** [comment]
I solved it . I just uninstall `Jedi - Python autocompletion `

**Comment by DamnWidget** [comment]
That's right, anaconda and Jedi can not coexists in the same ST3 installation.
