### ISSUE TITLE
Autoformat PEP8 Configure Indent-Size

### ISSUE THREAD

**Issue by sleighsoft** [DamnWidget/anaconda#616]
When I use https://packagecontrol.io/packages/Python%20PEP8%20Autoformat I can configure the indent-size. Is that also possible for the integrated pep8 autoformat capabilities in anaconda?

**Comment by DamnWidget** [comment]
There is a PR waiting to get merged that fixes that problem: https://github.com/DamnWidget/anaconda/pull/606

**Comment by DamnWidget** [comment]
The PR has been merged today, so now, anaconda will use the same indentation that you have configured in your ST3 for the file that you are editing.
