### ISSUE TITLE
importing module from current library using a "." indicates pep8 error

### ISSUE THREAD

**Issue by sunnyville** [DamnWidget/anaconda#624]
## Expected Behaviour
No indication of an error on that line.

## Actual Behaviour
White dot beside the line number.

## Steps to Reproduce
Importing any module from current directory like:
from . import {module_name} shows the white dot

## ST3, Anaconda and OS versions
ST3:3126, Anaconda:2.1.13 and Windows 10

I don't think I'm breaking any rules by importing like this. 
Any way to fix this?

**Comment by DamnWidget** [comment]
Can you add a snippet of code that reproduces the problem?
Which version of Python are you using?
