### ISSUE TITLE
FileNotFoundError is a valid python3 exception

### ISSUE THREAD

**Issue by K4YT3X** [DamnWidget/anaconda#628]
## Expected Behaviour
Consider FileNotFoundError as a valid exception
## Actual Behaviour
Linting "Undefined Name 'FileNotFoundError'"
![fnfe](https://cloud.githubusercontent.com/assets/21986859/24068916/ec41a0fe-0b70-11e7-9e8a-ad521a1f4e10.png)

**Comment by DamnWidget** [comment]
Are you using a Python3 interpreter?
