### ISSUE TITLE
Python process 100% in 2.1.17

### ISSUE THREAD

**Issue by hyperknot** [DamnWidget/anaconda#632]
## Expected Behaviour
Python process should only occasionally use CPU and stop after quitting ST3.
Downgrading to 2.1.16 fixes this issue.

## Actual Behaviour
- Python process goes to 100%
- Python process starts eating memory (I've seen 2 GB+)
- Python process does not terminate after quitting ST3

## Steps to Reproduce
- Start ST3, and start using autocomplete in 2.1.17
- Try it up to 10 times.
- After some time, autocomplete stops working and the Python process gets to this 100%, memory eating, non-quitting state.

## ST3, Anaconda and OS versions
ST: 3126
Anaconda: 2.1.17 (via Git)
OS X: 10.11.6

## ST3 Console Logs
https://bpaste.net/show/327b23369b45

## Anaconda's JsonServer Logs
(contains a **please report** part!)
Also, the log stops being written once the process gets into this 100% CPU stage.
https://bpaste.net/show/68c43760860c

**Comment by DamnWidget** [comment]
I did rollback latest Jedi update, let me know if 2.1.18 fixes the issue.

**Comment by hyperknot** [comment]
The rollback / 2.1.18 seems to have fixed it, I'll report if I found anything after longer testing.

**Comment by DamnWidget** [comment]
Ok, so I am closing it for now, feel free to reopen if you find something

**Comment by DamnWidget** [comment]
I am trying to find the issue and solve it as we really need to update to the latest Jedi version to solve some high memory consumption when using certain libraries so I need to know which libraries where you using in your project and which Python version.
