### ISSUE TITLE
in /messages, you seem to have a typo in each release message

### ISSUE THREAD

**Issue by numbermaniac** [DamnWidget/anaconda#637]
For example, in https://github.com/DamnWidget/anaconda/blob/master/messages/2.1.18.txt:

> what **do you can** find

I think you mean "what can you find" :)

Seems to be there in quite a few of the recent messages.

**Comment by DamnWidget** [comment]
I normally copy the previous one and edit it :P

**Comment by numbermaniac** [comment]
Lol yeah, I thought so. Just a note for future releases :)

**Comment by DamnWidget** [comment]
Finally fixed the typo (after I already released it xD)
