### ISSUE TITLE
Anaconda's auto completion doesn't work for imported library

### ISSUE THREAD

**Issue by DataTerminatorX** [DamnWidget/anaconda#642]
## Expected Behaviour

When I press `.` after a certain class of a imported library, I hope the pop-up will list all the possible methods of this class, like most IDEs can do.
E.g., I've typed in `import pandas as pd`, and then I type in `pd.`, there should be a pop-up listing all the possible methods and classes of `pandas`.

## Actual Behaviour

For now, it's OK with python's built-in classes. E.g., I've typed in `l = [1,2,3]`, then I typed in `l.`, the pop-up will list all the functions and methods of `list`.

But for imported libraries, Sublime Text only displays its built-in pop-up, which listed all the historical typed in words in my `.py` file, nothing to do with those libraries. Occasionally,  Anaconda's pop-up will replace ST's built-in pop-up (i.e., after I pressed `.`, the built-in pop-up appeared first, and after about one second, it would be replaced by Anaconda's pop-up), but for most cases, it failed.

## Configurations I've done
I've changed 4 configuration files, and I listed all the possible settings relating to auto-completion
1.  **Packages/User/Preferences.sublime-settings**
```
	"auto_complete": true,
	"auto_complete_commit_on_tab": false,
	"ignored_packages":
	[ ],
	"show_definitions": true,
	"tab_completion": false,
```
2. **Packages/User/Python.sublime-settings**
```
    "auto_complete_triggers": [{"selector": "source.python - string - comment - constant.numeric", "characters": "."}]
```
3. **Packages/User/Anaconda.sublime-settings**
```
    "enable_signatures_tooltip": true,
    "auto_python_builder_enabled": true,
    "disable_anaconda_completion": false,
    "suppress_word_completions": true,
    "suppress_explicit_completions": true,
    "complete_parameters": true,
    "complete_all_parameters": false,
    "display_signatures": true,
```
4. **Packages/Anaconda/Anaconda.sublime-settings**
Changes are the same as **Packages/User/Anaconda.sublime-settings**

## ST3, Anaconda and OS versions
ST3: `Build 3126`
Anaconda: `v2.1.18`
OS: `OS X 10.11.3`

**Comment by DamnWidget** [comment]
Two things to take into account.

* Are you sure that your configured python interpreter `can see` the pandas library in any of its import paths?
* The pandas library is huge, first time that Jedi parses it takes a while then it's contents are cached into memory so further access will be faster, that means that the first autocompletion is very slow or never happens.

**Comment by DataTerminatorX** [comment]
Hi @DamnWidget 
Thx for reply.
* I can run those codes successfully using `cmd+B`, so I guess the answer of the first question is yes.
* I've tested some more libraries, I found that auto-completion worked on `numpy`, but for many other libraries like `pandas`, `scikit-learn` and so on, it won't work no matter how long I waited.

I've pasted my changes in those 4 configuration files, could you help see if they are correct? E.g. ` "suppress_word_completions": true,` means Sublime's built-in auto-completion will be overridden but I can still see the built-in pop-up.

**Comment by DamnWidget** [comment]
What `suppress_word_completions` does is tell ST3 to don't show completions based in the context of the buffer being edited but just when we have completions to show from Jedi. You can check if the anaconda's shipped version of Jedi is able to complete any library just going to `~/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib` then run your python interpreter (all of this from the command line) and writing:
```python
from jedi import Script
print(Script('import pandas;pandas.').completions())
```
If you get an empty list, then Jedi is not able to complete the library (pandas here was just an example).

**Comment by DataTerminatorX** [comment]
Thx for reply @DamnWidget 

Having followed your suggestions, I `cd` to `anaconda_lib` and run `from jedi import Script` in the command line, then there reported  an error `from: can't read /var/mail/jedi`

Before doing this, I installed `anaconda` and `jedi` sequentially in ST3 ( using `package control`). So do I need to `pip install jedi` to handle such error?

**Comment by jraiskin** [comment]
A silent thanks from me as well! :+1:

**Comment by ScottTyson** [comment]
I seem to be having a similar problem.
I'm using latest SublimeText3, Anaconda-IDE, and the "real" Anaconda3.
The autocomplete does work, but it fails to deliver the full range of options.
For example, a pandas.DataFrame fails to show the "groupby" method.

I ran the following in my Anaconda3 terminal:
  from jedi import Script
  print(Script('import pandas;pandas.').completions())
And the output does show the "groupby" in the results.

Ideas? Thanks!

**Comment by DamnWidget** [comment]
Hi @ScottTyson 
Run the following in your anaconda's terminal:
```python
import jedi
print(jedi.__version__)
```

**Comment by ScottTyson** [comment]
import jedi
print(jedi.__version__)

... per the above commands, the jedi version is : 0.11.1

**Comment by ScottTyson** [comment]
Just to be clear, the jedi version 0.11.1 is part of the Anaconda3-IDE release.

From this directory ... C:\Users\styson\AppData\Roaming\Sublime Text 3\Packages\Anaconda ...

I ran these commands:
set PYTHONPATH=. 
python -c "import jedi; print(jedi.Script('import pandas;pandas.').completions())"

I got output similar to that when running in the Anaconda3-IDE dir.

I installed Anaconda3 AFTER I had installed DamnWidget-anaconda. Does that make a diff?

**Comment by ScottTyson** [comment]
I uninstalled DamnWidget-anaconda then reinstalled ... seems to work fine now.
Perhaps switching out the underlying Python distribution hosed things up somehow?
I had started with vanilla Python, then removed that, and installed Anaconda3.

Thanks for your help and speedy responses.

**Comment by zioalex** [comment]
Thanks guys! This helped me! I had a similar problem .
I just needed to change the Preferences.sublime-settings with:
```
       "auto_complete": true,
	"auto_complete_commit_on_tab": false,
	"show_definitions": true,
	"tab_completion": false
```
