### ISSUE TITLE
cannot use square brackets on hungarian keyboard layout

### ISSUE THREAD

**Issue by fejesd** [DamnWidget/anaconda#643]
## Expected Behaviour
When I press altgr+f or altgr+g, square brackets should be inserted into the text.
## Actual Behaviour
"Usage not found" or "Unable to find" messages are shown in the status bar
## Steps to Reproduce
Just press altgr+f or altgr+g with hungarian keyboard layout
## ST3, Anaconda and OS versions
ST3 buld3126 windows, Anaconda v2.1.18

**Comment by DamnWidget** [comment]
Those are regular ST3 shortcuts defined in anaconda, although the shortcuts are defined to use the Alt key and not the graphics Alt.

Go to the anaconda shortcuts settings in your ST3 `preferences -> packages -> anaconda` menu, then delete or comment any shortcut that interferes with your workflow.

**Comment by fejesd** [comment]
thank you for the fast solution.
