### ISSUE TITLE
wrong docstring for wrapped function

### ISSUE THREAD

**Issue by mchwalisz** [DamnWidget/anaconda#644]
## Expected Behaviour
I would expect that anaconda shows the correct docstring and function reference for wrapped functions.
I know that in similar scenario jupyter notebook works correctly. Still not sure if it is anaconda or jedi problem.

![wrapper2](https://cloud.githubusercontent.com/assets/2182186/24757830/a34fe8a4-1ae0-11e7-8608-99e3b88638b9.png)

## Actual Behaviour
![wrapper](https://cloud.githubusercontent.com/assets/2182186/24757418/7e91c272-1adf-11e7-953c-3231cd8c8eaa.png)

Shows wrong wrapping function reference.
## Steps to Reproduce

```python
from functools import wraps


def decorator(name=None):
    """wrapper doc string"""
    def _decorate(func):
        @wraps(func)
        def wrapper():
            print(name)
            return func()
        return wrapper
    return _decorate


@decorator('testing')
def wrap_user():
    """Nice doc string"""
    print('doing stuff...')

print(wrap_user.__name__)
print(wrap_user.__doc__)
wrap_user()
```
Execution results in:

```
wrap_user
Nice doc string
testing
doing stuff...
```
which is good name and docstring.

## ST3, Anaconda and OS versions
Sublime 3 Build 3126
Anaconda 2.1.18
Linux Mint 18.1

## Anaconda's JsonServer Logs

[anaconda_jsonserver.log.txt](https://github.com/DamnWidget/anaconda/files/902733/anaconda_jsonserver.log.txt)

**Comment by DamnWidget** [comment]
I am afraid that is a Jedi problem
