### ISSUE TITLE
[] keys not working on hungarian keyboard in windows

### ISSUE THREAD

**Issue by DJviolin** [DamnWidget/anaconda#646]
I tried to remap `anaconda_find_usages` and `anaconda_goto` keys which has the default `ctrl+alt+f` and `ctrl+alt+g` keys in the user keymap file, because it's blocking the `[ ]` keys:

```json
[
  { "keys": ["ctrl+alt+t"], "command": "anaconda_goto" },
  { "keys": ["ctrl+alt+z"], "command": "anaconda_find_usages" }
]
```

However this code not working.

**Comment by DamnWidget** [comment]
You can modify the anaconda key bindings editing directly the plugin key-bindings file in `Preferences -> Packages -> Anaconda -> Key Bindings (Default)` that will override the conflicting binding.

P.S: sorry for the delay I've been traveling for the past two weeks

**Comment by DJviolin** [comment]
Thank You! It's working.

**Comment by DamnWidget** [comment]
I am glad to know, I am closing this, feel free to re-open if you have any further problems
