### ISSUE TITLE
(feature request) toggle open/close autocomplete window with same key binding

### ISSUE THREAD

**Issue by bitworm** [DamnWidget/anaconda#649]
## Expected Behaviour
toggle autocomplete window with same key binding

## Actual Behaviour
opens but does not close autocomplete window

## Steps to Reproduce
1) `"auto_complete": false` in setup file
2) open autocomplete key window with `ctrl+space`
3) press `ctrl+space` again; nothing happens

## ST3, Anaconda and OS versions
subl: build 3126
anaconda: 2.1.18
macos 10.12.4

**Comment by DamnWidget** [comment]
Anaconda does not decides when or how to show the autocompletion popup but injects it's results on it. It is possible to do what you are asking for but we must hook into global key-bindings and I don't like the idea.

**Comment by bitworm** [comment]
Makes sense.  Do you happen to know how this could be configured in ST3 then?
