### ISSUE TITLE
Warning for Trailing white space in multi-line string

### ISSUE THREAD

**Issue by kmoza** [DamnWidget/anaconda#651]
## Expected Behaviour
Warning for trailing whitespace should not appear in multi line string quoted with """ even if the string has spaces in between.

## Actual Behaviour
Warning for multi line string with trailing whitespace should not be reported.

## Steps to Reproduce
Create a multiline string with trailing white space at the end of a line.
e.g: cmd1 = """bpmp_sanity -x test_ping_spe_smbox -x test_threaded_ping -x test_heap_mark -x 
                test_async_ping -x test_fwtrace -x test_ipc_sanity -x test_heap_end -x test_show_dt"""

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Can't reproduce I just get E501 with the sample code, I am using:
* Arch Linux 
* ST3 3126
* Anaconda v2.1.18
