### ISSUE TITLE
Auto_completion failed when typing import

### ISSUE THREAD

**Issue by coderchaser** [DamnWidget/anaconda#653]
## Expected Behaviour
I want to import some modules and auto_complete the module names.
If I type "import " and open the auto-completion, all of the module names are shown as modules.
But as soon as I type a letter, the list does not adapt, but just disappears.When I type all the characters of the module and press Enter,it will show the module in the next line.How can I fix this?https://github.com/srusskih/SublimeJEDI/issues/150 this dosen't work.
## ST3, Anaconda and OS versions
ST3,Anaconda,OS:Ubuntu 14.04
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
That is a well known limitation of Sublime Text 3 itself and the solution is in our README.md file (just [follow this link](https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly)). It is normal that the solution for SublimeJedi does not works, it is another totally different plugin.

P.S: I recommend to disable SublimeJedi while you use anaconda, they interfere with each other.

**Comment by coderchaser** [comment]
it works,Thank you very much!
