### ISSUE TITLE
Anaconda taking High Memory 

### ISSUE THREAD

**Issue by guptas08** [DamnWidget/anaconda#654]
## Expected Behaviour
I had installed Anaconda and using Jupyter Notebook. The problem is that in the Task Manager the Pythonw.exe process keeps on increasing. I have 8 GB RAM and after 10-15 minutes the memory becomes full. Could you please help me how to control the high memory usage? I am using Windows 7. 

## ST3, Anaconda and OS versions
Windows 7
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
I am afraid that this is not the project page of the anaconda distribution project you should direct your requests to the [continuum anaconda issues tracker](https://github.com/ContinuumIO/anaconda-issues)
