### ISSUE TITLE
'doc' Operation Hangs

### ISSUE THREAD

**Issue by PandaDragonThing** [DamnWidget/anaconda#655]
## Expected Behaviour
client requests: doc returns in a timely manner

## Actual Behaviour
client requests: doc sometimes hangs for 30 seconds before getting this error: `'str' object has no attribute 'is_scope'`

## Steps to Reproduce
Randomly occurs for only the 'doc' operation.

## ST3, Anaconda and OS versions
Windows 10 with server running in cygwin.

## ST3 Console Logs
Nothing

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Can you provide your JsonServer Logs please?

**Comment by DamnWidget** [comment]
This is related with #680 and #691 and should be fixed now.
