### ISSUE TITLE
Ellipsis literal not recognized

### ISSUE THREAD

**Issue by astronouth7303** [DamnWidget/anaconda#660]
## Expected Behaviour

A literal `...` is accepted as valid syntax everywhere.

## Actual Behaviour

Get an "[E] invalid syntax".

## Steps to Reproduce

1. Open a Python file
2. Type `...`

The ability to use `...` as a literal anywhere is new in Python 3.0.

**Comment by DamnWidget** [comment]
Pretty sure that you did not configured anaconda to use a Python3 interpreter, take a look at the [documentation](http://damnwidget.github.io/anaconda/anaconda_settings/)

**Comment by astronouth7303** [comment]
Ok, yeah, that took care of it.
