### ISSUE TITLE
Autocompletion popup shows after a sapce

### ISSUE THREAD

**Issue by foodish** [DamnWidget/anaconda#665]
## Expected Behaviour
When pressing tab key，it can show autocomplete popup rather than insert a sapce first.
## Actual Behaviour
When typing "import sql", there will not show popup; 
Then I press tab key, it will be insertting a space first, then a autocompletion popup shows which I can select sqlite3 from it now.
So, the result is "import sql sqlite3"
## Steps to Reproduce
 importing sqlite3 using "import sql" and then try typing tab key . There will be a space first then a autocomplete.
## ST3, Anaconda and OS versions
ST3: Build 3126 x64
Anaconda: v2.1.18
OS: win10
## ST3 Console Logs
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /F/Downloads/Programs/Sublime Text Build 3126 x64/sublime_text.exe
working dir: /F/Downloads/Programs/Sublime Text Build 3126 x64
packages path: /F/Downloads/Programs/Sublime Text Build 3126 x64/Data/Packages
state path: /F/Downloads/Programs/Sublime Text Build 3126 x64/Data/Local
zip path: /F/Downloads/Programs/Sublime Text Build 3126 x64/Packages
zip path: /F/Downloads/Programs/Sublime Text Build 3126 x64/Data/Installed Packages
ignored_packages: ["ConvertToUTF8", "Vintage"]
pre session restore time: 0.431951
startup time: 0.744951
first paint time: 0.749951
first paint time: 0.751951
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin ChineseLocalizations.Localization
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x000001E1AA509048> initial check failed because:

connection to localhost:50057 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 50057))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
Package Control: Skipping automatic upgrade, last run at 2017-05-28 11:48:48, next run at 2017-05-28 12:48:48 or after
Unable to open clipboard
Unable to open clipboard
reloading settings Packages/User/Anaconda.sublime-settings
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by ayfaar** [comment]
I am have the same problem(
