### ISSUE TITLE
cannot find my path cannot find where Python

### ISSUE THREAD

**Issue by adcnet** [DamnWidget/anaconda#666]
Frustrated cannot find my path cannot find where Python is as it uses Anaconda "install package" via Sublime Text 3 IDE.

http://damnwidget.github.io/anaconda/#

Have watched about 5 YT videos still stuck.

Have followed this exactly http://www.gtlambert.com/blog/python-sublime-text-3 / everything is fine until I run - ctrl - B

http://imgur.com/BbO8qy3

My OS is Windows 8

**Comment by DamnWidget** [comment]
Where do you installed the Python interpreter?

**Comment by adcnet** [comment]
I haven't?

I just installed ST3 and Anaconda?

Sorry I am new to coding just about to learn Python :)

**Comment by DamnWidget** [comment]
Then is pretty normal that you can't find the Python path as you didn't installed it. You should take a look at https://www.python.org/

**Comment by adcnet** [comment]
I was going on his install instructions he didn't mention installing a Python path. I guess its not meant for total beginners.

**Comment by adcnet** [comment]
So now I need to install Python although I have Anaconda?

**Comment by DamnWidget** [comment]
Anaconda is just a plugin for ST3 that enhances the Python developers experience when they write or navigate Python code using ST3, we don't provide, support or maintain any Python interpreter or distribution in any way.

Is better if  you start learning about Python itself before to worry about editors or editor plugins.

**Comment by adcnet** [comment]
Thank you for all your help much appreciated :)
