### ISSUE TITLE
Anaconda SublimeCodeIntel autocomplete conflict.

### ISSUE THREAD

**Issue by fili2306** [DamnWidget/anaconda#667]
## Expected Behaviour
SublimeCodeIntel's autocomplete should fire up
## Actual Behaviour
When Anaconda is installed alongside SublimeCodeIntel, Intel's autocomplete doesn't fire up
(Tested in Django modules imports)
## Steps to Reproduce
Install Anaconda alongside SublimeCodeIntel
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
SublimeCodeIntel interfere with any other completion plugin, Anaconda and SublimeCodeIntel doesn't work together, you must choose yo use one or another.

P.S: If you configure anaconda right yo should not have any need to use SublimeCodeIntel

**Comment by fili2306** [comment]
Oh okay, thanks. So is there a way for Anaconda to autocomplete modules from Django?
This is the link to the two screenshots I took. I'd like to configure Anaconda to show the list of modules from Django like SublimeCodeIntel does, is it possible? If so then, how can I do it?

**Comment by DamnWidget** [comment]
Anaconda can see whatever your configured python interpreter can see. I suggest you to take a look at the documentation web site http://damnwidget.github.io/anaconda/  specially the section related with configure the interpreter http://damnwidget.github.io/anaconda/anaconda_settings/

Anaconda uses Jedi to complete python code, Jedi is way more powerful than code intel.

**Comment by fili2306** [comment]
Thatnks, I'll take a look at it.
I'm closing the issue.
