### ISSUE TITLE
anacondaST3: ERROR

### ISSUE THREAD

**Issue by coderchaser** [DamnWidget/anaconda#668]
Everytime I launch st3,errors like the following will appear in a few minutes.But Anaconda seems fine,though It can't auto-complete some key words like `self`.
`
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x0000025993D0B2B0> initial check failed because:

connection to localhost:50212 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 50212))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
error: <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x0000025993D0B2B0> initial check failed because:

connection to localhost:50212 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 50212))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
Package Control: No updated packages
`

**Comment by DamnWidget** [comment]
If it works just ignore that error, if you don't want to see it anymore you can set `swallow_startup_errors` as `true ` in your config.
