### ISSUE TITLE
gpu overflows when creating a subprocess to run a code which use only a little gpu

### ISSUE THREAD

**Issue by IvyGongoogle** [DamnWidget/anaconda#669]
hello, I use anaconda2.7 and I encounter a thorny problem. I run `nvidia-smi` and there is more than 10 GB video memory left for my machine. but when I create a subprocess to run a code which will use video memory of 1 GB size,
 it still shows error about gpu overflow. So what casues this problem? 
can you give some advises?
thank you very much~~

**Comment by DamnWidget** [comment]
Hi, I already told you yesterday (or the day before) that this anaconda project is not the one that you are using, the anaconda python distribution project page is https://github.com/ContinuumIO/anaconda-issues/issues

This is a plugin for Sublime Text 3 editor.

**Comment by IvyGongoogle** [comment]
@DamnWidget, so sorry.

**Comment by DamnWidget** [comment]
Don't worry :)
