### ISSUE TITLE
/usr/bin/cmake: /home/xxx/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake

### ISSUE THREAD

**Issue by IvyGongoogle** [DamnWidget/anaconda#670]
hello, I use anaconda2.4.x, everytime I run cmake or make, it shows error:

`/usr/bin/cmake: /home/xxx/local/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)`

how to fix it?
can you give some advises?

**Comment by DamnWidget** [comment]
I am afraid that is a different anaconda project, try here: https://github.com/ContinuumIO/anaconda-issues/issues

**Comment by IvyGongoogle** [comment]
@DamnWidget I solve this though using cmake with higher version. thank you~
