### ISSUE TITLE
conda environments -- no pandas console output

### ISSUE THREAD

**Issue by jknaus** [DamnWidget/anaconda#671]
I have created different conda environments for my python projects and set project specific settings to use the correct python version of the respective environment.

My scripts now show a strange behaviour. Although they run without errors. I can only print pandas dataframes to the ST3 console if I use the conda root environment. With any other conda environment print(df) just produces empty output.

I double checked: pandas is installed in all environments. When I start my script manually from Windows cmd, activating the project's conda environment (i.e. not the root environment), the pandas dataframes are printed out. So it must be something within the ST3/Anaconda configuration.

Where could be the source of this error/bug/strange behaviour?

## ST3, Anaconda and OS versions
ST3 Build 3126, Anaconda 2.1.18, Windows 7, miniconda Python 3 distribution

**Comment by DamnWidget** [comment]
Wrong repository @jknaus, this is a plugin for ST3 not the Anaconda python distribution, their repository is https://github.com/ContinuumIO/anaconda-issues/issues 

Try there :)

**Comment by jknaus** [comment]
No, this is not a conda issue. I know about the possible confusions. Conda runs just fine as I described it in my original post. When I start my python script from commandline everything runs fine, even in the environments. The problem occurs only when I try to run my script from within ST3 using a correctly defined Anaconda build tool.
