### ISSUE TITLE
Support for type annotations

### ISSUE THREAD

**Issue by qmmp123** [DamnWidget/anaconda#673]
## Expected Behaviour
```
var: str
var.# here list completions 
```
## Actual Behaviour
Nothing
## Steps to Reproduce
type code from Expected Behaviour
## ST3, Anaconda and OS versions
build 3126, last version(installed via package control), ubuntu 16.04
## ST3 Console Logs
```
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin tern_for_sublime.tern
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2017-07-19 05:01:49, next run at 2017-07-19 06:01:49 or after
Unable to open /home/qmmp123/.config/sublime-text-3/Packages/Default/Default (Linux).sublime-keymap
Unable to open /home/qmmp123/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap
```
## Anaconda's JsonServer Logs
```
2017-07-19 05:24:27,564: INFO    : client requests: lint
2017-07-19 05:24:27,617: INFO    : About push back to ST3: b'{"success": true, "errors": [{"underline_range": true, "level": "E", "lineno": 22, "message": "[e] %s", "raw_error": "[E] invalid syntax", "offset": 17}], "uid": "cd99f2782c604bbaaedc6b8d38d94d5b", "vid": 15}\r\n'
2017-07-19 05:24:28,552: INFO    : client requests: autocomplete
2017-07-19 05:24:28,642: INFO    : About push back to ST3: b'{"success": true, "completions": [], "uid": "eda11cc944744c1ba7dd13ba0145e734"}\r\n'
2017-07-19 05:24:31,249: INFO    : client requests: lint
2017-07-19 05:24:31,306: INFO    : About push back to ST3: b'{"success": true, "errors": [{"underline_range": true, "level": "E", "lineno": 22, "message": "[e] %s", "raw_error": "[E] invalid syntax", "offset": 17}], "uid": "8c867004b2104390b6e16fc424da435f", "vid": 15}\r\n'
2017-07-19 05:24:31,345: INFO    : client requests: lint
2017-07-19 05:24:31,385: INFO    : About push back to ST3: b'{"success": true, "errors": [{"underline_range": true, "level": "E", "lineno": 22, "message": "[e] %s", "raw_error": "[E] invalid syntax", "offset": 17}], "uid": "47451d7a71a441fd9ebfe5c6e3fed6fb", "vid": 15}\r\n'
```
## PS
Sorry for my english
Before post issue, I have checked this feature in vim and it works fine

**Comment by DamnWidget** [comment]
What you mean that it works on vim? Using which plugin?

**Comment by qmmp123** [comment]
I used youcompleteme which uses jedi as backend.

**Comment by DamnWidget** [comment]
Are you using an interpreter equal or higher than Python 3.6 as your configured `python_interpreter` in Anaconda?

**Comment by qmmp123** [comment]
I am using python3.6.2

**Comment by DamnWidget** [comment]
Open the ST3 console and write this into it:
```python
from anaconda.anaconda_lib.workers.market import Market
Market.get(Market, window.id()).interpreter
```
Paste here the result

**Comment by qmmp123** [comment]
>>> from anaconda.anaconda_lib.workers.market import Market
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'anaconda'

**Comment by DamnWidget** [comment]
Sorry, use `from Anaconda.anaconda_lib.workers.market import Market`

**Comment by qmmp123** [comment]
/home/qmmp123/develop/online_shop/.venv/bin/python -B /home/qmmp123/.config/sublime-text-3/Packages/Anaconda/anaconda_server/jsonserver.py -p online_shop -e /home/qmmp123/develop/online_shop 11836

**Comment by DamnWidget** [comment]
So I understand that `/home/qmmp123/develop/online_shop/.venv/bin/python` is a python 3.6.2 interpreter right?

**Comment by qmmp123** [comment]
Yes

**Comment by DamnWidget** [comment]
I will take a look, maybe our Jedi library is too old and doesn't support this yet.

**Comment by qmmp123** [comment]
Thank you for the quick response

**Comment by DamnWidget** [comment]
Actually that is the problem, with our Jedi version:
```python
from jedi import Script
Script('var: string\nvar.).completions()
[]
```

With current Jedi master:
```python
from jedi import Script
Script('var: string\nvar.').completions()
[<Completion: capitalize>,  
 <Completion: casefold>,    
 <Completion: center>,      
 <Completion: count>,       
 <Completion: encode>,      
 <Completion: endswith>,    
 <Completion: expandtabs>,  
 <Completion: find>,        
 <Completion: format>,      
 <Completion: format_map>,  
 <Completion: index>,       
 <Completion: isalnum>,     
 <Completion: isalpha>,     
 <Completion: isdecimal>,   
 <Completion: isdigit>,     
 <Completion: isidentifier>,
 <Completion: islower>,     
 <Completion: isnumeric>,   
 <Completion: isprintable>, 
 <Completion: isspace>,     
 <Completion: istitle>,     
...]
```

The solution will be as simple as update Jedi but that will require a crossover full in deep test in all three platforms to check that nothing else is broken, it will take a bit of time.

**Comment by qmmp123** [comment]
Why anaconda can't use jedi as submodule?

**Comment by qmmp123** [comment]
Or how can I install jedi from git to anaconda?

**Comment by DamnWidget** [comment]
Anaconda vendors it's own copy of Jedi as rely in other Jedi installation could cause problems and in ths way we have to support only a Jedi version what is way cleaner and easier for us.

If you update Jedi by yourself signatures, goto, usages and documentation are gonna break as they introduced a breaking change not long ago and we don't support it yet. Anyway if you still want to update your in anacoda vendored version of Jedi you can totally do it just following this steps:

* Stop Sublime Text
* Make a copy of `Anaconda/anaconda_lib/jedi` as backup
* Download latest Jedi version
* Copy the `jedi` directory inside the Jedi package root into `Anaconda/anaconda_lib/jedi`
* Cross fingers
* Start Sublime Text

**Comment by qmmp123** [comment]
I have update jedi and it is work)

**Comment by DamnWidget** [comment]
You probably broke signatures, goto and usages support right?

**Comment by qmmp123** [comment]
In this code
`def post(self, request, *args, **kwargs):
        user = _user[request.session["pharmacy"]]
        array_with_cart_info = json.loads(request.POST["order"])[:-1]
        clientinfo = json.loads(request.POST["order"])[-1]
        data = {"purchaser": clientinfo["client_name"], "phone": clientinfo[
            "phone_number"], "comment": clientinfo["comment"], "user": user}`
usages for variable `user` dont work

**Comment by qmmp123** [comment]
But I think it is bug in jedi, because for other variables it works fine

**Comment by qmmp123** [comment]
I think you can close Issue, because we found solution

**Comment by DamnWidget** [comment]
No, you just updated your own copy of jedi but that doesn't really solves the issue, I will close it when I update Jedi in anaconda and fix the problems with usages, goto and signatures.

**Comment by DamnWidget** [comment]
This should work now out of the box with v2.1.19
