### ISSUE TITLE
@ operator: Invalid Syntax

### ISSUE THREAD

**Issue by ruffson** [DamnWidget/anaconda#674]
## Expected Behaviour
@-Operator supposed to work as infix operator for matrix multiplication like defined in: https://www.python.org/dev/peps/pep-0465/
## Actual Behaviour
Invalid syntax when using @ operator for matrix multiplication.
## Steps to Reproduce
```
import numpy as np
np.eye(3) @ np.eye(3) # Gives Invalid Syntax Lint-Error
```
## ST3, Anaconda and OS versions
ST3 build 3126, don't know how to see the version number of anaconda but should be up-to-date. OS: macOs Sierra.

**Comment by DamnWidget** [comment]
Are you using a Python 3 interpreter as your configured `python_interpreter` for anaconda?

**Comment by ruffson** [comment]
Oh wow tat fixed it, thank you! Worked with it for a while and didn't know your have to define that explicitly. Thank you so much!

**Comment by DamnWidget** [comment]
No problem 👍
