### ISSUE TITLE
[BUG] False positive linting

### ISSUE THREAD

**Issue by K4YT3X** [DamnWidget/anaconda#676]
![anaconda_bug](https://user-images.githubusercontent.com/21986859/28501224-ff4511e6-6f9c-11e7-9579-61c0dc9bac66.png)

## BUG Description
Giving out false positives
## Steps to Reproduce
this exact syntax: 
~~~~
print(P + BD + '\r[#] Entr0: Next Change in ' + C + str(x) + P + ' Seconds ' + W, end='')
~~~~
## ST3, Anaconda and OS versions
ST3: 3126
Anaconda: newest version at this time
## ST3 Console Logs
N/A
## Anaconda's JsonServer Logs
Found nothing useful

**Comment by DamnWidget** [comment]
There are no false positives going on in here, if you want Python3 syntax linting then configure a Python 3 interpreter.

http://damnwidget.github.io/anaconda/anaconda_settings/
