### ISSUE TITLE
Auto-completion of Anaconda really confused me.

### ISSUE THREAD

**Issue by coderchaser** [DamnWidget/anaconda#677]
## Expected Behaviour
Auto completion of keywords, function, parameters and so on.
## Actual Behaviour
Every time when I first open Sublime Text 3,Anaconda can complete all the module names and keywords such as `from` ,`import`.But *a few seconds* later,all these auto-coompletion fail.

Sorry to bother you.

**Comment by coderchaser** [comment]
My own configuration:
`
{
	"suppress_word_completions": true,
    "suppress_explicit_completions": true,
    // //"complete_parameters": true,    
    // "complete_parameters": false,
    // "complete_all_parameters": false,
    "anaconda_linting": false
}
`

**Comment by DamnWidget** [comment]
I am afraid that I can't help you if you don't follow the New Issue template and add all the logs that we ask for, with the information that you provided I can't do nothing but guess, please, provide your JsonServer logs and your console logs.

Also add list of your in use plugins (others than anaconda).

**Comment by coderchaser** [comment]
## ST3 Console Logs
>DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Bobliao/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Bobliao/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Bobliao/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 2.50432
startup time: 2.53532
first paint time: 2.55032
first paint time: 2.55032
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SublimeTmpl.sublime-tmpl
plugins loaded
Package Control: No updated packages
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x000001C6F3F3A978> initial check failed because:

connection to localhost:50087 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 50087))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
error: <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x000001C6F3F3A978> initial check failed because:

connection to localhost:50087 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 50087))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
Hi, I can't find the directory `%APPDATA\\Anaconda\\Logs`.
## Below are my in use plugins:
*AutoFileName 
*Package Control
*Sublime Tmpl

**Comment by coderchaser** [comment]
Here are some else problems, I don't know these below are caused by ST3 or Anaconda or Python.
## Description
When I open ST3, first Anaconda can auto complete those keywords like what I said before.But after it failed, there was a python progress left. And this python progress will take high CPU occupancy like the picture below shows.
![cpu_high](https://user-images.githubusercontent.com/20502148/28607350-1a2e7ec0-720e-11e7-8d62-d417cecb58d4.PNG)
I closed ST3 and reopened it,two python progress appeared, each of them took almost 30 percent CPU.Then my laptop was torn down by these two guys.I had to enforce shut down the laptop.

**Comment by coderchaser** [comment]
![cpu](https://user-images.githubusercontent.com/20502148/28608522-34134ec4-7213-11e7-9e49-ec3c61d3bb91.gif)

**Comment by DamnWidget** [comment]
I need your JsonServer logs probably it is crashing.

**Comment by coderchaser** [comment]
[anaconda_jsonserver.zip](https://github.com/DamnWidget/anaconda/files/1176619/anaconda_jsonserver.zip)

I found the JsonServer logs, please have a check.

**Comment by coderchaser** [comment]
[liaoxuefeng.zip](https://github.com/DamnWidget/anaconda/files/1176628/liaoxuefeng.zip)

I think maybe this log can show something.

**Comment by DamnWidget** [comment]
Yeah, your JsonServer is crashing for some reason but we don't get the traceback in the logs so you are gonna need to start it in Debug mode. This is the explanation of how to do it (extracted directly from the config file).

```javascript
/*
        Debug Mode:

        If you need to debug the jsonserver.py service for any reason, you
        can configure the following options to make the plugin to connect
        always to the same port in your local machine.

        Procedure:

            1. Set the debug_mode as true
            2. Set the debug_port to your desired port
            3. Close Sublime Text 3
            4. cd to your Packages/Anaconda directory
            5. Start the jsonserver manually:
                python -B anaconda_server/jsonserver.py -p test 9999 DEBUG
            6. Start your Sublime Text 3 and

        Then your anaconda plugin will use the configured server, and you will
        get debug messages in the terminal where you ran it.
    */
    "jsonserver_debug": false,
    "jsonserver_debug_port": 9999,```

I don't know what is it but I am guessing that is related with you using a Python2 interpreter and using UTF-8 encoded characters in your file system paths and file names.

Please, start the server using the same interpreter that you have configured for anaconda and paste here any exception that you get.

**Comment by coderchaser** [comment]
There is only Python3 in my PC.
I didn't change the default python interpreter, it was still `"python_interpreter": "python"`.
### DebugMode tradeback in terminal

```python
"python_interpreter": "python"
```

**Comment by DamnWidget** [comment]
Where is the traceback?

**Comment by coderchaser** [comment]
I think the python progress which takes high occupancy of CPU is related to the JsonServer.py. Because after I kill this progress,the `python -B anaconda_server/jsonserver.py -p test 9999 DEBUG` will be shut down in the terminal.

**Comment by coderchaser** [comment]
Is this tradeback in the terminal that you need? Or should I provide anything else?

**Comment by DamnWidget** [comment]
There is no tracebacks in the text that you pasted, that is just normal debug information, doesn't looks like there is any crashes or unhandled exceptions but there was something weird going on in your logs as teh connection with the JsonServer was being constantly reset.

This demonstrates that when you start the JsonServer manually from a terminal (cmd.exe or powershell) everything works as expected so this is why I am guessing this is an environmental issue and probably related with the fact that you make an extensive use of Unicode characters as your computer is set to use Chinese language (that requires 16 bits to accommodate some characters).

Please, run this into your ST3 console and paste the results:
```python
import sys
print(sys.stdin)
```

**Comment by coderchaser** [comment]
>>> import sys
>>> print(sys.stdin)
None

**Comment by DamnWidget** [comment]
How is that even possible? O.o
What happens if you don't use `print` and just write `sys.sdtin`?

**Comment by coderchaser** [comment]
```python
>>> import sys
>>> sys.stdin

```
nothing :)

**Comment by coderchaser** [comment]
May I ask what's the meaning of `teh connection`?

**Comment by coderchaser** [comment]
I run the test.py, codes in it:
```python
import sys
print(sys.stdin)
```
results in Pycharm:
```python
"E:\Program Files (x86)\Python\python.exe" E:/Code/Python/Pycharmprojects/Learning/code/liaoxuefeng/test.py
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
```
results in ST3:
```python
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='cp936'>
[Finished in 0.1s]

```

**Comment by DamnWidget** [comment]
Thats the problem, your encoding for ST3 is not UTF-8 (`encoding='cp936'` that is Simplified Chinese encoding), when ST3 starts a new process, it does with those encodings, when you start it from the terminal the encoding is UTF-8 and that is why we don't see any crash from the debug.

Try to set the environment variable (create it if it doesn't exists) `PYTHONIOENCODING` to `utf8` and see if the encoding changes in ST3.

**Comment by coderchaser** [comment]
Thanks! This works fine for me.So far,I have found the reason:I build my own build-system for Python,encoing=cp936.I change it back to the default Python build-system,and so far nothing seems weird.Really thanks @DamnWidget ,hope ST3 and Anaconda become better!

**Comment by coderchaser** [comment]
向咱们国人提个建议：千万不要随便使用网上的ST3的Python模板，编码可能是个坑，我这个就是这个问题，麻烦了作者这么长时间，衰~~~

**Comment by DamnWidget** [comment]
My Chinese is a bit rusty (I don't know any Chinese at all), what that means?

**Comment by coderchaser** [comment]
Haha, I want to remind my compatriots who encounter similar problems to watch the encoding :)
And in Chinese, 谢谢 means thank you. Anaconda is really a great ST3 plugin and you are such a nice developer.

**Comment by DamnWidget** [comment]
Oh, so you use the same character `谢` twice to say thank you, so curious. Thank you for your words, I just try to maintain the plugin for as long as I can. To become a good programmer is just a matter of time, I don't consider myself a "good programmer" really I am always learning and improving.

Regards.
