### ISSUE TITLE
When sublime text 3 was closed, the python process initiated by anaconda does not close, causing a memory leak

### ISSUE THREAD

**Issue by CrystalRays** [DamnWidget/anaconda#679]
## Expected Behaviour
When sublime text 3 was closed, the python process initiated by anaconda should close
## Actual Behaviour
When sublime text 3 was closed, the python process initiated by anaconda does not close, and its occupied memory gradually increased
![_ _20170727151403](https://user-images.githubusercontent.com/25876671/28660516-cfdd494a-72e5-11e7-9d58-85ecef84e056.png)

## Steps to Reproduce
Edit a .py file with sublime text 3 while anaconda is enable,and then exit sublime text 3,and then wait.
## ST3, Anaconda and OS versions
ST3: bulid 3126,OS: Linux Deepin 15.4.1, Anaconda: I don't know how to find it.
## ST3 Console Logs
How should get it after ST3 exited.
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
[anaconda_jsonserver.log.tar.gz](https://github.com/DamnWidget/anaconda/files/1179158/anaconda_jsonserver.log.tar.gz)

P.S.Sorry for my poor English.

**Comment by DamnWidget** [comment]
Are you sure that Python process is anaconda's? This is directly extracted from the bottom of your jsonserver logs

```2017-07-27 13:02:51,943: INFO    : client requests: doc
2017-07-27 13:31:32,067: INFO    : process 4745 does not exists stopping server...
2017-07-27 13:31:34,059: INFO    : Closing the socket, server will be shutdown now...```

As you can see, anaconda's jsonserver killed himself after noticing that ST3 wasn't open anymore...

**Comment by CrystalRays** [comment]
I am sure it is.
I tried several times and find that after ST3 is closed, the python process would remains for a while.But then it closed.

**Comment by CrystalRays** [comment]
I find that if I open several python objects in ST3 and then closed them all suddenly( by mistake). So I restart them at once, but because of the rapid restart of the sublime and anaconda, the python process before will not quit, and has been eating memory in the background.


![_ _20170727164503](https://user-images.githubusercontent.com/25876671/28661925-f9d3ecfe-72ea-11e7-9a10-f6133b422c5e.png)

**Comment by CrystalRays** [comment]
It had been occupying 2.6 GB memory now.

P.S. I had install a program to kill the occupying most process while the system resource is rare.

**Comment by DamnWidget** [comment]
What you describe is not possible on Posix systems as any JsonServer process started by anaconda is tied to the PID of your in execution Sublime Text 3, so even if you kill ST3 and start it in a millisecond, you will have a different PID and the previous JsonServer process will kill himself as it's creator PID is no in the system anymore.

The anaconda's JsonServer python process could remain up to 30 seconds in the system before to kill himself.

**Comment by CrystalRays** [comment]
Yes, it will have a new pid, but the previous JsonServer process didn't kill himself. You can see 
![_ _20170727173933](https://user-images.githubusercontent.com/25876671/28664308-9a74db62-72f2-11e7-863a-d6dd1d6cb904.png)

Maybe it's jsonserver's bug?I can always reproduce the situation, maybe you could try to reproduce too?

Would you want a gif that will show how it happens?

**Comment by DamnWidget** [comment]
Can you attach a `strace` to that process to see what it is doing?

**Comment by CrystalRays** [comment]
Well, I think I got something wrong, I'll close this tissue, and open another.
I'm sorry.

**Comment by DamnWidget** [comment]
Feel free to open a new issue with more information if you get more information or discover if something is really wrong and what is going on.

Also take into account that Anaconda can (and will) start more than one process for different ST3 windows
