### ISSUE TITLE
Lint description/message not shown

### ISSUE THREAD

**Issue by SemanticGames** [DamnWidget/anaconda#681]
[Issue similar to #533]

Hi,
I just installed Anaconda for the first time, I can see where the linter errors are (underlined), I have access to their descriptions via "Show error list", but nothing happens when I hover or click on the error.
I understand that a complete description should appear in the "status bar" (the bottom line of the window ?), but it's just not there.

Context:
I just upgraded from an old version of sublime text 2 to ST3, maybe there were previous packages installed including another python linter (not with package control though, and I can't find them).
OS: Ubuntu 16.04

Thank you

**Comment by DamnWidget** [comment]
This looks like a regression
