### ISSUE TITLE
Rename Object under Cursor doesn't operate

### ISSUE THREAD

**Issue by daniele-niero** [DamnWidget/anaconda#70]
Hello,

I still have a small problem with Anaconda. The tool Rename Object Under Cursor seems don't working. When I click on it I see the input bar appearing at the bottom of ST, I can write on it but when I click enter nothing happen and nothing is logged on the command line.

Is there anything I can do to see the possible errors or debug the problem somehow?

**Comment by evbo** [comment]
This issue still occurs even with a fresh anaconda install...

**Comment by iambrosie** [comment]
I can confirm the issue is still present.
