### ISSUE TITLE
Pipfile support

### ISSUE THREAD

**Issue by mhubig** [DamnWidget/anaconda#702]
Since it seems you can not use a `$VIRTUAL_ENV` environment variable (see #517) to set the correct `python_interpreter` path at the moment, a good enhancement of the situation could be to detect the presence of a [Pipfile](https://github.com/pypa/pipfile) and use [pipenv](https://github.com/kennethreitz/pipenv) to get the corresponding virtualenv path.

**General steps**

0. Check if `pipfile` support is enabled within the configuration.
1. Detect presence of `Pipfile`.
2. Check availability of `pipenv`.
3. Execute `pipenv --venv`.
4. If non of the steps failed, set `python_interpreter` to `$VIRTUAL_ENV/bin/python`
5. Optional: Add `$VIRTUAL_ENV/bin` to `$PATH`

**Comment by DamnWidget** [comment]
Environment variables will work again since v2.1.22
