### ISSUE TITLE
import module autocomplete failed

### ISSUE THREAD

**Issue by ycjcl868** [DamnWidget/anaconda#705]
Example: `import requests`
## Expected Behaviour
When I add `other word` before `import module` , it could auto-complete . 
![image](https://user-images.githubusercontent.com/13595509/30854584-b798bad4-a2e4-11e7-9c96-523a77e9d344.png)

## Actual Behaviour
When I input `import ` , it could list all modules
![image](https://user-images.githubusercontent.com/13595509/30854722-19564a7a-a2e5-11e7-96ff-aa1997bdf747.png)

But I go on input `import req` , it can't auto-complete.
![image](https://user-images.githubusercontent.com/13595509/30854679-f3536ae2-a2e4-11e7-8936-6224287c4132.png)

## ST3, Anaconda and OS versions
ST3: Build 3143 Latest
Anaconda:
Version: `2.1.21 Latest`
Setting: 
```json
{
  "python_interpreter": "/usr/bin/python",
  "anaconda_linting": false,
  "complete_parameters": true
}

```

**Comment by DamnWidget** [comment]
Take a look to: https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly

**Comment by ycjcl868** [comment]
I saw,but it can't work.

**Comment by DamnWidget** [comment]
It has to work, I can't reproduce it

![spectacle t17012](https://user-images.githubusercontent.com/329766/30859561-2ed32694-a2bc-11e7-8697-407b9baa2209.png)

**Comment by ycjcl868** [comment]
Thanks, it works.

![image](https://user-images.githubusercontent.com/13595509/30859558-d4fc6280-a2f6-11e7-83fc-0d0b8d8e5625.png)


----------
I understand ~
![image](https://user-images.githubusercontent.com/13595509/30859585-edbaba7e-a2f6-11e7-8eba-99c6bf9ab87c.png)

**Comment by JokerQyou** [comment]
I can reproduce this issue if I disable the builtin `Python` package and use `MagicPython` instead. Only this time I cannot fix it by putting `Completion Rules.tmPreferences` in either `Python` directory or `MagicPython` directory. I'm sure it has something to do with `MagicPython`, because if I use `Python` package and follow above steps everything is fine.
Any suggestions?

**Comment by ThankfulBird** [comment]
I have the same problem but i cant get how to solve it help me please!!

**Comment by GlassGruber** [comment]
@JokerQyou, @ThankfulBird  I had the exact same problem and finally managed to fix it. The problem with MagicPython is that it has a different folder structure from normal Python package. You have to put the `Completion Rules.tmPreferences` file in this folder `Packages\MagicPython\settings\sublime`. 

@DamnWidget Can I suggest an edit for the docs?
I had unfortunately a serious PEBCAK issue! In the _Behave badly_ section is written (bold is mine):

> Work-around: Create a new Python directory **in your Packages** directory...

It took me quite some time to realize that you meant the `Packages` folder and not the `Packages/User` as I tried hopelessly :(
As I read it now it looks obvious, but boy that _your_ totally tripped me out! A more simple and PEBCAK-proof suggestion could be:

**Work-around**: Create a new Python directory in the main Packages directory (access it via _Preferences > Browse Packages...) and copy the contents of the file Completion Rules.tmPreferences there with the same name. Delete your Sublime Text Cache file Cache/Python/Completion Rules.tmPreferences.cache.

Maybe there could be also a mention that for third party python language packages the location of the `Completion Rules.tmPreferences` file depends on the third package directory structure.

Thank you for your plugin!!! :smiley:
