### ISSUE TITLE
Invalid syntax for valid syntax

### ISSUE THREAD

**Issue by vlasenkov** [DamnWidget/anaconda#706]
## Expected Behaviour

Do not raise invalid syntax error.

## Actual Behaviour

![image](https://user-images.githubusercontent.com/13369474/30912906-f46e9eb2-a396-11e7-99ff-c8413803b343.png)

## Steps to Reproduce

Open Sublime and enter this code.

```
def load_hosts(filename):
    with open(filename) as f:
        return {job: [f'{host["host"]}:{host["port"]}' for host in hosts]
                for job, hosts in json.load(f).items()}
```

## ST3 and OS versions

Sublime 3. Build 3143, MacOS 10.12.4 (16E195)

**Comment by DamnWidget** [comment]
You have to configure anacoda to use a Python 3 interpreter if you want to use Python 3 syntax

![spectacle fw4160](https://user-images.githubusercontent.com/329766/30913317-aa61e6a8-a387-11e7-8b5c-49f86e8f859a.png)
