### ISSUE TITLE
how to add PySide/PyQt autocompletion

### ISSUE THREAD

**Issue by spamwax** [DamnWidget/anaconda#71]
I am trying to add autocompletion for PySide/PyQt by specifying `extra_paths` settings in the ST3's project settings, but it seems it doesn't help:

``` JavaScrip
    "extra_paths": [
      "/usr/local/lib/python2.7/site-packages",
      "/usr/local/lib/python2.7/site-packages/PySide",
      "/usr/local/lib/python2.7"
    ],
```

Is this possible using the current anaconda?

**Comment by flipphillips** [comment]
For what it might be worth, I was having the same problem here on MacOS X, and tracked it down to a path with a space in it-

	"extra_paths": ["/Applications/Maxwell 3/Libs/pymaxwell/python2.7" ,
					"/Users/flip/Dropbox/Sync/dev/mm-api/python",
					"/Users/flip/Dropbox/Sync/dev/mm-api/distrib/python_osx",
					// "/Users/flip/Dropbox/Python/github/psychopy",
					// "/Applications/Pixar/RenderManProServer-18.0/bin",
					// "/Users/flip/Dropbox/LeapDeveloperKit/LeapSDK/lib"
					]
If I keep the "Maxwell 3" path in there, find-definition, autocomplete, etc don't seem to be able to find anything. Commenting it out... things are findable. 

The same list is in my `$PYTHONPATH` and my programs run/build just fine, for what that is worth. It is only the plug-in that can't seem to find the definitions.
