### ISSUE TITLE
Linting marks 'nonlocal' statements as invalid syntax

### ISSUE THREAD

**Issue by kevinsv101** [DamnWidget/anaconda#711]
## Expected Behaviour
Utilize nonlocal keyword, and if utilized correctly, it is left unhighlighted.

## Actual Behaviour
Even when nonlocal keyword is utilized correctly and executing the program produces no errors,
linting marks nonlocal as invalid syntax
## Steps to Reproduce
Open or create a .py file with sublime and utilize the nonlocal keyword anywhere.

## ST3, Anaconda and OS versions
ST3: Version 3.0, Build 3143
Anaconda: 2.1.23
OS: OS X 10.12.6
## ST3 Console Logs
Nothing of note produced

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

[Logs.zip](https://github.com/DamnWidget/anaconda/files/1361559/Logs.zip)

**Comment by DamnWidget** [comment]
You have to configure your anaconda installation to use a Python3 interpreter
http://damnwidget.github.io/anaconda/anaconda_settings/
