### ISSUE TITLE
docstring and fonctions signatures not always showing

### ISSUE THREAD

**Issue by nsklaus** [DamnWidget/anaconda#712]
## Expected Behaviour
pygame docstring and methods signature should always get displayed.

## Actual Behaviour
pygame docstring and method signature aren't always displayed.

## Steps to Reproduce
for example, in a new file type the following:

```
import pygame
pygame.draw.rect()

```
i don't get no docstring and no method signature.

..but if i do this:
`pygame.Rect()`
i do get them.

please see screenshots below.

![anaconda-st3_1](https://user-images.githubusercontent.com/6810861/31349054-e3ab99ce-ad21-11e7-9177-dcfcafde3e10.png)
![anaconda-st3_2](https://user-images.githubusercontent.com/6810861/31349056-e3b9bb80-ad21-11e7-816b-ed0c906e14b2.png)
![anaconda-st3_3](https://user-images.githubusercontent.com/6810861/31349055-e3ad1934-ad21-11e7-98f3-903f68c17850.png)
![anaconda-st3_4](https://user-images.githubusercontent.com/6810861/31349548-f8ca2a26-ad23-11e7-8b73-a6cd21b87f32.png)

![bpython](https://user-images.githubusercontent.com/6810861/31349057-e3ba7e08-ad21-11e7-9b3e-f4f596acd9d8.png)

note that bpython can display docstring and method signature fine in all cases, but anaconda-st3 cannot seem to be able to do so. 
by the way, pygame project builds and runs fine from st3.
maybe i missed some important configuration steps ?
i don't understand why it doesn't work correctly or how should i make it works so. 
(if that's possible at all ?)

## ST3, Anaconda and OS versions
os: linux (Ubuntu 17.04)
st3: 3.0 build 3143
anaconda: 2.1.23

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
[anaconda_jsonserver.log](https://github.com/DamnWidget/anaconda/files/1369248/anaconda_jsonserver.log)

* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Compare Anaconda and BPython is like compare apples and oranges, for a start, anaconda relies on Jedi Python Autocompletion library while BPython implements it's own code analyzer, anaconda is based in an asynchronous client - server architecture (with it's delays, timeouts, latency  and problems) while BPython is a monolithic piece of software.

Basically, Anaconda can complete or analyze anything that Jedi can (with your configured anaconda python interpreter) and it doesn't have to match with what BPython or IPythoin or PyCharm can analyze or complete.

**Comment by nsklaus** [comment]
ok then. sorry for the comparison.
so how do i make anaconda to show docstrings and methods signatures in cases highlighted earlier ?

**Comment by nsklaus** [comment]
i've found a workaround as suggested here:
https://github.com/davidhalter/jedi/issues/769

it turns out jedi doesn't seem to support imports made in a try/except block.
until jedi figure this out, the workaround suggested to manually edit pygame's init.py do work. now i do get my popups :)

it's dirty but well, it works. file to edit is here:
`/usr/local/lib/python3.6/dist-packages/pygame/__init__.py`
