### ISSUE TITLE
Support for Sphinx style parameter definitions?

### ISSUE THREAD

**Issue by aaltat** [DamnWidget/anaconda#715]
If have methods that looks like this:
```
def find_xpath(driver, xpath):
    """Returns elements based on xpath

    :param driver: selenium.webdriver.remote.webdriver.WebDriver
    :param xpath: Xpath to use when searching the element.
    :rtype: selenium.webdriver.remote.webelement.WebElement
    """
    return driver.find_element_by_xpath(xpath)
```
It is possible to make `driver` parameter to provide automatic completions based on the Sphinx style doc strings? If it is not, is there some other doc string format which I could use so that completion could work?

**Comment by DamnWidget** [comment]
Anaconda uses Jedi so anaconda supports anything that Jedi supports
https://github.com/davidhalter/jedi/blob/master/docs/docs/features.rst#general-features

**Comment by aaltat** [comment]
I did read the documentation incorrectly, my bad. This works
```
def find_xpath(driver, xpath):
    """Returns elements based on xpath

    :param str foo: Element xpath
    :param driver: Selenium WebDriver
    :type driver: selenium.webdriver.remote.webdriver.WebDriver
    """
    return driver.find_elements_by_xpath(xpath)
```
