### ISSUE TITLE
Undefined name 'FileNotFoundError'

### ISSUE THREAD

**Issue by conformist-mw** [DamnWidget/anaconda#716]
## Expected Behaviour
Do not show lint error on built-in exception
## Actual Behaviour
Undefined name 'FileNotFoundError'
## Steps to Reproduce
Just install anaconda
## ST3, Anaconda and OS versions
Anaconda 2.1.23, Debian Buster
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
You have to configure a Python3 interpreter

**Comment by conformist-mw** [comment]
Sorry, I didn't understand you answer. Did you mean a build system? It's already python3.

**Comment by DamnWidget** [comment]
http://damnwidget.github.io/anaconda/anaconda_settings/

**Comment by conformist-mw** [comment]
My bad. Now it works perfect. Thank you :)
