### ISSUE TITLE
get_settings constantly querying anaconda_linting_behaviour and anaconda_linter_delay

### ISSUE THREAD

**Issue by hyperknot** [DamnWidget/anaconda#718]
I have no idea if this is normal, but it might cause some unnecessary battery usage as it just does this infinite loop the background.

## Steps to Reproduce
Put `print('get_settings', name, default)` inside `helpers.py/get_settings()`

## Expected Behaviour
Every settings should be queried at start.

## Actual Behaviour
The following 2 settings are queried continuously: anaconda_linter_delay and anaconda_linting_behaviour.

About every second or a bit more frequent I'm getting the following 2 lines:
```
get_settings anaconda_linter_delay 0.5
get_settings  anaconda_linting_behaviour None
```

## ST3, Anaconda and OS versions
ST: 3143, Anaconda: GitHub master, OS: OS X 10.12.6

## ST3 Console Logs
Usual

## Anaconda's JsonServer Logs
```
2017-10-27 00:33:20,547: DEBUG   : bind: address=('localhost', 54160)
2017-10-27 00:33:20,547: DEBUG   : listen: backlog=5
2017-10-27 00:33:20,547: INFO    : Anaconda Server started in 54160 for PID 49230 with cache dir /Users/user/Library/Caches/Jedi/anaconda-3
2017-10-27 00:33:20,621: INFO    : Incomming connection from ('127.0.0.1', 54168)
2017-10-27 00:33:20,621: INFO    : Incomming connection from ('127.0.0.1', 54169)
2017-10-27 00:33:20,633: INFO    : client requests: lint
```

**Comment by DamnWidget** [comment]
This is just querying the ST3 settings object (or the `view.settings` object) that is just a custom dictionary so the access should be O(1), I don't really see the problem here.

**Comment by hyperknot** [comment]
OK, if it's not actually reading and decoding the ST settings file on each get_settings then it's indeed quite efficient. So is there some kind of dictionary caching for every settings, except for the environment file?

**Comment by hyperknot** [comment]
I can confirm there is no file activity, only some in-memory lookup.
