### ISSUE TITLE
Test actions not available when the cursor is inside a Python comment

### ISSUE THREAD

**Issue by troeger** [DamnWidget/anaconda#727]
## Expected Behaviour

A right-click in a Python source code file should always offer the 3 testing actions related to the file itself:

  - Run tests on current file
  - Run full project tests
  - Repeat last test run

This should be especially the case when a file is newly opened, and the cursor is in the first line.

## Actual Behaviour

When the cursor is in a multi-line (''' foo bar ''')  or single-line (#) comment field, the options above are grayed out in the right-click context menu. They are also not available in the command palette.

PEP-8 recommends to have a multi-line comment at the beginning of your Python (library) file, so it would be good to have Anaconda-based testing working after opening such a file, without moving the cursor to another place.

## Steps to Reproduce

  - Install ST3 + Anaconda.
  - Open Python file with multi-line comment at the beginning.
  - Perform right-click -> Anaconda

## ST3, Anaconda and OS versions

  - Sublime v3.0, Build 3143
  - Anaconda 2.1.24
  - MacOS 10.13.1

## Anaconda's JsonServer Logs

Monitored, nothing happened in there during the right-click.

**Comment by DamnWidget** [comment]
Fix pending release
