### ISSUE TITLE
When I close Python through Anaconda I get an error

### ISSUE THREAD

**Issue by markgacoka** [DamnWidget/anaconda#730]
Everytime I put the exit() command in cmd to close the python console I get this error:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

What does this mean and how can I fix it?

**Comment by DamnWidget** [comment]
I have no idea what you are speaking about, this project is a plugin for Sublime Text 3 it had noting to do with your interpreter.
