### ISSUE TITLE
autocomplete cache loaded into memory slowly

### ISSUE THREAD

**Issue by llan-ml** [DamnWidget/anaconda#732]
I'm using sublime text 3 with Anaconda on Windows 10.

When I use some large libraries, such as
<pre>
import tensorflow as tf
x = tf.
</pre>
it usually takes several seconds to load something (perhaps cache of jedi) into memory.
![image](https://user-images.githubusercontent.com/22030149/33804690-24fcfac8-dde5-11e7-964c-2acaa0af4447.png)

As we can see, the disk utilization is only about 2.7MB/s, is there any way to load the cache faster?

**Comment by DamnWidget** [comment]
Anything related with caching results for the autocompletion is out of the scope of Anaconda plugin. In fact, that is controlled by Jedi itself. If you have some question about that is much better that you make it in the Jedi Github Project instead.
