### ISSUE TITLE
Why do I need to prees ctrl+alt+r to anaconda_auto_format twice?

### ISSUE THREAD

**Issue by kiddick** [DamnWidget/anaconda#733]
For some reason it doesn't work after 1 press
```
    {
        "command": "anaconda_auto_format", "keys": ["ctrl+alt+r"], "context": [
            {"key": "selector", "operator": "equal", "operand": "source.python"}
        ]
    },
```

**Comment by kiddick** [comment]
Hm, I had `{ "keys": ["ctrl+shift+r"], "command": "anaconda_auto_format" }` in ,y default.sublime keymap previously, but after I've changed it exactly to 
```
    {
        "command": "anaconda_auto_format", "keys": ["ctrl+alt+r"], "context": [
            {"key": "selector", "operator": "equal", "operand": "source.python"}
        ]
    }
```
from Anaconda default it started to be ok. And works now afrer only 1 press.

**Comment by DamnWidget** [comment]
As far as I know it should matter not to which keys do you map the command
