### ISSUE TITLE
Does auto completion works for statements?

### ISSUE THREAD

**Issue by coderchaser** [DamnWidget/anaconda#734]
## Expected Behaviour
Auto completion or prompt for statements.
## Actual Behaviour
It doesn't.
## Steps to Reproduce
First, an object of `numpy.ndarray`: `pts=numpy.array([[10,5],[20,30],[70,20],[50,10]],np.int32)`.Then when I type `pts.`,there should be some methods of `ndarray` like `reshape` or `resize`, but it doesn't.
## ST3, Anaconda and OS versions
ST3 Build 3143
Anaconda Latest Version
OS Ubuntu 14.04
## Anaconda's JsonServer Logs
[anaconda_jsonserver.log](https://github.com/DamnWidget/anaconda/files/1559866/anaconda_jsonserver.log)

Thank you@DamnWidget

**Comment by DamnWidget** [comment]
I thought I answered this ticket, seems like I did not. 
Jedi is known to have problems parsing/completing Numpy that is probably the cause.

By the way, `pts.` is not an statement, what you meant with `statements`?

**Comment by coderchaser** [comment]
Very glad to have your reply, sir.Maybe It's inaccurate to say "statements".
What I really mean is that when I create an instance of an object class,like `pts=numpy.array([[10,5],[20,30],[70,20]`,could I access the instance's method with a dot `.`?
 For example, a ndarray object has methods like `reshape`,`resize` and so on.When I type `pts.`, I want anaconda to pop the possible methods, statements or constants for me to choose. But it failed. Moreover, I find it really takes seconds for Anaconda to pop potential methods, classes or else of a module at the first time in a single py file. When it gets over at the first time, it will be really good at the second time,the third time....... So I want to ask how to improve the speed of anaconda's first trying to pop? My english is not very good,so if you are still confused ,I will upload a GIF.I will test other modules, when I have time, I will upload more details. I will close this issue on proper time.
By the way, Thank you again for your reply.I love Anaconda, it's such a nice plugin.In fact ,I am learning ROS, which doesn't have an IDE.So I use ST3+Anaconda to build something like that, though there is still some problems.
