### ISSUE TITLE
Linter marks Python3's f-strings as invalid

### ISSUE THREAD

**Issue by jwhite007** [DamnWidget/anaconda#737]
Python3 f-strings: https://docs.python.org/3/reference/lexical_analysis.html#f-strings

## Expected Behaviour
To not mark f-strings as invalid syntax

## Actual Behaviour
Marks f-strings as invalid syntax

## Steps to Reproduce
my_name = 'james'
print(f'my name is {my_name}')

## ST3, Anaconda and OS versions
ST3: Build 3126
Anaconda: 2.1.25
OS: Windows 7

## ST3 Console Logs
NA

## Anaconda's JsonServer Logs
NA

**Comment by jwhite007** [comment]
Addendum...

It turns out that the Python3 that I have installed on my system is 3.5. This is the python to which I point Anaconda. This may be the issue. f-strings were not introduced until 3.6. Is Anaconda's linter smart enough to do dot-version-specific linting? I will install 3.6 and try again.

Cheers

**Comment by DamnWidget** [comment]
Please, refer to this https://github.com/DamnWidget/anaconda/issues/631

**Comment by jwhite007** [comment]
@DamnWidget 

I apologize for the redundant issue post. I was sure that I searched both open and closed issues for this.

**Comment by DamnWidget** [comment]
No worries.
