### ISSUE TITLE
Feature Request: Settings for linter mark color

### ISSUE THREAD

**Issue by Igonato** [DamnWidget/anaconda#740]
The default white linter errors are a little bit too bright for my eyes. I wish there was an easy way to tone it down a little.

Also, It would be nice if it could be changed to red to match SublimeLinter default style.

**Comment by DamnWidget** [comment]
You can find information about how to personalize the linting options on the wiki and in the documentation web site ( you can find the link to the documentation in the very top of the GitHub project home page ).

**Comment by Igonato** [comment]
Sorry, missed it. Seems good enough. Thanks.
