### ISSUE TITLE
Syntax Error for python3.6 formatted string

### ISSUE THREAD

**Issue by MayukhSobo** [DamnWidget/anaconda#741]
For the following code, it is showing syntax error. It seems that it can not recognize the python3.6 syntax. I have tried almost everything from activating the virtualenv to launching the sublime from python 3.6 environment. But nothing worked. Please help

```python
self.cursor.execute(f"DESC {table};")
```

**Comment by DamnWidget** [comment]
This is before defining table:
![selection_003](https://user-images.githubusercontent.com/329766/35508461-4fdfdd26-04e8-11e8-865a-a85a309f5902.png)

This is after defining table:
![selection_004](https://user-images.githubusercontent.com/329766/35508484-6e2ff860-04e8-11e8-868a-afc35e1d685b.png)

Probably you did not configured your anaconda's python interpreter right, refer to http://damnwidget.github.io/anaconda/anaconda_settings/

**Comment by MayukhSobo** [comment]
@DamnWidget Could you be a little bit more specific. Because I don't want to make any project based or virtualenv based configuration. I need to make changes in global settings. When I added 

```json
"python_interpreter": "stackless_python3",
 "auto_python_builder_enabled": false,
```

It gave me an error during startup.

**Comment by diek** [comment]
I am on mac, I had to add the following to my anaconda user preferences
`{
  "python_interpreter": "/usr/local/bin/python3.6",
}`

**Comment by MalikRumi** [comment]
![screenshot from 2018-07-22 07-12-03](https://user-images.githubusercontent.com/5474426/43046517-ac8dd770-8d7e-11e8-9bb2-b6a2867d0c77.png)
The correct project settings do not solve this issue.

**Comment by MalikRumi** [comment]
The f string works, but obviously there is still the syntax error. I believe the problem is that your bundled version of pyflakes is 1.3.0. Checking package control says no updates are available. But Pyflakes is now on 2.0.0, and dealt with this issue a year ago. https://gitlab.com/pycqa/flake8/issues/296

**Comment by diazgilberto** [comment]
I had the same issue and I had to move the `"python_interpreter": path` from the `project.sublime-project` to the `Packages/User/Anaconda.sublime-settings` and then the error went away.
--
