### ISSUE TITLE
Anaconda (Jedi) thinks staticmethod == classmethod?

### ISSUE THREAD

**Issue by karolyi** [DamnWidget/anaconda#742]
## Expected Behaviour
When I write a method decorated with `staticmethod`, I expect the completion not to think that the first parameter is the class itself. That applies to `classmethod`, not `staticmethod`.

## Actual Behaviour
![image](https://user-images.githubusercontent.com/987055/36000631-dc6bcffa-0d23-11e8-9a52-81cb9433d63c.png)

## Steps to Reproduce
```python
class A(object):

    @staticmethod
    def test(x: int):
        x
```
## ST3, Anaconda and OS versions
Latest ST3dev, latest anaconda, linux ubuntu 17.10
## ST3 Console Logs
irrelevant

## Anaconda's JsonServer Logs
```
2018-02-08 23:02:21,748: INFO    : client requests: autocomplete
2018-02-08 23:02:22,658: INFO    : client requests: lint
```

**Comment by aymazon** [comment]
Link this:
https://github.com/davidhalter/jedi/issues/735#issuecomment-228654032

This is a bug.
