### ISSUE TITLE
Setting python_interpreter gets ignored

### ISSUE THREAD

**Issue by cloudtales** [DamnWidget/anaconda#745]
## Expected Behaviour
Project Configuration File:
[...]
"settings": {
		"python_interpreter": "$VIRTUAL_ENV/bin/python"
	}
"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"/bin/python\" -u \"$file\""
		}
	],
[...]
shell_cmd is not set to the value of python_interpreter. 

## Actual Behaviour
shell_cmd is always set to /bin/python. When I manually change the shell_cmd it is reset to "/bin/python" instead of the value of python_interpreter.

## Steps to Reproduce
Fresh Installation of ST3 + Anaconda via Package Control

## ST3, Anaconda and OS versions

ST3 - Version 3.0 Build 3143
Anaconda - Latest
OS = maOS 10.12.6

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
Use the absolute path to your `$VIRTUAL_ENV` instead of the shell variable.

**Comment by cloudtales** [comment]
@DamnWidget Thanks. Worked. But I had to delete the shell_cmd line to force re-creation. Why does $VIRTUAL_ENV not work? I started sublime via a shell where this var is set correctly (workon). 

Documentation: http://damnwidget.github.io/anaconda/anaconda_settings/#overriding-details-per-project

**Comment by DamnWidget** [comment]
Currently anaconda does not expand environment variables from your shell, just from Sublime project vars, this is something that I would like to change in the future when I can take the development of the pluign back as I have a very limited spare time on my hands since a while now.
