### ISSUE TITLE
what about golconda?

### ISSUE THREAD

**Issue by loricheung** [DamnWidget/anaconda#755]
Hi, I noticed that your golconda project has been removed from github, what happend ? Will it be reopend?

**Comment by DamnWidget** [comment]
Hi, no it has not, it is just marked as `private` while I am happy with the code quality. I've been working these days in the ST3 library https://github.com/DamnWidget/libconda and I am about to start the ST3 plugin that will render this one obsolete.

Sadly I don't have all the time that I would like I am very busy during the week and very tired during weekends but I will get there eventually.

Thanks for asking btw.
