### ISSUE TITLE
Autocomplete takes minutes to complete Scipy completions

### ISSUE THREAD

**Issue by amccaugh** [DamnWidget/anaconda#758]
When I try to perform an autocomplete on a scipy (or numpy) package, it ends up taking minutes to finish the autocomplete, and maxes out one of the cores of my CPU during this time. While it is working, all other autocomplete/docstring functionality stops working.  This only happens on my windows machines (two of them, both with Anaconda.org's Python 3.6.3 installed), it has not happened on my macbook (same configuration, Anaconda.org's Python 3.6.3).

## Steps to Reproduce

Typing the following very quickly autocompletes with the correct struct.pack() completion
```
import struct
struct.pa # ---> completes to struct.pack()
```
However, doing the same thing with scipy causes a huge delay (>2 minutes) and generates an enormous log file (>10,000 lines). 
```
import scipy.io
scipy.io.save  # ---> should complete to scipy.io.savemat() eventually
```

At this point, autocomplete/docstrings stop working completely until it's finished cranking on my CPU/hard drive.

The output from the jsonserver.py appears to create a huge number of dbg lines that look like this:
```
 dbg: eval_trailer: PythonNode(trailer, [<Operator: . start=(494, 25)>, <Name: __decimal_context__@494,26>]) in scope <CompiledObject: 'jedi.parser.token'>
  dbg: finder.filter_name "'__decimal_context__'" in (<CompiledObject: 'jedi.parser.token'>): []@None
  dbg: finder._names_to_types: [] -> set()
 dbg: eval_trailer: PythonNode(trailer, [<Operator: . start=(494, 25)>, <Name: __decimal_context__@494,26>]) in scope <CompiledObject: 'numpy.polynomial.hermite'>
  dbg: finder.filter_name "'__decimal_context__'" in (<CompiledObject: 'numpy.polynomial.hermite'>): []@None
  dbg: finder._names_to_types: [] -> set()
```

## ST3, Anaconda and OS versions

- SublimeText 3143
- Windows 7 x64
- Anaconda freshly installed today

## Anaconda's JsonServer Logs

Note this is the result of me logging everything from the python output to the log file with the command after performing the struct and scipy autocompletes as described above

`python -B jsonserver.py -p test 9999 DEBUG > scipy_log_file.log`

jsonserver log output file:  [scipy_log_file.zip](https://github.com/DamnWidget/anaconda/files/1908321/scipy_log_file.zip)

The actual anaconda_jsonserver.log isn't very interesting, while the autocomplete churns my CPU it just hangs at `INFO    : client requests: autocomplete` until the whole process is over, at which point it generates a `INFO    : About push back to ST3: b'{"success": true,` statement

**Comment by DamnWidget** [comment]
Hi, that looks like a Jedi problem, probably @davidhalter can give you more insights that I do

**Comment by davidhalter** [comment]
@DamnWidget Why do you have the debug mode activated?

**Comment by DamnWidget** [comment]
I don't, it gets activated when anaconda's DEBUG mode is enabled

**Comment by davidhalter** [comment]
@amccaugh It's probably still going to take a minute but how long does it take without anacondas DEBUG mode?

**Comment by amccaugh** [comment]
@davidhalter  @DamnWidget It appears that you're correct, disabling the DEBUG mode in anaconda reduces the amount of time numpy/scipy takes to load from a few minutes, down to a few seconds.  I had enabled debug mode for another reason and must have not realized that was what was slowing down the autocomplete so much.  Thanks for helping me clear this up
