### ISSUE TITLE
'conda list', 'conda --version', and 'conda install' do not work.

### ISSUE THREAD

**Issue by IvyGongoogle** [DamnWidget/anaconda#759]
hello, I get a troublesome problem. 
My `pip` and `python` of `xxx/local/anacoda2/bin`all works, but `conda` does not still work which let me crazy. 
can you give some advises? thank you very much~

**Comment by DamnWidget** [comment]
You can try to open this issue in the Anaconda Python distribution project and not in the Anaconda Sublime Text 3 plugin (that is this repo).
Just follow this link: https://github.com/conda/conda
