### ISSUE TITLE
Jedi used in Anaconda is outdated

### ISSUE THREAD

**Issue by DoctorAnonymous** [DamnWidget/anaconda#760]
## Expected Behaviour
Python Modules are updating and some of them are too large for old Jedi to auto-complete. 

## Actual Behaviour
Auto-complete is really slow in old version of Jedi, which is used in Anaconda. For example, tensorflow and PyOpenGL don't even response. 

## Steps to Reproduce
Just 'import tensorflow as tf; tf.', and Anaconda just show no auto-complete. (The actual situation might be different because of computer performance.)

## ST3, Anaconda and OS versions
ST3 3143
Mac OSX

My solution is to install the up-to-date Jedi via pip and delete the Jedi in Anaconda/anaconda_lib. Then  I change the 'definition.doc' to 'definition.docstring()' in Anaconda/anaconda_server/commands/doc.py because Jedi changes its api. Now Anaconda works better on my computer.

First time to report an issue. Sorry if I make any trouble :)

**Comment by DamnWidget** [comment]
There are many changes in Jedi API, update to `>=0.12.0` requires rewriting of some features and tests

**Comment by DamnWidget** [comment]
Please, give a try to the branch `jedi_0_12` if there are no major issues (all the tests are passing in several Python versions so far) I will make an update.

**Comment by DamnWidget** [comment]
Jedi has been updated to 0.12 in abaconda v2.1.27
