### ISSUE TITLE
 Why Anaconda\Scripts\pip-script.py is not present ？

### ISSUE THREAD

**Issue by NatsuSir** [DamnWidget/anaconda#762]
(base) C：\Users\***\pip install pip-10.0.1- py2.py3-none-any.whl

 Script file 'F:\Anacoda\Scripts\pip - script' is not present

**Comment by DamnWidget** [comment]
Being honest, I have no clue but that is expected as this project has no relation with the anaconda python distribution from continuum .

You can try to ask that same question in the right project: https://github.com/ContinuumIO/anaconda-issues

They will probably not be clueless about what you are asking in there.

**Comment by NatsuSir** [comment]
It has been solved ,thank you~

**Comment by smit271198** [comment]
I have same problem that pip-script.py is missing and due to that i can't able to download other important packages. So NatsuSir how you solved that error? Thanking You in advance...

**Comment by Arc-424** [comment]
fuckoff you

**Comment by larissavm** [comment]
This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"

**Comment by 17sergiodominguez** [comment]
Thank you very much

**Comment by maliktalha370** [comment]
Try to update Anaconda navigator (GUI) or other wise open Anaconda navigator, open you desired environment. Uninstall PIP package and reinstall again from there

**Comment by Hasitha-Sue** [comment]
> This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"

Thank you . It was helpful

**Comment by Josh1punch** [comment]
easy-install fixed it! tks

**Comment by zeintiz** [comment]
> This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"
tanks so much. it was very helpful. in addition i got an warning during installation:
WARNING: The easy_install command is deprecated and will be removed in a future version.

**Comment by syamalapadala** [comment]
> This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"

Thank you so much, It helped.

**Comment by anthonyweidai** [comment]
> This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"

Work like charm!

**Comment by Ayusummer** [comment]
Install `CMD.exe Prompt` in `Anaconda Navigator - Home` and run `conda update conda` then `conda update pip` also make sense
PS : `WARNING: Ignoring invalid distribution -ip (.....\anaconda\lib\site-packages)` can be solved by remove folders in `site-packages` with prefix `_` and `~`

**Comment by X-AVI-X** [comment]
Still showing that script file "link" not present

> This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"

**Comment by DinaTaklit** [comment]
For me I got this issue once I try to install packages using  `pip install -r requirements` within anaconda env. [Here is the detail of the issue I get](https://stackoverflow.com/questions/69895208/python-conda-error-could-not-install-packages-due-to-an-oserror-winerror-5) and the only thing that worked for me was `python -m ensurepip --default-pip` after that I have been able to instal requirements.

**Comment by huzhishan** [comment]
> For me I got this issue once I try to install packages using `pip install -r requirements` within anaconda env. [Here is the detail of the issue I get](https://stackoverflow.com/questions/69895208/python-conda-error-could-not-install-packages-due-to-an-oserror-winerror-5) and the only thing that worked for me was `python -m ensurepip --default-pip` after that I have been able to instal requirements.

Don't know why, but it works for me! Thanks!

**Comment by vii33** [comment]
`easy_install pip` is not recognized as a command in Powershell.

You can force conda to to reinstall pip with: `conda install --force-reinstall pip`   (worked for me at least)

**Comment by mxshen** [comment]
> `easy_install pip` is not recognized as a command in Powershell.
> 
> You can force conda to to reinstall pip with: `conda install --force-reinstall pip` (worked for me at least)

Worked for me as well, thank you!

**Comment by RafayAkram1** [comment]
It worked for me ... Thank you

**Comment by jpainam** [comment]
> This occurs when broken pip. The broken pip caused by the failed upgrade can be fixed by running: "easy_install pip"

Those looking for `get-pip.py`, here it's [get-pip](https://bootstrap.pypa.io/get-pip.py). Download and run `python get-pip.py`
