### ISSUE TITLE
How to specify the pylint path ?

### ISSUE THREAD

**Issue by toplinuxsir** [DamnWidget/anaconda#763]
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment]
You can't specify the pylint path, anaconda just uses the `pylint` executable that is in your environment PATH
