### ISSUE TITLE
Error Message from start

### ISSUE THREAD

**Issue by Guito1986** [DamnWidget/anaconda#766]
To just work... I don't know I am a beginner...

Everytime that I use Sublime for Python it shows an error message:

<Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x111a37550> initial check failed because:

can not connect to localhost in port 59149. tried to connect 21 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 59149))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.

Idem.

I don't understand what I am suppose to do...

ST3 : 3.1.1 Build 3176 - OS X High Sierra 10.13.4 - Anaconda v2.1.26

See above

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:

* OS X: ~/Library/Logs/anaconda I don't find nothing... there is no anaconda in Logs

Thank You

**Comment by Guito1986** [comment]
Could you explain to me all this like I am a retard or a child... Thank You

**Comment by DamnWidget** [comment]
As the error says, if anaconda works well for you, set the `swallow_startup_errors` to `true` so you will not be bothered about this on startup. If your anaconda installation does not work, come back and give us more details about what does not works.
