### ISSUE TITLE
Version 2.1.27 breaks Goto Definition

### ISSUE THREAD

**Issue by asfaltboy** [DamnWidget/anaconda#771]
## Expected Behaviour

In version 2.1.26, clicking "Anaconda -> Goto Definition" works well.

## Actual Behaviour

After upgrading to 2.1.27 "Goto definition" stops working for external packages (those in `venv/site-packages` dir) and the error "Unable to find <item clicked>" is displayed.

FYI: Navigating packages and modules in the project dir works well on 2.1.27.

Downgrade to 2.1.26 to make goto definition for venv packages work again.

## Steps to Reproduce

Upgrade to 2.1.27

## ST3, Anaconda and OS versions

- ST3 3.1.1 build 3176
- Anaconda 2.1.27
- MacOS 10.13.5 (17F77)

## ST3 Console Logs & Anaconda's JsonServer Logs

https://gist.github.com/b0f445adf1b318b7407a3e1b9763b050

The project settings define:

    "settings":
    {
        "python_interpreter": "/Users/pavel.savchenko/.virtualenvs/my_project/bin/python3"
    }

where python3 is version 3.6.4

**Comment by bdjurkan** [comment]
Same issue.

**Comment by DamnWidget** [comment]
Same comment, it works for me, if you don't give more information, like for example which modules are you trying to go to, which version of python are you using, which OS etc is nothing that I can do

**Comment by bdjurkan** [comment]
Sorry DamnWidget.
Goto Definition on Django modules.
ST3 build 3175
Anaconda 2.1.27
Debian 9.4 (stretch)
I use pynev for virtualenv.

.sublime-project:
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"/home/boris/.pyenv/versions/django-dev/bin/python\" -u \"$file\""
		}
	],
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "/home/boris/Programming/Python/Django-Projects/trydjango2-0"
		}
	],
	"settings":
	{
		"SublimeLinter.linters.htmlhint.disable": true,
		"anaconda_linting_behaviour": "always",
		"pep257": false,
		"python_interpreter": "/home/boris/.pyenv/versions/django-dev/bin/python",
		"test_command": "python -m unittest discover",
		"use_pylint": false,
		"validate_imports": false
	}
}

**Comment by asfaltboy** [comment]
Soz for the delay, was out with kid. I'm using python 3.6 and goto doesn't work to anything in the environment that is outside of current project dir (i.e in site-packages of the virtual environment).
Forgot to note that goto to local packages (in project dir) works fine.
Does goto work fine for you when using virtual environment? How do you define the interpreter to use? I use the project setting to point to the python3 binary in my venv.
OS and other details are mentioned in the ticket.

**Comment by bdjurkan** [comment]
Goto to local packages (in project dir) works fine for me too, but it does not work to
packages in virtual environment. It worked before.

**Comment by DamnWidget** [comment]
I just rollback to v2.1.26 in latest version, there is a branch `jedi_0_12` that can be test by anyone that has time and want to do it

**Comment by asfaltboy** [comment]
Just looking at the changelog of Jedi, it seems release [_0.12.1 (2018-06-30)_][2] mentions that using `parso < 0.3` is going to break everything (?) and the `jedi_0_12` branch is using [version 0.2.1][1]

[1]: https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0121-2018-06-30
[2]: https://github.com/DamnWidget/anaconda/blob/jedi_0_12/anaconda_lib/parso/__init__.py#L46

**Comment by vypr** [comment]
A solution seems to install SublimeJEDI alongside Anaconda for the proper autocomplete functions. All you have to do is just configure the project for your virtualenv and interpreter.
