### ISSUE TITLE
Add --ignore-missing-imports mypy setting

### ISSUE THREAD

**Issue by gregdingle** [DamnWidget/anaconda#775]
This would be useful for ignoring imports that do not support typing. 

See http://mypy.readthedocs.io/en/latest/command_line.html#follow-imports

See https://github.com/DamnWidget/anaconda/blob/423091102d3cbd500fb34d66da3632d0f7725844/anaconda_lib/linting/sublime.py#L390

**Comment by DamnWidget** [comment]
This should be solved via PR
