### ISSUE TITLE
Lint error list assumes all Mypy errors are in the current file

### ISSUE THREAD

**Issue by gregdingle** [DamnWidget/anaconda#786]
## Expected Behaviour

1) Show only errors in the current file
or
2) Show filename in error list and jump to other file on enter

## Actual Behaviour

All mypy errors in all files are shown in one list 

![image](https://user-images.githubusercontent.com/28797/45235597-3f2fd680-b28e-11e8-8121-675ef0690dd9.png)

## Steps to Reproduce

1. Create a type error in one file
2. Import that module into another file
3. Anaconda lint in second file
4. See error in first file shown as if it exists in second file

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by scuml** [comment]
@DamnWidget This was resolved.  Can close.
