### ISSUE TITLE
My code is marked up with breakpoints?  and boxes after running pdb

### ISSUE THREAD

**Issue by nyck33** [DamnWidget/anaconda#802]
## ST3 Console Logs 

DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /G/Comp Sci/_DeepLearning/openAI/Keras DQN/reinforcement-learning
packages path: /C/Users/nobut/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/nobut/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/nobut/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.70476
startup time: 0.77476
first paint time: 0.77876
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-flake8.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2019-01-22 17:44:38, next run at 2019-01-22 18:44:38 or after
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x00000218C9F027B8> initial check failed because:

connection to localhost:49960 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 49960))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
error: <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x00000218C9F027B8> initial check failed because:

connection to localhost:49960 timed out after 0.2s. tried to connect 7 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 49960))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
SublimeLinter: WARNING: cannot locate 'flake8'. Fill in the 'python' or 'executable' setting.

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs  

Could not find this

**Comment by nyck33** [comment]
I tried this:  import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 49960))

In the console now I have showing:

>>> import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 49960))

I think this is above my paygrade.  Is there a simple way to uninstall this so I can get my old ST3 back?

**Comment by nyck33** [comment]
Here's a screenshot:  https://i.stack.imgur.com/bWWfd.png

**Comment by nyck33** [comment]
I was able to disable it in settings:

"anaconda_gutter_marks": false,

**Comment by nyck33** [comment]
But I'd like to learn more about how to use in conjunction with pdb so I can see the debugger going through the code line by line.

**Comment by DamnWidget** [comment]
Hi, Anaconda does not integrates with PDB at any level, those boxes where just regular linting warnings from the PEP8 linter.

**Comment by nyck33** [comment]
I've done that but as mentioned this is all above my paygrade so just installed Pycharm and getting a kick of stepping through my code :)

**Comment by DamnWidget** [comment]
Good :+1:
