### ISSUE TITLE
Left point on line numbers

### ISSUE THREAD

**Issue by mesaglio** [DamnWidget/anaconda#806]
Someone help me, this marks appear on all me code.
<img width="1050" alt="captura de pantalla 2019-03-01 a la s 19 41 45" src="https://user-images.githubusercontent.com/29051129/53670715-632b0e00-3c5a-11e9-920a-d7560af6f364.png">

**Comment by DamnWidget** [comment]
That is the linter, if you don't want the linter to analyze your code disable it setting `anaconda_linting` to `false` on your anaconda settings.

**Comment by mesaglio** [comment]
Thanks!
