### ISSUE TITLE
Anaconda with mypy enabled shows mypy errors from all buffers in active buffer.

### ISSUE THREAD

**Issue by DDR0** [DamnWidget/anaconda#809]
## Expected Behaviour
Mypy errors show up on the file they occurred in.

## Actual Behaviour
When mypy alerts about an error in another file, I see an error at the line:column in the current file. For example, in the following screenshot, I do not expect an invalid type error to be marked on line 68 in my current file. There is, however, a reasonable candidate line 68 containing "builtins.callable" in another file.
![Screenshot_20190325_221001](https://user-images.githubusercontent.com/862627/54972892-d4549d00-4f4a-11e9-89c7-a40a5ce6ae61.png)
This only applies to .py files, other files which are not linted at all do not get the extra annotations.

## Steps to Reproduce
Enable mypy and set up project-specific imports. (I know I've specified the import folders in the wrong place, but it'll hold for now. Adding an __init__.py file had the same effect, imports are found and mis-reported.)
Anaconda.sublime-settings:
```json
{
	"python_interpreter": "python3",
	"mypy": true,
	"mypy_mypypath": "/home/david/Documents/Krontech/chronos-gui-2/src:/home/david/Documents/Krontech/chronos-web-interface/src",
	"«and a bunch of pep-8 ignores»"
```

## ST3, Anaconda and OS versions
ST3: 3200
Anaconda: 2.1.29
OS: Ubuntu 18.10

## ST3 Console Logs
[st3log.txt](https://github.com/DamnWidget/anaconda/files/3006631/st3log.txt)

## Anaconda's JsonServer Logs
[logs.zip](https://github.com/DamnWidget/anaconda/files/3006636/logs.zip)

As a side note, thanks for the program. It's great. :)

**Comment by wojwarych** [comment]
Hi,
After a recent fix I was finally able to use built-in MyPy integration of Anaconda instead of looking for other plugins to ST3.
However, I've stumbled upon the same issue as @DDR0
The problem seems to me to be that subprocess for MyPy check for specific file was called by its absolute path and CWD was set as the one where the subprocess is called (i.e. `anaconda_mypy.py` in `linting` directory).
It is somehow related to how MyPy is making code check, I believe - it will check errors in all files in directory tree to the file that you set to check.
For reference corresponding snippet of code in:
https://github.com/DamnWidget/anaconda/blob/4a748e7ded64a275b621d00e9f03814a49a7ea6d/anaconda_lib/linting/anaconda_mypy.py#L84-L103

I've managed to get errors only in specific files by getting only file name from `self.filename` with `split('\\')[-1]` in `shlex.split()` call and changing value of `cwd` in `kwargs` to the absolute path to `self.filename`

@DamnWidget I'll be glad if you could relate to this issue.
Also, I'm willing to help in fixing this issue in any case.

## ST3, Anaconda and OS versions
ST3: 3211
Anaconda: 2.1.35
OS: Windows 10

**Comment by DamnWidget** [comment]
If you are able to provide a proven PR for this I will be more than happy to review and merge it.

**Comment by kojiromike** [comment]
Is this the same issue as #786 ?

**Comment by wojwarych** [comment]
Yes, looks similar. I haven't done any PR yet - lack of time. :( And also, I found one edge case where my "hotfix" doesn't work properly.

**Comment by ZackSheffieldSEL** [comment]
It appears that mypy prefaces each error with the filename that was passed in to the Popen argument. Even when I give it that path to a \_\_main\_\_.py in my code base, it still parses other files besides that one... For example, given this command,

```mypy     --no-error-summary --hide-error-context --disallow-untyped-calls --disallow-untyped-defs --check-untyped-defs --incremental beamparse\beamparse\__main__.py```

I get the following output:

```
beamparse\beamparse\log.py:7: error: Skipping analyzing 'appdirs': found module but no type hints or library stubs
beamparse\beamparse\config.py:14: error: Skipping analyzing 'tqdm': found module but no type hints or library stubs
beamparse\beamparse\config.py:15: error: Skipping analyzing 'appdirs': found module but no type hints or library stubs
beamparse\beamparse\utils.py:48: error: "ResultParser" has no attribute "valid"
beamparse\beamparse\utils.py:49: error: "int" not callable
beamparse\beamparse\utils.py:52: error: "ResultParser" has no attribute "valid"
beamparse\beamparse\utils.py:57: error: "Tuple[Event, ...]" not callable
beamparse\beamparse\__main__.py:9: error: Skipping analyzing 'appdirs': found module but no type hints or library stubs
beamparse\beamparse\__main__.py:9: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
beamparse\beamparse\__main__.py:118: error: Too few arguments for "get_serial_numbers"
beamparse\beamparse\__main__.py:189: error: Module has no attribute "getch"
beamparse\beamparse\__main__.py:252: error: Argument 4 to "validate" has incompatible type "*Tuple[Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[str], None]]]"; expected "bool"
beamparse\beamparse\__main__.py:252: error: Argument 4 to "validate" has incompatible type "*Tuple[Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[str], None]]]"; expected "Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]]"
```

Notice that only the last 6 of all the mypy errors reported pertain to __main__.py. It appears that Anaconda assumes that all mypy output is pertinent to the file it's linting, which is not the case, given the output above. 

https://github.com/DamnWidget/anaconda/blob/e72ab5f095e5c061c900a37861c38add23b89ee1/anaconda_lib/linting/anaconda_mypy.py#L102-L134

So I inserted the following after lines 116 of anaconda_mypy.py:

```python
            if not line.startswith(self.filename):
                continue
```

It skips those files that are not pertinent to the current file and does not include in the in the list of errors returned by Mypy.check_source.

I'd be happy to make the changes and submit a PR but there are no contribution guidelines.

**Comment by scuml** [comment]
I think instead, we want to add "--follow-imports silent" to the parameter list.
https://mypy.readthedocs.io/en/stable/running_mypy.html#follow-imports

@ZackSheffieldSEL Could you run 
```mypy --no-error-summary --hide-error-context --disallow-untyped-calls --disallow-untyped-defs --check-untyped-defs --incremental beamparse\beamparse\__main__.py```

...and see if that gives the output you'd expect?

**Comment by ZackSheffieldSEL** [comment]
```
beamparse\beamparse\__main__.py:9: error: Skipping analyzing 'appdirs': found module but no type hints or library stubs
beamparse\beamparse\__main__.py:9: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
beamparse\beamparse\__main__.py:118: error: Too few arguments for "get_serial_numbers"
beamparse\beamparse\__main__.py:189: error: Module has no attribute "getch"
beamparse\beamparse\__main__.py:252: error: Argument 4 to "validate" has incompatible type "*Tuple[Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[str], None]]]"; expected "bool"
beamparse\beamparse\__main__.py:252: error: Argument 4 to "validate" has incompatible type "*Tuple[Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]], Optional[Callable[[str], None]]]"; expected "Optional[Callable[[Mapping[int, Tuple[Path, ...]]], Any]]"
```

Looks like that did the trick!

**Comment by scuml** [comment]
Great.  Thanks for verifying.  That should be slightly more performant.  

You can feel free to copy and paste the code locally until the next release is tagged: https://github.com/DamnWidget/anaconda/pull/858/files

And feel free to fork and submit a PR anytime.

**Comment by wojwarych** [comment]
Hey, that did work for me too! Thanks!
