### ISSUE TITLE
Creating new line after saving, auto_formatting

### ISSUE THREAD

**Issue by b3n35** [DamnWidget/anaconda#813]
Hi.

I want to disable creating new line after saving, but none error can fix my problem.

It works when I disable auto_formatting, but then don't work another things.

I am using package in Sublime Text 3.

**Comment by DamnWidget** [comment]
Which other things does not work if you disable auto formatting? As far as I remember, auto formatting is a pretty isolated feature, it should not have any effect in other stuff.
