### ISSUE TITLE
After installing cuda with anaconda, the nvcc -V command does not work.

### ISSUE THREAD

**Issue by ma3252788** [DamnWidget/anaconda#814]
## Expected Behaviour
if I type: nvcc -V
it should be the correct version 

## Actual Behaviour
No matter what version of cuda I install, using the nvcc -V command will get the same version.
## Steps to Reproduce
1 Install anaconda
2 Create an environment pytorch
3 activation environment
4 install pytorch, conda install pytorch-gpu
5 View the cuda version using the nvcc -V command
6 change the cuda version, conda install cudatoolkit=9.2
No matter how I change the cuda version, when I use nvcc -V, the display is 9.0

## ST3, Anaconda and OS versions
4.5.4
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
It's empty.
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by ma3252788** [comment]
Like this picture, after I installed cuda, I used nvcc -V and I didn't get anything.
![](http://filessl.machunjie.com/blog/file/20190422144116.png)

**Comment by DamnWidget** [comment]
I think you are looking for this other project https://github.com/ContinuumIO/anaconda-issues/issues
