### ISSUE TITLE
Cannot connect to localhost

### ISSUE THREAD

**Issue by carc1n0gen** [DamnWidget/anaconda#820]
I've used anaconda for months no problem, today I restarted sublime, and it just stopped working with the below error message.

## ST3, Anaconda and OS versions

ST3 3.2.1 on macOS 10.14.5

## ST3 Console Logs

```
can not connect to localhost in port 50857. tried to connect 21 times during 2.0 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that you can connect to your localhost writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("localhost", 50857))

If anaconda works just fine after you received this error and the command above worked you can make anaconda to do not show you this error anymore setting the 'swallow_startup_errors' to 'true' in your configuration file.
 ...last message repeated one more time in the last 10s
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x106445250> initial check failed because:
```

## Anaconda's JsonServer Logs
```
2019-06-10 19:25:30,427: ERROR   : Traceback (most recent call last):
  File "/Users/carson/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 338, in <module>
    server = JSONServer(('localhost', port))
  File "/Users/carson/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 157, in __init__
    if address_family == socket.AF_UNIX:
NameError: name 'address_family' is not defined

2019-06-10 19:25:30,427: ERROR   : name 'address_family' is not defined
2019-06-10 19:25:37,367: ERROR   : Traceback (most recent call last):
  File "/Users/carson/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 338, in <module>
    server = JSONServer(('localhost', port))
  File "/Users/carson/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 157, in __init__
    if address_family == socket.AF_UNIX:
NameError: name 'address_family' is not defined

2019-06-10 19:25:37,367: ERROR   : name 'address_family' is not defined
```

**Comment by karolyi** [comment]
f*ck, it's my bad... I'll fix it in a minute, will need a new release.

@DamnWidget if you could add me as a maintainer, I would be happy to contribute to taking care of this package. I use it on a day-to-day basis.

**Comment by adudek16** [comment]
+1
Whew. I was panicking that I did something wrong

**Comment by carc1n0gen** [comment]
Glad to see I'm not crazy

**Comment by adudek16** [comment]
I was pulling my hair out. I did make the same change as the commit so I could get back to work in the meantime. The messages haven't come back. I'm glad I decided to look again before making things even worse. :)

**Comment by DamnWidget** [comment]
I just gave you full access @karolyi 

Remember that you have to add the new release (that will be `2.1.32` to the `messages/2.1.32.txt` and reference it on `messages.json`. Also create a new release on Github if you can. 

You know my email, contact me with whatever you need and thanks you for stepping up to take care of this 👍

**Comment by bizoo** [comment]
Still crash in Windows.
`socket.AF_UNIX` doesn't exists on Windows, removing these lines fix the issue.

**Comment by qocu** [comment]
Anaconda version 2.1.31 ( I think ) 
on line 157 of `jsonserver.py` 

change to 

`if self.address_family == socket.AF_UNIX:`

does the work

**Comment by DamnWidget** [comment]
A fix was merged yesterday, for those that use the git repo instead of the Package Control package, just do a pull on master,for those using the Package Control bundle, you should wait till a new release is made, I am currently at work, if @karolyi didn't made the release when I get home I will do it.

**Comment by bizoo** [comment]
> Anaconda version 2.1.31 ( I think )
> on line 157 of `jsonserver.py`
> 
> change to
> 
> `if self.address_family == socket.AF_UNIX:`
> 
> does the work

Already tried but didn't works.
`socket.AF_UNIX` doesn't exists in Windows 10 1803 (I suppose it exists in 1903).
You have to remove them (or add a check before or try/except block).

**Comment by qocu** [comment]
@bizoo right, forgot about Windows

**Comment by bizoo** [comment]
The relevant part of Python 3.7 documentation:
```
socket.AF_UNIX
socket.AF_INET
socket.AF_INET6
```
These constants represent the address (and protocol) families, used for the first argument to socket(). If the AF_UNIX constant is not defined then this protocol is unsupported. More constants may be available depending on the system.

**Comment by karolyi** [comment]
I'll be fixing it in a couple hours, hold on tight guys

**Comment by DamnWidget** [comment]
Do not forget to also add a way to gracefully check that `socket.AF_UNIX`
exists in the `socket` module before try to comparing it, we do not want
old versions of Windows to raise an exception in there.

**Comment by karolyi** [comment]
should be fixed now with the latest release, let me know when it isn't.

**Comment by carc1n0gen** [comment]
Is there an ETA on this getting to package control? I guess I could just clone from git

**Comment by karolyi** [comment]
Good question, I don't know how package control picks up on updates, and I could find no information about it just yet. My hunch is that they run a cronjob-like update checker on the repositories checking for updates, so probably we'll have to wait.

**Comment by carc1n0gen** [comment]
For the time being I just made the same fix to my installed version

**Comment by karolyi** [comment]
It should be rolled out now.

**Comment by ray-man** [comment]
Still facing it, even after the update

**Comment by bizoo** [comment]
Sorry but still doesn't works:
```
2019-06-11 15:35:04,848: ERROR   : Traceback (most recent call last):
  File "C:\Users\rool\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\jsonserver.py", line 338, in <module>
    server = JSONServer(('localhost', port))
  File "C:\Users\rool\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_server\jsonserver.py", line 159, in __init__
    os.chmod(self.address, 0o600)
TypeError: coercing to Unicode: need string or buffer, tuple found
```

**Comment by mj3052** [comment]
I'm having this issue on OS X as well @karolyi 

I was able to fix it by not applying the WSL 1903 fix in case of system being darwin:
```
if platform.system().lower() not in ['linux', 'darwin']:
    # WSL 1903 fix
    os.chmod(self.address, 0o600)
```

**Comment by karolyi** [comment]
@mj3052 just released, hoping to have fixed everything this time.

**Comment by bizoo** [comment]
@karolyi Sorry have no access to my computer.
I'm on ST3 latest dev build and Python 2.7
From the error message in my previous message it looks that it's the self.address value that is not correct for chmod. 
It's a tuple but chmod want something else (string?)

**Comment by DamnWidget** [comment]
For the future, I would suggest to wrap any Windows change under:

```python
if os.name == 'nt':
    # awesome code here
```

Regards.

**Comment by karolyi** [comment]
> For the future, I would suggest to wrap any Windows change under:
> 
> ```python
> if os.name == 'nt':
>     # awesome code here
> ```
> 
> Regards.

Nope... Python in WSL gives 'posix' as `os.name`, mind you it's a linux emulation.

**Comment by DamnWidget** [comment]
I meant in general, not for this specific case :)

**Comment by eliasIBM** [comment]
Spent the first half of today trying to figure out what happened to my computer! Thanks mate!

**Comment by mj3052** [comment]
Seems like the issue went away with the latest release, nice work!
