### ISSUE TITLE
Anaconda is not in "build with" menu

### ISSUE THREAD

**Issue by Dr0bac** [DamnWidget/anaconda#829]
Hi, after sublime text start i get error message:

    <Anaconda.anaconda.lib.workers.local_worker.LocalWorker object at 0x03A7F2B0> initial check failed because: connection to localhost:49175 timed out after 0.2s. tried to connect 7 times during 2.0 seconds.

Checked in task manager, can't see process jsonserver.py

I'm on windows 8.1 and I have portable sublime text latest version, so i guess this is the problem?

sublime text folder and jsonserver.py is in:

    C:\Sublime Text Build 3207\Data\Packages\Anaconda\anaconda_server\jsonserver.py

What can i do?

**Comment by GuokLiu** [comment]
The same in MacOS
