### ISSUE TITLE
E731 ignore not respected

### ISSUE THREAD

**Issue by chrisSCM** [DamnWidget/anaconda#832]
## Expected Behaviour
Do not change a line "x = lambda a: a * 2" to "def x(a): return a * 2" when ignoring E731.
## Actual Behaviour
The line "x = lambda a: a * 2" is changed to "def x(a): return a * 2" when autoformatting with anaconda, using ctrl+alt+r, although E731 is ignored in the anaconda user settings.
## Steps to Reproduce
Create a file with one line:
x = lambda a: a * 2

Change User/Anaconda.sublime-settings to reflect this setting:

    "pep8_ignore":
    [
        "E731"
    ],

Press ctrl+alt+r

I also tried configuring ~/.config/pycodestyle and adding it to the User/Anaconda.sublime-settings like this:

"pep8_rcfile": "/home/xxx/.config/pycodestyle",

I verified that it works by changing the max_line_length setting and watching anaconda respect it.
## ST3, Anaconda and OS versions
ST3: 3.2.1 Build 3207
Anaconda: 2.1.9
OS: Ubuntu 18.04.3 LTS
## ST3 Console Logs
startup, version: 3207 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /
packages path: /home/xxx/.config/sublime-text-3/Packages
state path: /home/xxx/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/xxx/.config/sublime-text-3/Installed Packages
ignored_packages: ["Markdown", "Vintage"]
pre session restore time: 0.166273
startup time: 0.253821
first paint time: 0.285292
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.folding
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.list_back_links
reloading plugin MarkdownEditing.make_page_reference
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.open_home_page
reloading plugin MarkdownEditing.open_journal
reloading plugin MarkdownEditing.open_page
reloading plugin MarkdownEditing.prepare_from_template
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.replace_selected_command
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin MarkdownEditing.wiki_page
reloading plugin Origami.origami
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2019-08-21 14:58:58, next run at 2019-08-21 15:58:58 or after

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

[anaconda_jsonserver.log](https://github.com/DamnWidget/anaconda/files/3525536/anaconda_jsonserver.log)

**Comment by scuml** [comment]
The setting you should use is...
`"autoformat_ignore": ["E731"]`

Works as expected.  Can close issue.

**Comment by DamnWidget** [comment]
@chrisSCM please follow @scuml suggestion above, we would really being using black instead but I don't have any time to spare in adding any new features. Closing this now
