### ISSUE TITLE
autocopmlete still occurs even after adding `"auto_complete": false` to user preferences

### ISSUE THREAD

**Issue by wickedjargon** [DamnWidget/anaconda#836]
when `auto_complete` is set to `false` in `Preferences.sublime-settings` typing `import` in your .py file still displays a auto-complete dropdown.

## Expected Behaviour
for dropdown not to appear when typing `import ...`

## Actual Behaviour
dropdown does appear after typing your second `import...` statement

## Steps to Reproduce
1) put `"auto_complete": false` in your `Preferences.sublime-settings` file
2) with anaconda installed, try importing two modules at in a `.py` file, for example:

```
import random
import math
```
after typing import on the second import statement, a auto-complete dropdown will popup. When Anaconda is disabled, this does not occur.

**Comment by DamnWidget** [comment]
Well, that is weird, as the only thing that can trigger an autocompletion request is Sublime Text itself...

**Comment by wickedjargon** [comment]
Yes. But this can be easily replicated if you try it.

**Comment by DamnWidget** [comment]
Sorry, I could not reproduce this because as I said, the only thing that can trigger auto completions on Sublime Text is Sublime Text itself.

![video](https://user-images.githubusercontent.com/329766/68592928-228fbf80-048c-11ea-8ea6-193519fd1eb4.gif)
