### ISSUE TITLE
No Anaconda: Rename object under cursor in command pallete

### ISSUE THREAD

**Issue by aleksbykov** [DamnWidget/anaconda#837]
## Expected Behaviour
Run anaconda_rename from command pallete. CTRL+ALT+P pressing and search the Anaconda: Rename object under cursor.
## Actual Behaviour
not such anaconda command in command pallete

## Steps to Reproduce
1. press CTRL+ALT+P
2. Type Anaconda: Rename object under cursor
3. < not such command >
## ST3, Anaconda and OS versions
Version 3.2.2 build 3211, Anaconda 2.1.33, Ubuntu 18.04 kernel 5.0

**Comment by DamnWidget** [comment]
Added in latest version

**Comment by aleksbykov** [comment]
Thanks
