### ISSUE TITLE
Erroneous "invalid syntax" when unpacking a list using star operator

### ISSUE THREAD

**Issue by Syncrossus** [DamnWidget/anaconda#840]
Consider the following line of code:

```python
foo, *bar = some_list
```

## Expected Behaviour
Anaconda should recognize this as valid python, equivalent to
``` python
foo = some_list[0]
bar = some_list[1:]
```

## Actual Behaviour
Anaconda triggers an "invalid syntax" lint

## ST3, Anaconda and OS versions
ST version 3.2.2 build 3211
Anaconda version 2.1.34
Running on Kubuntu 18.04

## Anaconda's JsonServer Logs
See on [pastebin](https://pastebin.com/WZxYAtdE)

This may or may not be linked to issue #429 since both have to do with the star (`*`) operator.

**Comment by DamnWidget** [comment]
Make sure you are using a Python3 interpreter as your `python_interpreter` configuration option

**Comment by Syncrossus** [comment]
Sorry, I'm an idiot. I was certain I had done this but evidently not. This fixed it.
