### ISSUE TITLE
Extremely terrible code causes Anaconda to produce false errors

### ISSUE THREAD

**Issue by numbermaniac** [DamnWidget/anaconda#853]
## Expected Behaviour
Valid code should show no errors at the bottom of the screen.
## Actual Behaviour
![Screen Shot 2020-04-24 at 7 02 51 pm](https://user-images.githubusercontent.com/5206120/80196076-2db46180-8660-11ea-82b1-2a54adaca9bc.png)
## Steps to Reproduce
Save the following (very silly) code in a `.py` file:
```py
for i,n in(lambda n:[(i,n)for i in range(n+1)])(int(input("Number? "))):total=(total if n%i else print(i)or(print("Sum of all factors:",total+i)or total if i==n else total+i))if i else 0
```
This is a one-liner I wrote as a joke a while ago that takes a number and prints out all of its factors, then the sum of its factors. It runs without errors in Python 3.
## ST3, Anaconda and OS versions
* ST3: 3.2.2 Build 3211
* OS: macOS 10.14.6
* Anaconda: 2.1.35
## ST3 Console Logs
Nothing noteworthy I can see
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs
Nothing that appears related to the issue here.

**Comment by scuml** [comment]
That's some ... interesting code you have there. 

To help others read it better, here's it broken out.

```python
for i, n in (lambda n: [(i, n) for i in range(n + 1)])(int(input("Number? "))):
    total = (total if n % i else print(i) or (print("Sum of all factors:", total + i) or total if i == n else total + i)) if i else 0
```

This works pasting both lines into a python terminal, but take it out of the for loop 
```python
del(total)
n = 0
i = 1
total = (total if n % i else print(i) or (print("Sum of all factors:", total + i) or total if i == n else total + i)) if i else 0
# NameError: name 'total' is not defined
```

I dunno about this one.  I think an argument could be made that python has the bug letting this run in the first place.

**Comment by DamnWidget** [comment]
Apart from the shadow of sadness that this line of code puts upon my heart I am afraid that there is no solution, closing it for now.
