### ISSUE TITLE
Anaconda thinks the walrus operator is a dict operator

### ISSUE THREAD

**Issue by Dioarya** [DamnWidget/anaconda#855]
## Expected Behaviour
It'd only give errors if there's no spaces on either or both side of the operator, like this:
`foo:=bar`, `foo :=bar`, and `foo:= bar`

## Actual Behaviour
it thinks the walrus operator is a dict operator and throws an error.
and when you reformat it turns `foo := bar` to `foo: = bar`

## Steps to Reproduce
type the walrus operator
`foo := bar`

## ST3, Anaconda and OS versions
ST3: 3.2.2
Anaconda: V2.1.35
Windows 10: 18362.778

**Comment by scuml** [comment]
Please download and try #854 (download from https://github.com/scuml/anaconda/tree/assignment-operator). This should fix this issue, but we are waiting for verification that it works (and doesn't break anything else) on Windows and Linux systems.

**Comment by Dioarya** [comment]
I'm new to github, and how do I download #854?

**Comment by Dioarya** [comment]
How do I download that version of anaconda?

**Comment by Dioarya** [comment]
Where is the Packages folder typically located?

**Comment by Dioarya** [comment]
I downloaded the `anaconda_lib` folder and put it in the `Packages/Anaconda` folder, and it works. Thank you.
