### ISSUE TITLE
Support for Python 3.6 type hints and version of jedi included in the bundle

### ISSUE THREAD

**Issue by jsabater** [DamnWidget/anaconda#860]
Hello everyone!

I am using the latest version of Anaconda on SublimeText 3.2.2 on Ubuntu 18.04, installed through the package manager (I couldn't find the specific version anywhere, to be honest). I checked and it uses Jedi version 0.10.3. At the moment I am having trouble using annotations (type hinting, PEP 484) as they are not recognised (invalid syntax).

I've added the following options in the Anaconda user settings:
```
    "anaconda_linting": false,
    "mypy_py2": false,
    "python_interpreter": "python3"
```

`anaconda_linting` is set to `false` because I am using  Sublime-linting as I set up the environment a couple of years ago based on [this tutorial](https://realpython.com/setting-up-sublime-text-3-for-full-stack-python-development/).

Also in my system, Python 3 (3.6.9) is the default Python. Not sure if that translates inside Anaconda, though.

So I came to realise that the [Jedi](https://github.com/davidhalter/jedi) version in their repository is 0.17.1 and I also read [this issue](https://github.com/DamnWidget/anaconda/issues/760) and [this issue](https://github.com/DamnWidget/anaconda/issues/451). I also found [this issue](https://github.com/DamnWidget/anaconda/issues/673) and tried to follow the instructions there, but without any good results (probably my lack of knowledge).

So I have a question and a request:
* Is there any place where I can find instructions on how to update the version of the jedi package inside my anaconda installation?
* Do you have plans on updating the version of jedi included in anaconda anytime soon?

Thanks in advance.

**Comment by DamnWidget** [comment]
Anaconda will be probably using your default python interpreter that in Ubuntu will still be some version of Python 2.7 and that is why you get invalid syntax, you have to configure anaconda to use a valid python 3 interpreter, take a look at the [documentation](http://damnwidget.github.io/anaconda/anaconda_settings/) to check how to set a python interpreter.

About Jedi, every time we try to update Jedi it causes a different cascade of issues to some users, I did not try to update since long ago basically because I have no time to monitor the project as I was used to but is something that we can try at some point.

**Comment by jsabater** [comment]
Thanks for the quick response.

The default interpreter of my system is Python 3:

```
$ python -V
Python 3.6.9
```

Now I cannot be entirely sure whether Anaconda is actually using that interpreter (meaning I don't know how), so I set up my project file like this:

```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"/home/jsabater/venvs/genesisng/bin/python\" -u \"$file\""
		}
	],
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": "."
		}
	],
	"settings":
	{
		"python_interpreter": "~/venvs/genesisng/bin/python"
	}
}
```

I am still getting syntax errors, but I realised of this on the error message:

```flake8: error
E999 - SyntaxError: invalid syntax
```

So I was wondering whether I may be pointing my finger at the wrong place...

**Comment by DamnWidget** [comment]
Anaconda must be using `~/venvs/genesisng/bin/python` as python interpreter, whatever version that is. About that error, that is usually what PyFlakes (flake8) returns when it can not compile the source code that is going to be analyzed into an Abstract Syntax Tree and that usually happens when there are syntax errors.

**Comment by jsabater** [comment]
The Python version inside my virtualenv is 3.6.9, so it's gotta be something else. Could you think of some other places for me to look? Maybe when I set up Anaconda in SublimeText I did not pay attention to some variables? Or maybe I am missing some configuration option which is not something explained in the [documentation](http://damnwidget.github.io/anaconda/anaconda_settings/) you pointed me at (because of whatever reason, I'm not blaming anyone)?

**Comment by DamnWidget** [comment]
Is hard to know in remote, you can configure anaconda per project creating a `.sublime-project` file in the root of the directory where your project is in your disk, you can try to override your settings creating one and adding something like:

```javascript
{ 
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "."
        }
    ],
    "settings":
    {
        "python_interpreter": "your_desired_python_interpreter"
        ...
    }
}
```

And see what happens.

**Comment by jsabater** [comment]
Thanks for your suggestion, but that is something I already did, as explained in my [previous comment](https://github.com/DamnWidget/anaconda/issues/860#issuecomment-627902370).

I am honestly running out of ideas, as I can't find in my system what I am doing differently than other people, but thanks anyway.

**Comment by DamnWidget** [comment]
I am sorry man but is hard to give you more concrete answers with the information that we have. Can you share your logs with us?

**Comment by jsabater** [comment]
I have checked inside the Anaconda folder on `~/.config/sublime-text-3/Packages/Anaconda/` and I have not been able to find any log files. How can I activate Anaconda's logging or where can I find the logs?

**Comment by DamnWidget** [comment]
Sorry I should had mention the path in the previous answer. You can find the logs in `~/.local/share/anaconda/logs` on Linux

**Comment by jsabater** [comment]
I can't see any errors being added to my `~/.local/share/anaconda/logsgenesisng/anaconda_jsonserver.log` when I turn:

`def parse_args(input, allowed, pagination, logger):`

Into this:

```
from typing import Dict
def parse_args(input, allowed: Dict, pagination, logger) -> Dict:
```

And save the file. But I see the syntax error:
```
flake8: error
E999 - SyntaxError: invalid syntax
```

What triggers the log lines you are expecting? Should I check some log level parameter on some config file?

**Comment by jsabater** [comment]
Ah, wait! I restarted Sublime Text, typed something and found this on the log file:
```
2020-05-14 17:48:44,669: DEBUG   : bind: address=/home/jsabater/.local/share/anaconda/run/genesisng/anaconda.sock 
2020-05-14 17:48:44,669: DEBUG   : listen: backlog=5 
2020-05-14 17:48:44,669: INFO    : Anaconda Server started in /home/jsabater/.local/share/anaconda/run/genesisng/anaconda.sock for PID 26049 with cache dir /home/jsabater/.cache/jedi/genesisng and extra paths /home/jsabater/Projects/genesisng 
2020-05-14 17:48:44,734: INFO    : Incoming connection from '' 
2020-05-14 17:48:44,735: INFO    : Incoming connection from '' 
2020-05-14 17:48:44,747: INFO    : client requests: lint 
2020-05-14 17:48:44,845: ERROR   : MyPy was not found 
2020-05-14 17:48:44,846: DEBUG   : Traceback (most recent call last): 
  File "/home/jsabater/.config/sublime-text-3/Packages/Anaconda/anaconda_server/commands/mypy.py", line 34, in run 
    self.code, self.filename, self.mypypath, self.settings 
  File "/home/jsabater/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/linting/anaconda_mypy.py", line 61, in execute 
    raise RuntimeError("MyPy was not found") 
RuntimeError: MyPy was not found 

2020-05-14 17:48:47,757: INFO    : client requests: doc 
2020-05-14 17:48:48,249: INFO    : client requests: doc
```
So it seems MyPy is not installed. Should I install it inside my project's virtualenv? Or system wide? I found, amonth many others, `flake8-mypy==17.8.0` and `mypy==0.770`.

**Comment by scuml** [comment]
Up to you.  I'd install it per-project, and manually link it in each project settings file.

Including a sample settings below....
```
        "settings":
	{
		"mypy": true,
		"mypy_check_untyped_defs": true,
		"mypy_disallow_untyped_calls": true,
		"mypy_disallow_untyped_defs": true,
		"mypy_mypypath": "/Users/<username>/.local/share/virtualenvs/.../bin/mypy",
		"python_interpreter": "/Users/<username>/.local/share/virtualenvs/.../bin/python",
		"validate_imports": false
	}
```

**Comment by jsabater** [comment]
So whether I install it system-wide or in the virtualenv of each project is up to me but, nonetheless, I should have that configuration on the settings, either of my project or for the whole Anaconda installation, is that correct?

**Comment by scuml** [comment]
Yes.  Make sure you can run what put in `mypy_mypypath`, and then copy the path to one of those two locations.

**Comment by jsabater** [comment]
Both if I install the flake8-mypy Python package through pip3 with sudo or without it, and then I adapt the value of mypy_mypypath on the Anaconda settings, I get this error on Sublime Text:
```
SublimeLinter: #1 flake8 config.py ERROR:
=========================================

/home/jsabater/.local/lib/python3.6/site-packages is in the MYPYPATH. Please remove it.
See https://mypy.readthedocs.io/en/latest/running_mypy.html#how-mypy-handles-imports for more info
```

This error is from my last attempt, installing the packages as my local user but not inside the project's virtualenv as I think it would be a good idea for them to be available for all my projects, should I need them. Any idea?

Incidentally, does mypy come bundled with Anaconda or did I miss some installation instructions months ago (although, admittedly, I wasn't thinking of using annotations at the time)?
