### ISSUE TITLE
Anaconda no longer supports relative python interpreters

### ISSUE THREAD

**Issue by autumnjolitz** [DamnWidget/anaconda#863]
## Expected Behaviour

Anaconda looks at the project settings like:
```
	"settings":
	{
		"python_interpreter": "./python/bin/python"
	}
```
And dereferences the path as `$PROJECT_ROOT/python/bin/python`. It no longer does that.

This originally allowed for checking in a `$project_name.sublime-project` file for multiple developers who had run a setup script to place a virtualenv inside `$PROJECT_ROOT/python`. Recent changes to Anaconda has broken that collaboration completely by being unable to look locally to the project file as a relative path! 😮 

## Actual Behaviour

It spams the console with
```
The OS did return [Errno 2] No such file or directory: './python/bin/python'
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_process.LocalProcess object at 0x7fa7984204d0> process can not start a new anaconda JsonServer in the operating system because:

Anaconda can not spawn a new process with your current configured python interpreter (./python/bin/python)

Make sure your interpreter is a valid binary and is in your PATH or use an absolute path to it, for example: /usr/bin/python
```

## Steps to Reproduce

- Use a recent anaconda

## ST3, Anaconda and OS versions
Anaconda 2.1.36
ST 3.2.2
OSX 18.7.0

## ST3 Console Logs

```
The OS did return [Errno 2] No such file or directory: './python/bin/python'
anacondaST3: ERROR - <Anaconda.anaconda_lib.workers.local_process.LocalProcess object at 0x7fa7984204d0> process can not start a new anaconda JsonServer in the operating system because:

Anaconda can not spawn a new process with your current configured python interpreter (./python/bin/python)

Make sure your interpreter is a valid binary and is in your PATH or use an absolute path to it, for example: /usr/bin/python
```

## Anaconda's JsonServer Logs
Empty 😑

**Comment by DamnWidget** [comment]
Will take a look, this is probably due a side effect on the windows path fixes not long ago

**Comment by DamnWidget** [comment]
I could not reproduce this issue on my Linux box, could you please execute the following in the sublime text console?

```
from Anaconda.anaconda_lib.helpers import get_settings
from Anaconda.anaconda_lib.workers.interpreter import Interpreter
i = Interpreter(get_settings(view, 'python_interpreter'))
print(int)
```
And paste the results here please?

**Comment by autumnjolitz** [comment]
well I just reset my sublime projects back to having the path of `./python/bin/python` and it works now. I am so unbelievably confused. I do know my packages auto updated themselves recently but there's nothing to suggest why it works now (and not then!!!) 

Applying your code fragment returns this:
```
>>> from Anaconda.anaconda_lib.helpers import get_settings
>>> from Anaconda.anaconda_lib.workers.interpreter import Interpreter
>>> i = Interpreter(get_settings(view, 'python_interpreter'))
>>> print(i)
./python/bin/python -B /Users/autumn/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py -p instruct 55488 -e /Users/autumn/software/instruct 3293
```

I don't know how to explain the original error. :/

**Comment by DamnWidget** [comment]
Well, errors that resolves themselves are my favorite kind of errors :+1:
