### ISSUE TITLE
A bug that affects code reading

### ISSUE THREAD

**Issue by ma3252788** [DamnWidget/anaconda#867]
## Actual Behaviour
As soon as I open the py file, there will be a few random lines in it, and a dot will appear in front of each line, and this line will be framed by a white box. As shown below:
![](https://ypyssl.machunjie.com/machunjie/20200805203459.png)
## Steps to Reproduce
open *.py file
## ST3, Anaconda and OS versions
Anaconda 3
OS Macos 10.15.3
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by scuml** [comment]
This appears when there is a python coding style error in that line your code.  It could be an unneeded space at the end of the line, for instance.  To verify the lines with errors, press Command-Shift-P, and find `Anaconda: Show Error List` - this will list all the errors that you need to correct.  

In `Sublime Text > Preferences > Package Settings > Anaconda > Settings - User` you can set `auto_formatting` to  true to automatically fix linting errors. or you can change your `anaconda_linter_mark_style` to remove these boxes or style them differently.  The full list of settings you can change is in `Sublime Text > Preferences > Package Settings > Anaconda > Settings - Default`

**Comment by ma3252788** [comment]
> This appears when there is a python coding style error in that line your code. It could be an unneeded space at the end of the line, for instance. To verify the lines with errors, press Command-Shift-P, and find - this will list all the errors that you need to correct.`Anaconda: Show Error List`
> 
> In you can set to true to automatically fix linting errors. or you can change your to remove these boxes or style them differently. The full list of settings you can change is in `Sublime Text > Preferences > Package Settings > Anaconda > Settings - User``auto_formatting``anaconda_linter_mark_style``Sublime Text > Preferences > Package Settings > Anaconda > Settings - Default`

Thanks for the reply, I have found the setting item and it has been fixed now, thank you.
