### ISSUE TITLE
Option to show error when hover over gutter icon

### ISSUE THREAD

**Issue by guitaristtom** [DamnWidget/anaconda#868]
Is there a way to set it so that when I hover over the gutter icon it shows the error? Looking through the settings available, it doesn't seem like it, so I thought I'd ask. I see that this was previously mentioned in #301 but I wasn't sure if this has changed over the past few years or not.

I know it says the issue in the status bar (or in the phantom lines), but it would be nice to show it the other way. I know that SublimeLinter extensions (like [SublimeLinter-pylint](https://packagecontrol.io/packages/SublimeLinter-pylint)) can do it, and that's what I've grown accustomed to over the years with other languages.

**Comment by Kyu** [comment]
#864 is still active, you can test out that branch it works fine, mostly

**Comment by guitaristtom** [comment]
I _believe_ that's what I was looking for.
