### ISSUE TITLE
Linter doesn't work on MacOSX

### ISSUE THREAD

**Issue by AivanF** [DamnWidget/anaconda#869]
## Expected Behaviour
I wanted to observe warnings & errors in my code, especially about type checking.

## Actual Behaviour
Anaconda provides some input completion recommendations, but I see no linter output. I hope it can be fixed quite easily?

## Steps to Reproduce
I just installed `mypy` and Anaconda plugin by repo link because my ST3 couldn't find the package by name.

I also tried to enable some options in user settings, but got no result:

```
{
    "python_interpreter": "python3",
    "mypy": true,
    "use_pylint": true,
    "validate_imports": true,
    "anaconda_linter_phantoms": true
}
```

## ST3, Anaconda and OS versions
OS: MacOSX 10.15.1
ST3: 3.2.2
Anaconda: 2020.05.06.09.56.46

## ST3 Console Logs
How can I find it?

## Anaconda's JsonServer Logs

I got no `anaconda` folder in the `~/Library/Logs` directory 🤔

**Comment by MattDMo** [comment]
You can view the console by hitting <kbd>Ctrl</kbd><kbd>\`</kbd> or selecting **`View → Show Console`**.

**Comment by AivanF** [comment]
> You can view the console by hitting Ctrl` or selecting **`View → Show Console`**.

Thanks, but after I restarted my computer it started working fine. So, now I don't have an opportunity to check what the problem was.

**Comment by scuml** [comment]
Issue can be closed.
