### ISSUE TITLE
Something wrong with AutoComplete

### ISSUE THREAD

**Issue by TNTWEN** [DamnWidget/anaconda#871]
Environment：
Win 
Latest Sublime Text 3

After add this file https://raw.githubusercontent.com/DamnWidget/anaconda/master/Completion%20Rules.tmPreferences
The module could AutoComplete correctly
![image](https://user-images.githubusercontent.com/49018311/93556340-1d07dd80-f9ab-11ea-8316-e6f2a2b6482e.png)

But model's function still couldn't autocomplete
like this
![image](https://user-images.githubusercontent.com/49018311/93556420-47599b00-f9ab-11ea-9e81-ad25524ff185.png)
And after i enter the function completely：
![image](https://user-images.githubusercontent.com/49018311/93556538-88ea4600-f9ab-11ea-89f0-dc420a0673a4.png)

how to fix it to realize function autocomplete

Thanks a lot！

**Comment by scuml** [comment]
Please download the latest Anaconda update.  This should resolve the issue.

**Comment by scuml** [comment]
@DamnWidget Can be closed.
