### ISSUE TITLE
jedi.api.environment.InvalidPythonEnvironment: python/bin/python seems to be missing.

### ISSUE THREAD

**Issue by relikd** [DamnWidget/anaconda#878]
## Description
Auto-complete does not work anymore, at least for me. The reason could be that Jedi seems to get a wrong environment variable.
Before I changed my `python_interpreter` to `python3` the log below showed `python/bin/python` instead.

Could this line cause the issue?
https://github.com/DamnWidget/anaconda/commit/e8aeef9e591135af24cb56ed2d0a3a419dc38d00#diff-fbdafd583c2cf35eb5f9df02279d74c5b199e984b0b10b56e56c763f0a88fbe2R43

## ST3, Anaconda and OS versions
ST3 v3211
Anaconda 2.1.37
macOS 10.15.6

## Anaconda's JsonServer Logs
```
2020-10-13 11:19:27,856: DEBUG   : bind: address=('localhost', 57476)
2020-10-13 11:19:27,856: DEBUG   : listen: backlog=5
2020-10-13 11:19:27,857: INFO    : Anaconda Server started in 57476 for PID 10118 with cache dir /Users/username/Library/Caches/Jedi/project and extra paths /Users/username/customdir/project
2020-10-13 11:19:27,908: INFO    : Incoming connection from ('127.0.0.1', 57488)
2020-10-13 11:19:27,909: INFO    : Incoming connection from ('127.0.0.1', 57489)
2020-10-13 11:19:27,915: INFO    : client requests: lint
2020-10-13 11:19:27,941: INFO    : [anaconda_plugins] imported handlers for <module 'handlers_php' from '/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/lib/../../../anaconda_php/plugin/handlers_php/__init__.py'>
2020-10-13 11:19:27,969: INFO    : client requests: lint
2020-10-13 11:19:27,978: INFO    : client requests: doc
2020-10-13 11:19:27,981: ERROR   : python3/bin/python seems to be missing.
2020-10-13 11:19:28,004: ERROR   : Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 112, in found_terminator
    self.handle_command(handler_type, method, uid, vid, settings, data)
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 140, in handle_command
    handler(method, data, uid, vid, settings, self.return_back, DEBUG_MODE).run()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 29, in run
    super(JediHandler, self).run()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/lib/anaconda_handler.py", line 49, in run
    command(**kwargs)
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 101, in doc
    Doc(self.callback, self.uid, self.script, html)
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 45, in script
    return self.jedi_script(**self.data)
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 55, in jedi_script
    return jedi.Script(
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/api/__init__.py", line 184, in __init__
    self._inference_state = InferenceState(
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/api/project.py", line 210, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/api/environment.py", line 377, in create_environment
    return Environment(_get_executable_path(path, safe=safe))
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/jedi/api/environment.py", line 390, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: python3/bin/python seems to be missing.

2020-10-13 11:19:28,932: INFO    : client requests: lint
```

**Comment by relikd** [comment]
Changing the interpreter to an absolute path fixes the issue. So, somehow the last update broke relative paths for the interpreter setting.

**Comment by relikd** [comment]
But now the linting and auto-completion seem very slow. I can watch the tooltip window while it inserts one character after the other. Approx. 1 char per second of what I typed earlier.

**Comment by scuml** [comment]
Looked into getting jedi to pick up system python from the `python_interpreter` setting.  It's not elegant to implement on Anaconda's side and is probably best added as a method to the Jedi library.  If you leave `python_interpreter` blank, it will use the standard system python (which I know is python2 in 10.15) but might be work when OS 11 is released.

I can't replicate the speed issues you mentioned.  Is `jsonserver_debug` mode set to false?

**Comment by relikd** [comment]
Yes it is. Actually, I have not change a single setting until yesterday when I changed the interpreter. Is there a way to force reset everything? I tried re-installing Anaconda but that didn't solve it. The speed issue is getting so bad that I just disabled it completely for now.
And it seems not to be a speed issue per se, but a limitter or something. E.g. when I press tab to auto-complete a function it does nothing until 20 seconds later. Then it will insert it wherever my curser is at that time, not as actual function params.

Is it supposed to print DEBUG logs if debugging is disabled? Also, the linting seems to be invoked multiple times simultaniously on the same text chunk—if I see it correctly.
[logg.txt](https://github.com/DamnWidget/anaconda/files/5381419/logg.txt)

**Comment by relikd** [comment]
OK, now it gets weird.
If I uninstall Anaconda, restart Sublime, and then reinstall Anaconda, everything works as expected. Even without the need to change the interpreter (like it always was), speed fine, everything super.
But as soon as I quit and reopen Sublime again, the behavior starts again. Not able to connect to the Jedi server if I don't change the interpreter – and if I do, lots of lagging.

**Comment by scuml** [comment]
Try setting `jsonserver_debug` to False- that will likely solve the speed issue.

**Comment by relikd** [comment]
Already tried. the default setting is False. And I even copied the whole default settings to user settings. That didn't work either. The default config without any modifications does not work for me – or to be more precise, it work only for the first time when I install Anaconda, and only until I quit Sublime, then it breaks.
Is there something else I can try? I dont know what else could cause this

**Comment by relikd** [comment]
I just tried one more thing. I've installed Anaconda v2.1.37 and then replaced the package dir content with the github source from release v2.1.36. No speed issues, no interpreter issues. I am certain this has something to do with the latest release :/

Since you initiated #861, do you happen to know why it might fail? Could also be a bug in the newer Jedi version …

**Comment by relikd** [comment]
Ok, I fixed it by commenting out these two lines:
https://github.com/DamnWidget/anaconda/blob/master/anaconda_server/handlers/jedi_handler.py#L52-L53
Now its your turn to tell me why it fixes the issue; or what else I broke by disabling it 😄

**Comment by DamnWidget** [comment]
That is as leaving the `python_interpreter` in blank in all your configuration levels Oleg

**Comment by scuml** [comment]
Those lines are needed for Jedi's parsing engine to work using virtual environments.  If one is using system python, you can leave `python_interpreter` as blank.  I'm still researching how best to implement a patch to make things work as before.

**Comment by relikd** [comment]
What do you mean by leaving `python_interpreter` blank? Not setting a value and thus reusing the default settings that come along with Anaconda – or actually setting it blank `"python_interpreter": ""`?
If you meant the first scenario then no, it is not equivalent. As in my case, leaving the default value caused the issue.
And setting the value to `""` results in an error.

> Make sure your interpreter is a valid binary and is in your PATH or use an absolute path to it, for example: /usr/bin/python

**Comment by relikd** [comment]
So, lets go through the execution steps.

After you assign the `python_interpreter` to `jedi_project._environment_path`, it is used in [jedi.Project.get_environment()][1] and calls [jedi.environment.create_environment()][2].
Since `if os.path.isfile(path):` is false (default value is `python`), it further calls `_get_executable_path()` below.
On my mac the next condition returns:
```
if os.name == 'nt':
    ...
else:
    python = os.path.join(path, 'bin', 'python')
```
which will output `python/bin/python`.

That results in my initial error (title description)

[1]: https://github.com/davidhalter/jedi/blob/209e2713fd699b8a54aa4c8bbd0915e6c51f2092/jedi/api/project.py#L239
[2]: https://github.com/davidhalter/jedi/blob/209e2713fd699b8a54aa4c8bbd0915e6c51f2092/jedi/api/environment.py#L356

**Comment by relikd** [comment]
My proposed solution would be:
```
if self.settings.get("python_interpreter", "") != "":
    intrptr = self.settings.get("python_interpreter")
    if os.path.isdir(intrptr):
        jedi_project._environment_path = intrptr
```
(not sure if jedi env path can hold a path to an executable, but if so, the condition should be changed)

**Comment by scuml** [comment]
That's getting close to the solution.  We need to cover cases where someone links to the absolute path of the python binary in a virtual environment, as well as using a non-default system python (eg: python2.7 or python3) as the python interpreter.

**Comment by relikd** [comment]
We could add `... or os.path.isfile(intrptr)`, that would pass the environment. I also tried resolving the PATH variable (`"python"`) to always expand to the full path. That will also do it.

But then I still get the second problem, performance issues. Somehow it is not the same if you set the env to `/usr/bin/python` versus not setting the env at all. `JediHandler.jedi_script()` is called every time a file is linted, correct? My assumption is, the `create_environment` function of jedi is not very performant. Can we store and reuse the `_environment` variable in between linting?

**Comment by relikd** [comment]
Me again 😄, you can replace the existing code with this here:
```
if self.settings.get("python_interpreter", "") != "":
    os.environ.setdefault('VIRTUAL_ENV', self.settings.get("python_interpreter"))
```
This sets the environment without the `python/bin/python` error. Whether it is a full binary path or using PATH.

(I am still searching for the speed issues but that might be jedi’s fault… :/ … or the way anaconda calls jedi?)

**Comment by scuml** [comment]
Yes. That’s definitely going to make the fix. I’ll spend some time this weekend to try to find a comprehensive solution. Will post updates.

**Comment by yellowjigi** [comment]
Hello!
Thank you for your great effort in developing and maintaining this so much useful software.

I am new to the Sublime Text as well as AnacondaST3 and I think I have exactly the same issue-but kind of a variant that has not been mentioned-from this issue and also #875.

Once I restarted Sublime Text editor after installing the AnacondaST3, the autocomplete didn't work any more.

**Steps to reproduce**
Start Sublime Text
Install AnacondaST3 by Package Control of Sublime Text; Autocomplete works well
Restart Sublime Text; Autocomplete does not work any more

**To troubleshoot this issue,**
I referred to the anaconda_jsonserver.log file (where the logs that matter are exactly the same as the one from @relikd, except this line: `2020-10-18 23:03:57,811: ERROR   : C:\Users\username\Anaconda3\envs\py37\python\Scripts\python.exe seems to be missing.`, where `C:\Users\username\Anaconda3\envs\py37\python` is what I configured as an interpreter path to the Anaconda.sublime-settings.

**How I worked around**
While @relikd suggested that the full absolute path of the python interpreter be provided, I replaced the path for the python interpreter as `C:\Users\username\Anaconda3\envs\py37\python.exe` where _.exe_ was appended to the end; then the problem was solved.

I am not sure but in some cases like mine in Windows environment, if you don't put the extension (.exe) explicitly to the path, `Scripts\python.exe` is automatically added to the path (as seen from the log file).

**Versions**
Windows 10
Anaconda v2.1.37
Sublime Text v3.2.2 Build 3211

**Comment by relikd** [comment]
@yellowjigi yep, that suffix is added by jedi, not anaconda:
https://github.com/davidhalter/jedi/blob/209e2713fd699b8a54aa4c8bbd0915e6c51f2092/jedi/api/environment.py#L375-L378

**Comment by davidhalter** [comment]
```
if self.settings.get("python_interpreter", "") != "":
    os.environ.setdefault('VIRTUAL_ENV', self.settings.get("python_interpreter"))
```

I think that this is a bad idea. You should be using the explicit Jedi API for this. You can just use `create_environment(path)` instead.

I know at that point you probably need to cache your environments and check for changes of the python interpreter variable, but if you don't do that you will probably just run into issues.

**Comment by relikd** [comment]
I got to this solution because this is one of jedi's solutions. Jedi calls `get_cached_default_environment` which calls [`get_default_environment`][1]. That function reads the `VIRTUAL_ENV` and `CONDA_PREFIX` variables for any user-set values. It is not intended to set the var dynamically as I proposed it, but it is the preferred way for jedi to read the environment.

And I particularly chose this method because a) `get_cached_default_environment` reads like it already does some caching, and b) it's one of the official ways to set the jedi environment. If going this route still results in slow performance, then it can hardly be the fault of anaconda.

What bugs me is the behavior when setting the environment manually to the same value that is used if you not set an environment at all. How can the same value slow the parser down …

[1]: https://github.com/davidhalter/jedi/blob/209e2713fd699b8a54aa4c8bbd0915e6c51f2092/jedi/api/environment.py#L183-L189

**Comment by davidhalter** [comment]
> but it is the preferred way for jedi to read the environment.

It's not. It's just the default way. It has a couple of drawbacks like not being able to specify a venv or an executable.

> What bugs me is the behavior when setting the environment manually to the same value that is used if you not set an environment at all. How can the same value slow the parser down …

As I said before, I'm pretty sure that a new environment is created each time. I'm not sure why, but that's why it's slow. That has nothing to do with the parser. It is expected for this to happen if a new environment is created. The question is: Why is a new environment created?

I'm just not sure I trust your setup. It seems like nobody has had these issues in the last 6 months. Jedi has had issues with environments (especially in 2019), but these seem to have gone now. I suspect that there's probably a second Jedi installed that is loaded instead of the one you think that's loaded. I cannot help you at all with this, but you seem to be the one user in a million that has this issue.

**Comment by relikd** [comment]
We don't need to argue, the latest release v2.2.0 fixed it already.

Just a note on why I am (probably) not the one in a million. Setting the environment was just [introduced][1] in v2.1.37 and then [removed][2] again with the v2.2.0 patch. No one complained, including me, because it did work before. But again, we do not have to argue here. Everything works fine now. This issue can be closed.

[1]: https://github.com/DamnWidget/anaconda/commit/5af45c2e489621196a39ea8f82b154f8e6128193#diff-fbdafd583c2cf35eb5f9df02279d74c5b199e984b0b10b56e56c763f0a88fbe2R41-R44 
[2]: https://github.com/DamnWidget/anaconda/commit/5bc3ab7e35c9e0ac91a0d0428d3cc7011c547dd0#diff-fbdafd583c2cf35eb5f9df02279d74c5b199e984b0b10b56e56c763f0a88fbe2L42-L43
