### ISSUE TITLE
Stop popping up a completion when typing :

### ISSUE THREAD

**Issue by txtsd** [DamnWidget/anaconda#891]
## Expected Behaviour
When I type a colon `:`, no completion should popup.

## Actual Behaviour
A completion pops up when I type a colon `:`

## Steps to Reproduce
Type `class Test:`
or type `def testFunction():`

## ST3, Anaconda and OS versions
ST4: 4094
Anaconda: 2.1.37
OS: Arch Linux

**Comment by ZitCode** [comment]
Same problem! Sublime 4107, Ubuntu 20.10, the latest anaconda from PM.

**Comment by ZitCode** [comment]
I have found a solution (it's working, but I think _it's should be a temporary solution 'cause it just disabling completion when ':' is typed_)
In file listeners/completion.py (can be found by click on 'Preferences/Browse Packages' in Sublime Text, then open Anaconda folder) add lines
>         if int(sublime.version()) > 4000:
>             if view.substr(view.sel()[0].begin() - 1) == ':':
>                 return
Under 86 line `        view = active_view()` in function _complete. The file should look like this:

>     def _complete(self, data: Dict[str, Any]) -> None:
> 
>         view = active_view()
>         if int(sublime.version()) > 4000:
>             if view.substr(view.sel()[0].begin() - 1) == ':':
>                 return
>         proposals = data['completions'] if data['success'] else []

**Comment by txtsd** [comment]
Thanks for the temporary fix!

**Comment by dbazile** [comment]
Is this confirmed and on the roadmap to be fixed? I don't remember this behavior from Sublime Text 3 but in 4, it's driving me batty.

**Comment by diek** [comment]
This issue was closed, but it persists.
ST4: 4121
Anaconda: 2.2.2
OS: OS X Big Sur

<img width="1080" alt="s_capture_2021-11-27_22 09 08@2x" src="https://user-images.githubusercontent.com/1261158/143726055-f37d1c8f-8267-4d3f-8395-d0094b8be76f.png">

**Comment by DamnWidget** [comment]
@diek forgot to make a new release, ST will catch it up soon (release is v2.2.3)

**Comment by diek** [comment]
@DamnWidget , thanks, I appreciate all your help! Solid!
