### ISSUE TITLE
"ctrl + alt + r" not work

### ISSUE THREAD

**Issue by thep0y** [DamnWidget/anaconda#894]
## Expected Behaviour
Use key binding `ctrl + alt + r` to complete code formatting.
## Actual Behaviour
The key binding do not work, and there is no error message.
## Steps to Reproduce
This problem occurred after installing anaconda, without any steps to reproduce.
## ST3, Anaconda and OS versions
ST3 -> 3211
Anaconda -> latest
OS -> 5.10.7-3-MANJARO

## ST3 Console Logs
There is no error log, there is no log in the console when using `ctrl + alt + r`
## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs
[anaconda_jsonserver.log](https://github.com/DamnWidget/anaconda/files/5872080/anaconda_jsonserver.log)

**Comment by mavelim** [comment]
I had the same issue, I'm using Manjaro KDE and the key binding `ctrl+alt+r` was already assigned for the clipboard so it would not work on sublime.
The options are:
- Change the key binding in sublime eg. ` ctrl+shift+r` or 
- Replace the shortcut for the clipboard in Manjaro, so `ctrl+alt+r` is available, or even disable it if you don't use it

Hope it helps.

**Comment by thep0y** [comment]
> 

Thank you for your reply, but I am currently using `lsp-pyright` and `python-black`, the combination of these two plugins is capable of all development work.
