### ISSUE TITLE
User confusion: Vagrant integration docs should self-document what Vagrant is

### ISSUE THREAD

**Issue by gregkrsak** [DamnWidget/anaconda#918]
## Expected Behaviour
Visiting http://damnwidget.github.io/anaconda/vagrant/ will explain to a first-time user what "Vagrant" is.

## Actual Behaviour
Visiting http://damnwidget.github.io/anaconda/vagrant/ leaves a new user confused, in the edge case where they are seeking to learn about Vagrant for the first time.

## Steps to Reproduce
1. Introduce a friend to Python for the first time; perhaps suggest that they find and install "Anaconda".
2. Have them visit http://damnwidget.github.io/anaconda/ 
3. Have them select "Vagrant Integration" to visit http://damnwidget.github.io/anaconda/vagrant/
4. ?
5. Listen to them wonder why learning Python is so confusing.

## ST3, Anaconda and OS versions
N/A

## ST3 Console Logs
N/A

## Anaconda's JsonServer Logs
N/A

**Comment by DamnWidget** [comment]
The introduced friend can go to Vagrant to check their documentation or use Google, anaconda is not a wiki
