### ISSUE TITLE
[IMPORTANT] Giving a little push to the plugin

### ISSUE THREAD

**Issue by DamnWidget** [DamnWidget/anaconda#921]
Hello fellas

As you probably know, I am very busy with other projects and life in general. I do not use Python since long long ago, and I don't use Sublime Text anymore since long ago too. I asked for maintainers for the project to step up, a few persons did step up, for two days, and then disappeared into oblivion, that is perfectly fine, it is normal, people have their lives, their preferences and also, work for a Free Software / Open Source project is an extremely exhausting work.

Issues stack and stack in this repository and no one gives a crap about it, it really hurts my hearth to see you, fellow developers, suffering because the plugin stop working with more modern versions of Python, I really want you to be happy but I also want I to be happy so there is an conflict of interest in here.

When I work for Anaconda plugin I am not happy, I am the most opposite of happy that I can be, first, because I don't care about Python or Sublime Text anymore, second because I have other important things to do and third because it is pretty boring. But it really fucks me up to see this beautiful community in pain, suffering, crying out for help.

Dramatizations aside, I decided to dedicate some hours of my time to give **a small push** to the plugin so you, my beloved users can experience the joy of programming Python in a quality environment with your preferred text editor, but this is gonna be probably the last time I make any effort for you, as much as I love you all, you have to understand, I am only human, I am selfish, I prefer to invest my time in projects that are useful to me, don't get me wrong, I really love to give you tools, and make your life a little less miserable but the limit has to be somewhere, amirite?

So far I have the plugin working again with the latest version of Jedi and Python 3.10.1 in an Artix Linux box, that means, auto completion, docs, function signatures and goto, are working again. As I already stated, I am not gonna dedicate a tremendous amount of hours to this task, there are things that are pretty close to get obsolete because they are older than coal. For example, the crappy asynchronous IO loop that I wrote myself, and powers the communication between the ST3/4 part of the plugin and the Server side (yes, when I wrote this plugin, asyncio wasn't a thing yet, language servers weren't a thing either, call me a pioneer but I would prefer if you just call me a "friend").

This means, that, I might give the plugin a push and extend its life a few more years but you have to stand up and fight for what you love, damn it, if you love Sublime Text and you love Python and you love Anaconda, think about becoming a maintainer because some day I will not answer anymore and that day will be a very sad day.

I will make a new release as soon as I can, btw, I am not caring if older versions of Python gets broken by the update, if you were using anaconda flawlessly in your old as fuck Slackware with Python 2.7, just uninstall the plugin with package control, download a previous version manually and decompress it in your packages directory I couldn't care less about breaking compatibility with older versions anymore ( I am truly sorry but it is what it is ).

I am also not caring at all about Windows or MacOS, I am assuming they will work fine but I didn't test it.

Stay tuned.

**Comment by MattDMo** [comment]
I'm pretty sure I speak for the community when I say thank you very much for all the hard work you've done over the years! Anaconda has been a mainstay for me for a long time, all the way back to 2013/14 when I was thinking there just *had* to be something better than SublimeCodeIntel.

I do use other tools now for some tasks, notably LSP and pylsp, which is great, but it doesn't work with SublimeREPL, which is a major part of my workflow, so having a functional Anaconda for autocomplete and popup documentation is really important.

Unfortunately I don't know much about `asyncio` either, but I could certainly try to learn. Even if there isn't a major rewrite or feature set change, just keeping things going, trying to address issues, and merging good PRs is probably within my abilities. Let me think about it...
