### ISSUE TITLE
[WorkAround] Manually installing anaconda on ST3

### ISSUE THREAD

**Issue by amircheg** [DamnWidget/anaconda#933]
I followed the instructions in "For Sublime Text 3 Users" section carefully but wasn't able to get it to work. 
I have the latest release of ST3 (v3.2.2 build 3211) installed on my laptop.
ST3 install location: C:\softwares\Sublime Text 3
I downloaded anaconda-2.2.3.zip, extracted it to C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\anaconda-2.2.3
it shows anaconda-2.2.3 when i list packages, but nothing works...

**Comment by DamnWidget** [comment]
Latest version does not works with ST3 anymore, please, refer to the README 

https://github.com/DamnWidget/anaconda#very-important-notice-please-read-carefully

**Comment by DamnWidget** [comment]
Wait, you said you used the workaround... do you get any error in ST3 console?

**Comment by amircheg** [comment]
No nothing happens. No output, nothing...

**Comment by amircheg** [comment]
It is not the latest version of anaconda its the latest version of st3 btw

**Comment by DamnWidget** [comment]
Try to remove the version from the package name, so you end with `C:\Users\Admin\AppData\Roaming\Sublime Text 3\Packages\anaconda`  instead
