### ISSUE TITLE
Anaconda high memory usage

### ISSUE THREAD

**Issue by flomertens** [DamnWidget/anaconda#97]
I have found that lately anaconda jsonserver is eating memory pretty fast

I have logged the memory usage while working:

Memory usage: http://pastebin.com/XYBSHGvE
jsonserver log: http://pastebin.com/uSi7za36

Tell me if you need more information from me.

**Comment by SmartManoj** [comment]
Still

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/60766441-68481000-a0c7-11e9-81a9-7d3de1ccdcd8.png)
